### ISSUE TITLE
Unable to debug via VSCode

### ISSUE THREAD

**Issue by pangkoksiong** [microsoft/vscode-react-native#1008]
## Actual Behavior
1. Followed the instruction of "Debugging React Native applications".
2. Configuration was added successfully in launch.json file.
3. Clicked "green arrow" or F5 to start debugging.
4. The debugger float dialog appeared for few seconds then disappeared.
5. App was never started.

Note: 
1. react-native run-android can be executed successfully in terminal.
2. Debugging in Chrome browser works.

## Expected Behavior
1. App and debugger should start.

## Software versions
- React-Native VS Code extension version: 0.9.3
- VSCode version: 1.34.0
- OS platform and version: MacOS 10.14.4
- NodeJS version: 10.15.3
- React Native version: 0.59.8
- Expo SDK version (include if relevant): n/a

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
<EMPTY>
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
<React-Native is not available in the ListBox>
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
<EMPTY>
```

**Comment by ruslan-bikkinin** [comment]
Hi @pangkoksiong and thanks for reaching us. I've just tried to debug fresh RN 0.59.8 app on the latest extension version and see no problems with it. Please give us more details about your case:
* Show us your launch.json config
* Do you just open your app directory or you open workspace with multiple directories in it including your app?
* Do you use nvm? If so, make sure, that node versions is used in system terminal and in VS Code terminal are the same.

**Comment by pangkoksiong** [comment]
@ruslan-bikkinin , thank you very much for replying.

This comment resolves my problem. 
> Do you just open your app directory or you open workspace with multiple directories in it including your app?

Sorry for the false alarm and thank you for saving my days.

**Comment by amadeu01** [comment]
I'm facing this issue. 

My `launch.json`:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to packager",
      "program": "${workspaceRoot}/.vscode/launchReactNative.js",
      "type": "reactnative",
      "request": "attach",
      "trace": "verbose"
    },
    {
      "name": "Debug iOS",
      "program": "${workspaceRoot}/.vscode/launchReactNative.js",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios"
    }
  ]
}
```

the directory I opened in VSCode is:

```
.
├── README.md
├── android
├── app.json
├── assets
├── babel.config.js
├── debug
├── e2e
├── exp.json
├── index.js
├── ios
├── jest.config.js
├── jsconfig.json
├── node_modules
├── package-lock.json
├── package.json
├── patches
├── src
└── yarn.lock
```

**Comment by amadeu01** [comment]
I tried to create a new project and run. However, it didn't work either.

**Comment by ruslan-bikkinin** [comment]
Hi @amadeu01 please open new issue and fill Github issue template. As for newly created projects, "Debug ..." scenarios are temporarily [broken](https://github.com/microsoft/vscode-react-native/issues/1042) for RN v0.60 projects, however we have a [fix](https://github.com/microsoft/vscode-react-native/pull/1043) for it already. You can use "Attach to running packager" as a workaround instead.
