### ISSUE TITLE
Salsa not running properly on OSX, possible env variable issue

### ISSUE THREAD

**Issue by vcipriani** [Microsoft/vscode-react-native#102]
I just installed the extension in v0.10.9 and intellisense is not working.  At the bottom right Salsa is displaying in orange and showing "(Salsa !)".  Below is some more information:
- I confirmed typescript was installed to .vscode/node_modules.  It installed 1.9.0-dev.20160302.  My settings.json is pointing to this location.  

- `printenv` did not show VSCODE_TSJS as an environment variable.  I also did not see it in my .bashrc, .bash_profile, or profile.  I added the following line to my .bash_profile and confirmed it exists by running `printenv`.  After restarting vscode, it is still not working.
          `export VSCODE_TSJS=1`

**Comment by MSLaguana** [comment]
How are you running and restarting vscode? When we set the environment variable we do it with `launchctl setenv` which configures it for applications run from the GUI, but not if you are running it on the command line directly. Also if you are only closing the window but not `cmd-q` closing the whole thing, it won't restart and pick up new environment variables.

**Comment by vcipriani** [comment]
Thanks for the quick response.  I figured it out.  The settings.json was not being picked up because the .vscode folder was not in the root of the folder I had opened in vscode.  Fyi for others, you can see what version of typescript salsa is targetting by hovering over "(Salsa)" at the bottom right.

**Comment by digeff** [comment]
Glad you figured it out. Please reopen it if you still have more issues.
