### ISSUE TITLE
Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

### ISSUE THREAD

**Issue by balagopinath** [microsoft/vscode-react-native#1022]
## Actual Behavior
1. Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)
2. 

## Expected Behavior
1.  Start Debugging
2. 

## Software versions
- React-Native VS Code extension version:  0.9.3
- VSCode version: 1.34.0
- OS platform and version: Win 10
- NodeJS version: 10.13.0
- react-native-cli: 2.0.1
- react-native: 0.59.8
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

OS: win32 x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.7.46
Could not debug. Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

PASTE OUTPUT HERE
```
- [Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\RnD\Android\React-Native\kanimenApp 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (572/572), done.

[Error] Error: Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)


```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

[Extension Host] debugger listening on port 18914
workbench.main.js:238 [Extension Host] Git installation not found.
t.log @ workbench.main.js:238
workbench.main.js:238 [Extension Host] (node:14396) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.main.js:238
workbench.main.js:238 [Extension Host] (node:14396) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.main.js:238
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hi @balagopinath and thanks for reaching us. Could you please also add output from View -> Toggle Output -> Select React Native: Run android?

**Comment by balagopinath** [comment]
> [Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

**Comment by balagopinath** [comment]
Simulator version


![capture](https://user-images.githubusercontent.com/34679811/58870979-ceafcc00-86de-11e9-88f2-4be0aed7d797.jpg)

**Comment by SounD120** [comment]
@balagopinath It looks like ANDROID_HOME environment variable is absent in your PATH environment.  Please make sure that Android SDK is installed on your system and set up correctly.
To do that please do the following:
* Open Android Studio
* Click `Configure`
* Choose `SDK Manager`
* See if the string `Android SDK Location` exists
* Open Powershell
* Run Powershell script
```
[Environment]::SetEnvironmentVariable("ANDROID_HOME", "<Android SDK Location Path>", "User")
```

Please let us know if this helps.

**Comment by balagopinath** [comment]
Yes. Thanks @SounD120
