### ISSUE TITLE
Command failed: adb -s "emulator-5554" shell getprop ro.build.version.sdk

### ISSUE THREAD

**Issue by Vahe92** [microsoft/vscode-react-native#1026]
## Actual Behavior
1. Can't debug app.I'm getting 'Command failed: adb -s "emulator-5554" shell getprop ro.build.version.sdk' error. I tried to run this command from cmd and it worked.

## Expected Behavior
1. Run debugger without errors.

## Software versions
- React-Native VS Code extension version: 0.9.3
- VSCode version: 1.35.0
- OS platform and version: Windows 10
- NodeJS version: 10.16.0
- React Native version: 0.57.8

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Could not debug. Error while executing command 'adb -s "emulator-5554" shell getprop ro.build.version.sdk': Command failed: adb -s "emulator-5554" shell getprop ro.build.version.sdk
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Error: Error while executing command 'adb -s "emulator-5554" shell getprop ro.build.version.sdk': Command failed: adb -s "emulator-5554" shell getprop ro.build.version.sdk
```

**Comment by SounD120** [comment]
Hi @Vahe92 and thanks for reaching us. Could you please also add outputs from View -> Toggle Output -> Select React Native: Run android?

**Comment by Vahe92** [comment]
Hi SounD120 

[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

[Info] Attaching to running React Native packager

Building and installing the app on the device (cd android && gradlew.bat installDebug)...
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Reading env from: .env
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
...
...
...
:app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_XL_API_27_2(AVD) - 8.1.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 7s
179 actionable tasks: 1 executed, 178 up-to-date
Running C:\Users\Usr\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\Users\Usr\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.testapp/com.testapp.MainActivity)...
Starting: Intent { cmp=com.testapp/.MainActivity }

**Comment by SounD120** [comment]
@Vahe92 Could you please send us a screenshot of your Android Studio Android SDK configuration? You can find my configuration below as example:
![image](https://user-images.githubusercontent.com/32372875/59185924-53389980-8b7a-11e9-91d1-d4beda7cc169.png)
![image](https://user-images.githubusercontent.com/32372875/59185932-5c296b00-8b7a-11e9-85b9-2da5ed259f1c.png)

**Comment by SounD120** [comment]
@Vahe92 It looks like this behaviour is connected with Android SDK Platform-tools 29. I tested platform-tools 28 - it have no such problems. I'd recommend you to check your Platform-tools version, if it 29 then delete it and install 28 manually. You can do this using the following instruction:
* Open Android Studio
* Click `Configure`
* Choose `SDK Manager`
* Open `SDK Tools`
* Uncheck `Android SDK Platform Tools` and click `Apply`
* Download `Android SDK Platform Tools 28` using this link : https://dl.google.com/android/repository/platform-tools_r28.0.0-windows.zip
* Unzip this folder into `Android SDK Location` folder that is indicated at SDK Manager

Please let us know if this helps.

**Comment by SounD120** [comment]
Google is already informed about this behaviour and the corresponding issues has been created at their bug tracker:
https://issuetracker.google.com/issues/113808700
https://issuetracker.google.com/issues/134733050

**Comment by Vahe92** [comment]
Thanks SounD120. Going back from version 29 to 28 solved the problem.
