### ISSUE TITLE
We should update the log cat monitor killing logic, to not show an error when we kill it on purpose

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#103]
We should update the log cat monitor killing logic, to not show an error when we kill it on purpose
                // TODO #103: After the refactoring of the CommandExecutor is finished, we need to update this logic
                // to not show an error when a command was killed on purpose by us

**Comment by panarasi** [comment]
Today, react has `log-android` and `log-ios` commands. I would propose that we don't show logcat output inside the packager. Instead, the packager just shows its regular output. 
There should be a separate command that can start `log-ios` and `log-android` from the tasks panel.

**Comment by digeff** [comment]
@panarasi The logcat output appears on it's own output channel (last time I checked at least)

**Comment by vladimir-kotikov** [comment]
Tested this just now and logcat channel shows a message saying that `######### LogCat monitoring stopped because the debugging session finished ##########` when I stop debugging so this looks like has been already implemented.
