### ISSUE TITLE
Unable to debug via VSCode

### ISSUE THREAD

**Issue by amadeu01** [microsoft/vscode-react-native#1046]
## Actual Behavior

Followed the instruction of "Debugging React Native applications".
1. Configuration was added successfully in launch.json file.
2. Clicked "green arrow" or F5 to start debugging.
3. The debugger float dialog appeared for few seconds then disappeared.
4. App was never started.

Note:

react-native run-android can be executed successfully in terminal.
Debugging in Chrome browser works.
Expected Behavior

## Expected Behavior
1. App and debugger should start.
or
1. Attach to packager

## Software versions
- React-Native VS Code extension version: 0.10.0
- VSCode version: 1.36.0 (1.36.0)
- OS platform and version: MacOS 10.14.5 (18F132)
- NodeJS version: v12.6.0
- React Native version: 0.57.4, also with 0.60.0
- Expo SDK version (include if relevant):

<img width="396" alt="image" src="https://user-images.githubusercontent.com/11631092/60888854-0ce46200-a22e-11e9-9ab1-d540902b3393.png">

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
<EMPTY>
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
<EMPTY>
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
<EMPTY>
```

Similar to #1008

**Comment by ruslan-bikkinin** [comment]
Hi @amadeu01 thanks for reaching us. Do you use nvm?

**Comment by amadeu01** [comment]
hi @ruslan-bikkinin 
I use asdf for managing node versions. Is it any issue?

**Comment by uday5162** [comment]
Same problem here when I click on green arrow after successfully adding Configuration in launch.json.
debugger appeared for few seconds then disappeared.

**Comment by amadeu01** [comment]
any update on this?

**Comment by ruslan-bikkinin** [comment]
@amadeu01 sorry for the delay. 

Are you sure that output of the Developer Tools console (`Help -> Toggle Developer Tools -> Select Console` tab) is empty in your case after clicking at play button?

Also, did you try to fallback to the previous version of the extension by following the instructions from this comment: https://github.com/microsoft/vscode-react-native/issues/1012#issuecomment-511741934?

**Comment by uday5162** [comment]
Yes fallback to previous versions is working for me
Thanks :+1:

**Comment by amadeu01** [comment]
@ruslan-bikkinin sorry my delay to answer. 
I tried to kill chromes instance after select `Remotely debug` at RN's app. Then, I attached the debug again with VSCode, it worked so far :D 

Thanks 👍

**Comment by ruslan-bikkinin** [comment]
Alright, glad that your problem is resolved, may I close this then?

**Comment by draperj** [comment]
> Alright, glad that your problem is resolved, may I close this then?

Is there any indication on when this will be fixed in a future release, not requiring a rollback of the extension? I have not had success using the current or previous versions of this extension for debugging via VSCode with RN60+.

**Comment by amadeu01** [comment]
> Alright, glad that your problem is resolved, may I close this then? 

For my personal environment, I'm not facing the issue. So, you can close.

**Comment by ruslan-bikkinin** [comment]
@draperj please create separated issue for your case.

@amadeu01 thank for letting me know, I am closing this.
