### ISSUE TITLE
Unable to attach debugger to packager with Error: unexpected server response (400)

### ISSUE THREAD

**Issue by benabbon** [microsoft/vscode-react-native#1047]
## Actual Behavior
1. Attach packager fails with unexpected error: 400.

## Expected Behavior
1.  Attach packager actually attached debugger to packager

## Software versions
- React-Native VS Code extension version: 0.10.1
- VSCode version: 1.36.1
- OS platform and version: windows 10 x64 1903 (10.0.18362)
- NodeJS version: 10.11.0
- React Native version: 0.59.9

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Error: unexpected server response (400). Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: Reconnection to the proxy (Packager) failed. Please check the output window for Packager errors, if any. If failure persists, please restart the React Native debugger. (error code 1403)
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: unexpected server response (400)
    at ClientRequest._req.on (c:\Users\user\.vscode\extensions\msjsdiag.vscode-react-native-0.10.1\node_modules\ws\lib\WebSocket.js:653:21)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:441:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
```

The issue started appearing when we moved from react-native 0.57

NB: The same thing happens on Mac OS X.

**Comment by ruslan-bikkinin** [comment]
Hi @benabbon  and thanks for reaching us. Did you try running `react-native run-android` manually and then attach to the app using Chrome?

**Comment by SounD120** [comment]
Hi @benabbon . I just ran `Attach to packager` debug scenario on React Native 0.59.9 on clean application and I couldn't reproduce the error you describe. Could you please make sure that migration was performed correctly? This official migration guide might help: https://facebook.github.io/react-native/docs/upgrading

**Comment by benabbon** [comment]
I've never had the run-android possibility since my project has a custom setup: (The android folder contains two sub-android projects). This shouldn't be a problem, as I have the same issue with iOS, either by running run-ios, or by running through xcode, or by launching the packager from VS code.
I'm checking if the upgrade was done the right way.

**Comment by ruslan-bikkinin** [comment]
@benabbon do you have any news?

**Comment by benabbon** [comment]
We found that the issue is related to ws package. We wanted to fix a known vulnerability (WS-2017-0421) so we forced it to a minimal of 3.3.1, while react-native debugger leverages the version 1.1.5. The solution would be to move to react-native 0.60 as they upgraded to ws 6, but in the same time, vscode-react-native should move upper than 3.3.1, best would be the same version as react-native.

**Comment by ruslan-bikkinin** [comment]
@benabbon thanks for letting us know. I've added this to our backlog, so we will pick it up in order of priority. You can track the progress here: #1058.

**Comment by benabbon** [comment]
Thank you @ruslan-bikkinin !
