### ISSUE TITLE
Add additional handler for ENOENT error when running "react-native -v"

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/vscode-react-native#1057]
In some cases when customer is using node version managers like nvm, asdf looking at the error
"Current workspace does not contain React Native projects" it's not obvious that one of the reason why this error is shown might be PATH misconfiguration on customer side, e.g. there are two independent node versions are installed (one is system and one is from nvm). 
To make it more clear to customers the following changes should be made:

* Add additional handlers for ENOENT error when running `react-native -v` ([here](https://github.com/microsoft/vscode-react-native/blob/352e0e8e2a2c06f22043b96f79b00d5e030ea3e1/src/common/commandExecutor.ts#L86) and [here](https://github.com/microsoft/vscode-react-native/blob/352e0e8e2a2c06f22043b96f79b00d5e030ea3e1/src/common/commandExecutor.ts#L129))
* Add reference to Troubleshooting section of readme explaining how to deal with such errors

**Comment by SounD120** [comment]
The error `Current workspace does not contain React Native projects` may be connected with incompatibility of [new React Native CLI](https://www.npmjs.com/package/@react-native-community/cli) with `react-native -v` command which the extension uses. Recommendation is to use the [legacy React Native CLI](https://www.npmjs.com/package/react-native-cli) version which supports this command.

**Comment by SounD120** [comment]
Hey guys. I am closing this because this enhancement will be implemented as part of #1101.
