### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abhinavkhajuria** [microsoft/vscode-react-native#1061]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `0.10.2`
- OS Version: `Linux x64 4.4.0-154-generic`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/dj/msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt`
[msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-react-native/files/3415690/msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Hi @abhinavkhajuria and thank you for the report. Could you please describe what did you do in VS Code before high cpu load message has appeared?

**Comment by SounD120** [comment]
@abhinavkhajuria 
![2019-08-07_11-03-32](https://user-images.githubusercontent.com/32372875/62606518-18967780-b905-11e9-853a-442db1d88371.png)
As seen in your cpu profile the most of the time took by WebSocket functions which are the part of `noice-rpc-json` package that we use to connect debugger with application. This means that for some reason that WebSocket hanged - some message from application to debugger or vice versa took more time than usual. Did you faced this behaviour just once? Also, it will be very helpful if you described on when high cpu load message has appeared.

**Comment by abhinavkhajuria** [comment]
Well, this issue can be replicated during hot reloading, (when saving the code), and the occurrence of this is once in 2-3 days, since last month so far as per my observation.  And it generally occurs 2-3 hours of intensive development on VSCode.

**Comment by SounD120** [comment]
@abhinavkhajuria Could you please describe your hardware configuration? Also, it will be very helpful for us if you can share minimal application demo in which this behavior is reproduces.

**Comment by SounD120** [comment]
@abhinavkhajuria Do you have a chance to look at this?

**Comment by SounD120** [comment]
Hi @abhinavkhajuria . Reproducible demo and your hardware configuration is important information to understand where the performance bottleneck is. I close this issue for now due to inactivity. If you face this behavior in future - please add information about your configuration and demo application.
