### ISSUE TITLE
Support for VS Code Remote Containers

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/vscode-react-native#1062]
According to [customer report](https://github.com/microsoft/vscode-react-native/issues/1012#issuecomment-514678431), extension may have problems running inside [VS Code Remote Containers](https://code.visualstudio.com/docs/remote/containers).
It should be investigated and if any problems is found it should be resolved.

**Comment by ruslan-bikkinin** [comment]
Hi @pheuter, could you please clarify your use case of VS Code Remote Containers with the extension? As for now, it's not clear for us how it can be incorporated into React Native apps developing.

**Comment by pheuter** [comment]
Sure, and feel free to correct me if I misunderstood the use case. From my perspective I see Remote Containers as the tool by which I can enforce a consistent development environment across platforms. By setting up a Docker image with all the necessary prerequisites, as well as controlling the version of Node, developers are then able to work on the codebase with tools like autocompletion and consistent local environments.

For this reason I don't see local development and debugging on a React Native project as any different than a Node / React project and assumed that it should work via Remote Containers just the same.

**Comment by ruslan-bikkinin** [comment]
@pheuter understood, so you want to put Node environment, potentially, Android SDK into a container, build and run RN app using the container and be able to debug it via VS Code, is that correct?

**Comment by keithmattix** [comment]
For what it's worth, I constantly use VS Code Remote Containers for my react-native development workflow, and have virtually no problems

**Comment by pheuter** [comment]
@ruslan-bikkinin That's exactly right.

**Comment by RedMickey** [comment]
Hi @pheuter, we have investigated this issue and added [documentation about debugging inside Docker containers](https://github.com/microsoft/vscode-react-native/blob/master/doc/containerization.md). I’m closing this issue, please feel free to open new ones if needed.

**Comment by pheuter** [comment]
@RedMickey Great, thanks!

**Comment by airtonix** [comment]
@RedMickey the linked page has been deleted.

**Comment by RedMickey** [comment]
Hi @airtonix, I've updated the link in the message:

> we investigated this issue and added documentation about debugging inside Docker containers ...

Also you can find all the up-to-date documentation for the React Native Tools extension in [README.md](https://github.com/microsoft/vscode-react-native/blob/master/README.md).
Thank you.
