### ISSUE TITLE
debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null

### ISSUE THREAD

**Issue by joebernard** [microsoft/vscode-react-native#1063]
## Actual Behavior
1. When attempting to debug my React Native app, the following error is returned in the debug console:

>  Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:792:62)

The affected line of code is within the `resolveSkipFiles` function of chromeDebugAdapter.
2. Removing `skipFiles` from my config does eliminate the error, and the debugger does start even with the error.

Here is my launch config that is causes the error:
```
{
      "name": "Debug iOS",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios",
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/.vscode/.react",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js"
      ]
    }
```

## Expected Behavior
1. This error should not be occurring.

## Software versions
- React-Native VS Code extension version: 0.10.2
- VSCode version: 1.36.1
- OS platform and version: MacOS 10.14.5
- NodeJS version: 10.15.3
- React Native version: 0.59.10
- Expo SDK version (include if relevant): N/A

**Comment by SounD120** [comment]
Hi @joebernard . This is a VS Code bug and the corresponding issue was created in the VS Code repo:
https://github.com/microsoft/vscode/issues/72412
As soon as this bug will be fixed this issue should be resolved.
