### ISSUE TITLE
Start packager on Attach to packager debug configuration

### ISSUE THREAD

**Issue by dimitarnestorov** [microsoft/vscode-react-native#1069]
After I built my app on my device/simulator I don't need to rebuild it every time I start working on it so I need a launch configuration that only starts 
 and attaches to the packager. For now I'm using Attach to packager, but every time I launch VSCode I need to run it twice, because the packager control buttons in the status bar are missing: 
![image](https://user-images.githubusercontent.com/8790386/62844300-09c71080-bcc9-11e9-815b-87e4e1bb8e70.png)
So I run Attach to packager so that they appear, then start packager, then run again Attach to packager.

I know it's possible now with three clicks, but it feels unintuitive when it can be one click.

**Comment by SounD120** [comment]
Hi @dimitarnestorov and thanks for reaching us. Could you please fill all the information as noted in our [issue template](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md)? It will help to better understand the situation from our side.

**Comment by dimitarnestorov** [comment]
## Actual Behavior
1. Stats bar packaged controls are missing. Run Attach to packager to trigger their appearance.
2. Start packager.
3. Attach to packager.

## Expected Behavior
1. Run Start packager.

## Software versions
- React-Native VS Code extension version: 0.10.2
- VSCode version: 1.37.0
- OS platform and version: macOS 10.15
- NodeJS version: 11
- React Native version: 0.59.9

Not sure how this info is valuable since my issue is a feature request.

**Comment by SounD120** [comment]
@dimitarnestorov Understood. Thanks for your feedback, we'll consider that and manage in order of priorities.

**Comment by SounD120** [comment]
Hi @dimitarnestorov . This feature is implemented as part of [React Native Tools Preview](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) and will be available shortly. In the future preview version will replace the current one, so this feature will be there either.
