### ISSUE TITLE
Add React Native Hermes JS engine debugging support

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1073]
# Description
Facebook released [Hermes JS engine](https://github.com/facebook/hermes) and implemented it to React Native Android. This engine is compatible with [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) so we need to investigate how to implement Hermes debugging in React Native Tools. 

# Important notice
Currently, Hermes doesn't fully support Chrome debugger protocol, so there are some gaps in its implementation. If something not working as expected will be noticed (like object inspector bugs) in the extension debugger then the same thing should be tested in the latest Chrome (Run app, attach to it in Chrome, check how Chrome debugger behave in the same debug scenario).
Here is the Hermes debugging [issues list](https://github.com/microsoft/vscode-react-native/issues/1099).

# Implementation roadmap
- [x] `Run Android` scenario support
- [x] `Attach to packager` scenario support
- [ ] `Debug in Expo` scenario support (Expo [doesn't support Hermes yet](https://github.com/expo/expo/issues/5259), here's [a roadmap for adding it](https://github.com/expo/expo/issues/4927))
- [x] Support debugging on Android devices
- [x] Support debugging on Android emulators
- [x] Command pallete commands support
    - [x] React Native: Reload App
    - [x] React Native: Show Dev Menu
    - [x] React Native: Run Android on Device
    - [x] React Native: Run Android on Emulator
    - [x] React Native: Run Element Inspector
    - [x] React Native: Start Packager
    - [x] React Native: Restart Packager
    - [x] React Native: Stop Packager
- [x] Support existing debug scenarios properties
    - [x] `cwd`
    - [x] `target`
    - [x] `env`
    - [x] `envFile`
    - [x] `trace`
    - [x] `address`
    - [x] `port`
    - [x] `logCatArguments`
    - [x] `runArguments`
    - [x] `skipFiles`
    - [x] `launchActivity`
    - [x] `variant`
    - [x] `sourceMaps`
    - [x] `sourceMapPathOverrides`
- [x] Support multi-root workspaces
- [x] Add tests

**Comment by ASKAR001** [comment]
G

**Comment by SounD120** [comment]
Hermes Direct debugging for the extension has been added. With respect to Hermes Expo - I think it might be tracked as another issue when it is released.
