### ISSUE TITLE
[Onboarding] Add empowering error message / experience for "Current workspace does not contain React Native projects" error

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/vscode-react-native#1077]
## Actual Behavior
1. Clone a React Native project from GitHub. Do not restore packages.
2. Open React Native directory in Visual Studio Code.
3. Open the Command Palette and run "React Native: Run iOS on Simulator" command.
4. Error: Current workspace does not contain React Native projects.
5. Run "npm install" in Visual Studio Code terminal.
6. Open the Command Palette and run "React Native: Run iOS on Simulator" command.
7. Error: Current workspace does not contain React Native projects.

## Expected Behavior
This experience does not provide an empowering error message that enables customers to fix this issue themselves. 

We should do one or more of the following:

-[OK] Add a more empowering error message when node packages for a project are not restored. "You must run `npm install` in Terminal prior to running your React Native project."
-[Better] Restore packages automatically in this scenario, then try to identify the workspace as "React Native".

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```
<img width="1680" alt="Screen Shot 2019-08-16 at 2 54 04 PM" src="https://user-images.githubusercontent.com/1091304/63192654-d538b900-c028-11e9-9691-85a7e8c9c55c.png">
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hey guys. I am closing this because this enhancement will be implemented as part of #1101.
