### ISSUE TITLE
[Onboarding] React Native workspace not identified correctly.

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/vscode-react-native#1078]
## Actual Behavior
1. Clone a React Native project from GitHub. Do not restore packages.
2. Open React Native directory in Visual Studio Code.
3. Open the Command Palette and run "React Native: Run iOS on Simulator" command.
4. Error: Current workspace does not contain React Native projects.
5. Run "npm install" in Visual Studio Code terminal.
6. Open the Command Palette and run "React Native: Run iOS on Simulator" command.
7. Error: Current workspace does not contain React Native projects.
8. Close the current folder.
9. Re-open in Visual Studio Code.
10. Open the Command Palette and run "React Native: Run iOS on Simulator" command.
11. React Native iOS app deploys successfully.

## Expected Behavior
Step #7 should pick up that I've restored my node modules and identify my workspace correctly as a React Native workspace without requiring me to re-open the directory.

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```
<img width="1680" alt="Screen Shot 2019-08-16 at 2 54 04 PM" src="https://user-images.githubusercontent.com/1091304/63192654-d538b900-c028-11e9-9691-85a7e8c9c55c.png">

**Comment by SounD120** [comment]
Hey guys. I am closing this because this enhancement will be implemented as part of #1101.
