### ISSUE TITLE
Remove requirement to have react-native-cli installed globally

### ISSUE THREAD

**Issue by hedgepigdaniel** [microsoft/vscode-react-native#1087]
## Actual Behavior
1. Do not install `react-native-cli` globally because it requires unecessary work to set up a dev environment. Instead only install it as a dependency in the project. Use `yarn run react-native ...` instead of `react-native ...`.
2. Try to debug react-native app using this extension
3. Find that the debugger fails to start as in https://github.com/microsoft/vscode-react-native/issues/1067 unless `react-native` is in `$PATH`

## Expected Behavior

The extension should do one of two things:
- automatically run `react-native` from the binaries installed in the project if possible
- allow overriding the location of the `react-native` binary in the debugger configuration

**Comment by SounD120** [comment]
Hey guys. I am closing this because this enhancement will be implemented as part of #1101.
