### ISSUE TITLE
 [loc][Query][vscode-react-native] Localizability of 0; "package.reactNative.launch.target.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-react-native#1090]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Target to run on. Possible values: 'simulator', 'device', '<Android emulator/device id>', '<iOS simulator/device name>'

File Name:
Src\vscode-extensions\vscode-react-native.xlf

==========================================
Query:
Please, could you confirm if the following part of this sentence must be in English?

'simulator', 'device', '<Android emulator/device id>', '<iOS simulator/device name>'

**Comment by SounD120** [comment]
Hi @PDostalek . 'simulator', 'device' are not localizable. '<Android emulator/device id>', '<iOS simulator/device name>' must be localized.

**Comment by SounD120** [comment]
Hi @PDostalek do you need any more help from my side?

**Comment by PDostalek** [comment]
Thanks for clarification, closing
