### ISSUE TITLE
 [loc][Query][vscode-react-native] Localizability of 0; "package.reactNative.launch.runArguments.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-react-native#1091]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Run arguments to be passed to 'react-native run-<platform>' command (override all other configuration params)

File Name:
Src\vscode-extensions\vscode-react-native.xlf
==========================================
Query:
Would you please check if "<platform>" is translatable? I left it in English because usually a command name is not translated. However, the reason I'm escalating this is that values enclosed with angle brackets are generally translated in UI contents.

**Comment by SounD120** [comment]
Hi @PDostalek . What do you mean by 
> Would you please check if "" is translatable?

**Comment by PDostalek** [comment]
Excuse me : That should be "Would you please check if "<platform>" is translatable"

**Comment by ruslan-bikkinin** [comment]
@PDostalek looks like your question is missing a text inside double quotes. So you sent us a question:
> Would you please check if "" is translatable?

but it doesn't make any sense because there is no text inside "".

**Comment by PDostalek** [comment]
Is "Run" verb, as in run "argument"?
Or noun as in the "run argument"?

**Comment by SounD120** [comment]
@PDostalek "run argument" is a noun in this context. "platform" in angled brackets is translatable.

**Comment by SounD120** [comment]
Hi @PDostalek do you need any more help from my side?

**Comment by PDostalek** [comment]
Thanks
