### ISSUE TITLE
 [loc][Query][vscode-react-native] Localizability of 0; "package.reactNative.attach.trace.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-react-native#1092]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Logging level in debugger process. May be useful for diagnostics. If set to "Trace" all debugger process logs will be available in 'Debug Console' output window.

File Name:
Src\vscode-extensions\vscode-react-native.xlf

Query:
We are not sure how to translate the "Logging" in "Logging level in debugger process. "
Is this
Logging "level" (verb)
or
"Logging level"? (noun)

**Comment by SounD120** [comment]
Hi @PDostalek . It is a noun in this context. `Logging level` means how much logs user wants to see. There are different logging levels such as "verbose", "error" etc.

**Comment by SounD120** [comment]
Hi @PDostalek . Do you have any questions?

**Comment by PDostalek** [comment]
Perfect, thanks !
