### ISSUE TITLE
 [loc][Query][vscode-react-native] Localizability of 0; "./src/nativeStrings.child_exec_failed"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-react-native#1098]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Child exec failed {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What does the placeholder {0} stand for? Name of the child process? Shouldn't it be before the word 'failed' then?

**Comment by SounD120** [comment]
Hi @PDostalek . It looks like this string is from [vscode-cpptools](https://github.com/microsoft/vscode-cpptools). Our team can only answer localization questions for vscode-react-native extension. I recommend to send your question to vscode-cpptools team.

**Comment by PDostalek** [comment]
Many thanks for reffering
