### ISSUE TITLE
Known issues with Hermes debugging

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-react-native#1099]
The extension has experimental support for React Native Hermes debugging. At this moment we know about several issues related to Hermes debugging. Please see the list of known issues below. 

The table of problems consists of two columns: first one illustrates the problem when debugging the app with Hermes enabled using prototype of the debugger in the extension, second one - when Chrome is used for debugging the app. 

If you faced new issues with React Native Hermes debugging with React Native Tools, please send them to the commentaries section of this issue.

## The list of issues

1) The debugger doesn’t show Global, Closure variables. The debugger provides only Local variables (function scope). Google Chrome displays Global variables, but Locals aren't shown.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.05.33.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.06.35.png" alt="drawing"/>|https://github.com/microsoft/vscode-chrome-debug-core/pull/548|

2) The debugger doesn’t show value of numeric variables.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.21.23.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.23.59.png" alt="drawing"/>|https://github.com/microsoft/vscode-chrome-debug-core/pull/548|

3) [The debugger shows additional VM_unknown calls in Call Stack](https://github.com/facebook/hermes/issues/168)
  <br/>The debugger displays all the calls as well as Google Chrome, but also adds unknown calls.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.10.11.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.10.44.png" alt="drawing"/>| #1187  |

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs123.txt) for problems 1, 2, 3.

4) The debugger doesn’t provide complete object data (For example, Date object, Map object - there is only an object name without internal data).
  If an object contains an array the debugger doesn't display the object's data.
  Google Chrome displays some objects correctly, but not all (e.g. Map object).
  The debugger doesn’t provide properties containing in “this” object.

  See the issue [Application crashes on debugging Map and Set objects](https://github.com/facebook/hermes/issues/167).

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.26.54.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.27.40.png" alt="drawing"/>||
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.11.34.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.46.06.png" alt="drawing"/>||

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs4-1.txt) for problem 4 - 1 table row.
  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs4-2.txt) for problem 4 - 2 table row.

5) The debugger doesn’t show local variables, if there is any array definition in a handler function.
  <br/>The debugger remove local variables data only when it comes an array definition. Google Chrome displays array's data.
  
  See the issue [Runtime.callFunctionOn returns an empty value on debugging](https://github.com/facebook/hermes/issues/166).

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |Before the array definition: <br/><img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.59.44.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.04.51.png" alt="drawing"/>|https://github.com/microsoft/vscode-chrome-debug-core/pull/548|
  |After the array definition: <br/><img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.00.01.png" alt="drawing"/>||https://github.com/microsoft/vscode-chrome-debug-core/pull/548|

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs5.txt) for problem 5.

**Comment by RedMickey** [comment]
This issue is out of date, please see [the new one](https://github.com/microsoft/vscode-react-native/issues/1266).

**Comment by Abuchtela** [comment]
<details><summary>Details</summary>
<p>
https://github.com/microsoft/vscode-react-native/issues/1266


</p>
</details>
