### ISSUE TITLE
Throwing errors at activation

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode-react-native#110]
I have isolated the plugin and running it in the Insiders build. So no other extension is causing this.

![image](https://cloud.githubusercontent.com/assets/1297882/13524943/66289cf8-e1fe-11e5-8751-e78a1beb7d95.png)

Win10.

**Comment by digeff** [comment]
Hi @csholmq, thanks for reporting this issue. Can you give us some more details about your scenario? We are interested in the following:

1. Which version of react-native is your project using?
2. Have you tried uninstalling our extension and checking if this is still happening?
3. Do you see any additional errors in any output channel or other windows?
4. Does the functionality of the extension work after getting this error (Can you debug? Can you use the commands from the command palette)?

**Comment by csholmq** [comment]
Certainly! 

1. React Native 0.20.0. React Native Tools 0.1.0.
2. Yes.
3. No errors outside of the developer console.
4. Don't know about debugging, but simulating on Android and iOS works. Pretty new to React Native unfortunately.

This is what pops up when I start an Android simulator. Still works though.
![screen shot 2016-03-04 at 19 55 31](https://cloud.githubusercontent.com/assets/1297882/13537022/31aee276-e243-11e5-976f-11aa21bdf344.png)

Seems to behave the same on OS X as well.

**Comment by digeff** [comment]
Thanks for the feedback! We've identified the issue you showed us on the second screenshot, and the fix will be included in the next release.

Are you still able to reproduce the first issue consistently? What are the exact steps that you are doing?

**Comment by csholmq** [comment]
First error is still reproducible. 

1. Open Code (Insiders build)
2. Toggle Developer Tools
3. Console

**Comment by MSLaguana** [comment]
I believe the languageIds error is harmless, but thanks for pointing it out and we'll fix it for the next release.

**Comment by csholmq** [comment]
:+1:
