### ISSUE TITLE
After some reload cycles, debugging stops working

### ISSUE THREAD

**Issue by ospfranco** [microsoft/vscode-react-native#1100]
Hey, some I'm having some trouble with the vscode setup.

## Actual Behavior
1. Start react-native via vscode
2. Develop with live-reload/hot-reload
3. After a few cycles the debugger will die and the device/simulator says `debugger is not ready`

## Expected Behavior
Even after several cycles the debugger keeps working

## Software versions
- React-Native VS Code extension version: 0.11.0
- VSCode version: 1.37.1
- OS platform and version: MacOS Mojave
- NodeJS version: 10.16.3
- React Native version: 0.59.9
- Expo SDK version (include if relevant):NO EXPO

## Outputs (Include if relevant)
No output except for debugger not ready message

**Comment by RedMickey** [comment]
Hi @ospfranco and thanks for reporting.
Could you please provide us minimal demo application where this behavior is reproduced? Also it will be very helpful for us if you also describe:
1) Algorithm of actions leading to this behavior
2) How often does this behavior occur
3) Your hardware configuration which you can get by running react-native info terminal command inside your project

**Comment by RedMickey** [comment]
Hi @ospfranco. Do you have a chance to look at this?

**Comment by ospfranco** [comment]
Hey, sorry, I did not have time to produce a working demo application, currently very busy, I can try to provide more information though:

1. I cannot really tell you any deterministic steps to reproduce it, since I'm developing a fairly large application, only that after several live reload/hot reload cycles the debugger starts to slow down and eventually completely stops

2. Fairly often on my daily work, at least a couple of times per day

3. Here is my info:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 4.41 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.0 - ~/.volta/tools/image/node/12.9.0/6.10.2/bin/node
      Yarn: 1.17.3 - ~/.volta/tools/image/yarn/1.17.3/bin/yarn
      npm: 6.10.2 - ~/.volta/tools/image/node/12.9.0/6.10.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.0
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
```

I'll try to produce a working sample, sometime soon

**Comment by RedMickey** [comment]
Hi @ospfranco. We'd like to remind you that your demo project will help us to investigate your problem. Do you have a chance to create a demo project?

**Comment by ospfranco** [comment]
Hey, I just tried to reproduce the issue with a new project using RN 0.60.+ and I cannot reproduce it, so it is probably from dark edge case in our codebase, unfortunately the project is too large for me to spend time trying to debug this.

I'll close this for now, but if I manage to reproduce the issue I'll re open it and post it here.
