### ISSUE TITLE
Add local React Native CLI support

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-react-native#1101]
We received a lot of feedback connected with current work approach with React Native CLI from the extension side. The most problems arise with the extension requirement is to have global React Native CLI installed and with current React Native project version checking mechanism. 

Below we collected the list of issues that should be covered by the extension's workflow refactoring.

## The list of expected changes
 - [x]  Allow to switch between local, global and custom React Native CLI compatible with Facebook React Native CLI.
   - [x] Add local/custom React Native CLI support for Debug Android scenario.
   - [x] Add local/custom React Native CLI support for Debug iOS scenario.
   - [x] Add local/custom React Native CLI support for Debug in Exponent scenario.
   - [x] Add local/custom React Native CLI support for all Command Palette extension commands.
   - [x] Add React Native global command parameter to `settings.json` to specify React Native CLI command name.
   - [x] If there isn't CLI parameter in `settings.json`, the extension will use local CLI approach by default.
 - [x] Check React Native version on local and global levels. 
    * Using local CLI. 
       1. The extension checks if there is `react-native` package in `node_modules`. If the package is found, then return its version.
       1. If the extension cannot find the package in `node_modules`, it will check if there is `react-native` in `package.json` dependences. If a version is found in `package.json` the extension will warn that it requires this package to be launched.
      1. Otherwise the extension throws an error that there isn't any `react-native` version in the selected folder.
     * Using global CLI. If there is global React Native CLI, the extension will take React Native project version via global CLI command. Otherwise repeat local CLI steps.
 - [x] Add a telemetry event to notify that the extension couldn't launch because of there isn't `react-native` package in `node_modules`.
 - [x] Add an opportunity to work with React Native project with the extension after `node_modules` restoration without requiring to re-open the directory.
 - [x] Add tests.

## The list of covered issues
1. [[Debug] react-native@ isn't supported #1094](https://github.com/microsoft/vscode-react-native/issues/1094) 
1. [Remove requirement to have react-native-cli installed globally #1087](https://github.com/microsoft/vscode-react-native/issues/1087)
1. [Add additional handler for ENOENT error when running "react-native -v" #1057](https://github.com/microsoft/vscode-react-native/issues/1057)
1.  [Need to set the default cli command #1095](https://github.com/microsoft/vscode-react-native/issues/1095)
1. [[Onboarding] React Native workspace not identified correctly. #1078](https://github.com/microsoft/vscode-react-native/issues/1078)
1. [[Onboarding] Add empowering error message / experience for "Current workspace does not contain React Native projects" error #1077](https://github.com/microsoft/vscode-react-native/issues/1077)
1. [Current workspace does not contain React Native projects #1102](https://github.com/microsoft/vscode-react-native/issues/1102)

**Comment by ScreamZ** [comment]
@RedMickey Released on prod ?

**Comment by SounD120** [comment]
Hi @ScreamZ . It is currently planned to be released next week.

**Comment by SounD120** [comment]
Hi @ScreamZ . React Native Tools v0.13.0 just have been released. Please try it out and let us know how it works for you.
