### ISSUE TITLE
TypeError when trying to use Attach to packager config

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/vscode-react-native#1108]
## Actual Behavior
1. Run Haul
2. Use attach to packager config
3. Run React Native app
4. Get error in debug console

## Expected Behavior
1. Run Haul
2. Use attach to packager config
3. Run React Native app
4. No errors

## Software versions
- React-Native VS Code extension version: 0.11.1
- VSCode version: 1.38.1
- OS platform and version: Windows Version 1809
- NodeJS version: v8.16.0
- React Native version: 0.59.0 (React Native Windows 0.59.0-vnext.178)
- Expo SDK version (include if relevant): N/A

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Launched debug configuration contains 'program' property which is deprecated and will be removed soon. Please replace it with: "cwd": "${workspaceFolder}"
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 18192
TypeError: (intermediate value)(...) is not a function
    at Object.<anonymous> (E:\repo\.vscode\.react\debuggerWorker.js:124:9)
    at Module._compile (module.js:650:14)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

## Other Info
In the `debuggerWorker.js` that the output is referring to, a semicolon seems to be missing.
Here's what the relevant part of file looks like:

```
var nativeObjectToString = Object.prototype.toString;
Object.prototype.toString = function() {
    if (this === process) {
        return '';
    } else {
        return nativeObjectToString.call(this);
    }
}

(function(self) {
        'use strict';
        if (self.fetch) {
          return
        }
        self.fetch = fetch;
        function fetch(url) {
            return new Promise((resolve, reject) => {
                var data = require("fs").readFileSync(url, 'utf8');
                resolve(
                    {
                        text: function () {
                            return data;
                        }
                    });
            });
        }
      })(global);
```

If I add a semicolon after the curly brace before the `function(self)` line after running the attach to packager config in VS Code and save before booting the React Native app, things work as expected (no error messages, the app boots just fine).

Looks like a change went in to similar code in the repo recently with [this commit](https://github.com/microsoft/vscode-react-native/commit/13a9942728c2e3d62b3a5353d0a74b05cd2c8919), so that may be causing the issue.

**Comment by rurikoaraki** [comment]
Thanks! Do you have an idea of when the new release will come out?

**Comment by SounD120** [comment]
Hi @rurikoaraki . I think this week.

**Comment by rurikoaraki** [comment]
Just verified that the new release fixes this issue for us. Thanks for the quick fix!
