### ISSUE TITLE
Syntax coloring not working.

### ISSUE THREAD

**Issue by awclives** [Microsoft/vscode-react-native#111]
I am trying to use VS Code for a simple react native project.  I installed the react native extension, and it seemed to load correctly, and it also recognizes the js files as react jsx.  However, the syntax color is not working correctly.  For instance, in the attached screenshot, View and Text are white.

Let me know what other information I can provide.

![screen shot 2016-03-04 at 1 57 51 pm](https://cloud.githubusercontent.com/assets/7936391/13538593/1e11210c-e211-11e5-9fcc-32ec99334040.png)

**Comment by MSLaguana** [comment]
If you look in the bottom right of your window, it says "JavaScript". If you click on that, you should be able to change it to "JavaScript React" which supports the highlighting for JSX constructs.

Unfortunately you will need to modify this setting manually for all files which end in `.js` rather than `.jsx` because the default colourising is based on file extension.

**Comment by MSLaguana** [comment]
If you would like all `.js` files globally to be considered as `.jsx` and support JSX colorization, you can install the [js-is-jsx](https://marketplace.visualstudio.com/items?itemName=eg2.js-is-jsx) extension.

**Comment by awclives** [comment]
Hmm, it still doesn't work for me.  Attached a screenshot with the language mode changed to JavaScript React.  I must be missing something?

![screen shot 2016-03-04 at 2 27 21 pm](https://cloud.githubusercontent.com/assets/7936391/13539340/5c5a629e-e215-11e5-94af-5bf27e2fb78e.png)

**Comment by joshuaskelton** [comment]
What version of VS Code are you running?

**Comment by awclives** [comment]
0.10.9

**Comment by digeff** [comment]
@awclives Could you please send us a screenshot of the contents of the folders .vscode\typings\react and .vscode\typings\react-native of you workspace? So we can check if the extension copied the correct files to those locations.

**Comment by awclives** [comment]
I don't have a typings directory.
![screen shot 2016-03-07 at 12 55 43 pm](https://cloud.githubusercontent.com/assets/7936391/13579616/109f6420-e464-11e5-84cc-253321191796.png)

**Comment by digeff** [comment]
@awclives Sorry about the misunderstanding. I meant the .vscode folder inside your react-native project next to the android, App, ios, and node_modules folders. Can you please show us that one?

**Comment by awclives** [comment]
Hope this does it.

![screen shot 2016-03-07 at 1 30 32 pm](https://cloud.githubusercontent.com/assets/7936391/13580672/e53d7b46-e468-11e5-9d64-73370db1572a.png)

**Comment by joshuaskelton** [comment]
It appears that the other jsx extension you have installed overwrites the colorization provided by VS Code. Try this:

1. Uninstall the jsx extension by TwentyChung
2. Change your theme to Monokai

**Comment by awclives** [comment]
View and Text are still white.  
i also uninstalled and reinstalled the react native extension.

![screen shot 2016-03-07 at 2 34 44 pm](https://cloud.githubusercontent.com/assets/7936391/13582410/cc0e3238-e471-11e5-9d2d-7273cf220176.png)

**Comment by joshuaskelton** [comment]
Did you switch the language to JavaScript React?

**Comment by awclives** [comment]
working fine now.  thank you.

**Comment by prudhviraju255** [comment]
Hi, I am also getting the same problem I am sharing my screen In that screen mongoose word should be blue color but is showing as white. I dont understand why it is showing like that?

**Comment by prudhviraju255** [comment]
![white](https://user-images.githubusercontent.com/42236690/44464340-268db280-a638-11e8-890e-b5902661540b.PNG)

**Comment by ruslan-bikkinin** [comment]
Hi @prudhviraju255, syntax highlighting as well as code hinting is not a part of React Native Tools extension anymore. I'd suggest you to file your question to [vscode](https://github.com/Microsoft/vscode/issues) tracker.

**Comment by CoderTeam1** [comment]
Is this called syntax coloring? I thought it was code colouring

**Comment by reelkaeshi** [comment]
guys i found a solution to fix this.

Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!

**Comment by michaelcoughlan** [comment]
@reelkaeshi is right. I had the same issue, I had my colour theme set as "Dark" but it needs to be "Dark+", then you'll get all of the correct highlighting. Thanks!

**Comment by Kiisi-Felix-Destiny** [comment]
> guys i found a solution to fix this.
> 
> Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!

Thanks it worked

**Comment by jttreadway2020** [comment]
I have a project with only two files at the moment, index.html and package.json.  Package.json is colored correctly corresponding to .json files.   However, when I created the .html file it was not colored correctly. 

Ex.
![Example](https://user-images.githubusercontent.com/94445840/162288068-157eeca1-8040-48be-87ce-4f37cca04808.png)

I have tried several things to no avail... can someone please assist me?

**Comment by Coalregion105** [comment]
> guys i found a solution to fix this.
> 
> Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!

Changing it to dark+ worked for me, then as soon as I type it reverts back to white coloring, but only for certain things, I'm using C# and some of the namespaces are white, and some colored, but when I save there are no errors

**Comment by andrew-mendes** [comment]
> > guys i found a solution to fix this.
> > Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!
> 
> Thanks it worked

I just did this and it seems it partially worked for me. That first line with addEventListener should be colored as well, am I right?
<img width="438" alt="Code_HjZDpWBIDl" src="https://user-images.githubusercontent.com/83541996/185465205-c3af347b-c980-4124-a231-41f3994cf487.png">

**Comment by andrew-mendes** [comment]
> > guys i found a solution to fix this.
> > Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!
> 
> Thanks it worked

It worked for me as well. A bit of additional information if anyone still has this problem after changing the theme to Dark+:
Mine was partially working, then I clicked the format  the bottom bar that was set to JavaScript and changed it to Auto Detect. After this it fixed it all.
![38dEKmCqVn](https://user-images.githubusercontent.com/83541996/185465975-4cae9b7d-1b63-4505-bb2e-b33ca40accab.jpg)

**Comment by ipanda-Ai** [comment]
![image](https://user-images.githubusercontent.com/91093545/202349671-cb614b5b-5149-4065-904e-d570f37e2f89.png)

Having the same problem!
Don't know what i did but it turned all my jsx, ts, js files text white.  
I changed to Dark+ but nothing happened.  
restarted my PC and installed VSCode.  nothing happened,  please help.

**Comment by phiho2419** [comment]
>


> ![image](https://user-images.githubusercontent.com/91093545/202349671-cb614b5b-5149-4065-904e-d570f37e2f89.png)
> 
> Having the same problem! Don't know what i did but it turned all my jsx, ts, js files text white. I changed to Dark+ but nothing happened. restarted my PC and installed VSCode. nothing happened, please help.

![Screenshot_20221117_104756](https://user-images.githubusercontent.com/63381716/202350581-860d4c80-3907-43b9-b90f-1792200574ac.png)
Same to me !!!

**Comment by the-abe-train** [comment]
Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly.
https://github.com/microsoft/vscode-typescript-next/issues/46

**Comment by Czer0C** [comment]
> Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)

Can confirm that this works for me.

**Comment by Darshana-Waasala** [comment]
> Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)

I just updated the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and got the same issue. By disabling it, the syntax coloring came back.

**Comment by deny-wijaya** [comment]
> ![image](https://user-images.githubusercontent.com/91093545/202349671-cb614b5b-5149-4065-904e-d570f37e2f89.png)
> 
> Having the same problem! Don't know what i did but it turned all my jsx, ts, js files text white. I changed to Dark+ but nothing happened. restarted my PC and installed VSCode. nothing happened, please help.

downgrade plugin JavaScript and TypeScript Nightly to v5.0.20221115 , works for me

**Comment by jcerone** [comment]
@deny-wijaya can confirm this worked for me as well. Thanks!

**Comment by Geek1216** [comment]
Thanks, it is worked for me too :)

**Comment by huynhthaianhhd** [comment]
> Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)

Thanks, this works for me

**Comment by xvrx** [comment]
i just fixed it by disabling all @installed extensions, but i don't know which extension specifically caused the problem. Try finding out the culprit by enabling one-by-one

**Comment by kabanooovd** [comment]
![image](https://user-images.githubusercontent.com/86196300/202392921-a521866d-305b-4bfd-8048-87d61bd252be.png)
Had the same problem. 
Just uninstalled this ext and its wirked for me 
https://github.com/microsoft/vscode-typescript-next/issues/46

**Comment by fo-nhan** [comment]
![image](https://user-images.githubusercontent.com/84773005/202397448-fcde68af-7893-430d-b456-e782dc929cb2.png)
Giống @kabanooovd tôi chỉ cần gỡ cài đặt nó và mọi thứ trở lại như cũ

**Comment by AyudanteMorton** [comment]
v5.0.20221116 breaks my colour theme. Downgrading to the previous version fixes the issue though.

**Comment by benjaminpeto** [comment]
> Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)


Unfortunately it's not only the `JavaScript & TypeScript Nightly` theme effected. `Winter is Coming Theme` also has the same issue. **By disabling solves the issue**, _however I quite like that theme_ 😄 

<img width="1512" alt="Screenshot 2022-11-17 at 09 44 02" src="https://user-images.githubusercontent.com/66526461/202413828-3ab4a6d4-5a6a-45b3-ba5d-c218c6ce7b75.png">

**Comment by munj1** [comment]
> 

It works for me!

**Comment by bluesigor** [comment]
> > Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)
> 
> I just updated the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and got the same issue. By disabling it, the syntax coloring came back.

worked for me, thanks!!

**Comment by geekypradip** [comment]
> > > Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)
> > 
> > 
> > I just updated the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and got the same issue. By disabling it, the syntax coloring came back.
> 
> worked for me, thanks!!

it's the problem with there latest version , I shifted to previous version my issue has been gone

**Comment by NitinSirsath** [comment]
> > > > Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)
> > > 
> > > 
> > > I just updated the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and got the same issue. By disabling it, the syntax coloring came back.
> > 
> > 
> > worked for me, thanks!!
> 
> it's the problem with there latest version , I shifted to previous version my issue has been gone

Please share steps of  how to jump on previous version

**Comment by NitinSirsath** [comment]
In my case disabling extension ```JavaScript and TypeScript``` by microsoft  solved the issue. Just disable all the extensions and check which one is causing the problem.

**Comment by AABHINAAV** [comment]
Current version (5.0.20221116) of JavaScript and TypeScript Nightly is breaking color schemes of VSCode.
You can either downgrade the version of this extension or use Dark+ theme until this issue gets fixed.

**Comment by Nathusan** [comment]
Wow, I never realised how much I relied on syntax colouring! 
You guys are life savers!

**Comment by lucaoskaique** [comment]
> > Also having this issue as of the past few hours. It's related to an update to the extension JavaScript and TypeScript Nightly. [microsoft/vscode-typescript-next#46](https://github.com/microsoft/vscode-typescript-next/issues/46)
> 
> I just updated the [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and got the same issue. By disabling it, the syntax coloring came back.

Disabled and everything got back to normal. I didn't even installed that extension

**Comment by whoisseth** [comment]
> JavaScript and TypeScript Nightly v5.0.20221116 breaks my color theme. Downgrading to the previous version fixes the issue though.
Thanks, this solves the issue I was also facing the same issue.

**Comment by SaulMoreyra** [comment]
> > ![image](https://user-images.githubusercontent.com/91093545/202349671-cb614b5b-5149-4065-904e-d570f37e2f89.png)
> > Having the same problem! Don't know what i did but it turned all my jsx, ts, js files text white. I changed to Dark+ but nothing happened. restarted my PC and installed VSCode. nothing happened, please help.
> 
> downgrade plugin JavaScript and TypeScript Nightly to v5.0.20221115 , works for me

It work's for me!

**Comment by IAkashMondal** [comment]
MY old theme with Firefly pro bright
![app js fetching](https://user-images.githubusercontent.com/102036593/202517975-ead01f70-5c73-48ab-8853-3fb026b2738c.jpg)

now all text in white color:
![NOW](https://user-images.githubusercontent.com/102036593/202518162-77d76856-a543-43e4-9435-876e5cd13a7b.jpg)

and changing to "Dark+" isn't the solution because it wasn't my previous theme?

**Comment by IAkashMondal** [comment]
JavaScript and TypeScript Nightly  needs reload problem solved

**Comment by YounesseAmhend** [comment]
just disable prettier

**Comment by sahilbakoru** [comment]
**@joshuaskelton Thank you! **

**Comment by AmmarAlkhooly98** [comment]
For me disabling the extension "JavaScript Atom Grammar" solved the problem. If you do not have this extension and still facing this issue, try disabling each extension and chacking your syntax coloring after each extension is disabled.
Have a great day ❤️

**Comment by bahadir11** [comment]
> guys i found a solution to fix this.
> 
> Open your VS code and press the settings icon at the bottom left. Then come to the color theme section and choose the dark+ theme. at least my problem was solved this way, maybe you can solve it with this way too. Have a good day everyone!

this worked thanks
