### ISSUE TITLE
Arrow function loses its context

### ISSUE THREAD

**Issue by NeliHarbuzava** [microsoft/vscode-react-native#1116]
## Actual Behavior
0. I am running the RN app on Android emulator using _Debug Android_ configuration (or manually running **react-native run-android** and _Attach to packager_ config).
1. I have a component that has structure (simplified) just like this:
```
class Login extends React.Component {

    constructor(props) {
        super(props);

        console.log(this); // this points to Login component (which is right)

        this.state = {
            Username: null,
            Password: null
        };
    };

    componentDidMount() {
        console.log(this); // this points to Login component (which is right)

        const test = () => {
            console.log(this); // this points to global (which is wrong)
        };

        test();
    };

    render() {
        return (<View />)
    }
}
```
2. In **componentDidMount** method I make some calls using arrow functions, inside which I am calling methods of Login component via this. However, for some reason, whiile debugging via React Native Tools arrow function test loses its context and points to the global context, not Login component. So in the end all of Login methods called in arrow functions does not work. I assume, that this will be in other components too.
3. The app works very well in production and has no such problem while debugging via Chrome: this inside arrow function will point to Login component.

## Expected Behavior
1. While executing arrow function **test**() inside **componentDidMount**() method, _this_ inside **test**() function should point to Login component.

## Software versions
- "react-native": "0.59.10"
- React Native Tools 0.11.1
- VSCode Version: 1.38.1 (user setup)
- OS Windows 10 Pro, version 1903
- NodeJS version: 10.16.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 39510

Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future
Running application "myapp" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager.

[Info] Packager is already running.

[Warning] Error: React Native Packager running outside of VS Code. If you want to debug please use the 'Attach to packager' option

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Info] Enable JS Debugging

[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\Projects\Project 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1403/1403), done.

[Info] Enable JS Debugging

Starting custom debugger by executing: echo A debugger is not needed:  "d:\Projects\Project"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

Starting custom debugger by executing: echo A debugger is not needed:  "d:\Projects\Project"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] debugger listening on port 23750
console.ts:137 [Extension Host] (node:10880) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] (node:10880) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
```

**UPDATE**: I found that if I disable _Remote debugging_ and just see logs in _DEBUG CONSOLE_, everything works fine. But without `Remote debugging` I cannot debug the app on breakpoints. When I am enabling _Remote debugging_ again, the problem with invalid _this_ variable goes again.

**Comment by SounD120** [comment]
Hey @EricCornelson could you please take a look on this as it looks like node-debug2 issue?

**Comment by EricCornelson** [comment]
On the surface, this looks like another incarnation of this issue: https://github.com/microsoft/vscode/issues/12066, though I'd have to see what React Native is compiling arrow functions to. If we know that it's mapping, for example, `this` => `_this`, then we can work around the issue by just watching the `_this` variable. You should also be able to see the closure scope in the variables pane to inspect the object's fields, e.g.: 
![_thisexample](https://user-images.githubusercontent.com/38218905/65899698-20085900-e369-11e9-8a9e-af8100c72e9f.png)

**Comment by SounD120** [comment]
@EricCornelson I found out how it maps in React Native. It maps to `_this<NUMBER>`, here is the example for that specific case:
![image](https://user-images.githubusercontent.com/32372875/65949812-924e6b80-e445-11e9-9901-a6e73f874d8b.png)

**Comment by SounD120** [comment]
Hi @NeliHarbuzava , @EricCornelson . Since the behavior is connected with a VS Code bug and the corresponding issue was created in the VS Code repo I am closing that issue:
https://github.com/microsoft/vscode/issues/12066
As soon as this bug will be fixed this issue should be resolved.
