### ISSUE TITLE
Debugging doesn't start on iOS and Android

### ISSUE THREAD

**Issue by guveniscan** [microsoft/vscode-react-native#1121]
## Actual Behavior
1. After pressing run button to debug Android or iOS app, the debug bar quickly dismisses and app doesn't run
![ScreenRecording2019-09-29at22344](https://user-images.githubusercontent.com/3617820/65839043-02f06d80-e30a-11e9-9ae3-41b6b51e8a9b.gif)

## Expected Behavior
1. It should trigger iOS simulator or Android device in the same way `react-native run-ios` or `react-native run-android` do

## Software versions
- React-Native VS Code extension version: 0.11.2
- VSCode version: 1.38.1
- OS platform and version: macOS 10.14.6
- NodeJS version: v10.13.0
- React Native version: 0.61.1
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
No output
```

`launch.json`

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Debug iOS",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios"
        },
        {
            "name": "Debug Android",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "android"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/start",
            "trace": "verbose"
        }
    ]
}
```

I have recently upgraded to RN 0.61.1 before that things were running smoothly. Manually running `react-native run-ios` and `react-native run-android` works.

**Comment by RedMickey** [comment]
Hi @guveniscan and thanks for reaching us. Could you please try to do the following:

1. Remove `node_modules` from your project
1. Execute `npm i`
1. Restart VS Code window
1. Try to debug

If after these steps the problem remains, could you please send us your `package.json` content?

**Comment by guveniscan** [comment]
It persists, this is my package.json:

```
{
  "name": "xxxxxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "0.0.26",
    "@types/react-redux": "^7.1.4",
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-modal": "^11.4.0",
    "react-native-reanimated": "^1.3.0",
    "react-native-root-toast": "^3.1.2",
    "react-navigation": "^3.13.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "@types/jest": "24.0.15",
    "@types/react": "16.8.23",
    "@types/react-native": "0.60.2",
    "@types/react-test-renderer": "16.9.0",
    "babel-jest": "24.8.0",
    "eslint": "6.1.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.9.0",
    "redux-devtools": "^3.5.0",
    "typescript": "3.5.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by RedMickey** [comment]
@guveniscan then could you please run `react-native --version` command and send us its output?
Could you please also add the following parameter to iOS debug scenario in your `launch.json` file:
```
"trace": "verbose"
```
Then launch debugging and please send us the following logs outputs:
## Outputs
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native:Run iOS in ListBox):
```
```

**Comment by guveniscan** [comment]
Thanks for the follow up. There is no output to `react-native --version`

The output of `react-native start --verbose` looked fishy though with current release: 0.61.1 and cached release 0.60.0:
<img width="1081" alt="Screen Shot 2019-09-30 at 13 43 37" src="https://user-images.githubusercontent.com/3617820/65876031-bf891400-e388-11e9-9140-e7a095e358e9.png">

Also I am missing both `React-Native` and `React-Native:Run iOS` from the listbox at output tab

<img width="1087" alt="Screen Shot 2019-09-30 at 13 41 41" src="https://user-images.githubusercontent.com/3617820/65875706-1b06d200-e388-11e9-9f8c-e4ff30445000.png">

**Comment by RedMickey** [comment]
@guveniscan сould you please try to reinstall your current `react-native-cli` globally and then try to run `Debug iOS` scenario again?
```
npm uninstall -g react-native-cli
npm uninstall -g @react-native-community/cli
npm install -g react-native-cli
```

**Comment by guveniscan** [comment]
@RedMickey that worked, sorry for all the trouble. can we confirm the issue was because `react-native-cli` was installed locally?

**Comment by SounD120** [comment]
@guveniscan If `react-native-cli` was installed locally, yes, because it is [required](https://github.com/microsoft/vscode-react-native#getting-started) for the extension to have `react-native-cli` to be installed globally.

**Comment by galla-devlop** [comment]
> @RedMickey that worked, sorry for all the trouble. can we confirm the issue was because `react-native-cli` was installed locally?

how do you know whether it is installed locally or globally ??

**Comment by galla-devlop** [comment]
> @guveniscan сould you please try to reinstall your current `react-native-cli` globally and then try to run `Debug iOS` scenario again? You can use the following commands:
> 
> ```
> npm uninstall -g react-native-cli
> npm uninstall -g @react-native-community/cli
> npm install -g react-native-cli
> ```

Where should we need to run this commands ?? i am new to react native , not getting exactly .

**Comment by guveniscan** [comment]
@galla-devlop those are global npm commands (will install/uninstall packages globally on your device) so you can run in any folder (your project folder or any other folder) through your shell

**Comment by Mmmkay** [comment]
It still wont work for me. Debugging Toolbar opens and disappers after 3-4 seconds. I also have no output or `React-Native` in the output list box. `react-native-cli` is installed global and running it manually via `react-native run-android` works flawless.

Output of `react-native --version`:
> react-native-cli: 2.0.1
> react-native: 0.61.2

Here is my `launch.json`
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Android",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "trace": "verbose"
        }
    ]
}
```
and the `package.json`
```javascript
{
  "name": "TestProject2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.2"
  },
  "devDependencies": {
    "@babel/core": "7.6.4",
    "@babel/runtime": "7.6.3",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Version of Node is 12.9.1 and im using Windows 10 64Bit with the latest updates. OS is completly fresh (2 days old).
