### ISSUE TITLE
[Feature Request] add command "React Native: Start LogCat Monitor"

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/vscode-react-native#1136]
![image](https://user-images.githubusercontent.com/19633881/66645254-2f32b500-ec4d-11e9-8659-ca68e61e8ff6.png)

It would be easier if i can only run logcat without running command `React Native: Run Android on Device` just to start logcat when i'm disconnected my device from adb, and reconnect my devices,

because when i disconnected my devices and reconnect, logcat not showing new log from monitor

## Actual Behavior
1. connect device to adb
2. run command `React Native: Run Android on Device`
3. logCat Show in Output Panel
4. disconnect device from adb
5. need to repeated step 1 just to run logCat

## Expected Behavior
1. connect device to adb
2. run command `React Native: Run Android on Device`
3. logCat Show in Output Panel
4. disconnect device from adb
5. reconnect device to adb
6. run command `React Native: Start LogCat Monitor`

## Software versions
- React-Native VS Code extension version: 0.12.1
- VSCode version: 1.37.1
- OS platform and version: Android (Oreo) 
- NodeJS version: 10.16.0
- React Native version: 0.60.5
- Expo SDK version (include if relevant): Not used

**Comment by zxccvvv** [comment]
Hi @SounD120 sorry to mentioning you,

I just need this feature ASAP, or if it's not possible, could you tell me how can i run `adb logcat -s [ip:port of phone] *:S ReactNative:V ReactNativeJS:V` and let the log show in `Output panel` like picture below?

![image](https://user-images.githubusercontent.com/19633881/66977723-3f291980-f0d1-11e9-9c0c-d63492352ac4.png)

**Comment by SounD120** [comment]
Hi @zxccvvv and thanks for your feature request. We'll consider that and manage in order of priorities. But if you'd like to contribute to the project - you can try to create command pallette commands for that using our [contribution guide](https://github.com/microsoft/vscode-react-native/blob/master/CONTRIBUTING.md).
Also I recommend to see the following code references, they might be helpful for better understanding of the extension code:
1) [LogCat Monitor](https://github.com/microsoft/vscode-react-native/blob/master/src/extension/android/logCatMonitor.ts)
2) [LogCat Monitor start in React Native application launch context](https://github.com/microsoft/vscode-react-native/blob/8411a7add0eb3565f53f70285384909e7b4a5049/src/extension/android/androidPlatform.ts#L249-L257)
3) [CommandPalletteHandler where the new commands could be added](https://github.com/microsoft/vscode-react-native/blob/master/src/extension/commandPaletteHandler.ts)

**Comment by SounD120** [comment]
Hi @zxccvvv . This feature was implemented and will be available in the next [React Native Tools (Preview)](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) release.
