### ISSUE TITLE
Vscode react native  debug in exponent App is not opening

### ISSUE THREAD

**Issue by snownoop** [microsoft/vscode-react-native#1137]
## Actual Behavior
1. Created clean project with expo init (Mac Os catalina, latest Xcode, expo 35.0.0, latest vscode react native extension)
2. expo start works good for App, app is opening in IOS simulator and working fine.
3. When i triying to use debug in exponent inside VScode in both lan and tunnel ways, i opening simulator and see this message
<img width="377" alt="Screenshot 2019-10-13 at 23 18 39" src="https://user-images.githubusercontent.com/4146589/66721868-d8c1a400-ee0f-11e9-9aeb-57df061f0c94.png">

there are no errors in vscode debug console.
When i click on try again, i see that console output changes inside vscode, so there is connection between vscode debug in expo and simulator expo app, but real app is not loading and keep showing this screen.
Same for my iphone.

## Expected Behavior
Debug in exponent should work as before. 

## Software versions
- React-Native VS Code extension version: 0.12.1, with reinstalled @expo/xdl check:
https://github.com/microsoft/vscode-react-native/issues/1060
- VSCode version: 1.39.1
- OS platform and version: Mac Os catalina
- NodeJS version: 10.16.0
- React Native version: 35
- Expo SDK version (include if relevant): 35

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
no erros in clonsole
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
-
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
-
```

**Comment by SounD120** [comment]
Hi @snownoop and thanks for reaching us. This looks similar to https://github.com/microsoft/vscode-react-native/issues/1109. Could you please try to check the content of your `.expo/settings.json` file?
There should be no `"https": false` line in it, if you find one please delete it and try to run `Debug in Exponent` scenario.
Please let us know if it helped.

**Comment by snownoop** [comment]
@SounD120 you are my saver ! Working good. Removing `https: false` helped me. Thanks, we can close the issue.

**Comment by SounD120** [comment]
@snownoop Great! Feel free to open new ones if needed.

**Comment by netpoe** [comment]
@snownoop can you please share your `.vscode/launch.json` config? I'm having a similar issue and removing `https: false` didn't work for me. 

thanks
