### ISSUE TITLE
Error while executing command 'react-native.cmd run-windows --proxy --no-packager': Error while executing command 'react-native.cmd run-windows --proxy --no-packager' (error code 101)

### ISSUE THREAD

**Issue by admin-excior** [microsoft/vscode-react-native#1152]
## Actual Behavior
1. Error debug 

## Expected Behavior
1. Debug and run react-native windows app  

## Software versions
- React-Native VS Code extension version: 
React native tools version 0.12.1
- VSCode version: 
1.39.2
x64
- OS platform and version: 
Windows 10 home 
Version 1809
- NodeJS version: 
v12.9.1
- React Native version: 
0.60.0
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.8.2
Could not debug. Error while executing command 'react-native.cmd run-windows --proxy --no-packager': Error while executing command 'react-native.cmd run-windows --proxy --no-packager' (error code 101)
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=windows

Loading dependency graph, done.
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

 BUNDLE  [windows, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (568/568), done.

jest-haste-map: watch error:
  Error: EBUSY: resource busy or locked, open 'c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\msbuild.ProjectImports.zip'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:350:35)
    at getContent (c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:149:41)
    at Object.<anonymous> (c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:199:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:78:24)
    at _next (c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:98:9)
    at c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:103:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (c:\Users\manqo\OneDrive - Excior\Projects\Kola-Reservation\room_display_0_60_6\node_modules\jest-haste-map\build\worker.js:95:12)

[Error] Error: Error while executing command 'react-native.cmd run-windows --proxy --no-packager': Error while executing command 'react-native.cmd run-windows --proxy --no-packager' (error code 101)

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
(node:12308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:243
workbench.desktop.main.js:sourcemap:243 [Extension Host] (node:12308) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.desktop.main.js:sourcemap:243

**Comment by SounD120** [comment]
Hi @admin-excior and thanks for reaching us. Could you please also add the version of `react-native-windows` version you are using?

**Comment by admin-excior** [comment]
Hi there @SounD120. Thanks for the prompt response. I tried using react-native run-windows and I get the following errors.

1. 
![image](https://user-images.githubusercontent.com/54540616/67856623-a5745a00-fb1d-11e9-8169-d8106e0a9d87.png)
I checked and have run apps before so my laptop is definitely on developer mode.

2. On the npm command output
![image](https://user-images.githubusercontent.com/54540616/67856715-d5bbf880-fb1d-11e9-9be5-3d6291f70fd8.png)

I'm using react-native-windows vnext. i.e. "react-native-windows": "0.60.0-vnext.52",

**Comment by SounD120** [comment]
@admin-excior As seen from your logs the same issue persists even without the extension. It looks like a React Native Windows bug. I recommend you to describe your issue in [React Native for Windows repository](https://github.com/microsoft/react-native-windows). I am closing this issue for now. Please feel free to reopen if needed.

**Comment by admin-excior** [comment]
Thanks.

**Comment by mofax** [comment]
Was this issue opened in the [React Native for windows repo](https://github.com/microsoft/react-native-windows)? If so, could you please provide a link for the sake of people who have the same problem and land here first.
