### ISSUE TITLE
FAILURE: Build failed with an exception. while running react-native run-android 

### ISSUE THREAD

**Issue by galla-devlop** [microsoft/vscode-react-native#1153]
## Actual Behavior
1. Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
2. 

## Expected Behavior
1. App has to launch in emulator 
2. 

## Software versions
- VSCode version: 1.33.1
- OS platform and version: Windows_NT x64 10.0.17763
- NodeJS version: 10.2.0
- React Native version: 0.61.2
- React-native-cli: 2.0.1

## Outputs (Include if relevant)
D:\LearningWS\React Native\FirstApp\TestProjs>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 864 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Configure project :
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TestProjs'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TestProjs'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (D:\LearningWS\React Native\FirstApp\TestProjs\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (D:\LearningWS\React Native\FirstApp\TestProjs\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (D:\LearningWS\React Native\FirstApp\TestProjs\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

D:\LearningWS\React Native\FirstApp\TestProjs>

```
PASTE OUTPUT HERE
```
[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager.

[Info] Packager is already running.

[Warning] Error: React Native Packager running outside of VS Code. If you want to debug please use the 'Attach to packager' option

[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager. Then try the restart packager again.

```
PASTE OUTPUT HERE
```
Source path error: ENOENT: no such file or directory, scandir 'D:\LearningWS\React Native\FirstApp\TestProjs/app/src/main\'
Check the "appSrcRoot" and "apkFile" entries in launch.json
```
PASTE OUTPUT HERE
```
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.5-all.zip'.
A problem occurred configuring root project 'TestProjs'.
Could not resolve all artifacts for configuration ':classpath'.
Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
Required by:
    project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
Could not resolve net.java:jvnet-parent:4.
Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
Content is not allowed in prolog.

**Comment by RedMickey** [comment]
Hi @galla-devlop, thanks for reaching us. It looks like the issue is relevant to [the one that you've already asked here several days ago](https://github.com/microsoft/vscode-react-native/issues/1141).
This seems not related to the extension functionality (as it doesn't work when you try to run it from scratch either) so not sure that we could help here. 
I believe correct place to address this question would be [react-native repository](https://github.com/facebook/react-native) as there is an issue with its installation itself. 
Thank you!

**Comment by SHAHEERSHAHZADofficial** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Cannot resolve external dependency com.google.gms:google-services:4.3.10 because no repositories are defined.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
