### ISSUE TITLE
/bin/sh: 1: adb: not found

### ISSUE THREAD

**Issue by thejacer87** [microsoft/vscode-react-native#1196]
## Actual Behavior
1. Select "React native: Run Android on device/emulator" or "Debug Android".
2. Get error "adb not found".

## Expected Behavior
1. Run app on android device/emulator

## Software versions
- React-Native VS Code extension version: 0.14.0
- VSCode version: 1.41.1
- OS platform and version: 4.19.98-1-MANJARO 
- NodeJS version:  13.7
- React Native version: "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz"
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: linux x64
Adapter node: v12.4.0 x64
vscode-chrome-debug-core: 6.8.8
Could not debug. Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: adb: command not found
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point doesn't exist neither at index.js nor index.android.js. Skip prewarming...

[Info] Building and running application.

[Error] Error: Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: adb: command not found
```
i read through https://github.com/microsoft/vscode-react-native/issues/723 and tried to follow the fix there (moving the android path variables from .bashrc to .bash_profile), and it didn't change anything. 

here's my path: 

```
$ echo $PATH
/home/thejacer87/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/thejacer87/Android/flutter/bin:/home/thejacer87/Android/Sdk/platform-tools
```

when i tried running `code .` from the terminal, then tried to debug, i got a slightly different output:

```
Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point doesn't exist neither at index.js nor index.android.js. Skip prewarming...

[Info] Building and running application.

[Error] Error: Android project not found. (error code 1203)
```

**Comment by RedMickey** [comment]
Hi @thejacer87 and thanks for reaching us. We tried to reproduce this problem and found out that it occurred in case trying to debug an Expo application using `Debug Android` scenario. There is `Debug in Exponent` scenario in the extension to debug such applications. 
Could you please try to launch `Debug in Exponent` scenario for debugging?

Seems that you have correct configuration for terminal, but for some reasons system graphical shell doesn't pick up `PATH` parameters.
Could you please also try to do the following changes in `~/.bashrc` and `.~/.bash_profile` files to provide correct `PATH` parameters to the graphical shell:
- In `.~/.bash_profile`:
  - You can move React Native configurations to `~/.bashrc` file
  - Add the following code: 
  ```
  if [ -f $HOME/.bashrc ]; then
          source $HOME/.bashrc
  fi
  ```
  - In terminal run `source ~/.bash_profile`
- In terminal run `source ~/.bashrc`
- Restart VS Code editor

Also please make sure that `~/.profile` contains something like this to forward all settings from `~/.bashrc` :
```
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```
If there isn't such code in `~/.profile` add it to this file:

1. Run `nano ~/.profile`
1. Add the code above and save the changes
1. Run `source ~/.profile`
1. Restart VS Code editor

Please let us know about your results.

**Comment by thejacer87** [comment]
was able to get it running with debug in exponent. thanks. im just getting started with RN so didnt know there was a difference
