### ISSUE TITLE
Error: Could not found executable

### ISSUE THREAD

**Issue by ramyareye** [microsoft/vscode-react-native#1198]
## Actual Behavior
1. After starting a new project, it's running well on XCode but got this one on VSCode :
`Could not debug. Could not found executable in /path/ios/build/*/Build/Products/Debug-iphonesimulator (error code 403)`

## Expected Behavior
1. it should just works :)
I think it's related to cli new update [here](https://github.com/react-native-community/cli/commit/25a2c44c4a52341110e7a64d681aaefaf4726a97) - [as described here](https://callstack.com/blog/react-native-cli-3-1-0-and-4-0-0-whats-new/)
a new watch mode added to version 3.1 and it may breaks something
My previous projects with cli < 3.1 (3.0.4) work well on VSCode

## Software versions
- React-Native VS Code extension version:  1.14.0 - latest
- VSCode version: latest: 1.42.1 
- OS platform and version:  mac
- NodeJS version: 12
- React Native version: 0.61.5

**Comment by ramyareye** [comment]
@SounD120 @RedMickey thanks :) I should wait till next minor release to use, right?

**Comment by SounD120** [comment]
Hi @ramyareye . Yes this fix will be released in the next update. We'll let you know.

**Comment by SounD120** [comment]
Hi @ramyareye . React Native Tools v0.14.1 just have been released.

**Comment by ramyareye** [comment]
@SounD120 a question, did you work on new watch mode, r & d keys? 

![](https://static.callstack.com/wp/2020/02/13172315/New-watch-mode-in-React-Native-CLI-3.1.0-768x441.png)

Thanks

**Comment by SounD120** [comment]
Hi @ramyareye . No, we didn't. We have the command palette commands for that in the extension
![image](https://user-images.githubusercontent.com/32372875/75888151-fb466f00-5e3b-11ea-9346-0f92cd0437db.png)

**Comment by ramyareye** [comment]
I think these are different. New commands are inside metro bundler which there weren't before. 
I don't really know if the API is the same.

Anyway at the time the "d" command doesn't work in metro bundler.
