### ISSUE TITLE
Could not debug. Error while executing command 'd:\MyOffice\X\WebApp\FR\web\DevProject\x-wrist-react-native\node_modules\.bin\react-native.cmd run-android --no-packager'

### ISSUE THREAD

**Issue by RichardsonVJohnson** [microsoft/vscode-react-native#1202]
Problem : can't debug react-native android on real device throwing above error.

Steps
--------------------
1. Android Device connected
2. Selected Debug Android in VS Code
3. Causing the following error
Could not debug. Error while executing command 'd:\MyOffice\X\WebApp\FR\web\DevProject\x-wrist-react-native\node_modules\.bin\react-native.cmd run-android --no-packager': Error while executing command 'd:\MyOffice\X\WebApp\FR\web\DevProject\x-wrist-react-native\node_modules\.bin\react-native.cmd run-android --no-packager' (error code 101)

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.31
- OS platform and version: Windows 10
- NodeJS version: 13
- React Native version: 16.9.0

Debug Console
-------------------------------
OS: win32 x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.8.8
Could not debug. Error while executing command 'd:\MyOffice\X\WebApp\FR\web\DevProject\x-wrist-react-native\node_modules\.bin\react-native.cmd run-android --no-packager': Error while executing command 'd:\MyOffice\X\WebApp\FR\web\DevProject\x-wrist-react-native\node_modules\.bin\react-native.cmd run-android --no-packager' (error code 101)

**Comment by SounD120** [comment]
Hi @RichardsonVJohnson and thanks for your question. It seems that there was a problem while buikding and starting the Android application. Could you please check the `View -> Toggle Output -> React Native, View -> Toggle Output -> React Native: Run android` output window and attach outputs to this issue?

**Comment by RichardsonVJohnson** [comment]
Sure , here it is 

I tried again and now 

Debug Console shows 
--------------------------
Could not debug. Unknown error: not all success patterns were matched. 
 It means that "react-native run-android" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run android output windows. (error code 712)


Output [Run-android]
--------------------------
BUILD SUCCESSFUL in 48s
543 actionable tasks: 3 executed, 540 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync  C:\Users\Login\AppData\Local\Android\Sdk/platform-tools/adb ENOENT
info Starting the app on "388aa8b77d2b"...

**Comment by SounD120** [comment]
@RichardsonVJohnson The error pointed below means that the extension is unable to locate Android Debug Bridge(adb) at path `C:\Users\Login\AppData\Local\Android\Sdk\platform-tools\`.
```
C:\Users\Login\AppData\Local\Android\Sdk/platform-tools/adb ENOENT
```
It can mean that Android SDK is configured incorrectly or installed not in `C:\Users\Login\AppData\Local\Android\Sdk`. Please ensure that your PATH environment variable is configured correctly for React Native development and Android SDK in installed correctly. You can find more information about environment settings in [official React Native documentation](https://facebook.github.io/react-native/docs/getting-started.html).

**Comment by RichardsonVJohnson** [comment]
@SounD120 , sdk path and platform tool paths are already set , but don't know where its merged like this
app is running with react-native run-android, but its happening while debugging

**Comment by RichardsonVJohnson** [comment]
is there any checklist for solving this issue ?

**Comment by RichardsonVJohnson** [comment]
the problem is identified so that let's figured out the solution
