### ISSUE TITLE
using "target": "iPhone Name" opens iPhone 8 Simulator

### ISSUE THREAD

**Issue by rafaelmaeuer** [microsoft/vscode-react-native#1206]
## Actual Behavior
When more than one device is connected it complains `error Could not find a device named: "true". Available devices: - iPhone Name1 (c0b...d20) - iPhone Name2 (b11...a59)`.
When using `"target": "iPhone Name1"` in Debug config it opens up iPhone 8 Simulator instead of using "iPhone Name1" as target.

## Expected Behavior
When using `"target": "iPhone Name1"` in Debug config the App should be installed on connected device "iPhone Name1" instead of iPhone 8 Simulator.

## Software versions
- React-Native VS Code extension version: 0.14.1
- VSCode version: 1.42.1 (VSCodium)
- OS platform and version: macOS Catalina (10.15.3)
- NodeJS version: 13.7.0
- React Native version: 0.61.5
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
error Could not find a device named: "true". Available devices:
  - iPhone Name1 (c0b...d20)
  - iPhone Name2 (b11...a59)
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
Error: No application in the Launch Services database matches the input criteria.
```

**Comment by SounD120** [comment]
Hi @rafaelmaeuer and thanks for reaching us. As for now `target` argument is not yet supports launching using a specific device, as a workaround you can use `runArguments` options [as described in documentation](https://github.com/microsoft/vscode-react-native/blob/master/doc/debugging.md#debugging-on-ios-device).

**Comment by SounD120** [comment]
Hi @rafaelmaeuer . This feature was added in #1207 and will be released in next extension version. After that you'll be able to specify the exact iOS device to run as follows:
```
"target": "device=iPhone Name1"
```
