### ISSUE TITLE
xcodebuild workspace using wrong name

### ISSUE THREAD

**Issue by andyeskridge** [microsoft/vscode-react-native#1212]
## Actual Behavior
1. Launching a debug session for ios results in an error that the workspace doesn't exist

## Expected Behavior
1. Debug configuration picks up the correct .xcworkspace name

## Software versions
- React-Native VS Code extension version: 0.14.1
- VSCode version: 1.42.1
- OS platform and version: macOS 10.15.3
- NodeJS version: 13.8.0
- React Native version: 0.61.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Could not debug. Command failed: xcodebuild -workspace notifyUnstable.xcworkspace -scheme notifyUnstable -sdk iphonesimulator -configuration Debug -showBuildSettings
xcodebuild: error: 'notifyUnstable.xcworkspace' does not exist.
```

It looks like the changes in https://github.com/microsoft/vscode-react-native/pull/1199 aren't working for my current project. It is looking for a workspace that has the same name as a scheme in my workspace.

**Comment by RedMickey** [comment]
Hi @andyeskridge and thanks for reaching us. The cause of the problem was found out, and now we are working on a bugfix.

**Comment by RedMickey** [comment]
@andyeskridge, we saw your comments in the [PR](https://github.com/microsoft/vscode-react-native/pull/1213) that should fix this issue. Could you please let us know more about your project configuration? It also will be very helpful for us if you send us a demo project, so we could take into account all its features and test carefully the changes.

**Comment by RedMickey** [comment]
@andyeskridge, do you have a chance to look at this?

**Comment by SounD120** [comment]
Hi @andyeskridge . It looks like we were able to reproduce [your specific case](https://github.com/microsoft/vscode-react-native/pull/1213#issuecomment-595301382), so we proposed a fix for it. It will be released in a new extension version. Please feel free to open new issues or reopen this one in case of any problems with the extensions. Thanks.
