### ISSUE TITLE
env and envFile launch parameters are not passing to the packager

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1235]
It appears that the `env` and `envFile` launch parameters are being passed to the `react-native run-android` command, but are *NOT* being passed to the packager.

In my case, I'm using `babel-plugin-transform-inline-environment-variables` which enables access to the packager's ENV via `process.env.VARIABLE_NAME`.

_Originally posted by @svvitale in https://github.com/microsoft/vscode-react-native/issues/566#issuecomment-603945006_

**Comment by JiglioNero** [comment]
@svvitale Hello, in the next version there will be an opportunity to transfer custom environment variables from `env` and `envFile` to Packager. More details: https://github.com/microsoft/vscode-react-native#custom-environment-variables
