### ISSUE TITLE
The link to "setting up debug environments" is wrong in the extension's page on vscode

### ISSUE THREAD

**Issue by giladpn** [microsoft/vscode-react-native#1258]
## Actual Behavior
In VSCode, please go to the extension "react native tools" and click it to get the description page. Roll down to the section that says
"You can debug your app on an Android emulator, Android device or iOS simulator, iOS device. Please see the documentation for debugging on iOS devices [...]
**See Setting up debug environment for more details**."

The link provided to "setting up debug environments" returns a 404. This link is:
https://github.com/Microsoft/vscode-react-native/blob/master/doc/debugging.md

## Expected Behavior
A working link with a detailed description of how to debug on Android and iOS, please.

## Software versions
- React-Native VS Code extension version: 0.14.2
- VSCode version: 1.44.2
- OS platform and version: Windows 10 build 1909
- NodeJS version: 16.4.4
- React Native version: 4.7.0
- Expo SDK version (include if relevant): n/a

**Comment by SounD120** [comment]
Hi @giladpn thanks for questioning. The documentation readme file has been rewritten and now all the documentation has gathered in updated [Readme.md](https://github.com/microsoft/vscode-react-native/blob/master/README.md) file. Once the extension will be updated to the new 0.15.0 version, the extension description in the VS Code marketplace will update too and this problem should be resolved.
We'll let you know when it will happen.

**Comment by giladpn** [comment]
Thanks for the prompt response. Reading that [Readme.md](https://github.com/microsoft/vscode-react-native/blob/master/README.md) file is indeed an improvement. Please feel free to close this issue and if I have follow up issues I will open them separately. Thanks!
