### ISSUE TITLE
Better logging experience

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1272]
Reading logs is something all developers need to do when debugging their apps and we could improve that experience for React Native developers.
Some of the ideas we've received are around enabling filtering, colors, better formatting, etc. similar to what Chrome Dev Tools has.
Taking into account the limitations of VS Code, what are the things we can do to improve the developer experience?

**Comment by molant** [comment]
A comment from one of our users:

>  I don't like the fact that everything is printed to output. I like having multiple terminals to keep things separated (packages, deployment, log-android)

**Comment by SounD120** [comment]
Hi @molant, I've made a comparison of current stable React Native Tools logging and a preview version one:
The extension logging is divided by several output channels: 
* React Native - main extension channel which collects outputs from React Native Packager and shows critical errors in the extension
* These channels spawns only when the specific launch scenario is executed
    * React Native: Run Android
        * LogCat monitor(to get LogCat output from Android device)
    * React Native: Run iOS
    * React Native: Run exponent
* Verbose logs (these logs are shown up if only `trace: "verbose"` option is enabled)
    * React Native Chrome Proxy(preview only, contains logging outputs which was sent to debugger and from debugger)
    * In stable version expanded logs are printed into Debug Console
    * Global extension errors are controlled by VS Code and are printed in VS Code Developer Tools
* Debug Console which is used to receive application logs (`console.log` and other RN app `std` outputs) 

Please see the outputs examples below: 
* Debug Console

|RNT current debug console|RNT preview debug console|
|---|---|
|![image](https://user-images.githubusercontent.com/32372875/88521132-33259d00-cffd-11ea-91ae-9ae5a0c39f0e.png)|![image](https://user-images.githubusercontent.com/32372875/88520949-f3f74c00-cffc-11ea-9cfb-e18f4d18859b.png)|

* React Native Channel

React Native channel looks the same way in both stable and preview version so I just provide one example of logs in this channel: 
[RNT React Native channel example.txt](https://github.com/microsoft/vscode-react-native/files/4980951/RNT.React.Native.channel.example.txt)


* React Native: Run Android

These logs includes only the `react-native run-android` command outputs which are mostly Gradle build logs, so these outputs have not been changed from stable to preview version: [RNT Run Android channel example.txt](https://github.com/microsoft/vscode-react-native/files/4980978/RNT.Run.Android.channel.example.txt)

* LogCat Monitor example (is spawned on Debug Android scenario only)

[RNT LogCat Monitor example.txt](https://github.com/microsoft/vscode-react-native/files/4981110/RNT.LogCat.Monitor.example.txt)


* React Native: Run exponent

```log
[Info] Starting React Native Packager.

[Info] Application is running on Expo. Open your Expo app at exp://x.x.x.x:19000 to see it.

[Info] Application is running on Expo. Please shake device and select 'Debug JS Remotely' to enable debugging.

```
* React Native: Run iOS

These logs includes only the `react-native run-ios` command outputs which are mostly XCode build logs, so these outputs have not been changed from stable to preview version: [RNT Run ios channel example.txt](https://github.com/microsoft/vscode-react-native/files/4981077/RNT.Run.ios.channel.example.txt)

* Verbose logs

These logs are used for diagnostic purposes only, so they are subject to change and it makes no sense to provide them here.

**Note: color highlighting in Output channels is currently not implemented.**
Please let me know if you'd like to know more about logging specific of the extension.

**Comment by molant** [comment]
Thanks for the update @SounD120 !

Can a user switch between channels?
Also I've seen there are some "hacks" to [colorize channels](https://github.com/microsoft/vscode/issues/11005). Could this apply to us?

**Comment by SounD120** [comment]
@molant Sure, we can switch between channels if they were created. For example if you launch `Debug Android` scenario - channel `Run Android` is spawned to the output channels list. 
This is how it looks:
![image](https://user-images.githubusercontent.com/32372875/88901063-f8b83c00-d258-11ea-8a6b-4f717c8354b2.png)

With respect to the "hacks" - yes, I saw these ones, I think we can implement that solution.

**Comment by molant** [comment]
Awesome,

What do you think about updating the documentation showing how people can change between channels and what each channel is for and also doing the coloring?

Maybe we could split this into 2 different PRs: docs + coloring.

**Comment by SounD120** [comment]
@molant Sounds good. I think we can pick this up when finish preparing the debug adapter for direct iOS debugging (#1226).

**Comment by EzioLi01** [comment]
Close this issue since all related PRs are completed. Please open a new issue if you still have other feature requests.
