### ISSUE TITLE
Debbuger not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by leobragatti** [microsoft/vscode-react-native#1273]
When I try to start the debbuger on Android Simulator, i keep getting the error:
[Error] Error: Could not start the packager.

I just using a default config in launch.json:
```
{
    "name": "Debug Android",
    "cwd": "${workspaceFolder}",
    "type": "reactnative",
    "request": "launch",
    "platform": "android",
    "trace": "verbose",
}
```

## Software versions
- React-Native VS Code extension version: 0.15.0
- VSCode version: 1.45.0
- OS platform and version: Ubuntu 20.04 LTS
- NodeJS version: 12.16.3
- React Native version: 0.62.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: linux x64
Adapter node: v12.8.1 x64
vscode-chrome-debug-core: 6.8.8
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"reactnative","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsBreakpointLocationsRequest":false,"supportsLogPoints":true,"supportsTerminateRequest":true}}
'projectRoot' setting is not found: /home/leonardo/Programming/repos/JavaScript/KeepAlives/.vscode/settings.json file doesn't exist or its content is incorrect.
Handle launch request: {
  "name": "Debug Android",
  "cwd": "/home/leonardo/Programming/repos/JavaScript/KeepAlives",
  "type": "reactnative",
  "request": "launch",
  "platform": "android",
  "trace": "verbose",
  "__sessionId": "2b26eb39-38ca-4da1-a5bb-9f4f7c541964",
  "sourceMaps": true
}
Could not debug. Could not start the packager.
To client: {"seq":0,"type":"event","event":"terminated"}
From client: disconnect({"restart":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"FullSessionStatistics/SourceMaps/Overrides","data":{"aspNetClientAppFallbackCount":0}}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Debug] 'react-native' package with value '0.62.2' is found in 'dependencies' section of package.json

[Info] Starting Packager

[Debug] Executing command: /home/leonardo/Programming/repos/JavaScript/KeepAlives/node_modules/.bin/react-native start --port 8081

[Error] Error: Could not start the packager.
```

**Comment by RedMickey** [comment]
Hi @leobragatti and thanks for reaching us. Could you please try to run the packager using React Native CLI command `npx react-native start` and send us its output in case of an error?
If there are any problems, please run the command `npx react-native doctor` and send us its output too.
Please let us know about your results.

**Comment by leobragatti** [comment]
@RedMickey When i run native CLI command `npx react-native start` it works fine.
In any case, I ran `npx react-native doctor' and here's the output:
```
Common
 ✖ Node.js
   - Version found: N/A
   - Version supported: >= 8.3
 ✖ npm
   - Version found: N/A
   - Version supported: >= 4.x

Android
 ✓ JDK
 ✓ ANDROID_HOME
 ✓ Android SDK - Required for building and installing your app on Android

Errors:   2
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.

Attempting to fix 2 issues...

Common
 ✖ Node.js
   Read more about how to download Node.js at https://nodejs.org/en/download/
 ✖ npm
   Read more about how to download node at https://nodejs.org/
```

I don't know it's related to the fact I installed node via snap store

**Comment by RedMickey** [comment]
@leobragatti, could you please check if there are Node.js and npm in `PATH` variable? Please run the command `echo $PATH` and send us its output.

**Comment by leobragatti** [comment]
@RedMickey here's the output, as you aksed:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

As you can see, `/snap/bin` is in the `PATH`.
And when I ran `which node`, the output is `/snap/bin/node`

**Comment by RedMickey** [comment]
@leobragatti, we tried to reproduce the problem on Ubuntu 20.04. We installed Node.js using Snap Store and we could start the packager in the extension despite the errors, that `react-native doctor` shows.
As seen from your `PATH`, it seems it doesn't contain paths for Android SDK. For example, we have the following `PATH` content:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/Android/Sdk/emulator:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/tools/bin:/home/user/Android/Sdk/platform-tools:/home/user/Android/Sdk/emulator:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/tools/bin:/home/user/Android/Sdk/platform-tools
```
Could you please check if your dev environment is configured correctly according to [Setting up the development environment](https://reactnative.dev/docs/environment-setup) guide?

**Comment by leobragatti** [comment]
@RedMickey Sorry, I didn't sent the full PATH. Here's the full path:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/files/Programming/Android/emulator:/files/Programming/Android/tools:/files/Programming/Android/tools/bin:/files/Programming/Android/platform-tools:/home/leonardo/.antigen/bundles/zsh-users/zsh-syntax-highlighting
```

I configured the enviroment correctly, as explained in the guide. In MacOS works fine.
As I pointed in this [comment](https://github.com/microsoft/vscode-react-native/issues/1273#issuecomment-627338028), the Android SDK is in the Path.

**Comment by SounD120** [comment]
Hi @leobragatti . There may have been an internal failure in the packager process. Could you please also check if there any outputs in Developer Tools? You can find them by opening `Help -> Toggle Developer Tools -> Select Console tab`. 
Also, do you have `.env` file in your project root?

**Comment by leobragatti** [comment]
Hi @SounD120,
I've attached the console output with process.env
[console.log](https://github.com/microsoft/vscode-react-native/files/4650559/console.log)

And I don't have a `.env` file in my project

**Comment by SounD120** [comment]
@leobragatti It seems that the paths are correct as `snap/bin` folder is in the PATH in VS Code. Could you please try to install React Native Tools v0.14.2 from the VS Code Marketplace? 
You can do this using the following instruction:
* Open `Extensions` tab in VS Code
* Find React Native Tools entry and do the right click on it
* Select `Install Another version` and choose `0.14.2`
* Close VS Code
* Open VS Code

Please let us know if this helped and the packager started to launch after that.

**Comment by leobragatti** [comment]
@SounD120 I did what you suggested, but the packager failed to start.
There's anything else I can do?

**Comment by SounD120** [comment]
@leobragatti React Native Tools v0.16.0 just have been released, please try it out and let us know how the packager launches on this version.

**Comment by leobragatti** [comment]
@SounD120 I've updated the extension, but still no success
Here's the output:
```
[Debug] Begin to activate...

[Debug] Extension version: 0.16.0

[Debug] Projects found: 1

[Debug] Add project: /home/leonardo/Programming/repos/JavaScript/KeepAlives

[Debug] React Native version: 0.62.2

[Debug] Command palette: added folder /home/leonardo/Programming/repos/JavaScript/KeepAlives

[Debug] Extension messaging server started at /tmp/vscode-reactnative-58b686d471b463e05d3e355fa7ba232a2826d2c9267356ca26998fb2dd9d050d.sock.

[Debug] 'react-native' package with value '0.62.2' is found in 'dependencies' section of package.json

[Info] Starting Packager

[Debug] Executing command: /home/leonardo/Programming/repos/JavaScript/KeepAlives/node_modules/.bin/react-native start --port 8081

[Error] Error: Could not start the packager.
```

**Comment by leobragatti** [comment]
@SounD120 I uninstalled the vscode from snap store and installed the .deb package.
I don't know why, but it worked. It looks like there's a problem when using the snap packages, because it's not the first app I had problem. I uninstalled Inkscape for the same reason

**Comment by SounD120** [comment]
@leobragatti Maybe snap packages works with PATH in a different way. Anyway, glad to hear that your problem is resolved, so I am closing this issue. Feel free to add new details or reopen the issue if needed.
