### ISSUE TITLE
Allow for simulator selection before debugging

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1275]
> Way to select simulator.

This is a request I've heard from a few developers when talking to them directly.
I believe right now we launch the first one or developers need to create custom entries in `launch.json`, is that correct?

Will need to explore how this could look like.

**Comment by RedMickey** [comment]
Hi @molant. Yes, for now, by default the extension uses the first device or emulator found. If a user wants to use a specific device or emulator for debugging, it's required to add `target` field to a debug configuration in `launch.json` file and specify the concrete device or emulator.
We'll investigate how we can improve this workflow.

**Comment by SounD120** [comment]
@molant @RedMickey I think we can enhance that as part of #1278 debug configuration provider refactoring. Added more context here: https://github.com/microsoft/vscode-react-native/issues/1278#issuecomment-627442740

**Comment by JiglioNero** [comment]
Selection of a virtual device for [iOS](https://github.com/microsoft/vscode-react-native/pull/1374) and [Android](https://github.com/microsoft/vscode-react-native/pull/1361) platforms were implemented.
