### ISSUE TITLE
Run the application without debugging

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1276]
Right now we only launch the application in debug mode. A couple developers have proposed having a way to run it in no debug mode as well.

**Comment by RedMickey** [comment]
Hi @molant, the extension provides four Command Palette commands for launching an application:
* Run Android on Emulator
* Run Android on Device
* Run iOS on Simulator
* Run iOS on Device

These commands allow to start an application without debugging. [Here](https://github.com/microsoft/vscode-react-native#react-native-commands-in-the-command-palette) you can find more info about the extension's commands.

**Comment by molant** [comment]
But the `Run` commands actually start the application and attach the debugger, right?
I think what the developer was asking was to run the app and not attach the debugger.

**Comment by molant** [comment]
@RedMickey I'm re-reading this 🤦‍♂️
I think this is again another issue related to #1278
I'll reach out to the developer see if they were expecting to have an option to do run without debugging when running F5.

**Comment by sregg** [comment]
Yes, I'm expecting an option in `launch.json`.
I have a 6 different launch configs (dev/stage/prod x android/ios) and would like to have a way to launch them from the green play button in the Run tab but with no debugger when I don't need it.

**Comment by molant** [comment]
Let's do it in preview then

**Comment by RedMickey** [comment]
We added three scenarios in React Native Tools Preview which allow to run applications without debugging:
- Run Android (Preview)
- Run iOS (Preview)
- Run Android Hermes (Preview) - Experimental

To try them out, please, install [React Native Tools Preview version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview).
