### ISSUE TITLE
[Bug] React native debugger stuck 

### ISSUE THREAD

**Issue by bijaykanshinew** [microsoft/vscode-react-native#1288]
Earlier, it was working fine. But today it stopped working.
Once i click "debug androd(<project name>)" . it launch the emulator but breakpoint stopped working, it is continue to showing line moving from left to right as you can see in below link

https://ibb.co/W2Mc88m

It launch emulator but didn't start debug. it doesn't show any error.

react-native-cli: 2.0.1
react-native: 0.62.2
ubuntu: 18.04

**Comment by SounD120** [comment]
Hi @bijaykanshinew and thanks for reaching us. Could you please try to launch the debug scenario and then check the outputs in VS Code Developer Tools Console? You can find it this way `Help -> Toggle Developer Tools -> Select Console tab`.

**Comment by SounD120** [comment]
@bijaykanshinew Have you seen my recommendation above?

**Comment by bijaykanshinew** [comment]
@SounD120 i didn't see anything in "console tab"
https://ibb.co/pfsM6bC
FYI -> i am using React native tool 0.16.0

**Comment by SounD120** [comment]
@bijaykanshinew Based on screenshot it looks like the Remote Debugging on your device is disabled. Could you please open React Native Developer Menu as described in the [official React Native documentation](https://reactnative.dev/docs/debugging#accessing-the-in-app-developer-menu) and enable Remote Debugging?

**Comment by bijaykanshinew** [comment]
@SounD120 i don't see remote debugging js option in emulator
https://ibb.co/FbmhH5Q
Pressing "ctrl + M" close the emulator.

**Comment by SounD120** [comment]
@bijaykanshinew It was renamed to `Debug` in the most recent versions, so just press this button.

**Comment by bijaykanshinew** [comment]
@SounD120 thanks, it's working :)
