### ISSUE TITLE
[Feature] Icon only status bar display 

### ISSUE THREAD

**Issue by phatmann** [microsoft/vscode-react-native#1289]
# 🚀 Feature request

What do you want to be added?

Instead of text in status bar, just show an icon to indicate status. This icon should show when VS Code starts to make it easy to start packager. 

## What scenarios will this solve?

I don't use RN status bar because it is too wide.

## What will this allow you to do? Will this benefit other developers?

Show RN in status bar on smaller screens

**Comment by molant** [comment]
Are you talking about [this status bar](https://reactnative.dev/docs/statusbar)

If so that is part of the core of React Native and I suggest you open an issue in [their repo](https://github.com/facebook/react-native/issues). This is repo is for the [VS Code React Native Tools Extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native)

**Comment by phatmann** [comment]
I mean the status bar in VS Code. 

Tony

**Comment by molant** [comment]
Are talking about E in this picture?

![image](https://user-images.githubusercontent.com/606594/82673268-6a8b5e00-9bf6-11ea-9c51-2f255bc4a17f.png)

**Comment by phatmann** [comment]
Yep!

Tony

**Comment by molant** [comment]
I'm having some problems understanding the following:

> This icon should show when VS Code starts to make it easy to start packager.

Do you want to start debugging by clicking on this icon? Do you want to do something else? Does the icon change depending on the status (and if so, what are the statuses you are expecting)?

**Comment by phatmann** [comment]
Right now the RN extension only shows in status bar after running packagerat least once. This means starting the packager cannot be done from status bar. I’d like if it always showed up, in “stopped” mode. 

Tony

**Comment by phatmann** [comment]
Today the RN extension shows its status (started or stopped) in the status bar. The icon would go the same thing. 

Tony

**Comment by JiglioNero** [comment]
Hi, @phatmann 
The behavior will be changed in the next version of React Native Tools. The React Native Packager status bar commands behavior has been changed and now the extension will be activated if the path `node-modules/react-native` exists in project root, and the Packager Status Indicator will look like this:

![image](https://user-images.githubusercontent.com/35271042/87446574-4f155180-c5ae-11ea-8faa-3899a9bb0f3f.gif)

**Comment by phatmann** [comment]
This issue should not have been closed. The request was to hide the text "React Native Packager" from the status bar and just show play/stop and restart icons.

**Comment by JiglioNero** [comment]
Hi @phatmann
We add several variants of Packager Status Indicator representation.
Now you can switch representation of Packager Status Indicator in VSCode Status Bar with `react-native.packager.status-indicator` option in `settings.json` to short or full variant. Full variant is default.
|Variant|Indicator representation|
|---|---|
|Full (default)|![image](https://user-images.githubusercontent.com/43934531/87786180-2ad1a300-c842-11ea-9440-6770a52c9f6a.png)|
|Short|![image](https://user-images.githubusercontent.com/43934531/87786256-4dfc5280-c842-11ea-85cc-d49611ef7da6.png)|

**Comment by phatmann** [comment]
That's awesome! Well done.
