### ISSUE TITLE
[Feature] Bundle extension

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1294]
# 🚀 Feature request

What do you want to be added?

From [VS Code - Bundling Extensions](https://code.visualstudio.com/api/working-with-extensions/bundling-extension):

>  Loading 100 small files is much slower than loading one large file. That's why we recommend bundling. Bundling is the process of combining multiple small source files into a single file.

There is more information in the link above.

## What scenarios will this solve?

This should make the extension to load faster.

**Comment by EricCornelson** [comment]
In case it helps, [here](https://github.com/microsoft/vscode-js-debug/blob/c485cf391030dd9da18e32a65181f25e9c3e64df/gulpfile.js#L181) is a link to how vscode-js-debug is creating the webpack config and running webpack to create the bundle.
