### ISSUE TITLE
[Feature] Nightly builds

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1295]
# 🚀 Feature request

What do you want to be added?

Have a nightly build of the extension so I can test the latest code.

There is some guidance in the [VS Code documentation](https://code.visualstudio.com/api/working-with-extensions/continuous-integration)

**Comment by molant** [comment]
@SounD120 the new preview extension is [available in the marketplace](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview).

Are the releases done automatically? Can we close this issue?

**Comment by SounD120** [comment]
Yes, sure. I forgot to do this :)
