### ISSUE TITLE
[Feature] Prompt user to test the preview extension

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1306]
# 🚀 Feature request

We would like to get more telemetry from the [preview extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview). We should prompt users to give it a try and let them now they can use it side by side with the stable one.

Things to take into account:

- Use the built-in vs code toast.
- Don't prompt the user right after installation and/or activation
- Do not ask the user again if they say no (at least for the same version, but I'm tempted to not prompt the user for at least 3 months).
- Do not ask all users. Ideally we should have a percentage that we can change remotely so we can start small and grow it when our confidence is higher.
- This should go into master although we could use this prompt logic for other things in the future so maybe we should have separate commits so we could cherry-pick them

## What scenarios will this solve?

This will help us catch bugs faster and reach stable status with the new debugger sooner.

**Comment by SounD120** [comment]
@molant For now we don't have a mechanism to control the percentage. We can show it for all users only once and for example after a constant timeout. Are you talking about creating a server to control such metrics?

**Comment by molant** [comment]
I definitely don't think we should show it to all users. Don't think we are ready for all of them to test and I'm sure quite a few will be annoyed.

If we don't want/can't have a server to control the percentage then a poor person's solution could be to use GitHub directly. We could use GitHub pages and have one page that has a json with the different experiments we want to run and to what percentage of the population it should go (in this case there's just one experiment).

A couple extra things I've thought about:
- We should show the prompt only to users that are running the debugger
- We should have a "quick guide" on how to migrate/copy the stable configurations to work with the new one, or even automate that process if it is just "copy/pasting" and changing the `type`.

**Comment by SounD120** [comment]
@molant Hm, sounds interesting. Do you mean that, for example, the Github page should return object like this:
```json
{"percentage": "0.3"}
```
so we could connect to the endpoint on extension activation and calculate if we should show the prompt?
I think we can trigger that view if only the debug scenario was triggered and the probability was calculated based on percentage. In that prompt we can place a link to the preview branch Readme section where the instruction will be placed. How do you think?

**Comment by molant** [comment]
Yes, exactly that. Only caveats are that it will probably won't have the right content-type (although I could be wrong) and that we should make it a bit more flexible in case we start running more experiments in the future. For example:

```json
{
  "nightlyPromt": 0.1,
  "experiment2": 0
}
```

The property name is the name of the experiment, the value is the percentage of the population to show.
We will have to know when we've rolled the dice so this isn't executed every single time, and we will need a way to "refresh" or "force" a new value. Maybe we just need to store the previous value and compare to the new one, if it is the same we do nothing but if it is different and we weren't already part of the population we show the prompt if conditions are met (this probably needs a bit more thought to make sure we are not spamming more people when we increase percentages).

> In that prompt we can place a link to the preview branch Readme section where the instruction will be placed. How do you think?

We might need 2 prompts:

1. One from the stable extension to install the new one
1. One from the preview one about how to configure it (research suggests not a lot of people read the readme file that gets opened on install)

**Comment by SounD120** [comment]
@molant We can create some lock file in the extension folder after the extension activation. The only question is - how the Github page should be created: as a new repository, or as part of our preview branch?
