### ISSUE TITLE
"Open developer menu" command doesn't work from the terminal for iOS and RNW

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-react-native#1313]
# 🚀 Feature request
We need to investigate if we can trigger `Reload app` and `Show DevMenu` commands on iOS and RNW without triggering `NativeModules` inside of React Native core. 
More info:
https://github.com/microsoft/react-native-windows/issues/3822#issuecomment-629566126

## What scenarios will this solve?

This will allow to not depend on React Native code base inside of `debuggerWorker.js` and may be helpful when the only direct debugging will be allowed

**Comment by RedMickey** [comment]
We found out that we can use `Reload app` and `Show DevMenu` commands via Metro bundler, but for now the `Show DevMenu` command doesn't work properly. We opened [the issue](https://github.com/react-native-community/cli/issues/1213) about this problem.

**Comment by EzioLi01** [comment]
This 

> We found out that we can use `Reload app` and `Show DevMenu` commands via Metro bundler, but for now the `Show DevMenu` command doesn't work properly. We opened [the issue](https://github.com/react-native-community/cli/issues/1213) about this problem.

This issue is still existing, keep tracking.

**Comment by EzioLi01** [comment]
Still repro on 0.71.1.

**Comment by EzioLi01** [comment]
This issue should be fixed with https://github.com/facebook/react-native/pull/36115.
