### ISSUE TITLE
autocompleted/suggestion no more show after autto updated vscode

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/vscode-react-native#1316]
## Actual Behavior
1. No more auto completed suggestion after auto updated vscode to v1.46.0

here's an example: usually i'm type "did" to autocompleted `componentDidMount(){...}`

![image](https://user-images.githubusercontent.com/19633881/84480779-4d125700-acbf-11ea-8ea0-a2c618f6e0a0.png)

## Expected Behavior
1. bring back autocomplete

## Software versions
- React-Native VS Code extension version: v0.16.0
- VSCode version: 1.46.0
- OS platform and version: Windows 10
- NodeJS version: 10.19.0
- React Native version: 0.62.2
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```

**Comment by RedMickey** [comment]
Hi @zxccvvv and thanks for reaching us. I upgraded VS Code to 1.46.0 and didn't face problems with [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense) work and autocomplete. The extension doesn't provide features for code autocomplete. VS Code uses TypeScript language service to extract type declarations from `*.d.ts` files, and then based on this data implements autocomplete (you can find more info about IntelliSense and React [here](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_intellisense)).
I checked that autocomplete works without this extension (VS Code 1.46).

![image](https://user-images.githubusercontent.com/33267199/84667431-06289980-af2b-11ea-99a7-b1625646e6a8.png)

Do you have autocomplete problems only in React Native projects? Could you please check if autocomplete works in other `javascript` and/or `typescript` projects?

Could you please also send us the following logs in case of incorrect work of autocomplete?

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by mjbvz** [comment]
Also reported against VS Code here: https://github.com/microsoft/vscode/issues/99926 and
https://github.com/microsoft/vscode/issues/100026

Still looking for easy steps to reproduce this

**Comment by zxccvvv** [comment]
hi @RedMickey and @mjbvz 
Actually I don't know how to reproduce this issue, it just happened unexpectedly,
even i've tried to used `Developer: Reload Window` many times that day
but i can confirm that autocomplete is work 2 days later after i'm posted the issues,

also it's good if i can check or force to run `IntelliSense` manually in `vscode`,
since i just see makes sense option is `Developer: Show Running Extenstions` when pressing `CTRL+SHIFT+P`  to check if `IntelliSense` is already run
