### ISSUE TITLE
[Bug]  If there is a space in the ADB path, it will not work properly

### ISSUE THREAD

**Issue by yuki2006** [microsoft/vscode-react-native#1321]
1.

set .zshrc
PATH="${PATH}":"/Volumes/Macintosh HD/Users/foo/Library/Android/sdk/platform-tools"

2.
Run Debug Android

## Debug output

<details>
<summary>Debug Console</summary>

```text
デバッグできませんでした。コマンド '/Volumes/Macintosh HD/Users/foo/Library/Android/sdk/platform-tools/adb devices' の実行中にエラーが発生しました : Command failed: /Volumes/Macintosh HD/Users/foo/Library/Android/sdk/platform-tools/adb devices
/bin/sh: /Volumes/Macintosh: No such file or directory```

```

## Environment

* React Native Tools extension version: 0.16.0

**Comment by SounD120** [comment]
Hi @yuki2006 and thanks for your question. It is no need to go down to level of mounted drives to set the path to the Android SDK. You can try to do it using the following recommendations:
Could you please try to replace your current content of `.zshrc` by these lines?
```
export ANDROID_HOME=/Users/$USER/Library/Android/sdk/
export ANDROID_SDK_ROOT=$ANDROID_HOME
PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
```
Please let us know if this helped.

**Comment by yuki2006** [comment]
Thank you @SounD120 .

Probably it's okay, but
I'm working with the ADB on a different drive due to less storage..

**Comment by RedMickey** [comment]
@yuki2006, I tried to modify my `.zshrc` file the following way:
```
PATH="$PATH:/Volumes/Macintosh HD/Users/user/Documents/temp_sdk/folder with space/sdk/platform-tools"
export ANDROID_HOME=/Users/akvelon/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
```
And the `adb devices` command worked correctly in the extension.

Could you please also try to add backslash(`\`) before the space in your configuration string to wrap the space?
```
set .zshrc
PATH="${PATH}":"/Volumes/Macintosh\ HD/Users/foo/Library/Android/sdk/platform-tools"
```

**Comment by yuki2006** [comment]
Sorry @RedMickey 

I checked again.
The project included local.properties (generated by Android Studio).
sdk.dir was written there.

```
sdk.dir=/Volumes/Macintosh HD/Users/foo/Library/Android/sdk
```

The extension did not work properly under these conditions.

PATH was not the cause..

**Comment by SounD120** [comment]
@yuki2006 We fixed that situation and now path acquired from `sdk.dir` will be wrapped in quotes when when any command is executed. It should help to avoid such situations in future. This fix will be available in the next extension release.
