### ISSUE TITLE
Error Setting Up IntelliSense

### ISSUE THREAD

**Issue by joshuaskelton** [Microsoft/vscode-react-native#135]
![screen shot 2016-03-10 at 4 42 32 pm](https://cloud.githubusercontent.com/assets/14099985/13689634/3206e9a8-e6df-11e5-8f78-4ff51a4e8e7a.png)

Looks like we are trying to read from `${workspaceRoot}/.vscode/settings.json` when it doesn't exist on disk.

### Repro Steps

1. Create a new React Native project `react-native init MyProject`
2. Open project with VS Code

**Comment by johnoscott** [comment]
in my case, `.vscode/settings.json` exists but is invalid. The file contents are indeed invalid :

` e{}`

**Comment by mroswald** [comment]
I'm not sure if that's really a bug. A non-existing file should be catched by the current version (I can't reproduce the steps) and invalid JSON can't be read... which is quite normal

**Comment by MSLaguana** [comment]
We've changed how this code works and I haven't seen this issue come up for a while (unless I create a deliberately non-parsable settings.json) so I believe this is fixed.
