### ISSUE TITLE
'property declarations' can only be used in a .ts file.

### ISSUE THREAD

**Issue by tianhonghui** [Microsoft/vscode-react-native#136]
![screen shot 2016-03-11 at 10 56 18 am](https://cloud.githubusercontent.com/assets/3898564/13691946/e94c18ca-e777-11e5-81d6-f93ba284dccf.png)
Define arrow function inside class report error:
'property declarations' can only be used in a .ts file.

This file work well when I run in react native.

**Comment by MSLaguana** [comment]
This is related to #85. Unfortunately the intellisense / red-squigglies are only aware of standard javascript constructs, while react uses babel to support the newer es6 classes and other constructs.

**Comment by moneyonrails** [comment]
It looks like it's a linting problem, where visual studio code highlights the code red but it actually works when I run it.
