### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by VIJAYAA94** [microsoft/vscode-react-native#1360]
- Issue Type: `Bug`
- Extension Name: `vscode-react-native`
- Extension Version: `0.16.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.47.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by SounD120** [comment]
Hi @VIJAYAA94 . It looks like no information about your issue has been added. Please add this information and reopen, or create new issue with this information.
