### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by naivedeveloper95** [microsoft/vscode-react-native#1375]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\satyam.suman\msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RedMickey** [comment]
Hi @naivedeveloper95 and thanks for the report. Could you please provide your CPU profile file as described in your issue? 
Also I recommend to try out the [React Native Tools Preview](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) version which has significant performance improvements in comparison with the current one.

**Comment by naivedeveloper95** [comment]
Sure. Here is my CPU profile.
[cpuProfile.txt](https://github.com/microsoft/vscode-react-native/files/5125219/cpuProfile.txt)

**Comment by RedMickey** [comment]
@naivedeveloper95, Thanks for the CPU profile file. I analyzed the CPU profile and it seems that freeze has happened during the extension activation. We improved performance of the extension in the [React Native Tools Preview](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) version. I think that this problem has been resolved in the new version. Please try it out, if you want.
