### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by no-trouble** [microsoft/vscode-react-native#1376]
[Error] Error: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --device --no-packager --verbose 时出错: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --device --no-packager --verbose 时出错 (error code 101)

**Comment by RedMickey** [comment]
Hi @no-trouble and thanks for reaching us. Could you please add a description of your problem in accordance to our [bug report template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md)? That will be very helpful for us.
