### ISSUE TITLE
执行命令 /Users/**/Documents/**/node_modules/.bin/react-native run-ios --simulator --no-packager --verbose 时出错 (error code 101)

### ISSUE THREAD

**Issue by no-trouble** [microsoft/vscode-react-native#1377]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1
2. Step 2

## Expected behavior

I want to be able to run and debug ReactNative applications in VSCode. Since my iOS native project has multiple targets, I hope I can specify a specific scheme in the configurations in launch.json.

## Debug output

<details>
<summary>Debug Console</summary>

```text
OS: darwin x64
Adapter node: v12.8.1 x64
vscode-chrome-debug-core: 6.8.9
无法进行调试。执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --no-packager --verbose 时出错: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --no-packager --verbose 时出错 (error code 101)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] 正在启动包生成工具

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-sqlite-storage: https://github.com/andpor/react-native-sqlite-storage
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/lishuai/Documents/yd/hxg_app_for_block_sort 

Loading dependency graph, done.
[Info] 已启动包生成工具。

[Info] 预热捆绑缓存。这可能需要一段时间...

[Info] 即将获得: http://localhost:8081/index.bundle?platform=ios

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1563/1563), done.

[Warning] 已预热捆绑缓存。

[Info] 生成并运行应用程序。

[Error] Error: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --no-packager --verbose 时出错: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --no-packager --verbose 时出错 (error code 101)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:56
onFirstListenerAdd @ event.ts:116
_event._event @ event.ts:516
O @ listWidget.ts:563
L @ abstractTree.ts:1080
createMouseController @ abstractTree.ts:1166
K @ listWidget.ts:1262
O @ abstractTree.ts:1162
t.AbstractTree @ abstractTree.ts:1290
l @ objectTree.ts:33
createTree @ asyncDataTree.ts:403
x @ asyncDataTree.ts:372
W @ listService.ts:727
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
renderBody @ variablesView.ts:101
render @ paneview.ts:243
render @ viewPaneContainer.ts:265
onDidAddViewDescriptors @ viewPaneContainer.ts:1265
create @ viewPaneContainer.ts:976
create @ debugViewlet.ts:90
create @ panecomposite.ts:44
showComposite @ compositePart.ts:215
doOpenComposite @ compositePart.ts:146
openComposite @ compositePart.ts:110
doOpenViewlet @ sidebarPart.ts:275
openViewlet @ sidebarPart.ts:230
run @ activitybarActions.ts:103
runAction @ actions.ts:202
run @ actions.ts:194
onClick @ actionViewItems.ts:163
(anonymous) @ actionViewItems.ts:143
processImmediate @ internal/timers.js:439
Show 5 more frames
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:56
onFirstListenerAdd @ event.ts:116
_event._event @ event.ts:516
O @ listWidget.ts:563
L @ abstractTree.ts:1080
createMouseController @ abstractTree.ts:1166
K @ listWidget.ts:1262
O @ abstractTree.ts:1162
t.AbstractTree @ abstractTree.ts:1290
l @ objectTree.ts:33
createTree @ asyncDataTree.ts:403
x @ asyncDataTree.ts:372
W @ listService.ts:727
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
renderBody @ watchExpressionsView.ts:76
render @ paneview.ts:243
render @ viewPaneContainer.ts:265
onDidAddViewDescriptors @ viewPaneContainer.ts:1265
create @ viewPaneContainer.ts:976
create @ debugViewlet.ts:90
create @ panecomposite.ts:44
showComposite @ compositePart.ts:215
doOpenComposite @ compositePart.ts:146
openComposite @ compositePart.ts:110
doOpenViewlet @ sidebarPart.ts:275
openViewlet @ sidebarPart.ts:230
run @ activitybarActions.ts:103
runAction @ actions.ts:202
run @ actions.ts:194
onClick @ actionViewItems.ts:163
(anonymous) @ actionViewItems.ts:143
processImmediate @ internal/timers.js:439
Show 5 more frames
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:56
onFirstListenerAdd @ event.ts:116
_event._event @ event.ts:516
O @ listWidget.ts:563
L @ abstractTree.ts:1080
createMouseController @ abstractTree.ts:1166
K @ listWidget.ts:1262
O @ abstractTree.ts:1162
t.AbstractTree @ abstractTree.ts:1290
l @ objectTree.ts:33
t.CompressibleObjectTree @ objectTree.ts:188
createTree @ asyncDataTree.ts:1142
x @ asyncDataTree.ts:372
t.CompressibleAsyncDataTree @ asyncDataTree.ts:1127
z @ listService.ts:770
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
renderBody @ callStackView.ts:220
render @ paneview.ts:243
render @ viewPaneContainer.ts:265
onDidAddViewDescriptors @ viewPaneContainer.ts:1265
create @ viewPaneContainer.ts:976
create @ debugViewlet.ts:90
create @ panecomposite.ts:44
showComposite @ compositePart.ts:215
doOpenComposite @ compositePart.ts:146
openComposite @ compositePart.ts:110
doOpenViewlet @ sidebarPart.ts:275
openViewlet @ sidebarPart.ts:230
run @ activitybarActions.ts:103
runAction @ actions.ts:202
run @ actions.ts:194
onClick @ actionViewItems.ts:163
(anonymous) @ actionViewItems.ts:143
processImmediate @ internal/timers.js:439
Show 7 more frames
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:56
onFirstListenerAdd @ event.ts:116
_event._event @ event.ts:516
O @ listWidget.ts:563
createMouseController @ listWidget.ts:1277
K @ listWidget.ts:1262
A @ listService.ts:223
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
renderBody @ breakpointsView.ts:93
render @ paneview.ts:243
render @ viewPaneContainer.ts:265
onDidAddViewDescriptors @ viewPaneContainer.ts:1265
create @ viewPaneContainer.ts:976
create @ debugViewlet.ts:90
create @ panecomposite.ts:44
showComposite @ compositePart.ts:215
doOpenComposite @ compositePart.ts:146
openComposite @ compositePart.ts:110
doOpenViewlet @ sidebarPart.ts:275
openViewlet @ sidebarPart.ts:230
run @ activitybarActions.ts:103
runAction @ actions.ts:202
run @ actions.ts:194
onClick @ actionViewItems.ts:163
(anonymous) @ actionViewItems.ts:143
processImmediate @ internal/timers.js:439
2console.ts:137 [Extension Host] (node:3185) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:463
_receiveMessage @ ipc.net.ts:747
(anonymous) @ ipc.net.ts:602
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
2console.ts:137 [Extension Host] (node:3185) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:463
_receiveMessage @ ipc.net.ts:747
(anonymous) @ ipc.net.ts:602
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 284.46 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

* `envinfo`:

```text
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 337.67 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
    Homebrew: 2.2.12 - /usr/local/bin/brew
    pip3: 19.0.2 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1103.0.32.62 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: Build 3211
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_201 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Protoc: 3.7.1 - /usr/local/protobuf/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.2 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 72.0.2
    Safari: 13.1
```

* React Native Tools extension version: 0.17.0
* VSCode version: 1.48.2
* Expo SDK version (if applicable): VERSION

**Comment by RedMickey** [comment]
Hi @no-trouble, the extension provides an opportunity to specify the name of an iOS scheme in debug configurations. You can do the following to specify a target app:
1. You can create a scheme for the concrete target using Xcode. 
1. Add the name of a custom iOS scheme to the [`scheme` parameter](https://github.com/microsoft/vscode-react-native#debugger-configuration-properties) in your debug configuration. For example like this:
    ```
        {
            "name": "Debug iOS",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "scheme": "customSchemeName"
        }
    ```

So the extension will use the specified scheme to build and run the application. 
Please let us know about your results.

**Comment by no-trouble** [comment]
@RedMickey Hello，I copied your configuration to my launch.json, but it is still the original problem. Will there be other problems? I followed [link](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode -react-native) is configured in this tutorial, and there is no problem when I run a pure js project.

[Info] 包生成工具已在运行。

[Info] 预热捆绑缓存。这可能需要一段时间...

[Info] 即将获得: http://localhost:8081/index.bundle?platform=ios

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

[Warning] 已预热捆绑缓存。

[Info] 生成并运行应用程序。

[Error] Error: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --scheme CY_Stock_Dev --no-packager --verbose 时出错: 执行命令 /Users/lishuai/Documents/yd/hxg_app_for_block_sort/node_modules/.bin/react-native run-ios --simulator --scheme CY_Stock_Dev --no-packager --verbose 时出错 (error code 101)

**Comment by RedMickey** [comment]
@no-trouble, could you please try to launch your iOS app from the terminal to check if the `react-native run-ios` command works correctly?
Please run the command in the terminal and send us its output:
```
npx react-native run-ios --simulator --scheme CY_Stock_Devnt --verbose
```

**Comment by no-trouble** [comment]
hello, `npx react-native run-ios --simulator --scheme CY_Stock_Dev --verbose` This command can run my project normally in the terminal。

its output:
lishuai:hxg_app_for_block_sort ➜ npx react-native run-ios --simulator --scheme CY_Stock_Dev --verbose
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-sqlite-storage: https://github.com/andpor/react-native-sqlite-storage
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-sqlite-storage (to unlink run: "react-native unlink react-native-sqlite-storage")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
debug Reading /Users/lishuai/Documents/yd/hxg_app_for_block_sort/ios/Podfile.lock
info Found Xcode workspace "CY_Stock.xcworkspace"
info Launching iPhone 11 (iOS 13.6)
info Building (using "xcodebuild -workspace CY_Stock.xcworkspace -configuration Debug -scheme CY_Stock_Dev -destination id=47E9A8C5-EABE-4D8F-ABD3-8D11624B8F10")
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Check Pods Manifest.lock'
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'RCTOrientation' from project 'RCTOrientation')
▸ Running script '[CP] Check Pods Manifest.lock'
    Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCTHuodePlayer' from project 'RCTHuodePlayer')
    Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCTHuodePlayer' from project 'RCTHuodePlayer')
    Mapping architecture armv7s to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'RCTHuodePlayer' from project 'RCTHuodePlayer')
▸ Running script '[CP] Check Pods Manifest.lock'
    OpenGLES is deprecated. Consider migrating to Metal instead. (in target 'FMPlayer' from project 'FMPlayer')
▸ Running script '[CP] Check Pods Manifest.lock'
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'RNCustomKeyboard' from project 'RNCustomKeyboard')
▸ Running script '[CP] Check Pods Manifest.lock'
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'gRPC-gRPCCertificates' from project 'Pods')
▸ Processing ResourceBundle-gRPCCertificates-gRPC-Info.plist
    MobileCoreServices has been renamed. Use CoreServices instead. (in target 'CY_Stock_Dev' from project 'CY_Stock')
    GLKit is deprecated. Consider migrating to MetalKit instead. (in target 'CY_Stock_Dev' from project 'CY_Stock')
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Linking CY_Stock_Dev
⚠️  ld: meta method 'resetHostSettings' in category from /Users/lishuai/Library/Developer/Xcode/DerivedData/CY_Stock-algvsdcdfnccpxfpwcomduqowgvy/Build/Intermediates.noindex/CY_Stock.build/Debug-iphonesimulator/CY_Stock_Dev.build/Objects-normal/x86_64/GRPCCall+Tests.o conflicts with same method from another category
⚠️  ld: meta method 'useInsecureConnectionsForHost:' in category from /Users/lishuai/Library/Developer/Xcode/DerivedData/CY_Stock-algvsdcdfnccpxfpwcomduqowgvy/Build/Intermediates.noindex/CY_Stock.build/Debug-iphonesimulator/CY_Stock_Dev.build/Objects-normal/x86_64/GRPCCall+Tests.o conflicts with same method from another category
⚠️  ld: meta method 'useTestCertsPath:testName:forHost:' in category from /Users/lishuai/Library/Developer/Xcode/DerivedData/CY_Stock-algvsdcdfnccpxfpwcomduqowgvy/Build/Intermediates.noindex/CY_Stock.build/Debug-iphonesimulator/CY_Stock_Dev.build/Objects-normal/x86_64/GRPCCall+Tests.o conflicts with same method from another category
▸ Running script 'Update Launch Screen App Version'
▸ Processing CY_Stock_Dev-Info.plist
▸ Running script '[CP] Copy Pods Resources'
▸ Running script 'Start Packager'
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'title_define' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'gRPC' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'RNSpringScrollView' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'react-native-viewpager' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'gRPC-Core' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'glue_data_define' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'gRPC-ProtoRPC' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'data_define' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'BVLinearGradient' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'Masonry' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'SDWebImage' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'glue_service' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'historydata_define' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'Protobuf' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'data_define_req_rep' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'gRPC-RxLibrary' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'data_define_fund_flow' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target '!ProtoCompiler' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target '!ProtoCompiler-gRPCPlugin' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'Picker' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'nanopb' from project 'Pods')
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.1, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'quote_service' from project 'Pods')
▸ Build Succeeded
2020-08-28 16:37:26.384 xcodebuild[14007:293852] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fc412bfc5a0), lishuai的Xs Max, iPhone, 13.6.1 (17G80), 00008020-0010593C0CBB002E> == Underlying device preparation errors ==
2020-08-28 16:37:26.384 xcodebuild[14007:293852] [MT] iPhoneConnect: Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.
Domain: com.apple.platform.iphoneos
Code: 5
Failure Reason: allowsSecureServices: 1. isConnected: 0. Platform: <DVTPlatform:0x7fc41060c6f0:'com.apple.platform.iphoneos':<DVTFilePath:0x7fc41060c410:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>. DTDKDeviceIdentifierIsIDID: 0
User Info: {
    DVTDeviceDescription = "\Ud83d\Udcf1<DVTiOSDevice (0x7fc412bfc5a0), lishuai\U7684Xs Max, iPhone, 13.6.1 (17G80), 00008020-0010593C0CBB002E>";
}
--
2020-08-28 16:37:26.384 xcodebuild[14007:293852] [MT] iPhoneConnect: 📱<DVTiOSDevice (0x7fc412bfc5a0), lishuai的Xs Max, iPhone, 13.6.1 (17G80), 00008020-0010593C0CBB002E> == END: Underlying device preparation errors ==
info Installing "/Users/lishuai/Library/Developer/Xcode/DerivedData/CY_Stock-algvsdcdfnccpxfpwcomduqowgvy/Build/Products/Debug-iphonesimulator/CY_Stock_Dev.app"
info Launching "com.yuanda.hui-xuan-gu-enterprise"
success Successfully launched the app on the simulator

**Comment by RedMickey** [comment]
@no-trouble, Could you please send us a minimal demo application in which this problem is reproduced? This will be helpful for better understanding of the situation from our side, so we can investigate the issue faster.

**Comment by no-trouble** [comment]
Thank you for your help, I can run the project on the simulator.

**Comment by RedMickey** [comment]
@no-trouble, nice to hear! Do you need any more help from our side or I can close the issue?
