### ISSUE TITLE
[Bug] "spawn node ENOENT" after attached to packager and start remote debugging on MacOS

### ISSUE THREAD

**Issue by bojie-liu** [microsoft/vscode-react-native#1379]
# 🐛 What is the bug? How can we reproduce it?
1. npx react-native init Awesome
2. Add "Attach to packager" configuration.
3. yarn start Awesome project and start attaching
4. enable Debug in RN debug panel on android device
5. DEBUG CONSOLE throws "Error: spawn node ENOENT" and connect timeout

## Expected behavior

connect succeeded and be able to set breakpoint

## Investigation
in ~/.vscode/extensions/msjsdiag.vscode-react-native-0.17.0/src/debugger/forkedAppWorker.js the following code spawns using "node" executable, although the env PATH is /usr/bin:/bin:/usr/sbin:/sbin and actual node is located at /usr/local/bin/. Setting ~/.bash_profile, /etc/profile etc. does not change the PATH in extension. I replace "node" with "/usr/local/bin/node" and it works.
```
        this.debuggeeProcess = cp.spawn("node", nodeArgs, {
            stdio: ["pipe", "pipe", "pipe", "ipc"],
        })
```

## Debug output

<details>
<summary>Debug Console</summary>

```text

OS: darwin x64
Adapter node2: v12.8.1 x64
vscode-chrome-debug-core: 6.8.9
启动调试器应用辅助进程。
已建立代理(包生成工具)与 React Native 应用程序之间的连接
Error: spawn /usr/local/bin/no ENOENT。调试将不起作用: 请尝试从应用内重新加载 JS，或重新连接 VS Code 调试器: React Native 辅助进程引发错误 (error code 1407)
调试器辅助进程在端口 41948 上已加载运行时

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: 0.17.0
* React native version (if applicable): 0.62.2
* MacOS version: 10.15.1
* node version: v13.12.0

**Comment by SounD120** [comment]
Hi @bojie-liu and thanks for reaching us. VS Code PATH context is currently changed by configuring `.zshrc` file since after the macOS 10.15 zsh became the default Terminal instead of bash.
I recommend you to create `.zshrc` file and place your PATH environment settings in there. After that reboot VS Code and try to launch debugging. Please let us know if this helped.

**Comment by SounD120** [comment]
Hi @bojie-liu. Is this issue still relevant for you?

**Comment by bojie-liu** [comment]
It still does not work. My default config file is ~/.zprofile. And adding path in ~/.zshrc the problem still shows up.

**Comment by SounD120** [comment]
@bojie-liu In my case I am using such `~/.zshrc` configuration and don't have `~/.zprofile` file at all and it works for me:
```
export JAVA_HOME="$(/usr/libexec/java_home)"
export ANDROID_HOME=/Users/$USER/Library/Android/sdk/
export ANDROID_SDK_ROOT=$ANDROID_HOME
PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
export PATH="/usr/local/opt/node@10/bin:$PATH"
```
Could you please try to move your settings to `~/.zshrc` and try to launch debugging again? VS Code internal context seem to be non-login, so it might ignore profile file. Also, does `node` command work if you launch it from the terminal?

**Comment by SounD120** [comment]
Hi @bojie-liu . Did the instruction above help you? Let us know if you still experiencing issues with the extension.

**Comment by SounD120** [comment]
Hi @bojie-liu . I close this issue due to inactivity. Feel free to reopen if needed.

**Comment by shahriar0247** [comment]
yeah same problem, 

![image](https://user-images.githubusercontent.com/47810596/206462576-ad6b1528-d528-4fa3-a9ec-e6fac59466fc.png)
![image](https://user-images.githubusercontent.com/47810596/206463038-66c4ac0e-9384-4990-8d94-e0f69f242e6e.png)

**Comment by shahriar0247** [comment]
![image](https://user-images.githubusercontent.com/47810596/206463093-1b8681f1-5b70-4d7d-bbe6-e7ce5d5a89a2.png)

**Comment by shahriar0247** [comment]
![image](https://user-images.githubusercontent.com/47810596/206463161-904c4407-2046-43cc-a714-5b3de4cacd27.png)

**Comment by EzioLi01** [comment]
Hey @shahriar0247 , could you please create a new issue if needed? Also could please help to add repro steps or demo for it?
