### ISSUE TITLE
Debugging RN Apps with Custom Port throwing "Timeout while connecting to remote debugger"

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/vscode-react-native#1389]
## Actual Behavior
1. `settings.json` :
```
{
  "react-native": {
    "packager" : {
      "port": 9091
    }
  }
}
```
2. `launch.json` :
```
{
  "configurations": [
    {
      "name": "Attach to packager",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "attach",
      "port": "9091"
    }
  ]
}
```

caused red error :
![image](https://user-images.githubusercontent.com/19633881/92850774-0693dc00-f417-11ea-8515-76a8de9dd802.png)

## Expected Behavior
1. should be able to debug even with custom port

## Software versions
- React-Native VS Code extension version: v.0.17.0
- VSCode version: help->about =
```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
- OS platform and version: 
- NodeJS version: 
- React Native version: 0.61.5
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

![image](https://user-images.githubusercontent.com/19633881/92851366-ad787800-f417-11ea-9809-26d7fecc6f54.png)

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):

![image](https://user-images.githubusercontent.com/19633881/92851582-ec0e3280-f417-11ea-8b24-b0e88e2493aa.png)

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

![image](https://user-images.githubusercontent.com/19633881/92851764-24157580-f418-11ea-880c-dd3a35bddfbc.png)

**Comment by SounD120** [comment]
Hi @zxccvvv and thanks for the question. Have you seen issue #993? It looks similarly to your case. 
Please make sure to set up your application using developer menu:
<details>
<summary>Port setup instruction</summary>

![image](https://user-images.githubusercontent.com/32372875/92897889-3bf3f600-f426-11ea-8e3f-c520c67ef366.png)

![image](https://user-images.githubusercontent.com/32372875/92897976-4c0bd580-f426-11ea-80e6-d7b60afeca7f.png)

![image](https://user-images.githubusercontent.com/32372875/92898024-53cb7a00-f426-11ea-8e24-2f54c097d16e.png)
</details>

Also make sure to forward your ports to your device via `adb reverse tcp:9091 tcp:9091` command since attach command cannot predict to which platform it will be attached.

Please let us know if you face any difficulties during this process.

**Comment by SounD120** [comment]
Hi @zxccvvv . Did the instruction above help you? Please let us know if you face any problems.

**Comment by zxccvvv** [comment]
Sorry for the late reply, I'm not with my PC right now.

I'll give the detail problem ASAP when im on PC

Regards

**Comment by zxccvvv** [comment]
Hi @SounD120 , I don't know why when i uninstalled Unity debugger extenstension, the debug is rurnning well with regular setting like this:

```
{
  "configurations": [
    {
      "name": "Attach to packager",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "attach"
    }
  ]
}
``` 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19633881/93422158-56721780-f8dd-11ea-8533-3a206f97bc2f.gif)

but when i tried to used `Hermes` like below in `launch.json` :

```
{
  "configurations": [
    {
      "name": "Attach to Hermes application - Experimental",
      "cwd": "${workspaceFolder}",
      "type": "reactnativedirect",
      "request": "attach"
    }
  ]
}
```

I got an error :

![image](https://user-images.githubusercontent.com/19633881/93421523-c7183480-f8db-11ea-8cdd-ee6ef43e7d99.png)

I've set port in RN to `localhost:9091`, and because i've enabled hermes in my current Apps, i think the right choice is to use `Hermes Debugging`, eventhought i don't know the different of `regular Attach to Packager` and `Hermes Attach to Packager`

**Comment by SounD120** [comment]
@zxccvvv The difference between Hermes debugging and regular debugging is that the Hermes one uses direct debugging and attaches directly to the JS engine on the device(in that case remote debugging in dev settings in the app must be disabled).
The regular debugging uses out of process debugging, it means that debugger attaches to the app via the proxy which communicates with the debugged device (`debuggerWorker.js` is the proxy).

By your screenshots it seems that you need to disable remote debugging on your device and also add: "port": "9091" to your Hermes attach scenario and try to attach to the app when it will be running. Also please take into account that Hermes engine is pretty new and still there might be some [known issues while debugging](https://github.com/microsoft/vscode-react-native/issues/1266).

**Comment by zxccvvv** [comment]
> By your screenshots it seems that you need to disable remote debugging on your device and also add: "port": "9091" to your Hermes attach scenario and try to attach to the app when it will be running. Also please take into account that Hermes engine is pretty new and still there might be some [known issues while debugging](https://github.com/microsoft/vscode-react-native/issues/1266).

i don't get it a part of `add: "port": "9091" to your Hermes attach scenario and try to attach to the app when it will be running`
does my step-by-step gif below is wrong?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19633881/93432636-05b7ea00-f8f0-11ea-8ecc-7c7f22a20818.gif)

**Comment by SounD120** [comment]
@zxccvvv In order to change listening port for the debugger you need to change your [Metro bundler configuration(`metro.config.js`) ](https://facebook.github.io/metro/docs/configuration/#server-options) and restart the packager to apply this change. Otherwise the packager will listen for the debugger on 8081 port.
In my case I use such configuration and it works for the Hermes attach scenario that you have sent:
```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  server: {
    port: 9091,
  },
};

```

**Comment by zxccvvv** [comment]
> Otherwise the packager will listen for the debugger on 8081 port.

**Comment by SounD120** [comment]
@zxccvvv Yes, it was launched and worked on 9091 port, but Hermes engine expects you to attach on 8081 port if this is not configured explicitly. I glad that it helped to you. We'll add more information about that case in our documentation.
