### ISSUE TITLE
Syntax Highlighting Shows Lots of Red Characters for react-native

### ISSUE THREAD

**Issue by trackwell-mike** [microsoft/vscode-react-native#1400]
I'm sure this error is specific to my setup and not replicable, but in case others have the same issue, I'm posting it publicly. 

1. I'm working in a team environment and for some reason, my syntax highlighting shows the majority of my code as red characters (errored?).

2. This happens on most of my .JS files.

3. My teammates do not have this issue and we believe that we have the same/similar setups, so we can't track down what's causing my issue. 

**Thanks for any help!**

## Software versions
- React Native Tools: v0.17.0
- VSCode version: 1.49.0
- OS platform and version: Mac OS 10.15.6 (19G2021)
- NodeJS version: 12.14.1
- React Native version: 0.62.2
- VSCode Theme: Light (Visual Studio)

**Snippit:**
![image](https://user-images.githubusercontent.com/61172689/93481640-c5934000-f8cc-11ea-8fdf-82b77b4e2d3c.png)

and

![image](https://user-images.githubusercontent.com/61172689/93482380-a648e280-f8cd-11ea-9922-70970fd3bf0a.png)

**Comment by SounD120** [comment]
@trackwell-mike This extension does not provide syntax highlighting for React Native, I recommend you to reach out to[ main VS Code repository](https://github.com/microsoft/vscode) and send your issue there.
