### ISSUE TITLE
Could not pass environment variables from .env file to  runArguments from launch configuration

### ISSUE THREAD

**Issue by TanasieAlex** [microsoft/vscode-react-native#1405]
# Could not pass environment variables from .env file to  runArguments from launch configuration
I have the following launch configuration:
{
      "name": "Debug Android",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "android",
      "envFile": "${workspaceFolder}/.env", Also tried with: "envFile": ".env"
      "runArguments": [
        "--appId",
        "myApp.${env:MY_APP_ID}",
        "--variant",
        "Debug${env:MY_VARIANT}"
      ],
}

The .env file is located in the project root folder and it contains two variables:
MY_APP_ID=myAppId
MY_VARIANT=myVariant

I also tried using the env property to pass the variables directly but it did not work.

## Expected behavior

The runArguments should contain the values of the variables from the .env file.

## Debug output

<details>
<summary>React Native output channel</summary>

```text

[Error] Error: Error while executing command 'd:\MyApp\node_modules\.bin\react-native.cmd run-android --appId myApp. --variant Debug --no-packager': Error while executing command 'd:\MyApp\node_modules\.bin\react-native.cmd run-android --appId myApp. --variant Debug --no-packager' (error code 101)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` :

```text
Common    
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```

* `envinfo`:

```text
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 3.85 GB / 15.86 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE     
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD        
  Managers:
    pip2: 19.2.3 - C:\Python27\Scripts\pip2.EXE
  Utilities:
    Git: 2.22.0. - C:\Program Files\Git\cmd\git.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-27 | Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6200805
    VSCode: 1.49.0 - C:\Users\v.a.tanasie\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.4.29806.167 (Visual Studio Community 2019), 15.9.28307.1033 (Visual Studio Community 2017)
  Languages:
    Java: 1.8.0_211 - C:\Program Files\Java\jdk1.8.0_211\bin\javac.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  Databases:
    SQLite: 3.28.0 - C:\Users\v.a.tanasie\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
    Internet Explorer: 11.0.19041.1
```

* React Native Tools extension version: v0.17.0

**Comment by JiglioNero** [comment]
Hi @TanasieAlex , unfortunately we have no control over the definition of [Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) that are used as variables in `launch.json`, because this happens at the VS Code side before the extension can interact with `.env` file. For now in order to pass environment variables to `launch.json` file, it is necessary to define them at the system environment variables. We recommend you to reach out to main VS Code repository and create a feature request for that.

**Comment by TanasieAlex** [comment]
Thank you. Will do that.
