### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matrubhartiapps** [microsoft/vscode-react-native#1410]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.49.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Rohit\msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Hi @matrubhartiapps and thanks for the report. Could you please add the CPU profile file as pointed in your issue? This file is crucial for understanding the reason of the performance issues. Also I'd like to recommend the [React Native Tools Preview](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) version which has 
 significant performance improvements and other enhancements.

**Comment by SounD120** [comment]
Hi @matrubhartiapps React Native Tools v1.0.0 just has been released. Please try it out and let us know if there any performance issues. Closing this for now. Feel free to reopen if needed.
