### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by shahanvp16** [microsoft/vscode-react-native#1416]
- Issue Type: `Bug`
- Extension Name: `vscode-react-native`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by SounD120** [comment]
Hi @shahanvp16 . React Native Tools v1.0.0 just has been released. Please try it out and let us know if there any issues. Closing this for now due to insufficient information about the issue. Feel free to reopen if needed.
