### ISSUE TITLE
[Bug] Permission denied with launch command

### ISSUE THREAD

**Issue by webda2l** [microsoft/vscode-react-native#1423]
# 🐛 What is the bug? How can we reproduce it?

1. Launch Command 'React Native: Run Android on Emulator' or 'React Native: Launch Android Emulator'
2. Nothing happen (even after restart VSCode & Computer, or with new Emulator image)

## Expected behavior

As usual, it works last week again but not anymore. Due to recent update of VScode or this extension?

## Debug output

<details>
<summary>Debug Console</summary>

Nothing change about user permissions

```text
david@laptop:~$ $ANDROID_HOME/tools/emulator -list-avds
Pixel_3a_API_28
david@laptop:~$ ll $ANDROID_HOME/tools/
total 1900
drwxrwxr-x  6 david david   4096 août   7 11:50 ./
drwxrwxr-x 15 david david   4096 août   7 11:50 ../
-rwxrwxr-x  1 david david   4853 août   7 11:50 android*
drwxrwxr-x  2 david david   4096 août   7 11:50 bin/
-rwxrwxr-x  1 david david 625840 août   7 11:50 emulator*
-rwxrwxr-x  1 david david 410592 août   7 11:50 emulator-check*
```
</details>

<details>
<summary>React Native output channel</summary>

```text
Stack: Error: The command "emulator -avd {0}" threw an exception: {1} (error code 305): Error while executing command 'emulator -list-avds': Command failed: emulator -list-avds
/bin/sh: 1: emulator: Permission denied

	at Function.getWrappedError (/home/david/.vscode/extensions/msjsdiag.vscode-react-native-1.0.1/dist/rn-extension.js:1:150748)
	at Function.wrapError (/home/david/.vscode/extensions/msjsdiag.vscode-react-native-1.0.1/dist/rn-extension.js:1:7038)
	at /home/david/.vscode/extensions/msjsdiag.vscode-react-native-1.0.1/dist/rn-extension.js:1:200306

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

```
</details>

## Environment

```text
Common
 ✓ Node.js
 ✓ npm

Android
 ✖ JDK
   - Version found: N/A
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME
```

I have Android studio, it's a snap version, and it works and was ok previously.

```
david@laptop:~$ snap list
Name                  Version                     Rev   Tracking         Publisher     Notes
android-studio        4.0.1.0                     91    latest/stable    snapcrafters  classic

```

* `envinfo`:

```text
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 460.65 MB / 7.54 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  Managers:
    Apt: 2.0.2 - /usr/bin/apt
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 5.5.0 - /home/linuxbrew/.linuxbrew/bin/gcc
    Git: 2.25.1 - /usr/bin/git
    FFmpeg: 4.2.4 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 19.03.8 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Nano: 4.8 - /usr/bin/nano
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    PHP: 7.4.3 - /usr/bin/php
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.2 - /usr/bin/python3
  Databases:
    SQLite: 3.31.1 - /home/linuxbrew/.linuxbrew/bin/sqlite3
```

* React Native Tools extension version: 1.0.1

**Comment by webda2l** [comment]
Sound like the way to call `emulator -list-avds` was different before and ok with my previous setup (a bit to light).

Adding `export PATH=$PATH:$ANDROID_HOME/emulator` in my $HOME/.bashrc as recommended in https://reactnative.dev/docs/environment-setup seems have fixed the problem.

I close, thanks.

**Comment by JiglioNero** [comment]
Hi @webda2l , After the release of React Native Tools v1.0.0, we control the launch of the emulator not only from react-native-cli but also from the VS Code extension. Therefore, it is possible that the emulator does not have permissions to run from the VS Code process. Please try to provide the execution permissions of Android SDK executables for the VS Code process.

**Comment by webda2l** [comment]
@JiglioNero Last recommendations of https://reactnative.dev/docs/environment-setup fixed the problem, I wasn't fully uptodate.
Thanks for your work.

**Comment by JiglioNero** [comment]
@webda2l I'm glad to hear it, we will keep this problem in mind, if something like this happens in the future - we will include it in our documentation.

**Comment by Aruljothi21** [comment]
after run.sh file run in react
/tmp/dev-57852a7b.sh: 1: vite: Permission denied

how resolve the issue or error?
