### ISSUE TITLE
Linux - Cannot install extension on VS Code

### ISSUE THREAD

**Issue by bmccorm2** [microsoft/vscode-react-native#1428]
Hey guys - 

I tried this with two different distributions (Ubuntu and Arch) and I cannot install the extension.  I try to install from the marketplace in VS Code and also from the command line.  In both env I have nodejs and npm installed.  I have installed the create-react-app package to get started.  

When i go to my windows machine it comes up and installs fine.  

Thanks for any help!

![image](https://user-images.githubusercontent.com/11781610/94892393-b7ebc780-0441-11eb-8ce9-14097fcc937b.png)

**Comment by SounD120** [comment]
Hi @bmccorm2 and thanks for questioning. What version of VSCodium are you using? The latest version of React Native Tools requires VS Code >= 1.40 to run. Also I'm not sure how the marketplace works with the VSCodium build as this is not an official build and it might work differently. In this case, I recommend installing the official VS Code build and trying to install the extension into it.

**Comment by SounD120** [comment]
@bmccorm2 As seen from [this lines in the VSCodium repository](https://github.com/VSCodium/vscodium/blob/master/prepare_vscode.sh#L48) - it modifies the original links to the Marketplace, [so it is not connected to the original Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace). I am closing this issue as this is not an issue of the extension or original VS Code build.

**Comment by bmccorm2** [comment]
@SounD120 Thanks for the info!  I just changed the URL that codium points to for the extension gallery and now it comes up fine.  Thanks for the links!
