### ISSUE TITLE
Extension tries to configure VSCODE_TSJS even though it's not needed

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#143]
VS Code version = 0.10.10
OS X = Yosemite 10.10.5

![screen shot 2016-03-11 at 2 23 17 pm](https://cloud.githubusercontent.com/assets/14098140/13717199/df86c37c-e794-11e5-961e-31e37566a649.png)

**Comment by StoneRen** [comment]
OS X EI Capitan
VSCode = 0.10.11

**Comment by mghohoo** [comment]
I have the same problem with StoneRen.
status bar shows Javascript 1.9****dev.
But it's no intellisense problem in windows.

**Comment by hamiltonia** [comment]
Can you please let us know what version of VS Code and the react-native extension you're using?

**Comment by mghohoo** [comment]
Intellisense works in ubuntu 1504.
--------------------------
MAC:
VSCode = 0.10.11
React Native Tools = 0.1.2
react-native = 0.2.0

**Comment by mghohoo** [comment]
Maybe permisson cause this problem.No intellisense if code is installed  by brew cask.
Now I manually install it,just copy to /Applications.It works.

**Comment by MSLaguana** [comment]
This should not be required nor should it be happening any more.
