### ISSUE TITLE
[Feature] Hiding Debug Console code location

### ISSUE THREAD

**Issue by ramyareye** [microsoft/vscode-react-native#1438]
# 🚀 Feature request

I need to get rid of log code line location as you see in picture. (on right starting with localhost:...) 

<img width="1116" alt="Screen Shot 2020-10-13 at 3 19 12 PM" src="https://user-images.githubusercontent.com/6318491/95856785-74f5f200-0d67-11eb-8c7b-4d52a045948e.png">

I'm not sure if we can handle it in vs code or rn output

thanks

**Comment by SounD120** [comment]
Hi @ramyareye . For now there is no concrete way to do that from the extension side, so I recommend you to create a feature request to add that capability in [main VS Code repository](https://github.com/microsoft/vscode).
