### ISSUE TITLE
Calling start packager, and stop packager doesn't stop the packager

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#145]
#Calling quickly:

1. Start Packager
2. Stop Packager
doesn't stop the packager

Also we can call Start Packager multiple times in which succession, which seems to start new instances of the packager.

Correct screenshot:
![screen shot 2016-03-11 at 4 47 46 pm](https://cloud.githubusercontent.com/assets/14098140/13719380/8d85f2cc-e7a9-11e5-8780-8609ec003456.png)

**Comment by meenakb** [comment]
Is that right screenshot?

**Comment by meenakb** [comment]
Additionally, an extraneous warning is thrown on:

1. Start packager from the terminal
2. From VS Code, start the packager

Expected: ######### Packager is already running. ##########
Actual:
######### Packager is already running. ##########
[Warning] Debugging is not supported if the React Native Packager is not started within VS Code. If debugging fails, please kill other active React Native packager processes and retry.
