### ISSUE TITLE
Stop using enableBreakpointsFor in package.json under debuggers contribution

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-react-native#1450]
Hi VS Code dev here 👋 

Please stop using the `enableBreakpointsFor` field in your `package.json`.
It is deprecated and we will stop supporting it in our next stable release (in a month).
Here's where you use it https://github.com/microsoft/vscode-react-native/blob/master/package.json#L122

Here's an alternative how you should use it
https://github.com/microsoft/vscode-mock-debug/blob/master/package.json#L112

So the `breakpoints` attribute is no longer under `debuggers` that is the difference.

All the best
isidor

**Comment by SounD120** [comment]
Hi @isidorn , added a fix. Thanks for pointing on this!

**Comment by isidorn** [comment]
Thank you.
