### ISSUE TITLE
Error al ejecutar el comando "d:\APP\HorokoBar\node_modules\.bin\react-native.cmd run-android --no-packager" (error code 101)(error code 303)

### ISSUE THREAD

**Issue by PlayCodeStudios** [microsoft/vscode-react-native#1452]
error starting application debugging

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Run - Start Debuging
2. 
## Expected behavior

Run the app in Android Virtual Device

## Debug output

<details>
<summary>Debug Console</summary>

[Info] El empaquetador ya se está ejecutando.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Descarga que se va a obtener: http://localhost:8081/index.bundle?platform=android

[Warning] El conjunto en caché se ha preparado.

[Info] Building and running application.

[Sun Nov 08 2020 20:45:34.515]  BUNDLE  ./index.js 

[Error] Error: Error al ejecutar el comando "d:\APP\HorokoBar\node_modules\.bin\react-native.cmd run-android --no-packager": Error al ejecutar el comando "d:\APP\HorokoBar\node_modules\.bin\react-native.cmd run-android --no-packager" (error code 101)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Warning] No se admite el destino simulator para la plataforma Android. 
 Si quiere usar un simulador o un dispositivo concreto para iniciar la aplicación Android,
 especifique el identificador del dispositivo (como en la salida "adb devices") en su lugar.

[Info] El archivo local.properties no existe. Se usa la ubicación de Android SDK de PATH.

[Info] Iniciando el empaquetador de React Native.

[Info] Asociando al empaquetador de React Native en ejecución

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 8 workers...
info Installing the app...
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
10 actionable tasks: 2 executed, 8 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:processDebugResources' (type 'LinkApplicationAndroidResourcesTask').
> File 'C:\Users\playc\AppData\Local\Android\Sdk\platforms\android-29\android.jar' specified for property 'androidJar' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081


```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Test first install of react native

* React Native Tools extension version: last

**Comment by SounD120** [comment]
Hi @PlayCodeStudios and thanks for reaching us. Do you see the same behavior when execute `react-native run-android` command from the terminal? Could you please try to run this command and send us the outputs?

**Comment by SounD120** [comment]
@PlayCodeStudios Also I'd recommend you to run `npx react-native doctor` command from your project folder so the RN CLI utility will try to find problems with your project like incorrect Android SDK configuration and other problems that might be connected with your environment.

**Comment by PlayCodeStudios** [comment]
[IMG]https://drive.google.com/file/d/153BvkZcwYvd_XcRnO3w591BNQc3gKK6M/view?usp=sharing[/IMG]

im new in this, this is my first install react native, I'm not quite sure what I'm doing.
This is the guide that I followed step by step to install React native, .

https://www.ryadel.com/en/react-native-visual-studio-code-windows-hello-world-sample-app/

I used React Native CLI method and everything ran fine until I wanted to run it in an AVD

**Comment by SounD120** [comment]
@PlayCodeStudios Judging by the logs, React Native or/and Android SDK environment might be configured incorrectly, so I recommend to check if your environment meets the requirements from the official [React Native Getting Started instruction](https://reactnative.dev/docs/environment-setup). Also make sure that your AVD Android version meets the Android SDK version that is installed.
Also I recommend to use this Powershell command to configure Android SDK in your PATH environment variable:
```pwsh
[Environment]::SetEnvironmentVariable("ANDROID_HOME", "<path to your Android SDK>",
[System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", "%ANDROID_HOME%",
[System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("Path", $env:Path+";%ANDROID_HOME%\emulator;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools\bin",
[System.EnvironmentVariableTarget]::Machine)
```
**Make sure to replace `<path to your Android SDK>` placeholder by your existing Android SDK folder path.**

**Comment by PlayCodeStudios** [comment]
this code run good now i can run npx react-native doctor, if you can help me finish setup my first app in react native I'd appreciate it.

after run doctor that is result. (even I can see that there are a couple of things wrong)

PS D:\app> cd horokobar
PS D:\app\horokobar> npx react-native doctor
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors:   3
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors:   3
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.

**Comment by PlayCodeStudios** [comment]
im fixing all

**Comment by PlayCodeStudios** [comment]
PS D:\app\horokobar> npx react-native doctor
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors:   2
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✖ JDK
   - Version found: 1.8.0_211
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors
Attempting to fix 2 issues...

Android
 - Downloading JDK from "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip" (this may tak √ JDK installed successfully. Please restart your shell to see the changes
 × There was an error finding the Android SDK root
PS D:\app\horokobar>

**Comment by SounD120** [comment]
@PlayCodeStudios Does the `react-native run-android` command work after the JDK installation from RN CLI doctor command? If it is not - please make sure that the following environment variables are defined and point to the existing folders containing the components of Android SDK.
You can do this using the following Powershell commands:
```pwsh
echo $env:JAVA_HOME
echo $env:ANDROID_HOME
echo $env:ANDROID_SDK_ROOT
```
This command will show you values of the crucial Android SDK setup variables.

**Comment by PlayCodeStudios** [comment]
Yes, I did everything from the beginning with the official guide that you sent me and everything worked ok, the problem was badly written user values. thanks to you for helping me, long live the GitHub community
