### ISSUE TITLE
[Feature] Document how to attach to debugger for Windows

### ISSUE THREAD

**Issue by luisnaranjo733** [microsoft/vscode-react-native#1467]
# 🚀 Feature request

Document how to attach to debugger for Windows

## What scenarios will this solve?

The documentation for this extensions currently only explains how to configure RNW projects to basically run the ```npx react-native run-windows``` command. This does a lot of goodness (start metro bundler, build native app, install it, launch it, automatically attach to VS Code for debugging). This is the magical F5 first debug run scenario.

What is missing is documentation for how to attach an already built/installed/launched RNW app (which is already connected to metro) to VS Code for debugging. This is a common scenario. I would argue that it is just as useful as the scenario described above. For react-native apps, most of the changes are in the JS layer. So there's no need to re-build the full native app most of the time. You can just launch the app and it will automatically load the bundle from metro.

The vscode-react-native extension should clearly document how developers can attach pre-built non Hermes RNW apps to the VS Code debugger without forcing them to rebuild the native app when they don't need to (productivity shortcut).

This same scenario is (sort of) documented for Android and iOS, but there is a documentation gap here for Windows. The documentation should also be transparent about the fact that only web debugging scenarios are currently supported for RNW, as Hermes for Windows is still experimental (Windows Hermes direct debugging should probably be tracked as a separate standalone thing, but is less important right now since Hermes is opt-in)

**Comment by luisnaranjo733** [comment]
I was able to figure out how to do this with my own experimentation, but the docs should definitely give some guidance on this because it's not clearly documented.

1. Add the "Attach to packager" configuration to .vscode/launch.json

```
{
      "name": "Attach to packager",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "attach"
    }
```

2. Start metro bundler (either through the command line or through the VS Code extension command)
3. Select the "Attach to packager" configuration and click the play button. Wait a few seconds to let it settle.
4. Launch your react-native Windows app, which should auto connect to Visual Studio Code debugger at this point (mine is automatically launching with remote debugging enabled)

**Comment by RedMickey** [comment]
@luisnaranjo733 We updated the documentation for RNW applications debugging. Thank you for your help.
