### ISSUE TITLE
Unable to run a new created project from visual studio Code

### ISSUE THREAD

**Issue by AlenToma** [microsoft/vscode-react-native#1490]
# 🐛

I'm new to react native, and I always work with visual studio 2019. There I worked with Xamarin.
As you know when you download Visual studio and work with xamarin the android SDK is installed in 

`C:\Program Files (x86)\Android\android-sdk\platform-tools`
for Which the adb is located in `C:\Program Files (x86)\Android\android-sdk\platform-tools`

So I created a `local.properties` and added `sdk.dir=C:\Program Files (x86)\Android\android-sdk\platform-tools`

Then I run my react native project on android. 

Also with the addition to the error below where i get `java.io.IOException: The filename, directory name, or volume label syntax is incorrect`
I also get no emulator found which is very odd because I have all the Emulator installed in the above path. 
So i Plugged in my android device instead.

please guide me if this is something that have to do with the android SDK beging installed by visual studio 2019

## Expected behavior

the application should run

## Debug output

```
[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify device id (as in 'adb devices' output) instead.

[Info] Using Android SDK location defined in android/local.properties file: C:\Program Files (x86)\Android\android-sdk\platform-tools.

[Info] Starting React Native Packager.

[Info] Attaching to running React Native packager

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1296 file(s) to forward-jetify. Using 8 workers...
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
info Installing the app...
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.

> Configure project :app

[33mInstalling unimodules:[0m
 [32munimodules-core[33m@[31m6.0.0[0m from [35mD:\Projects\NovelLator\node_modules\@unimodules\core[0m
 [32munimodules-react-native-adapter[33m@[31m5.7.0[0m from [35mD:\Projects\NovelLator\node_modules\@unimodules\react-native-adapter[0m
 [32mexpo-application[33m@[31m2.4.1[0m from [35mD:\Projects\NovelLator\node_modules\expo-application[0m
 [32mexpo-constants[33m@[31m9.3.5[0m from [35mD:\Projects\NovelLator\node_modules\expo-constants[0m
 [32mexpo-error-recovery[33m@[31m1.4.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-error-recovery[0m
 [32mexpo-file-system[33m@[31m9.3.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-file-system[0m
 [32mexpo-font[33m@[31m8.4.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-font[0m
 [32mexpo-image-loader[33m@[31m1.3.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-image-loader[0m
 [32mexpo-keep-awake[33m@[31m8.4.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-keep-awake[0m
 [32mexpo-linear-gradient[33m@[31m8.4.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-linear-gradient[0m
 [32mexpo-location[33m@[31m10.0.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-location[0m
 [32mexpo-permissions[33m@[31m10.0.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-permissions[0m
 [32mexpo-secure-store[33m@[31m9.3.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-secure-store[0m
 [32mexpo-splash-screen[33m@[31m0.8.1[0m from [35mD:\Projects\NovelLator\node_modules\expo-splash-screen[0m
 [32mexpo-sqlite[33m@[31m8.5.0[0m from [35mD:\Projects\NovelLator\node_modules\expo-sqlite[0m
 [32mexpo-updates[33m@[31m0.4.1[0m from [35mD:\Projects\NovelLator\node_modules\expo-updates[0m
 [32munimodules-app-loader[33m@[31m1.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-app-loader[0m
 [32munimodules-barcode-scanner-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-barcode-scanner-interface[0m
 [32munimodules-camera-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-camera-interface[0m
 [32munimodules-constants-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-constants-interface[0m
 [32munimodules-face-detector-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-face-detector-interface[0m
 [32munimodules-file-system-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-file-system-interface[0m
 [32munimodules-font-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-font-interface[0m
 [32munimodules-image-loader-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-image-loader-interface[0m
 [32munimodules-permissions-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-permissions-interface[0m
 [32munimodules-sensors-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-sensors-interface[0m
 [32munimodules-task-manager-interface[33m@[31m5.4.0[0m from [35mD:\Projects\NovelLator\node_modules\unimodules-task-manager-interface[0m

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\NovelLator\node_modules\react-native-reanimated\android\build.gradle' line: 89

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> java.io.IOException: The filename, directory name, or volume label syntax is incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

```
And this is My build.grade.
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```
In `C:\Program Files (x86)\Android\android-sdk\build-tools` I have the `29.0.2` map version. 
* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by RedMickey** [comment]
Hi @AlenToma and thanks for reaching us.
Could you please try to run your project from the terminal using `npx react-native run-android` command in the project root folder? This will allow us to understand if this is an issue of the extension or React Native command.
Could you please also check if your system environment is setup properly in accordance with [the official "Setting up the development environment" guide](https://reactnative.dev/docs/environment-setup)?

With respect to this error:

> error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.

I could launch an Android emulator after configuring PATH the following way:
1. Add `ANDROID_HOME` env variable. It's needed to put `Program Files (x86)` in quotes otherwise, I got an error when starting the emulator
    ![image](https://user-images.githubusercontent.com/33267199/105180686-ee0d9e00-5b3b-11eb-8824-b1dbc4ac9adb.png)
2. Add these paths to PATH
    * `%ANDROID_HOME%\emulator`
    * `%ANDROID_HOME%\platform-tools`
    * `%ANDROID_HOME%\platforms`
3. Run `npx react-native run-android` command

Please let us know about your results.

**Comment by AlenToma** [comment]
Yes I was finally able to fix this

**Comment by RedMickey** [comment]
@AlenToma Glad to hear that. Then I am closing this issue. Feel free to open new ones if needed.

**Comment by ubaidian** [comment]
i added local.properties also I'm running with npx react-native myApp attached my mobile & adb devices showing its connected but facing the same issue plz help with it @RedMickey

**Comment by ubaidian** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> java.io.IOException: The filename, directory name, or volume label syntax is incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with 
--info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> java.io.IOException: The filename, directory name, or volume label syntax is incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with 
--info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

    at makeError (C:\react\tset\node_modules\execa\index.js:174:9)
    at C:\react\tset\node_modules\execa\index.js:278:16       
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
info Run CLI with --verbose flag for more details.

**Comment by RedMickey** [comment]
Hi @ubaidian and thanks for reaching us. Could you please create a new issue for your specific case and describe your problem using our [issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md).
Could you please also specify the content of your `local.properties` parameter?
You can also try to run the `npx react-native doctor` command in the terminal in your project root folder to check whether your development environment is configured correctly.
