### ISSUE TITLE
[Feature] Automatically refresh component when add or change breakpoint

### ISSUE THREAD

**Issue by DmitryKvant** [microsoft/vscode-react-native#1491]
# 🚀 Feature request

 Automatically refresh component (fast refresh or hot reload) when add or change breakpoint in vscode

## What scenarios will this solve?

spend time for resave document

**Comment by RedMickey** [comment]
Hi @DmitryKvant and thanks for your feedback.
Could you please tell if I understand you correctly, that an application should be hot reloaded after any change of breakpoints in VS Code?

**Comment by RedMickey** [comment]
Hi @DmitryKvant, do you have a chance to look at this? Could you please a bit clarify expected behavior of the extension?

**Comment by DmitryKvant** [comment]
> Hi @DmitryKvant and thanks for your feedback.
> Could you please tell if I understand you correctly, that an application should be hot reloaded after any change of breakpoints in VS Code?

yeah its correct thx for answer

**Comment by RedMickey** [comment]
Hi @DmitryKvant, we investigated the feature request and came to the conclusion that the expected behavior isn't very popular and quite uncommon. Therefore, for now we close the issue.
