### ISSUE TITLE
[Bug] Error Code 500 when debugging

### ISSUE THREAD

**Issue by JMRMEDEV** [microsoft/vscode-react-native#1499]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Install the VS code react native plugin with the recommended expo configuration.
2. Press debug un Expo for getting the QR that will launch the app on Android. 

To be able to run my app in debugging in Expo. 

What were you expecting to happen?

Not having troubles when running my app like when I use the regular metro bundler.

I get a 500 error server code when trying to run my app.

![image](https://user-images.githubusercontent.com/58167190/106956093-b84fe400-66fb-11eb-9724-6fa70a1444bb.png)

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```

```text

/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5436 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ /C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5436
workbench.html:1 A cookie associated with a cross-site resource at https://visualstudio.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] (node:9700) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5009 Extension Host
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5009 Debugger attached.
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1779  WARN UNRESPONSIVE extension host, 'msjsdiag.vscode-react-native' took 100% of 11752.092ms, saved PROFILE here: 'c:\Users\JMR\AppData\Local\Temp\exthost-166bd0.cpuprofile' Array(1)
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] (node:9700) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ /C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1979 Element already has context attribute
w @ /C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1979
/C:/Users/JMR/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4084 [Embedded Page] A cookie associated with a cross-site resource at https://dev.azure.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/windows-process-tree/lib/index.js.map: Unknown error

```
[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is Expo app......
[Info] Starting Packager

                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          
                 Welcome to React Native!
                Learn once, write anywhere

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

No issue with doctor-config-json-not-readNo issue with doctor-npm-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-react-native-not-installed[Info] Enable JS Debugging

[Info] Packager is already running.

No issue with doctor-config-json-not-readNo issue with doctor-npm-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-react-native-not-installed[Thu Feb 04 2021 15:10:30.326]  BUNDLE  .vscode/exponentIndex.js 

error: Error: Unable to resolve module `../../images/svgs/logo_et.svg` from `scenes\AboutUs\index.js`: 

None of these files exist:
  * images\svgs\logo_et.svg(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
  * images\svgs\logo_et.svg\index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (c:\Users\JMR\Desktop\Red Mars\Projects\Terappia\Expo\terappia\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

```text

Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ workbench.desktop.main.js:sourcemap:5436
workbench.html:1 A cookie associated with a cross-site resource at https://visualstudio.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
workbench.desktop.main.js:sourcemap:310 [Extension Host] (node:9700) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:310
workbench.desktop.main.js:sourcemap:5009 Extension Host
workbench.desktop.main.js:sourcemap:5009 Debugger attached.
workbench.desktop.main.js:sourcemap:1779  WARN UNRESPONSIVE extension host, 'msjsdiag.vscode-react-native' took 100% of 11752.092ms, saved PROFILE here: 'c:\Users\JMR\AppData\Local\Temp\exthost-166bd0.cpuprofile' Array(1)
workbench.desktop.main.js:sourcemap:310 [Extension Host] (node:9700) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.desktop.main.js:sourcemap:310
workbench.desktop.main.js:sourcemap:1979 Element already has context attribute
w @ workbench.desktop.main.js:sourcemap:1979
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/windows-process-tree/lib/index.js.map: Unknown error


```

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text

Common
 ✓ Node.js
 ✓ npm
 ✓ Python

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.

```

Note: I already tried to fix it with e, but I get this error:

![image](https://user-images.githubusercontent.com/58167190/106958054-74aaa980-66fe-11eb-9bad-a8f2c8d01324.png)

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: 1.3.0
* Expo SDK version (if applicable): 39.0.2

**Comment by JiglioNero** [comment]
Hi @JMRMEDEV , we have fixed this bug. This fix will be available on the Marketplace when the release of a new version of React Native Tools is deployed. But you can install the extension with this fix right now by following steps:

- Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-react-native/files/6009596/vscode-react-native-1.4.0.vsix.zip).
- Uninstall extension
- Close VS Code
- Open VS Code
- Click `Extensions -> ... -> Install from VSIX...` and select downloaded VSIX

**Comment by JMRMEDEV** [comment]
@JiglioNero Fantastic! It does solve the issue. Thank you for the support.
