### ISSUE TITLE
[Feature] Surface error messages from run-windows

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode-react-native#1511]
# 🚀 Feature request

when run-windows runs into an error, we show some error message. However the vscode extension only shows the exitcode of the process which is not useful. vscode-react-native should capture the error message from run-windows and show it in the error messagebox

## What scenarios will this solve?

better troubleshooting of why the extension / RNW failed run-windows. We're seeing several folks who haven't run the dependencies script, e.g.

**Comment by chrisglein** [comment]
Context in [this issue](https://github.com/microsoft/react-native-windows/issues/7180) on the RNW repo
