### ISSUE TITLE
[Bug] Document dependency requirement for RNW

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode-react-native#1512]
# 🐛 What is the bug? How can we reproduce it?

Please document that in order to use vscode-react-native for RNW, developers will need to install the dependencies; this currently includes full VS, even though devs can then use VSCode and vscode-react-native to build afterwards. VS and its packages are required to install the compilers, etc.

**Comment by chrisglein** [comment]
Context in [this issue](https://github.com/microsoft/react-native-windows/issues/7180) on the RNW repo

**Comment by RedMickey** [comment]
Thanks for [the notification about stopping of support for the WPF platform](https://github.com/microsoft/vscode-react-native/pull/1513#discussion_r583821648). We'll consider removing support of WPF platform for RNW in [this issue](https://github.com/microsoft/vscode-react-native/issues/1515).

**Comment by asklar** [comment]
thanks @RedMickey !
