### ISSUE TITLE
Opening React Native project not generating /launchReactNative.js

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode-react-native#152]
Similar to #99 

After opening any React-Native project (either freshly created, or an older project) VS Code is not generating the .vscode/launchReactNative.js file that is supposed to be created. This is blocking me from running the debugger giving this error:
![reactdebug](https://cloud.githubusercontent.com/assets/12900364/13764085/13e0b774-ea09-11e5-9954-8177aca31011.JPG)

**Comment by MSLaguana** [comment]
Are you opening a folder which contains a `package.json` that specifies a dependency on react-native? If those conditions are met, then we should create the launchReactNative.js file. Which version of our react-native plugin are you running at the moment? You can find out by hitting f1 and then typing `>ext show` and selecting show installed extensions.

**Comment by vsccarl** [comment]
It looks like I'm using version 0.1.2 of the native plugin.

My Package.json file looks like this:
![reactpackagejson](https://cloud.githubusercontent.com/assets/12900364/13784410/5fe30fc2-ea8c-11e5-8533-612171095003.JPG)

**Comment by MSLaguana** [comment]
One final thing I forgot we look for: Is the react-native dependency installed? do you have a node_modules/react-native/ folder with a package.json in it?

**Comment by digeff** [comment]
@vsccarl: Do you get any kind of errors when you open your React-Native project in VS Code?
What happens if you try to use the commands from the React-Native palette like run-android or run-ios? Do they work? Do you get any kind of error?

**Comment by vsccarl** [comment]
@MSLaguana Here is what my node_modules/react-native/package.json  looks like:
[package.txt](https://github.com/Microsoft/vscode-react-native/files/174876/package.txt)

@digeff There aren't any errors when opening the project. Running the run-android command gives this:
![reactnativeerror](https://cloud.githubusercontent.com/assets/12900364/13795332/6c59e830-eabd-11e5-816a-0c683984fab8.JPG)

**Comment by MSLaguana** [comment]
That error on `run-android` suggests that our extension is not being activated at all. How are you opening your project with vscode? Are you using "open folder", and does the folder that you open contain your package.json directly?

**Comment by vsccarl** [comment]
@MSLaguana Yes, I'm using open folder which contains the package.json that I linked earlier:
![reactpackagejson](https://cloud.githubusercontent.com/assets/12900364/13797689/b17d254e-eacc-11e5-8a71-5750913dcc9f.JPG)

**Comment by digeff** [comment]
@vsccarl Could you please go to Help --> Toggle Developer Tools --> Console and check if there are any messages there. If there are, could you please send us a screenshot or paste the text?
Thanks!

**Comment by vsccarl** [comment]
@digeff Here are the Dev Tools console errors:

![devtoolsreactnative](https://cloud.githubusercontent.com/assets/12900364/13823501/11f5d94e-eb67-11e5-80e4-6feb81d8f72d.JPG)

**Comment by MSLaguana** [comment]
Ah, that would explain it! Looks like you've run into https://github.com/Microsoft/vscode-react-native/issues/155

What version of vscode are you using? Are you using 0.10.11?

**Comment by vsccarl** [comment]
I'm using 0.10.12-alpha

**Comment by digeff** [comment]
@vsccarl For the time being I'd advise you to use the latest stable version of VS Code where that error shouldn't be happening. I'll update this issue after we've push a fix for this to master.

**Comment by digeff** [comment]
@vsccarl  The fix is now available on our master branch. It will be included in our next release.

**Comment by aidansteele** [comment]
For what it's worth I had the same issue today with a brand new installation of both React Native and this extension. Turns out that the extension had trouble spawning `react-native` because I had only installed the CLI locally, not globally. Globally installing fixed that issue. 

Perhaps instead of launching `react-native` we should execute the RN within node_modules?

**Comment by MSLaguana** [comment]
The 'react-native-cli' node package is intended to be installed globally, and that is what we intend to call. That in turn will use a local install of react native to do things. Did you have react-native-cli installed when you hit this?

Sent from Outlook
________________________________

**Comment by code945** [comment]
i just had the same issue, and i have installed the react-native-cli globally.
C:\Users\hongxu.lin>react-native -v
react-native-cli: 1.0.0
react-native: n/a - not inside a React Native project directory
C:\Users\hongxu.lin>cd c:\projects\superL
c:\projects\superL>react-native -v
react-native-cli: 1.0.0
react-native: 0.34.1

still don't have launchReactNative.js,do you guys @MSLaguana @aidansteele   know what's the   problem?

**Comment by MSLaguana** [comment]
Could you please tell me what VSCode extensions you have installed, and also go to `Help -> Toggle Developer Tools` and tell me if you see any errors in the console there? I've heard reports that having certain other extensions installed can somehow stop ours from loading properly (which would cause this issue).

**Comment by code945** [comment]
I have React Native Tools v0.2.0 installed, and my vscode is 1.6.0
![2016-10-11_15-07-23](https://cloud.githubusercontent.com/assets/9688970/19261446/d5e9341c-8fc3-11e6-92cb-d5c581a07d1e.png)

**Comment by MSLaguana** [comment]
That error explains why it isn't working for you: We are trying to run `react-native -v` in your project, and it is failing to find the global install of react-native. How have you installed it? Is it actually on your PATH?

**Comment by code945** [comment]
I can run react-native -v and get `react-native-cli: 1.0.0 react-native: n/a - not inside a React Native project directory`  and i can see react-native-cli under C:\Users\hongxu.lin\AppData\Roaming\npm\node_modules\
is that mean i have installed the react-native-cli globally? Any other debug info that may help?

**Comment by MSLaguana** [comment]
Could you please run `where react-native` and see what the result is?

**Comment by code945** [comment]
c:\>where react-native
C:\Users\hongxu.lin\AppData\Roaming\npm\react-native
C:\Users\hongxu.lin\AppData\Roaming\npm\react-native.cmd

**Comment by MSLaguana** [comment]
Hmm, that should mean it works. Can you please try one more thing: In your project folder on the command line, can you run vscode (I believe you should be able to run `code`) and see if that behaves differently?

**Comment by code945** [comment]
c:\projects\superL>vdcode
'vdcode' is not recognized as an internal or external command,
operable program or batch file.

c:\projects\superL>code
after i run code the vscode show up(before is minimized window)

**Comment by MSLaguana** [comment]
Please close vscode first, then try again. I'm curious to see if the way that you start it changes the environment variables and perhaps could allow it to find the react-native install.

**Comment by code945** [comment]
That's solve my problem, thanks!!! So it means that i can't run vscode from the shortcut icon on the desktop, only node cmd?

**Comment by MSLaguana** [comment]
It suggests that some environment variables are different in your command line environment. If you make sure that your `PATH` environment variable includes your `%appdata%\npm` folder where `react-native.cmd` is located, then vscode should be able to find it when you launch it outside the console.
