### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RamaSoni** [microsoft/vscode-react-native#1535]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMIN\AppData\Local\Temp\msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JiglioNero** [comment]
Hi @RamaSoni  and thanks for the report. Could you please add the CPU profile file as pointed in your issue? This file is crucial for understanding the reason of the performance issues.
