### ISSUE TITLE
Hi @Tj3n and thanks for reaching us.

### ISSUE THREAD

**Issue by mike22664** [microsoft/vscode-react-native#1539]
Hi @Tj3n and thanks for reaching us.
Under the hood the extension uses [`expo/xdl`](https://github.com/expo/expo-cli/tree/master/packages/xdl#readme) package to run Expo apps. While investigating we found out the problem could occur due to incorrect mapping of React Native and Expo SDK versions in [this function](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Versions.ts#L220-L244). The extension uses that function to prepare the project for debugging in VS Code. During the preparation, the extension is modifying `app.json` file and adding `sdkVersion` property with the mapped Expo SDK version there.
Could you please open `app.json` file in your project root folder and check if `sdkVersion` property is set to `40.0.0`? If the property contains `41.0.0` sdk version, please replace it with `40.0.0` and then try to debug the application again.
Please let us know about your results.

_Originally posted by @RedMickey in https://github.com/microsoft/vscode-react-native/issues/1528#issuecomment-799398739_

**Comment by JiglioNero** [comment]
Hi @mike22664 , I think this issue was opened accidentally, if so then can we close it?
