### ISSUE TITLE
error loading react-native extension in mar2016 release

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-react-native#155]
install the latest alpha build from https://vscode-builds.azurewebsites.net/alpha

install the react-native extension from the gallery

check the console, see this:

![image](https://cloud.githubusercontent.com/assets/1487073/13800182/f90e88a0-eae3-11e5-8e07-644fb833320b.png)

**Comment by MSLaguana** [comment]
Looks like the node debugger extension has changed publisher according to https://github.com/Microsoft/vscode-node-debug/blob/master/package.json, so we'll need to update that. I wonder if the publisher change will retroactively work with current versions, or if this is a breaking change...

**Comment by MSLaguana** [comment]
Following discussion on the node-debug extension github page, we should remove the dependency in package.json and check for both names when we activate, providing an appropriate error/warning in the case where neither is found.

**Comment by digeff** [comment]
@chrisdias The fix is now available on our master branch. It will be included in our next release.
