### ISSUE TITLE
[Bug] An error occurred while attaching debugger to the application. (error code 1410)

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode-react-native#1558]
# 🐛 What is the bug? How can we reproduce it?

Following the steps to resolve this bug in a previous [repo issue](https://github.com/microsoft/vscode-react-native/issues/1486) did not resolve it for me.

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:
launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to packager",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "attach",
      "sourceMaps": true
    }
  ]
}
```

1.  Launch simulator
2. Start RN with `yarn start`.
3. If debug is active, it will launch chrome devtools. Turn off `debug`, close devtools browser.
4. Restart `debug` on simulator.
5. In VSC, select "Attach to packager" and press Run button.

## Expected behavior
VSC reloads the app in `debug` mode.
## Actual behavior
<img width="418" alt="debugger-error" src="https://user-images.githubusercontent.com/313819/116602465-6335ff80-a8f1-11eb-90d1-b17ea7a752d8.png">

## Debug output

<details>
<summary>Debug Console</summary>

```text
No output
```
</details>

<details>
<summary>React Native output channel</summary>

```text
No RN output channel exists
```
</details>

<details>
<summary>Developer Tools console</summary>

```text

workbench.desktop.main.js:62 [Extension Host] (node:22845) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
m @ workbench.desktop.main.js:62
15workbench.desktop.main.js:62 [Extension Host] Error: EISDIR: illegal operation on a directory, read
workbench.desktop.main.js:2786 Extension Host
workbench.desktop.main.js:2786 Debugger attached.
workbench.desktop.main.js:626  WARN UNRESPONSIVE extension host, 'wangtao0101.vscode-js-import' took 79% of 2812.951ms, saved PROFILE here: 'file:///var/folders/sz/vx56zcrn2xg03s0t2089vpb80000gp/T/exthost-8bad7b.cpuprofile' Array(11)
workbench.desktop.main.js:62 [Extension Host] [vscode-icons] v11.4.0 activated!
workbench.desktop.main.js:62 [Extension Host] (node:22845) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
m @ workbench.desktop.main.js:62
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/3c4e3df9e89829dce27b7b5c24508306b151f30d/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

Android version: 
![android-version](https://user-images.githubusercontent.com/313819/116603582-b066a100-a8f2-11eb-8cc1-2f48aacbbfeb.png)

```text
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A [Note: `echo $ANDROID_HOME` produces `/Users/mstelly/Library/Android/sdk`]
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   1
Warnings: 0

```

* `envinfo`:

```text
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.64 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/mstelly/.rvm/rubies/ruby-2.6.3/bin/pod
    Homebrew: 3.1.4 - /usr/local/bin/brew
    pip3: 21.0.1 - /usr/local/bin/pip3
    RubyGems: 3.0.9 - /Users/mstelly/.rvm/rubies/ruby-2.6.3/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.15. - /usr/bin/gcc
    Git: 2.31.1 - /usr/local/bin/git
    Clang: 1200.0.32.29 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.55.2 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    WebStorm: 2021.1
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: javac 16 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.4 - /usr/local/bin/python3
    Ruby: 2.6.3 - /Users/mstelly/.rvm/rubies/ruby-2.6.3/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 90.1.23.73
    Chrome: 64.0.3282.140
    Safari: 13.1.3
```

* React Native Tools extension version: `v1.4.2`
* Expo SDK version (if applicable): N/A

**Comment by mjstelly** [comment]
For the life of me, I have no idea what magical combination of begging and cursing I used, but VSC debugger decided to start working today. Good news: it's working. Bad news: I have no way of reproducing it. So, it could flake out again the next time I launch VSC. ¯\_(ツ)_/¯

**Comment by RedMickey** [comment]
@mjstelly, It could be that by your project root path the extension cannot reach `./node_modules/react-native` folder or a `./package.json` file, which contains `react-native` dependency. 
To recognize your project as a React Native one, at first the extension tries to get a React Naive version from the `react-native` module from `projectRoot/node_modules` folder. If the extension cannot retrieve a React Native version from node modules, it will try to get the version from `projectRoot/package.json` file. So, if the version has been found successfully, the extension will activate and mark a project as React Native.

To customize your project root path you can use `react-native-tools.projectRoot` property in the extension settings (`Settings -> Extensions -> React Native configuration` or in `settings.json` file).

If the issue is reproduced again, could you please create and send us a minimal demo project with this problem or an approximate structure of your project, so we could reproduce and investigate the issue faster?
If the project could content any sensitive data you can send it to my working email: v-miezhe@microsoft.com
