### ISSUE TITLE
Single quote in JSX breaks vscode code formatting

### ISSUE THREAD

**Issue by taypo** [Microsoft/vscode-react-native#156]
If there is a single quote inside JSX, code formatting does not work for the entire file. Furthermore, if such a file is opened and tried code formatting, it breaks for __all other files__ until a vscode restart.

Sample: 
```javascript
class Sample extends Component {
	render() {
		<View style={styles.container}>
			<Text style={styles.title}>Don't</Text>
		</View>
	}
}
```

vscode 0.10.11 on windows 7

ps: while writing this issue, I looked at the markdown preview and it also does break after the quote. So may be I'm wrong here. In any case, it should not have got broken for the entire IDE.

**Comment by hamiltonia** [comment]
Thanks for reporting @taypo - this is actually an issue with VS Code and not the react-native extension. I've opened a new issue with your info here: https://github.com/Microsoft/vscode/issues/4324

FWIW - it does appear that the issue can be worked around by using multiple lines of text, e.g.

```
<View style={styles.container}>
    <Text style={styles.title}>
        Don't
    </Text>
</View>
```

I will be closing this issue - please continue to monitor the VS Code issue directly.
