### ISSUE TITLE
[Bug] No ios device available after upgrade to RN 0.64.1

### ISSUE THREAD

**Issue by stef1103** [microsoft/vscode-react-native#1564]
After upgrading project from RN 0.63.3 to RN 0.64.1 i'm not able anymore to run/debug iOS through visual studio code debug utility, both simulator or physical device connected to the Mac. Hermes is disabled.

With 0.63.3 everything was working fine, with 0.64.1 i'm able to run/debug ios project only using react-native run-ios.
Debug/run android is working fine.

**Launch.json**
```text
{
            "name": "Debug iOS Simulator",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "target": "D4B35782-3627-49EA-9D13-F810CBA94C2B"
},
{
            "name": "Debug iOS Device",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "target": "device"
 },
```

**Debug output**
<details>
<summary>React native output</summary>

```text

[Error] Error: Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712)

```
</details>

<details>
<summary>React Native: Run ios output:</summary>

```text

debug Reading ../ios/Podfile
debug Reading ../ios/Podfile.lock
info Found Xcode workspace "myapp.xcworkspace"
error Could not find a device with udid: "D4B35782-3627-49EA-9D13-F810CBA94C2B". Available devices:

```
</details>

<details>
<summary>Debug console output:</summary>

```text

Launching the application

```
</details>

**Environment**

<details>
<summary>npx react-native doctor output</summary>

```text

Common
 ✓ Node.js
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.3
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   1
Warnings: 0

```
</details>

<details>
<summary>envinfo:</summary>

```text

System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 2.27 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
    Homebrew: 3.1.5 - /usr/local/bin/brew
    pip3: 21.1.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.11 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 90.0.4430.93
    Edge: 90.0.818.56
    Firefox: 88.0
    Firefox Developer Edition: 89.0
    Safari: 14.1

```
</details>

* React Native Tools extension version: 1.4.2

**Comment by RedMickey** [comment]
Hi @stef1103 and thanks for reaching us.
I investigated this issue and found out that it is related to [the issue](https://github.com/react-native-community/cli/issues/1404) in [`react-native-community/cli`](https://github.com/react-native-community/cli). It seems that in XCode 12.5 some changes have been made, that affected the command used in RN CLI, which is responsible for finding iOS devices/simulators.
While investigating I tried to run the command, which is used in the extension to launch an iOS app, in the terminal and also get an error:
```
npx react-native run-ios --udid 6B971A1E-774B-40DF-BEFE-E3D48CB764BF --no-packager --verbose

debug Reading /Users/user/Documents/test_react/AwesomeProject0641/ios/Podfile.lock
info Found Xcode workspace "AwesomeProject0641.xcworkspace"
error Could not find a device with udid: "6B971A1E-774B-40DF-BEFE-E3D48CB764BF". Available devices:
```

[The issue](https://github.com/react-native-community/cli/issues/1404) in `react-native-community/cli` is already fixed, and the solution will be available in the next release of the CLI. But for now you can follow [this workaround](https://github.com/react-native-community/cli/issues/1404#issuecomment-833483585) and patch the current version of RN CLI in your project to be able to run your application on a specified iOS device/simulator. After that the RN command above and the debugging scenario in the extension should work properly, and an application should be launched on a specified device.
