### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ngoc-dev** [microsoft/vscode-react-native#1569]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `0.3.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\A5C15~1.RAM\AppData\Local\Temp\vsmobile.vscode-react-native-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RedMickey** [comment]
Hi @ngoc-dev and thanks for the report. Could you please add the CPU profile file as pointed in your issue? This file is crucial for understanding the reason of the performance issues.

**Comment by RedMickey** [comment]
@ngoc-dev, do you have a chance to look at this?
