### ISSUE TITLE
[Bug] property sourceMapPathOverrides is not allowed

### ISSUE THREAD

**Issue by munkledata** [microsoft/vscode-react-native#1586]
We are using Typescript with react native and certain parts of the code I cannot put a breakpoint. It just instantly disappears as soon as I place it. The documentation suggests using sourceMapPathOverrides to resolve this issue, but that option doesn't appear to be an option anymore. When I try  to add it to launch.json vscode complains and says "property sourceMapPathOverrides is not allowed".  Is the documentation out of date or is this a bug?

**Comment by RedMickey** [comment]
Hi @munkledata and thanks for reaching us. Currently the `sourceMapPathOverrides` parameter is supported in attachment debugging scenarios.

![image](https://user-images.githubusercontent.com/33267199/121157122-f566e700-c851-11eb-94c5-ad1c5dcdc55f.png)
I also tried to use the parameter in launch debugging scenarios, and the extension could handle it despite the `Property sourceMapPathOverrides is not allowed` warning.
We should fix this warning and allow this parameter for launch debugging scenarios.

**Comment by RedMickey** [comment]
@munkledata, we added the `sourceMapPathOverrides` parameter to launch debugging configurations. The fix will be available in the next release.
