### ISSUE TITLE
[Feature] Add context variable for custom keybindings

### ISSUE THREAD

**Issue by AmaanKulshreshtha** [microsoft/vscode-react-native#1599]
# 🚀 Feature request

I would like to request for context variable.

## What scenarios will this solve?
I had assigned the same keyboard combination for stopping and starting the packager. But only one of the functionalities works like that.
I would like the option of using the "when" flag so that I can trigger the "start the packager" when it is in "stopped" state and vice versa. Currently, I have bound my keys to "restart packager". But there are some case where I'd like option of explicitly stopping the packager, and starting it again.

## What will this allow you to do? Will this benefit other developers?
Add more convenient bindings.

I think it will help others too

**Comment by RedMickey** [comment]
Hi @AmaanKulshreshtha and thanks for reaching us.
We added context variables for the following features:
|Context variable|Feature|
|---|---|
|`isRNPackagerRunning` - true if the packager is running|Metro packager|
|`isRNTNetworkInspectorRunning` - true if the Network inspector is running|Network inspector|

Now it's possible to assign the same keyboard combination for `Start Packager` and `Stop Packager` commands using `when` clauses. For example like this:
![Screen Shot 2021-07-08 at 16 29 38](https://user-images.githubusercontent.com/33267199/124930347-eb2f3880-e009-11eb-8bf0-6f3757423389.png)

These context variables will be available in the next version of the extension.
