### ISSUE TITLE
[Feature] Add extension to Open VSIX

### ISSUE THREAD

**Issue by clin1234** [microsoft/vscode-react-native#1613]
# 🚀 Feature request

Add vscode-react-native to Open VSIX

## What scenarios will this solve?

This allows derivatives of VS Code, such as VSCodium, to be able to use the extension.

**Comment by RedMickey** [comment]
Hi @clin1234, we're not likely to do this. However, VSIX files of the extension are available for download on the [release page](https://github.com/microsoft/vscode-react-native/releases) of this repo and we encourage you to use them.
