### ISSUE TITLE
Put errors into a window so that errors can be copied!!!! For goodness sake.

### ISSUE THREAD

**Issue by gfmoore** [microsoft/vscode-react-native#1629]
## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by RedMickey** [comment]
Hi @gfmoore and thanks for reaching us. We've investigated ways to copy the error message from a modal window:

- On macOS it's possible to select text in modal windows and then copy it using `cmd+C`/`cmd+V` shortcuts.
    ![image](https://user-images.githubusercontent.com/33267199/128489888-2e421a81-2dcc-401c-a08d-645cce438e80.png)

- On Windows we couldn't select text in modal windows in VS Code, it seems that this isn't the issue of the extension. So, we'd recommend you to file the issue about such behavior to the [VS Code repo](https://github.com/microsoft/vscode).
    ![image](https://user-images.githubusercontent.com/33267199/128496616-be47b63c-64af-4c9a-8a14-894871c1f9ee.png)
    However, we found out how to copy text from a modal window. When the window appears, simply make sure it’s active and press the standard Windows copy shortcut combination of `Ctrl+C`. Now the data is in the clipboard, so you  can paste the contents into notepad or webpage etc. (Please note this only works on Windows)
    Below is an example of a copied message:
    ```
    [Window Title]
    Visual Studio Code
    
    [Content]
    Could not find the task 'gulp: build'.
    
    [ ] Remember my choice for this task  [Debug Anyway] [Configure Task] [Cancel]
    ```

We'll also improve error logging while debugging by duplicating error messages in the Debug console. So, it will be possible to copy an error message from the console.
![image](https://user-images.githubusercontent.com/33267199/128496830-872fc757-3553-4585-b19f-ba8bc812e8dd.png)

**Comment by gfmoore** [comment]
Fair enough then.

Now I need to get it working!!!

:)

**Comment by RedMickey** [comment]
@gfmoore If you have any questions or problems with the extension, we will be happy to help you.
