### ISSUE TITLE
React Native intellisense never enabled.

### ISSUE THREAD

**Issue by nitsujri** [Microsoft/vscode-react-native#164]
I continuously get the when I launch VS code:

`React Native intellisense was successfully configured for this project. Restart to enable it.`

React 0.21.0
react-native-cli@0.1.10
VS Code 0.10.11
VS Code React Native Tools 0.1.2

Any idea on what I might be missing to enable it?

Thanks,
Justin

**Comment by hamiltonia** [comment]
What OS are you using? How are you closing and restarting VS Code? On OS X in particular you will need to completely quit VS Code (Cmd+Q), not just the open window, but the app itself.

**Comment by hamiltonia** [comment]
Closing due to lack of feedback, if you're still having this issue feel free to reopen the thread.

**Comment by lihuazhang** [comment]
![image](https://cloud.githubusercontent.com/assets/872749/14547490/d533e1ea-02e0-11e6-9ecb-c26e16f6834c.png)

I got this issue too. When I restart system and launch VS Code. The message pop up. 

On OSX 10.11.4
![image](https://cloud.githubusercontent.com/assets/872749/14547501/fc9dfa54-02e0-11e6-94eb-dab40a40b8ef.png)

**Comment by hamiltonia** [comment]
@lihuazhang what version of VS Code are you using? Are you completely exiting out of VS Code before restarting it (cmd+Q)?

**Comment by lihuazhang** [comment]
@hamiltonia 1.0.0 (1.0.0). This only happens  when I restart OSX and launch the Code for the first time.

**Comment by patrick91** [comment]
the message did disappear when I run Visual Studio Code setting `VSCODE_TSJS` to 1

```
VSCODE_TSJS=1 code .
```

Maybe it is related to #143

**Comment by miqu** [comment]
The same problem on Debian Linux. Installed code from Debian package. Complains every time.

**Comment by neilyoung** [comment]
Same here. "code ." then 

  React Native intellisense was successfully configured for this project. Restart to enable it.

Regardless of how many time you restart - it will come again. VSCODE_TSJS=1 provokes an error message on first start but seems to work somehow. But what the hell is this??

**Comment by MSLaguana** [comment]
This is a remnant from supporting earlier versions of VS Code, and we're working on a fix for it. The VSCODE_TSJS environment variable was for opting in to a then-experimental different way of providing intellisense (which understood jsx, among other things) but it is no longer needed.

**Comment by neilyoung** [comment]
Yes, thanks. Found the meaning by myself already. But it is still helpful. Using latest code insider.

**Comment by MSLaguana** [comment]
In the currently published version with up-to-date versions of vscode this environment variable should no longer be checked for or set.
