### ISSUE TITLE
[Feature] Start Run Android on Emulator etc from Tasks.json rather than using F1

### ISSUE THREAD

**Issue by gfmoore** [microsoft/vscode-react-native#1646]
# 🚀 Feature request

What do you want to be added?

## What scenarios will this solve?

What will this allow you to do? Will this benefit other developers?

I have other things in my Tasks and like to keep the task manager drawer open Zhang Shen Task Manager extension).

What command can I put in my tasks.json?

**Comment by JiglioNero** [comment]
Hi @gfmoore and thanks for contacting us. Extension commands can be run in VSCode tasks using command identifiers. You can use React Native Tools commands in `tasks.json` file as follows:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Android on Emulator",
      "command": "${command:reactNative.runAndroidSimulator}", 
      "problemMatcher": []
    }
  ]
}
```
Where `reactNative.runAndroidSimulator` is the ID of the `Run Android on Emulator` command.

You can find the list of the extension commands with IDs [here](https://github.com/microsoft/vscode-react-native#react-native-commands-in-the-command-palette).

**Comment by gfmoore** [comment]
That's fantastic. You peeps are the best! :)
