### ISSUE TITLE
SyntaxError: Unexpected token [Error : 0704] - when opening folder

### ISSUE THREAD

**Issue by JeandeCampredon** [Microsoft/vscode-react-native#166]
Our current project was perfectly working on:
OS X 10.11.3
vscode 10.11
react native tool 0.1.0

since I upgraded to:
OS X 10.11.3
vscode 10.11
react native tool 0.1.2

I have the following error when I lauch vscode and can't figure out what it is:
```
"Error while setting up IntelliSense: SyntaxError: Unexpected token /"
[Error : 0704]  Failed to setup IntelliSense: Unexpected token /
```

Any help please :D ? Is there anywhere I can find more details on the errors ?

PS: still working on my personal computer with the old version of the extension

**Comment by hamiltonia** [comment]
Hi @JeandeCampredon, 

Sorry you're having problems after the update. Can you verify a couple things:

How are you opening your project? Have you tried both:
- opening vscode, then opening the root folder of your project
- navigating to your project folder from a terminal window and opening the project with "code ."

Can you inspect the settings.json file in your project's .vscode folder, what does it contain?

**Comment by JeandeCampredon** [comment]
Hi @hamiltonia thank you for answering so fast !

- I have tried opening both way with the same result.

- my jsconfig.json is pretty simple :
```
{
    "compilerOptions": {
      "module": "system",
      "experimentalDecorators": true
    },
    "exclude": [
      ".git",
      "node_modules",
      "android",
      "ios",
      "config",
      "planning",
      ".idea",
      "Andromeda",
      "scripts"
    ]
}
```

- here is the path where I find my project :
`/Users/jean/Work/Corona`

but It might come from my project since initiating a new project with the react-native-cli is working

**Comment by hamiltonia** [comment]
Glad that it's working for some projects. 

Do you have a settings.json file under the project/.vscode directory? That file is most likely what's causing the error, either trying to read it, or writing it. With older versions of the extension we create this file to help with IntelliSense, with your version it shouldn't be needed but it may be causing problems.

**Comment by JeandeCampredon** [comment]
Indeed removing the project settings (I moved it to the user settings) fixed the issue, thank you !
I am not really sure to understand why though, here is my previous settings.json :
```
// Place your settings in this file to overwrite the default settings
{
  "editor.tabSize": 2,
  "files.autoSave": "afterDelay",
  "files.trimTrailingWhitespace": true,
  "telemetry.enableTelemetry": true
}
```

**Comment by hamiltonia** [comment]
The issue appears to be the default comment placed at the top of the settings.json. We're unable to parse the JSON while that's there, which results in an error and we fail to initialize. Strangely enough this doesn't repro in the latest [insider](https://code.visualstudio.com/insiders) build of VS Code. I will investigate what changed there, in the meanwhile the workaround is to simply remove that comment from your settings.

**Comment by MSLaguana** [comment]
We now handle comments in settings.json correctly.

**Comment by JeandeCampredon** [comment]
Great news ! Well done
