### ISSUE TITLE
[Bug] Cannot launch "Debug Android" (error code 303)

### ISSUE THREAD

**Issue by Elias-Graf** [microsoft/vscode-react-native#1666]
# 🐛 What is the bug? How can we reproduce it?

When pressing the play button it just shows `[Info] Starting Packager`, and after a long time it fails with `Could not start the packager. (error code 303)`. I normally launch the app with: `npm start` and then in a different terminal `npm run android`.

Steps:

1. `npx react-native init test`
0. open the project with code
0. create the default launch.json for debug android & run that

## Expected behavior

The packager to start

## Debug output

<details>
<summary>Debug Console</summary>

```text
Launching the application
An error occurred while launching the application. Could not start the packager. (error code 303)
```
</details>

<details>
<summary>React Native output channel</summary>

```text
[Info] Starting Packager

[Error] Error: Could not start the packager.
```
</details>

<details>
<summary>Developer Tools console</summary>

```text
console.ts:137 [Extension Host] (node:9562) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code-insiders --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode…t/rn-extension.js:1)
	at Timeout._onTimeout (vscode-file://vscode…t/rn-extension.js:1)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
mainThreadExtensionService.ts:63 [[object Object]]s.tmpDir is not a function
mainThreadExtensionService.ts:64 TypeError: s.tmpDir is not a function
	at e._sendFirstFileOnDisk (vscode-file://vscode…t/rn-extension.js:1)
	at Timeout._onTimeout (vscode-file://vscode…t/rn-extension.js:1)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
console.ts:137 [Extension Host] An error occurred while launching the application. Could not start the packager. (error code 303) (at u.log (/home/elias/.vscode-insiders/extensions/msjsdiag.vscode-react-native-1.6.1/dist/rn-extension.js:21:28847))
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✖ Node.js
   - Version found: N/A
   - Version supported: >= 8.3
 ✖ npm
   - Version found: N/A
   - Version supported: >= 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✖ ANDROID_HOME
```

* `envinfo`:

```text
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 15.60 GB / 31.33 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Managers:
    Apt: 2.2.4 - /usr/bin/apt
  Utilities:
    Make: 4.3
    GCC: 10.3.0
    Git: 2.30.2
    FFmpeg: 4.3.2 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.8 - /usr/bin/docker
  IDEs:
    Nano: 5.4
  Languages:
    Bash: 5.1.4 - /usr/bin/bash
    Java: 1.8.0_292
    Perl: 5.32.1 - /usr/bin/perl
    Python3: 3.9.5
  Databases:
    MySQL: 0.21.04.3 - /usr/bin/mysql
    SQLite: 3.32.2 - /home/elias/Android/Sdk/platform-tools/sqlite3
```

* React Native Tools extension version: `v1.6.1`
* Expo SDK version (if applicable): -

**Comment by RedMickey** [comment]
Hi @Elias-Graf and thanks for reaching us. According to your system environment information, it seems that there are no Node.js, Android SDK and `ANDROID_HOME` variable in the PATH. 
Could you please tell us if you have completely set up your development environment according to the [official React Native guide](https://reactnative.dev/docs/environment-setup)?
Could you please also tell us if you ran `npx react-native doctor` and `envinfo` commands in the system terminal or in the terminal in VS Code editor?

**Comment by Elias-Graf** [comment]
>  it seems that there are no Node.js

I wouldn't trust this doctor tool if it can't even run `node -v` and `npm -v`, I mean I'm clearly running `npx react-native docutor`, would be quite impressive if I managed that without node ;)

This might be interesting as well:
```txt
❯ which node
/snap/bin/node
❯ which npm
/usr/local/bin/npm
❯ which npx
/usr/local/bin/npx
```

> Android SDK and ANDROID_HOME

Yeah, I have that inside a `local.properties` file, e.g.: `sdk.dir=/home/elias/Android/Sdk` 

> Could you please tell us if you have completely set up your development environment according to the official React Native guide?

Uh, sure, I've read through it and added

```text
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

to my `.zshrc`.

I've also installed the android Q SDK.

Is there more configuration I'm missing? (It seems weird that `npm start` and `npm run android` are working if it couldn't find something of that significance though).

> Could you please also tell us if you ran npx react-native doctor and envinfo commands in the system terminal or in the terminal in VS Code editor?

I actuall don't remember, so here is both 😉

### System terminal emulator:

```text
 ✖ Node.js
   - Version found: N/A
   - Version supported: >= 8.3
 ✖ npm
   - Version found: N/A
   - Version supported: >= 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME
```
### Integrated terminal:

```text
 ✖ Node.js
   - Version found: N/A
   - Version supported: >= 8.3
 ✖ npm
   - Version found: N/A
   - Version supported: >= 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✖ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME
```
In both cases the command was executed inside the projects working directory :)

**Comment by RedMickey** [comment]
@Elias-Graf Thanks for the outputs.
Could you please tell if you installed VS Code using snap store or from the [.deb package](https://code.visualstudio.com/#alt-downloads)? We had a [similar issue](https://github.com/microsoft/vscode-react-native/issues/1273) with VS Code installed from snap store, and it was [resolved after reinstallation](https://github.com/microsoft/vscode-react-native/issues/1273#issuecomment-632801648) of the editor from the .deb package.

**Comment by Elias-Graf** [comment]
@RedMickey It is indeed installed via `snap`, but I'm being honest here, I'm not really happy with the fix of installing another package :/. 

VSCode has to be installed in [classic](https://ubuntu.com/blog/how-to-snap-introducing-classic-confinement) mode, so there shouldn't be any difference.

**Comment by Elias-Graf** [comment]
Is this issue being tracked in the vscode repo or is it only happending with this extension?

**Comment by RedMickey** [comment]
@Elias-Graf While investigating this issue we found two similar issues in VS Code repo ([issue1](https://github.com/microsoft/vscode/issues/102355), [issue2](https://github.com/microsoft/vscode/issues/102723)). The problem occurs if both Node.js and VS Code are installed from snap store. According to these comments ([comment1](https://github.com/microsoft/vscode/issues/102355#issuecomment-657707702), [comment2](https://github.com/microsoft/vscode/issues/102723#issuecomment-659708019), [comment3](https://github.com/microsoft/vscode/issues/102723#issuecomment-668266884)) the issue could be in Node.js distributed via snap store.
Under the hood, in the extension we use Node.js child processes to run React Native CLI and npm commands. To start Node.js child processes we use `spawn` and `exec` functions which could work incorrectly and cause errors (if Node.js and VS Code are installed from snap store). We found the [open issue](https://github.com/nodejs/snap/issues/13) in _nodejs/snap_ repo about this problem. So, the original issue could be on Node.js side. We also found out an interesting fact, that if one of VS Code and Node.js isn't installed from snap store, everything works fine, but installation of both of them via snap causes issues.
Thus, we would recommend to install Node.js from other sources than snap store to avoid incorrect behavior of Node.js spawn functions.

**Comment by Elias-Graf** [comment]
Huh, how interesting. Is there anything I can do to help you and the node.js guys? 

And good one on the investigation, very thorough 👍.

**Comment by etatanova** [comment]
Hi @Elias-Graf We have reported about this issue to the [nodejs/node](https://github.com/nodejs/node/issues/37982#issuecomment-926588045) and [nodejs/snap](https://github.com/nodejs/snap/issues/13#issuecomment-926588479) repositories. So, we will track these issues and test proposed fixes. Since it's a Node.js issue, we don't think there's anything actionable from the React Native Tools side on this. Thank you for your assistance!
Until the issues in Node.js are fixed, as the workaround we would recommend to install Node.js from other source than the Snap Store.

**Comment by etatanova** [comment]
I am closing this issue because this is an external issue (Node.js related). Please feel free to open new ones if needed.
