### ISSUE TITLE
[Bug] v1.6.1 hermes debugging in iOS broken

### ISSUE THREAD

**Issue by vcellu** [microsoft/vscode-react-native#1671]
# 🐛 What is the bug? How can we reproduce it?

We have a fairly large project.  v1.6.0 we were able to debug with hermes on simulator.  Simply upgrading to v1.6.1 we receive cannot attach to debugger on port 8081
1. upgrade from v.1.6.0 to v1.6.1
2. Step 2

## Expected behavior

Works like v1.6.0

## Debug output

<details>
<summary>Debug Console</summary>

```
connecting to port 8081

```
</details>

<details>
<summary>React Native output channel</summary>

</details>

<details>
<summary>Developer Tools console</summary>

</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.08.30.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 26.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
   - Version supported: Not Found
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0
```

* `envinfo`:

```text
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.01 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/vel/.rvm/gems/ruby-2.6.6/bin/pod
    Gradle: 7.0.2 - /usr/local/bin/gradle
    Homebrew: 3.2.12 - /usr/local/bin/brew
    pip3: 21.1.3 - /usr/local/bin/pip3
    RubyGems: 3.0.8 - /Users/vel/.rvm/rubies/ruby-2.6.6/bin/gem
  Utilities:
    CMake: 3.21.1 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.31.1 - /usr/local/bin/git
    Clang: 13.0.0 - /usr/bin/clang
    Ninja: 1.8.2 - /Users/vel/workspace/depot_tools/ninja
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.8 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 26.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: 3211 - /Users/vel/bin/subl
    VSCode: 1.60.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.10 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Protoc: 3.17.3 - /usr/local/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.6 - /usr/local/bin/python3
    R: 4.0.2 - /usr/local/bin/R
    Ruby: 2.6.6 - /Users/vel/.rvm/rubies/ruby-2.6.6/bin/ruby
  Databases:
    SQLite: 3.32.2 - /Users/vel/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 14.1.2
  Monorepos:
    Yarn Workspaces: 1.22.11
    Lerna: 3.22.1
```

* React Native Tools extension version: 1.6.1
* Expo SDK version (if applicable): VERSION

**Comment by RedMickey** [comment]
Hi @vcellu and thanks for reaching us. We tried to reproduce this problem on a new plain React Native app (RN 0.65.1, iOS Hermes) and could debug it without problems.
Could you please try to create a plain React Native app and check whether iOS Hermes debugging works there?
If debugging of the plain React Native app also doesn't work, could you please set the extension log level to `Trace` and send us logs from Debug Console, `React Native`, `React Native: Run ios` output channels for the plain project?
You can change the extension log level by adding the `settings.json` file to the `.vscode` folder with the following content:
```
{
    "react-native-tools.logLevel": "Trace"
}
```

If debugging of the plain React Native app works correctly, could you please also set the extension log level to `Trace` for your original project, try to debug it again and send us the same logs as for the plain project? It would also be very helpful for us if you could provide a small demo project with this problem, so we could reproduce it.

Please, let us know about your results.

**Comment by vcellu** [comment]
Sorry, for the late reply.  After reinstalling the extension it works again. in V1.6.1

**Comment by RedMickey** [comment]
@vcellu Glad to hear that! Then I am closing this issue. Feel free to open new ones if needed.
