### ISSUE TITLE
[Bug] Unable to debug on iOS device after update to Xcode 13

### ISSUE THREAD

**Issue by sfedorov-at-wiley** [microsoft/vscode-react-native#1677]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

Running debugger on device using Xcode 13 is no longer possible, because `xcrun instruments` were deprecated and removed.

Steps to reproduce:
1. Update Xcode to latest version
2. Use following launch.json config
```json
{
    "name": "Debug iOS Device",
    "cwd": "${workspaceFolder}",
    "type": "reactnative",
    "request": "launch",
    "platform": "ios",
    "target": "device"
}
```
3. Run debugger

## Expected behavior

What were you expecting to happen?
To start without errors

## Debug output

<details>
<summary>Debug Console</summary>

```text

Launching the application
An error occurred while launching the application. Error while executing command '[MyAppPath]/node_modules/.bin/react-native run-ios --device --no-packager --verbose' (error code 101) (error code 303)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command '[MyAppPath]/node_modules/.bin/react-native run-ios --device --no-packager --verbose' (error code 101)

```
</details>

<details>
<summary>React Native: Run ios output channel</summary>

```text

info Found Xcode workspace "[WorkspaceName].xcworkspace"
xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
error Command failed: xcrun instruments -s
xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

Error: Command failed: xcrun instruments -s
xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    ...Stack trace...

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.09.13.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: Not Found
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
```

* `envinfo`:

```text

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 324.59 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
    Homebrew: 3.2.14 - /usr/local/bin/brew
    pip3: 21.2.4 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 1300.0.29.3 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.8 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.55.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2019.2.4
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.11 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.7 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    PostgreSQL: 13.4 - /usr/local/bin/postgres
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 94.0.4606.61
    Safari: 15.0
```

* React Native Tools extension version: v1.7.0
* Expo SDK version (if applicable): Not applicable

**Comment by RedMickey** [comment]
Hi @sfedorov-at-wiley and thanks for reporting. Under the hood the extension uses the `react-native run-ios` command from RN CLI to launch the application on an iOS device.
Could you please try to run the `npx react-native run-ios --device` command in the terminal to check if it works there?
We also found similar open issues in [`react-native-community/cli`](https://github.com/react-native-community/cli/issues/1474) and [`facebook/react-native`](https://github.com/facebook/react-native/issues/32255) repos, so it seems the problem could be related to React Native CLI which uses `instruments`.

Could you please also tell us the version of the `react-native` package used in your project?

**Comment by sfedorov-at-wiley** [comment]
@RedMickey I usually run app on device directly from Xcode. So that's why I found this issue while using the extension.
I can confirm, that `npx react-native run-ios --device` fails to execute with the same reason.
Version of package is `"react-native": "0.63.3"`

Problem is, that for now I have no workaround to debug my app on device. So I'll be glad if you suggest something to try out

**Comment by JiglioNero** [comment]
Hi, @sfedorov-at-wiley. In React Native `v0.63` CLI uses the deprecated `instruments` command, which was removed in XCode 13. 
According to the [comment](https://github.com/facebook/react-native/issues/32255#issuecomment-932039063) this error can be solved by increasing the version of the `react-native` package to at least `v0.64`. It also possible to rewrite the use of the `instuments` utility to the` xctrace` utility in the `node_modules\@react-native-community\cli-platform-ios\build\commands\runIOS\index.js` file in the `runIOS` function manually as proposed in this [patch](https://github.com/react-native-community/cli/commit/c5ca3b6c693eec2c7f0c7d5082352fd117e9620e) (please note, that since this is TS code, it's needed to use its JS equivalent to apply the patch in already built RN CLI code). 
Also you can find other possible solutions in this [issue](https://github.com/facebook/react-native/issues/32255)

**Comment by RedMickey** [comment]
This issue was fixed in React Native CLI in the PR https://github.com/react-native-community/cli/pull/1484.

**Comment by Damoness** [comment]
nice
