### ISSUE TITLE
[Bug] Debug with hermes on IOS

### ISSUE THREAD

**Issue by sontruongna** [microsoft/vscode-react-native#1693]
# 🐛 When I debug with Attach to hermes on IOS:
1. I can't reload app in Debug Menu. I have to disconnect and attach again.
2. When I put a breakpoint anywhere and then disconnect and attach again, breakpoint  jump into node_modules/metro-runtime/src/polyfills/require.js

Steps:

1. npx react-native init Test --template react-native-template-typescript
2. Podfile: hermes_enabled => true 
3. pod install
4. Xcode run
5. Watch the video for more details

https://user-images.githubusercontent.com/93734269/140406588-59be98c2-5004-4bb2-bb13-627720255ec7.mov

https://user-images.githubusercontent.com/93734269/140406632-15eb9715-4d85-4427-ae07-f7f93309fc52.mov

* React Native Tools extension version: 1.7.1
* Macbook Pro M1
* Xcode Version: 13.1
* React Native Version: 0.66.2

**Comment by AndrewMorsillo** [comment]
Can confirm I am seeing the same issue in my project

* React Native Tools extension version: v2021.10.3121
* Macbook Pro M1
* Xcode Version: 13.1
* React Native Version: 0.66.2

**Comment by RedMickey** [comment]
Hi @sontruongna and @AndrewMorsillo and thanks for reaching us. We fixed this issue in the [PR](https://github.com/microsoft/vscode-react-native/pull/1696). You can try out the fix in the latest version of the [React Native Tools (Preview)](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) extension. I'm closing the issue, please feel free to open new ones if needed.

**Comment by SeanDunford** [comment]
Can confirm that the `Preview` fixes this issue, ty.
