### ISSUE TITLE
[Feature] Prompt satisfaction survey

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1697]
# 🚀 Feature request

VS Code is currently the one decided when to show the [satisfaction survey](https://www.surveymonkey.com/r/6FJGVDV).
I'd like us to be more in control as now it is not showing to anyone.

We could probably do something similar to what was done with the tips notification where the extension loads a remote config file and then decides to show or not the toast.

I was thinking about something like this:

1.  Download toast configuration
2. If survey is opened, continue. If not, do nothing (we could close it if we have enough answers)
1.  If user has been marked as leave alone for a period of time, not do anything
1.  If user has not been shown a toast recently, decide if show it or not based on a percentage in the configuration
  1. If yes: show the toast with a link to the survey, and mark the user as leave alone for an extended time
  2. If no: mark the user as leave alone for a short period of time

The reason for having to periods of time are:
- For those who answer, we don't want them to have survey fatigue
- For those that are not prompted, we want to remove them from the pool of candidates for a while to make sure we ask 10% of the user over that period of time. Otherwise we might end up asking way to more people 

Hopefully this makes sense. If you see something wrong in the logic above, feel free to correct it!

## What scenarios will this solve?

We will get a better understandment of the areas that need to be improved.

**Comment by RedMickey** [comment]
Hi @molant, could you please tell if I understood you correctly about this rule?

> For those that are not prompted, we want to remove them from the pool of candidates for a while to make sure we ask 10% of the user over that period of time. Otherwise we might end up asking way to more people

If a user isn't included in 10% of the users we prompt a survey, we should remove the person from candidates for a long period of time the same as we do if the user has taken the survey.

**Comment by molant** [comment]
@RedMickey I'm thinking the duration should be shorter so we can prompt them sooner that the others. Otherwise we risk "running out" of users really soon.
What about this:

* Users that get prompted --> Not bother for 3 months
* Users that do not get prompted --> Not bother for 1 month

**Comment by RedMickey** [comment]
@molant Ok, thanks. And If a user was prompted and rejected the survey (e.g. by clicking `Remind Me later`), should we also delay the survey for a month?

**Comment by molant** [comment]
If he rejects it, it should be 3 months.
