### ISSUE TITLE
[Bug] Failed to run a debug test in VS Code for a react-native app error code #604 and code #1410

### ISSUE THREAD

**Issue by Samsonroyal** [microsoft/vscode-react-native#1743]
# 🐛 Failed to run a debug test in VS Code for a react-native app error code #604 and code #1410

The bug is an error code 604 and code 1410. I followed through the steps suggested by @SounD120 but still got the same error code prompt when i run debug.

1. I installed react-native-cli globally by npm install -g react-native-cli
2. I initialized a new react-native app called "DoneWithIt inside a folder named "Demo" on desktop
3. I installed all the necessary react-native extensions including react-native-tools
4.  created a new launch.json file and added two configurations to it; attach to packager and debug android
5. I changed the `"cwd": "${WorkspaceFolder}"` to `"cwd": "${Demo}"` as suggested by @SounD120 
6. selected attach to packager configuration and ran the debug test and still received the same error

## Expected behavior

I am expecting the debug console to show that my program has been tested successfully and has no bugs existent.

## Debug output

<details>
<summary>Debug Console</summary>

```

An error occurred while attaching debugger to the application. Seems to be that you are trying to debug from within directory that is not a React Native project root. 
 If so, please, follow these instructions: [https://github.com/microsoft/vscode-react-native#customization]() (error code 604) (error code 1410) (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text



```
</details>

<details>
<summary>Developer Tools console</summary>

```text

workbench.desktop.main.js:75 [Extension Host] An error occurred while attaching debugger to the application. Seems to be that you are trying to debug from within directory that is not a React Native project root.  If so, please, follow these instructions: https://github.com/microsoft/vscode-react-native#customization (error code 604) (error code 1410)
I @ workbench.desktop.main.js:75

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.

🎉 Didn't find any issues with the project!
```

* `envinfo`:

```text
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 978.95 MB / 7.90 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.2.4 - ~\anaconda3\Scripts\pip3.EXE
  Utilities:
    Git: 2.30.0. - C:\Program Files\Git\cmd\git.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0
  IDEs:
    VSCode: 1.64.0 - C:\Users\Were\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.0.32014.148 (Visual Studio Community 2022)
  Languages:
    Python: 3.9.7 - C:\Users\Were\anaconda3\python.EXE
  Databases:
    SQLite: 3.36.0 - C:\Users\Were\anaconda3\Library\bin\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
```

* React Native Tools extension version: v1.9.0
* Expo SDK version (if applicable): VERSION

**Comment by Samsonroyal** [comment]
@JiglioNero I have opened a new issue

**Comment by JiglioNero** [comment]
@Samsonroyal Thank you very much. The fact is that `workspaceFolder` is a variable reserved by VS Code to indicate the directory in which VS Code is open. If you open the root of your React Native project with VS Code, then it's enough to leave the value `"cwd": ${workspaceFolder}"` 

![image](https://user-images.githubusercontent.com/43934531/152807331-799cf923-9f4e-4356-b0ba-006cd676bf33.png)

or for monorepo projects, specify subproject root as follows: `"cwd": "${workspaceFolder}/Projects/ProjectOne"`

![image](https://user-images.githubusercontent.com/43934531/152807477-acf90546-1886-4d5a-9a0f-e85780d4f3e8.png)

**Comment by Samsonroyal** [comment]
![Screenshot 2022-02-07 180759](https://user-images.githubusercontent.com/26835888/152814608-f9e5d286-e38c-4e48-add9-62da3ffeb5d5.png)
This is the output upon running a debug test

**Comment by RedMickey** [comment]
Hi @Samsonroyal, according to your screenshot it seems that the `Demo` folder is opened in the editor. In this case the `${workspaceFolder}` is already equal to the `Demo` folder path (e.g. `some/path/to/Demo`). 
If we specify the path in `cwd` like `${workspaceFolder}/Demo/DoneWithIt`, the computed path will be `some/path/to/Demo/Demo/DoneWithIt`. Since such a path doesn't exist, the extension throws the error.
If we specify the path in `cwd` like `${workspaceFolder}/DoneWithIt`, the computed path will be `some/path/to/Demo/DoneWithIt`. This should be the correct path.

Could you please try to use the `${workspaceFolder}/DoneWithIt` value in the `cwd` parameter?
You can also find more info about reserved VS Code variables [here](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables).

**Comment by JiglioNero** [comment]
Hi @Samsonroyal Did you have a chance to check it?

**Comment by Samsonroyal** [comment]
Hello 👋🏾 @RedMickey and @JiglioNero u haven’t had a chance to check it out; I’m out of the city and can’t access my laptop. I’ll be able to check it around Monday 14th when I’m back. I really do hope it works

**Comment by JiglioNero** [comment]
Hi @Samsonroyal Just a friendly ping.

**Comment by Samsonroyal** [comment]
Hello @JiglioNero I did check it out
![success](https://user-images.githubusercontent.com/26835888/154761428-162e4e59-6870-41c7-8c55-b5542380c4af.png)
 and it gives me so much joy to say; it successfully ran a debug test, as you can see in the terminal it says "attaching to the application". I am smiling with glee.

**Comment by JiglioNero** [comment]
@Samsonroyal We are glad that your problem was successfully solved. Feel free to contact us further
