### ISSUE TITLE
Unable to find 'opn' package location

### ISSUE THREAD

**Issue by rmargolinross** [microsoft/vscode-react-native#1766]
# 🐛 What is the bug? How can we reproduce it?
I am trying to debug on android and I keep getting an error that the opn package location is not found. I have no idea how to fix this issue.

```An error occurred while launching the application. The package 'opn' was not found. Error: Opn package location not found (error code 501) (error code 502) (error code 303)```

## Environment

```text
 ✓ Node.js
 ✓ npm
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2022.03.21.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   1
Warnings: 0
```

* `envinfo`:

```text

  System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 931.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
    Homebrew: 3.4.5 - /usr/local/bin/brew
    pip3: 20.2.3 - /usr/local/bin/pip3
    RubyGems: 3.3.7 - /usr/local/opt/ruby/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 13.1.6 - /usr/bin/gcc
    Git: 2.31.1 - /usr/local/bin/git
    Clang: 13.1.6 - /usr/bin/clang
  Servers:
    Apache: 2.4.51 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.13 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 14.0.2 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.9.1 - /usr/local/bin/python3
    Ruby: 3.1.1 - /usr/local/opt/ruby/bin/ruby
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 100.0.4896.60
    Safari: 15.3
```

* React Native Tools extension version: Latest

**Comment by JiglioNero** [comment]
Hello @rmargolinross and thanks for contacting us. This error occurs when starting Packager. The fact is that the extension cannot find the `open` package in `node_modules` and inside the dependencies of the `react-native` package. Please try deleting the `node_modules` folder and then run the 'npm install' command. If this does not help, please send a basic demo project that will reproduce this error.

**Comment by rmargolinross** [comment]
@JiglioNero I managed to get it kinda running after doing your suggestion and starting my project freshly. I do still have issues but I believe they are all on my side so should be all set for now.

**Comment by GSingh01** [comment]
This issue is reproducible easily with yarn monorepo. It tries to locate 'open' package under app folder's node modules but in workspaces 'open' is hoisted. Any suggestion or fix please?

**Comment by JiglioNero** [comment]
Hi @GSingh01, have you tried [this](https://github.com/microsoft/vscode-react-native/issues/1766#issuecomment-1088679157) way to fix?

**Comment by GSingh01** [comment]
@JiglioNero the above fix wont work. But as suggested tried by clearing node_modules at both project level and root but looks like extension doesn't have way to look at workspace root.
To add i am using yarn with monorepos

**Comment by GSingh01** [comment]
i was able to bypass the error by using symlink to open and opn in workspace root. But now packager is not running and the reason i feel is same that the extension is looking for deps under .bin folder for app but it is hoisted in workspace root.
 there should be an option in launch.json to specify workspaceroot(to look for missing node_module in root as well) in addition to cwd or best would be if it can respect yarn workspace config in root package.json

**Comment by GSingh01** [comment]
In the meantime here is workaround

1. Set symlinks to open, opn and @react-native-community. Used expo-yarn-workspaces &  configured package.json as
```
//app's package.json
{
  ...,
   "expo-yarn-workspaces": {
      "symlinks": [
        "open",
        "opn",
        "@react-native-community/cli"
      ]
    }
  }
  ```
  
2. copy files from root node_modules/.bin to app's
```
//app's package.json
{
  ...,
  "cpToBin": "shx cp ../../node_modules/.bin/react-native ./node_modules/.bin/react-native && shx cp ../../node_modules/.bin/react-native.cmd ./node_modules/.bin/react-native.cmd",
  "postinstall": "expo-yarn-workspaces postinstall & yarn cpToBin"
}
```

**Comment by JiglioNero** [comment]
Hi @GSingh01 You can specify the path to the desired project in the following way:
```json
"cwd": "${workspaceFolder}/projects/rnProgect"
```
If this information did not help you, it would be great if you created a small demo project on which this error can be reproduced.

**Comment by JiglioNero** [comment]
@GSingh01 did you have a chance to check it?

**Comment by GSingh01** [comment]
@JiglioNero sorry i didnot managed to work on it yet, but this is easily reproducible with yarn monorepos. So if you wish try it on your side and you can reproduce it

**Comment by JiglioNero** [comment]
@GSingh01 Could you please attach output of the command `npx envinfo`

**Comment by JiglioNero** [comment]
@GSingh01 Did you have a chance to look at this?

**Comment by mrivera-ms** [comment]
> Hi @GSingh01 You can specify the path to the desired project in the following way:
> 
> ```json
> "cwd": "${workspaceFolder}/projects/rnProgect"
> ```
> 
> If this information did not help you, it would be great if you created a small demo project on which this error can be reproduced.

@JiglioNero, I am getting the same error. The issue happens in monorepos because the project is in a subfolder (as indicated in the 'cwd' line you wrote)  and the missing reference is in node_modules at the root of the repo. 

@GSingh01 proposed a solution:

> This issue is reproducible easily with yarn monorepo. It tries to locate 'open' package under app folder's node modules but in workspaces 'open' is hoisted. Any suggestion or fix please?
