### ISSUE TITLE
Cannot debug standalone react native project without android code

### ISSUE THREAD

**Issue by tianhonghui** [Microsoft/vscode-react-native#177]
I have a standalone react native project without android project.
when I use debugger to debug android it will stop cause It cannot find android project.

with version 0.1.0, the debugger met the same error but will not stop,and I can debug the project.

any idea to fix this?

**Comment by tianhonghui** [comment]
This is the error log:
```
node --debug-brk=35706 launchReactNative.js android 9090 simulator 
Debugger listening on port 35706
[vscode-react-native] Downloaded debuggerWorker.js (Logic to run the React Native app) from the Packager.
[vscode-react-native] Executing command: react-native run-android
Android project not found. Maybe run react-native android first?
[vscode-react-native] Finished executing: react-native run-android
[vscode-react-native] [Error : 0706]  Cannot debug application: Android project not found.
```

**Comment by MSLaguana** [comment]
What exactly are you trying to debug? If you do not have an android project then you cannot run your react native app on android, and thus you can't debug a react native app on android...

In version 0.1.0 we did not detect when the `react-native run-android` command failed, so in that case it may have been running older native code on the device if you had a previous install of your app on there somehow. We now ensure that the app is up to date to avoid potential issues with mismatched native code.

Is there a reason that you do not want to add an android project?

**Comment by tianhonghui** [comment]
> Is there a reason that you do not want to add an android project?
Actually I have a react native project without android or iOS code in git repository maybe A,and android project in git repository B,iOS project in git repository C.

So I want start debugger alone without additional gradle task.

**Comment by tianhonghui** [comment]
In another word, if I didn't change any android or iOS code,there is no reason that I need reinstall the app when I start the debugger.

**Comment by MSLaguana** [comment]
I see, that makes sense. We don't currently support an "attach to running app" type of scenario, but it is something that we could look into.

**Comment by tianhonghui** [comment]
Thanks for this amazing tools.

**Comment by MSLaguana** [comment]
We've added code to support this scenario now, so the next release will let you debug an already running app.
