### ISSUE TITLE
[Feature] Display QRCode in Output Log and/or Debug Console

### ISSUE THREAD

**Issue by 90dy** [microsoft/vscode-react-native#1778]
# 🚀 Feature request

What do you want to be added?

Display QRCode in Output Log and/or Debug Console

## What scenarios will this solve?

Prevent to have to display it via spliting and permit to retrieve it easily

What will this allow you to do? Will this benefit other developers?

Fastest development, prevent having to restart the packager after closing the QRCode tab

**Comment by EzioLi01** [comment]
> Hey @90dy! Thanks for reaching us and providing the great suggestion. We will work on investigating and discussing your suggestion with the team to make sure that it will work and have a good user experience in extension. Any response we will update here.

This feature is completed, please let me know if it have any issue or bug in your working.
