### ISSUE TITLE
[Bug] Debugger throws:Uncaught TypeError TypeError: process.send is not a function

### ISSUE THREAD

**Issue by dengpan1** [microsoft/vscode-react-native#1814]
when i try to debug my react-native app, vscode throws this error:

Uncaught TypeError TypeError: process.send is not a function
    at postMessage (/home/pan/go/berty/js/.vscode/.react/debuggerWorker.js:72:13)
    at sendReply (/home/pan/go/berty/js/.vscode/.react/debuggerWorker.js:180:7)
    at executeApplicationScript (/home/pan/go/berty/js/.vscode/.react/debuggerWorker.js:164:7)
    at <anonymous> (/home/pan/go/berty/js/.vscode/.react/debuggerWorker.js:191:7)
    at <anonymous> (/home/pan/go/berty/js/.vscode/.react/debuggerWorker.js:68:9)
    at emit (events:527:28)
    at emit (internal/child_process:938:14)
    at processTicksAndRejections (internal/process/task_queues:84:21)
    --- TickObject ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:201:43)
    at emitInitScript (internal/async_hooks:506:3)
    at nextTick (internal/process/task_queues:133:5)
    at handleMessage (internal/child_process:954:13)
    at channel.onread (internal/child_process:623:11)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- PIPEWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:201:43)
    at _forkChild (child_process:171:13)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution:407:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution:67:3)
    at <anonymous> (internal/main/run_main_module:7:1)
No debugger available, can not send 'variables'

**Software versions**

- React Native Tools version: 1.9.2
- vsode version: 1.70.1
- OS platform and version: Ubuntu20.04(WSL)
- Node JS version: v16.16.0
- React Native version: 18.2.0
- react-native-cli version: 2.0.1

**Comment by EzioLi01** [comment]
Hey @dengpan1, thanks for reaching us, do you have repro steps to share? Or just init new RN app in your side will show this error?

**Comment by dengpan1** [comment]
> 

Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), 
the steps is:
1. launch "React Native Pckager" in vscode
2. launch "Attach to packager" in vscode
3. Open the app in the Android emulator and enable the Debugging
4. and then I get this error in VScode

**Comment by EzioLi01** [comment]
> > 
> 
> Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> 
> 1. launch "React Native Pckager" in vscode
> 2. launch "Attach to packager" in vscode
> 3. Open the app in the Android emulator and enable the Debugging
> 4. and then I get this error in VScode

In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.

**Comment by dengpan1** [comment]
> > > 
> > 
> > 
> > Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> > 
> > 1. launch "React Native Pckager" in vscode
> > 2. launch "Attach to packager" in vscode
> > 3. Open the app in the Android emulator and enable the Debugging
> > 4. and then I get this error in VScode
> 
> In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.

My project is https://github.com/berty/berty/tree/master/js, I'm not familiar with RN, How do I find dependent packages?

**Comment by EzioLi01** [comment]
> > > > 
> > > 
> > > 
> > > Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> > > 
> > > 1. launch "React Native Pckager" in vscode
> > > 2. launch "Attach to packager" in vscode
> > > 3. Open the app in the Android emulator and enable the Debugging
> > > 4. and then I get this error in VScode
> > 
> > 
> > In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.
> 
> My project is https://github.com/berty/berty/tree/master/js, I'm not familiar with RN, How do I find dependent packages?

I will look into project firstly.

**Comment by dengpan1** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> > > > 
> > > > 1. launch "React Native Pckager" in vscode
> > > > 2. launch "Attach to packager" in vscode
> > > > 3. Open the app in the Android emulator and enable the Debugging
> > > > 4. and then I get this error in VScode
> > > 
> > > 
> > > In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.
> > 
> > 
> > My project is https://github.com/berty/berty/tree/master/js, I'm not familiar with RN, How do I find dependent packages?
> 
> I will download your project frontend part and look into project firstly.

thank you for your help.

**Comment by dengpan1** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> > > > 
> > > > 1. launch "React Native Pckager" in vscode
> > > > 2. launch "Attach to packager" in vscode
> > > > 3. Open the app in the Android emulator and enable the Debugging
> > > > 4. and then I get this error in VScode
> > > 
> > > 
> > > In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.
> > 
> > 
> > My project is https://github.com/berty/berty/tree/master/js, I'm not familiar with RN, How do I find dependent packages?
> 
> I will download your project frontend part and look into project firstly.

thank you for your help.

**Comment by dengpan1** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yes, I appeared in the same situation as [#606](https://github.com/microsoft/vscode-react-native/issues/606), the steps is:
> > > > 
> > > > 1. launch "React Native Pckager" in vscode
> > > > 2. launch "Attach to packager" in vscode
> > > > 3. Open the app in the Android emulator and enable the Debugging
> > > > 4. and then I get this error in VScode
> > > 
> > > 
> > > In #606, it said that `rn-nodeify` and `react-native-tcp` package will override `global.process`, Do you also use these packages? Or maybe some others caused same issue.
> > 
> > 
> > My project is https://github.com/berty/berty/tree/master/js, I'm not familiar with RN, How do I find dependent packages?
> 
> I will download your project frontend part and look into project firstly.

thank you for your help.

**Comment by EzioLi01** [comment]
@dengpan1 After investigation, it should have some conflicts between Berty internal debugger and RNT.
In this app, it have default debugger using MS Edge or Google Chrome DevTools and I suggest that you can try to use it firstly.

**Comment by dengpan1** [comment]
> @dengpan1 After investigation, it should have some conflicts between Berty internal debugger and RNT. In this app, it have default debugger using MS Edge or Google Chrome DevTools and I suggest that you can try to use it firstly.

well, thank you, I'm currently using Google Chrome DevTools for debugging.

**Comment by EzioLi01** [comment]
Close this issue, since it's the external issue related to specific project, will keep an eye on other RN projects.
