### ISSUE TITLE
Hermes debugging fails on RN 0.69 with expo-dev-client

### ISSUE THREAD

**Issue by evelant** [microsoft/vscode-react-native#1829]
# 🐛 What is the bug? How can we reproduce it?

Attempting to attach to Hermes for debugging fails on an iOS simulator on react-native 0.69 when app is built with expo-dev-client.

Reproduction project: https://github.com/evelant/vscode_hermes_debug_crash/

1. Unzip the simulator build from `build-1662134896311.tar.gz`
2. Drag and drop it into ios simulator to install
3. Start metro with `yarn react-native start --reset-cache`
4. Attach hermes debugger in vscode
5. Add a breakpoint -- it does not bind
6. Reload app by pressing r in metro console.
7. Observe VSCode hang when a breakpoint executes on the first line of the entire minified app bundle.

The debugger attaches but does not bind breakpoints. Upon reloading the app (press R in metro console) the debugger stops on the first line of the entire minified app output bundle. This hangs VSCode in most cases.

This makes debugging when using hermes and expo-dev-client impossible. Since hermes is soon to be the default I think this issue will probably impact a lot of people.

## Expected behavior

Debugger should bind breakpoints when attached to a hermes app built using EAS (expo-dev-client).

## Debug output

<details>
<summary>React Native output channel</summary>

```text

None

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

  ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._storeToDisk (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:24770)
    at ClientRequest.<anonymous> (/Users/imagio/.vscode/extensions/msjsdiag.vscode-react-native-1.9.2/dist/rn-extension.js:1:24494)
    at ClientRequest.emit (node:events:538:35)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
workbench.desktop.main.js:1974 Extension Host
workbench.desktop.main.js:1974 Debugger attached.
< ----- here is where the reload happens and breakpoint on minified app bundle is hit
workbench.desktop.main.js:603  INFO UNRESPONSIVE extension host: starting to profile NOW
workbench.desktop.main.js:603  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
workbench.desktop.main.js:603  WARN UNRESPONSIVE extension host: 'evgeniypeshkov.syntax-highlighter' took 95% of 5416.958ms, saved PROFILE here: 'file:///var/folders/gx/fwg565ys3177ht4tnx40wqv80000gn/T/exthost-8f9917.cpuprofile' (17) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
workbench.desktop.main.js:1974 Extension Host
workbench.desktop.main.js:1974 Debugger attached.
workbench.desktop.main.js:603  INFO UNRESPONSIVE extension host: starting to profile NOW
workbench.desktop.main.js:603  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
🎉 Didn't find any issues with the project!
```

* `envinfo`:

```text
envinfo hangs on macos, output of react-native info:

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 113.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /var/folders/gx/fwg565ys3177ht4tnx40wqv80000gn/T/yarn--1662138135883-0.0826695647289113/node
    Yarn: 1.22.19 - /var/folders/gx/fwg565ys3177ht4tnx40wqv80000gn/T/yarn--1662138135883-0.0826695647289113/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/imagio/.rvm/rubies/ruby-3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

* React Native Tools extension version: 1.9.2
* Expo SDK version (if applicable):  "expo": "~46.0.9",

**Comment by EzioLi01** [comment]
@evelant Thanks for reaching us, looking into this.

**Comment by EzioLi01** [comment]
Hey @evelant, for the expo app debugging, I suggest that you can follow below steps and try it firstly. It works on my site for your demo app.

1. Suggest debug expo app using Expo Go app in your simulator(https://expo.dev/client).
2.  Install Expo Go in your simulator
3. Open your demo app
4. In `launch.json`, add
'        {
            "name": "Debug in Exponent",
            "request": "launch",
            "type": "reactnative",
            "cwd": "${workspaceFolder}",
            "platform": "exponent",
            "expoHostType": "local"
        }
'
5. After build success, you can find QRCode and app link opened in web view, like `exp://120.0.0.1:19000`
6. Open Expo Go, input link to label and open project
7. Press CMD+D to open dev menu
8. Enable remote js debugger
9. Add breakpoint in your project, and it should work fine.

Please let me know if you have any trouble in these steps. Thanks!

**Comment by evelant** [comment]
@EzioLi01 The issue here is particularly with the combination of `hermes`  + `expo-dev-client`. If you use expo-go it is using neither of those. Please try it with the hermes + expo-dev-client build that I provided in the reproduction and I think you'll see the issue.

**Comment by EzioLi01** [comment]
> @EzioLi01 The issue here is particularly with the combination of `hermes` + `expo-dev-client`. If you use expo-go it is using neither of those. Please try it with the hermes + expo-dev-client build that I provided in the reproduction and I think you'll see the issue.

Thanks for the clarification, will try it again.

**Comment by EzioLi01** [comment]
@evelant  I have tried to follow your steps, but in step 3, I replaced `yarn react-native start --reset-cache` to `npx expo start --dev-client` mentioned in official documentation to start Metro, it works fine for my side. 
Could you please try it? Does it meet your expectations?

**Comment by EzioLi01** [comment]
Hey @evelant, do you have a chance to check it again?

**Comment by EzioLi01** [comment]
Close this issue since customer have no further updates, please reopen this or create a new one if you still have some problems.
