### ISSUE TITLE
Update documentation for RN 0.70: Hermes as default, debug expo app in expo-dev-client

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode-react-native#1830]
Update documentation for RN 0.70: Hermes as default, debug expo app in expo-dev-client

**Comment by ldorigo** [comment]
Hello, some changes described here are unclear:

- "1. Using `CMD + D` or `Ctrl + M` to open dev menu, then enable local devtools": how do I "enable local devtools"? There is no option called that (Only visible buttons in the dev menu are: "toggle performance monitor", "toggle element inspector", "open JS debugger", and "Fast Refresh").
- "1. Add `Attach to application` command `./vscode/launch.json`": What does this mean? I assume you mean "Add a debug configuration"? When selecting "Attach to application",  I have to choose between "Application in direct mode" and "Classic application". Which one is it?

Thanks !
