### ISSUE TITLE
Debugging Expo Custom Dev Client

### ISSUE THREAD

**Issue by atif7865** [microsoft/vscode-react-native#1840]
## Actual Behavior
1. Debugging does not work with expo custom development client

## Expected Behavior
1. Need to set breakpoints and debug my app
2. Need to be able to debug my app after having run npx eas prebuild and running custom dev client. In the past I was able to use the debugging in VSCode however since I build my custom dev client I am unable to run it. It seems as if the breakpoints are not respected at all and the app renders fully. Additionally in the past, whenever debugging would start, an orange bar would appear under VSCode, however that does not happen anymore now. 

## Software versions
- React-Native VS Code extension version: 1.9.3
- VSCode version: 1.71.2
- OS platform and version: macOS Monterey 12.5
- NodeJS version: 16.17
- React Native version: 0.69.6
- Expo SDK version (include if relevant): 46

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching the application
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

No issue with doctor-config-json-not-readNo issue with doctor-npm-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-no-react-native-in-package-jsonNo issue with doctor-legacy-async-storageNo issue with doctor-not-using-expo-forkNo issue with doctor-invalid-version-of-react-nativeNo issue with doctor-react-native-not-installed[Info] Enable JS Debugging
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
  ERR [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
log.ts:301  INFO UNRESPONSIVE extension host: starting to profile NOW
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 Debugger attached.
log.ts:301  INFO UNRESPONSIVE extension host: starting to profile NOW
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 Debugger attached.
log.ts:301  INFO UNRESPONSIVE extension host: starting to profile NOW
```

**Comment by atif7865** [comment]
I realized I had not provided content of launch.json

here it goes:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug in Exponent",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent",
            "sourceMaps": true
        }
    ]
}
```

**Comment by EzioLi01** [comment]
Hey @atif7865, thanks for reaching us. Extension team is out of office recently for the vacation. I will investigate it when we back to office.
Btw, here is the doc for debugging expo-dev-client(https://github.com/microsoft/vscode-react-native#debug-on-expo-dev-client), I'm not sure if it's meet your scenario, but could you please try it firstly follow this steps? Using attach request rather than launch request.

**Comment by atif7865** [comment]
> Hey @atif7865, thanks for reaching us. Extension team is out of office recently for the vacation. I will investigate it when we back to office. Btw, here is the doc for debugging expo-dev-client(https://github.com/microsoft/vscode-react-native#debug-on-expo-dev-client), I'm not sure if it's meet your scenario, but could you please try it firstly follow this steps? Using attach request rather than launch request.

Thank you @EzioLi01 ! I must say I can't remember the last time I felt so good about getting such amazing support. A lot of paid support systems aren't as good. So Thank you for that!

I have followed the steps in the guide and unfortunately it still isn't working. I will wait for the team to come back from their vacation and respond. Thank you again!

**Comment by EzioLi01** [comment]
> > Hey @atif7865, thanks for reaching us. Extension team is out of office recently for the vacation. I will investigate it when we back to office. Btw, here is the doc for debugging expo-dev-client(https://github.com/microsoft/vscode-react-native#debug-on-expo-dev-client), I'm not sure if it's meet your scenario, but could you please try it firstly follow this steps? Using attach request rather than launch request.
> 
> Thank you @EzioLi01 ! I must say I can't remember the last time I felt so good about getting such amazing support. A lot of paid support systems aren't as good. So Thank you for that!
> 
> I have followed the steps in the guide and unfortunately it still isn't working. I will wait for the team to come back from their vacation and respond. Thank you again!

That's OK, so is it possible to provide your related project repo and dev-client build for the investigation, it will be great to help us to identify issue, thank you!

**Comment by EzioLi01** [comment]
> > > Hey @atif7865, thanks for reaching us. Extension team is out of office recently for the vacation. I will investigate it when we back to office. Btw, here is the doc for debugging expo-dev-client(https://github.com/microsoft/vscode-react-native#debug-on-expo-dev-client), I'm not sure if it's meet your scenario, but could you please try it firstly follow this steps? Using attach request rather than launch request.
> > 
> > 
> > Thank you @EzioLi01 ! I must say I can't remember the last time I felt so good about getting such amazing support. A lot of paid support systems aren't as good. So Thank you for that!
> > I have followed the steps in the guide and unfortunately it still isn't working. I will wait for the team to come back from their vacation and respond. Thank you again!
> 
> That's OK, so is it possible to provide your related project repo and dev-client build for the investigation, it will be great to help us to identify issue, thank you!

Hey @atif7865, we're back, for this comment, is it possible to provide your related project repo and dev-client build for the investigation, it will be great to help us to identify issue?

**Comment by EzioLi01** [comment]
I have updated expo-dev-client documentation for some details, you can read it and try it again. If it still have some failures, please refer to the previous message :smile:

**Comment by atif7865** [comment]
Hi team, Thanks a bundle. The detailed steps solved the problem. The trick was that after closing the browser and reloading the app, I realized that the dev-tools automatically turn off again. So close browser, reload app, turn on dev-tools again did the trick. Thank you again

**Comment by EzioLi01** [comment]
> Hi team, Thanks a bundle. The detailed steps solved the problem. The trick was that after closing the browser and reloading the app, I realized that the dev-tools automatically turn off again. So close browser, reload app, turn on dev-tools again did the trick. Thank you again

That's great! Close this issue as resolved. Any issue for extension need to help please contact us!
