### ISSUE TITLE
[Bug] Wrong android sdk path

### ISSUE THREAD

**Issue by maurizioceravolo** [microsoft/vscode-react-native#1846]
# 🐛 What is the bug? How can we reproduce it?

The error is quite easy to reproduce- I installed the extension, then

1. I followed the instruction to debug on android
2. Clicked on the run button for Debug Android

## Expected behavior

I expected to debug my application. Insted I got an error. The path of adb it says it's "\Users\cloud\Library\Android\sdk\platform-tools\adb". There's no user cloud on my computer. I tried to see the code of the extension. The problem shoud be in the function getSdkLocationFromLocalPropertiesFile, but I don't know where it is defined or how it works.

## Debug output

<details>
<summary>Debug Console</summary>

```text

An error occurred while launching the application. Error while executing command '"\Users\cloud\Library\Android\sdk\platform-tools\adb" devices': Command failed: "\Users\cloud\Library\Android\sdk\platform-tools\adb" devices
Impossibile trovare il percorso specificato.
 (error code 303)

```
</details>

<details>

* React Native Tools extension version: 1.10.0
* Computer: Window 11

**Comment by EzioLi01** [comment]
@maurizioceravolo Thanks for reaching us, looking into this issue.

**Comment by maurizioceravolo** [comment]
> @maurizioceravolo Thanks for reaching us, I have tried it and it cannot repro on my local machine. Could you please try to follow below step to show us some details for your computer environment variables?
> 
> Run `npx react-native doctor` in you project root to get config details. Run `set` command in windows command line and check your environment path named `ANDROID_HOME`& `ANDROID_SDK_ROOT`. Run `adb` directly in windows command line and check if it can work correctly.

@EzioLi01 thanks a lot for your answer. 
` npx react-native doctor` said I have no skd installed. It's not true, but I solved the error, and now it's all ok.
The set command gave me
the following result
```
ANDROID_HOME=C:\Users\porta\AppData\Local\Android\Sdk
ANDROID_SDK_ROOT=C:\Users\porta\AppData\Local\Android\Sdk
```
this path it's quite different from the one of the error I'ma sking about.
`adb` work as charm, but I still can't get debug work and always with the error to this path
\Users\cloud\Library\Android\sdk\platform-tools\adb
and I really don't know where it get it

**Comment by EzioLi01** [comment]
@maurizioceravolo  
Thanks for checking! Could you please help to try this step?
In your project folder, please find if it had `local.properties` file in `/projectFolder/android` path?

**Comment by EzioLi01** [comment]
> @EzioLi01 thanks really a lot. My bad. It's not a bug, it's a setting in local.properties. This is not a project developed by me, and I'm new in react. I have to maintain it now. Sorry for bothering you, bur really really thanks.

That's great! Happy to see your debugger working! Our extension will read `local.properties` firstly to get sdk path.
Maybe we can do some enhancement for extension that switch to local sdk path rather than throw exception if sdk path in `local.properties` is incorrect.

Close this issue as resolved! Thank you!
