### ISSUE TITLE
[Bug] Output panel behavior affecting `vscode-go` extension behavior

### ISSUE THREAD

**Issue by uudashr** [microsoft/vscode-react-native#1854]
# 🐛 What is the bug? How can we reproduce it?

Seems that react native extensions changing the original behavior of the output panel. It causing issues for another extension (`vscode-go`) and might be affecting the other extensions as well.

The output shown like this (this is output from `vscode-go` test feature).
I can observed that:
1. Some of the line are red colored (seems that it come from the `stderr`)
2. The line `/Users/nuruddin.ashr/temp/hello/hello_test.go:6` cannot be clicked.
![Screen Shot 2022-11-03 at 18 37 18](https://user-images.githubusercontent.com/166053/199716671-b8866c9b-4498-4f8d-9257-e6d7c1e8973f.png)

This is issue if you using both `vscode-react-native` and `vscode-go` installed.

## Expected behavior
Without the `vscode-react-native` extension installed it shows like this.
The line `/Users/nuruddin.ashr/temp/hello/hello_test.go:6` can be clicked.
![Screen Shot 2022-11-03 at 18 36 53](https://user-images.githubusercontent.com/166053/199716740-c34622ff-c86e-4b1a-93d7-4d6e6746b17b.png)

## Debug output

<details>
<summary>Debug Console</summary>
n/a
</details>

<details>
<summary>React Native output channel</summary>
n/a
</details>

<details>
<summary>Developer Tools console</summary>

n/a
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:
n/a

* `envinfo`:
n/a

* React Native Tools extension version: v1.10.0
* Expo SDK version (if applicable): n/a

**Comment by EzioLi01** [comment]
Hey @uudashr ,  thanks for reaching us. I will investigate on this issue, and any update will comment here. Thanks!

**Comment by EzioLi01** [comment]
We do have some settings to support user customize log color and some others. Will try to repro this and investigate why the line is non-clickable.

**Comment by EzioLi01** [comment]
Hey @uudashr , I'm getting started on this, is it possible if you can share any project to repro this issue?

**Comment by uudashr** [comment]
Use https://github.com/uudashr/hello
You need to install [go extension](https://marketplace.visualstudio.com/items?itemName=golang.go)
1. Open the project `code <the directory>`
2. Open any file (or just open `hello_test.go`)
3. Open "Command Pallete" (cmd + shift + p on Mac) and choose "Go: Test Package". It will shows the test output

**Comment by EzioLi01** [comment]
Will disable some color configs to ignore custom output window. And plan to refactor some tm grammar in the future.

**Comment by EzioLi01** [comment]
Hey @uudashr , I disable tm-grammar for some parts of log, you can try to use the latest [nightly preview version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) to check it, the nightly version I think will be published tomorrow. Please reopen this issue and let me know if you still facing same in latest preview version.
