### ISSUE TITLE
[Feature/Question] Multithread debugging

### ISSUE THREAD

**Issue by gfrancischini** [microsoft/vscode-react-native#1855]
# 🚀 Feature request

Libraries like https://github.com/joltup/react-native-threads adds another JS thread by using the packager on the same port. It happens that by adding another JS thread the Hermes debugger connect to this second thread and not the first one

I know this library is not still maintained but I would like to understand how feasible would be to add a support for debugging 2 JS process so I can rewrite some parts of the js thread library to make it easier to use together with JSI/TurboModules

Thanks

**Comment by EzioLi01** [comment]
Hey @gfrancischini , thanks for reaching us, I have checked this repo and it seems stop to maintain from 2020, I also checked some latest issues, some of them are blocking issues(like crash, obsoleted functions). I.m not sure but will investigate and evaluate feasibility of it.

Any thought please let me know, thank you!

**Comment by gfrancischini** [comment]
@EzioLi01 thanks for the quick response. Yes, it is unmaintained for now but I was able to make it work with rn 0.67.3

I'm just changing some stuff so it work better using the bundler with babel instead the way it is today. 

I would like to invest some time on it but I honest don't want to put some extra effort unless we can properly debug it (I hate console logs lol)

**Comment by EzioLi01** [comment]
RNT debugger is depended on [vscode-js-debug](https://github.com/microsoft/vscode-js-debug), need to do further investigation on this in the future.
