### ISSUE TITLE
[Performance] Latest release 1.10.0 output view high cpu usage

### ISSUE THREAD

**Issue by electroidru** [microsoft/vscode-react-native#1867]
## Curent behavior

In the latest release of the extension version I notice high CPU usage and degrade performance for the output window.
I have a lot of dynamic logs and with the output open I noticed high cpu usage for the Code Helper (Rendered) and Code application on my mac. That's affect overall performance and productivity.

## Expected behavior

Expect output windows not to affect the cpu usage. I think that's related to the new color output. That's looks nice, but the cpu usage is high. Once downgraded back to the version 1.7.1 installed previously, CPU and performance isn't affected with the output window opens.

## Environment

npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2022.09.05.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 30.0.2
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

System:
    OS: macOS 11.6.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
    Memory: 16.51 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/reactnative/ridyapp2/node_modules/.bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
    Composer: 2.4.1 - /usr/local/bin/composer
    Homebrew: 3.6.1 - /usr/local/bin/brew
    pip2: 20.3.4 - ~/Library/Python/2.7/bin/pip2
    pip3: 22.2.2 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.32.0 - /usr/local/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.51 - /usr/sbin/apachectl
    Nginx: 1.23.1 - /usr/local/bin/nginx
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.11 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.4.30 - /usr/local/opt/php@7.4/bin/php
    Protoc: 3.21.5 - /usr/local/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.10.6 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MongoDB: 4.4.13 - /usr/local/opt/mongodb-community@4.4/bin/mongo
    MySQL: 11.6 - /usr/local/bin/mysql
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 14.1.2

* React Native Tools extension version: 1.10.0

**Comment by EzioLi01** [comment]
@electroidru Thanks for reaching us, we have disable some parts of output log colorize in [nightly preview version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview), could you please try it and let me know if you still facing this issue?

**Comment by electroidru** [comment]
@EzioLi01 As far as I can see cpu is not affected in that nightly release. However I didn't see any output colorize, neither in the Run Android, neither in the LogCat output (that one was giving very high cpu usage with colorized output).

**Comment by EzioLi01** [comment]
> 

@electroidru Yes, we disable logs since we want to refactor some tm-grammars for extension, we will enable this feature again when we complete this task.

**Comment by EzioLi01** [comment]
I think we can closed this issue, please see #1861 this one for the feature further update. Thanks!
