### ISSUE TITLE
Unable to run IOS Simulator

### ISSUE THREAD

**Issue by 5ecured** [microsoft/vscode-react-native#1885]
# 🐛 What is the bug? How can we reproduce it?
After successfully initializing a react native cli project, I **npm start** to start the metro server. I then open a new terminal to **npm run ios**. The IOS Simulator automatically opens, but after 1 or 2 seconds gives me a long error. Strange, because `npx react-native doctor` shows all green ticks

## Expected behavior

For the IOS simulator to work as intended - displaying the React Native app

## Debug output

It is a long error, I have put it into pastebin: https://pastebin.com/6bFTMDTr

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

Common
 ✓ Node.js
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   0
Warnings: 0

**Comment by EzioLi01** [comment]
Hey @5ecured , thanks for reaching us. Checked your issue, seems you cannot open your RN app by `react-native command`. This repo is related to react-native debugger extension on vscode. NOT the react-native framework source repo, I suggest that you can open issue on [this repo](https://github.com/facebook/react-native/issues) to get help, also you can check RN official [documentation](https://reactnative.dev/docs/getting-started) to get some details.

**Comment by EzioLi01** [comment]
Hello @5ecured , do you have any updates on this?

**Comment by 5ecured** [comment]
Sorry @EzioLi01 . Understand, will try to post in that repo. Also thank you for the other links. You may close this issue
