### ISSUE TITLE
[Feature] Add notification for local file overwrite

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-react-native#1887]
# 🐛 What is the bug? How can we reproduce it?

I had a lot of trouble with (seemingly) nondeterministic behaviours while trying to set up my development environment. I finally found out that it's because this extension seems to silently overwrite files without notifying the user, leading to variable results for various commands depending on when they are run.

## Expected behavior

Either explicitly notify the user that files are being overwritten, or better, don't overwrite files at all and use temporary files.

## Repro

Create an expo app:

```
yarn create expo-app --template
```

Select "Blank (Typescript)" (probably works with others too, I found it with this one) and select name "testapp".

Change app.json to use "jsEngine: 'hermes'".

Make a copy of current state:

```
cp -r testapp testapp_original
```

Start the "Attach to Hermes" debug configuration (and see it fail).

Then do:

```
diff --recursive testapp testapp_original
```

And notice that it changed `node_modules/open/...`

(Which seems to be related to the reason why "Attach to hermes" fails)

**Comment by EzioLi01** [comment]
@ldorigo Looking into this, thanks for another issue! :satisfied:

**Comment by EzioLi01** [comment]
@ldorigo Ack, it's related to RN packager kicks off. It's the good suggestion that we can add notification for now. And also I will look into reverting this changes when debug session is end.
