### ISSUE TITLE
[Bug] Property scheme is not allowed

### ISSUE THREAD

**Issue by MBach** [microsoft/vscode-react-native#1890]
# 🐛 What is the bug? How can we reproduce it?

1. For iOS App, in `launch.json` add `"scheme":"myApp-debug"` for example
2. Warning is visible in editor

## Expected behavior

No warning should be visible. Is the property still valid? Is it the documentation?

* React Native Tools extension version: `v1.10.0`

**Comment by EzioLi01** [comment]
Hey @MBach , thanks for reaching us. Do you mean the `scheme` property in [react-native-cli](https://github.com/react-native-community/cli/blob/main/docs/commands.md)?

**Comment by MBach** [comment]
> Do you mean the `scheme` property in [react-native-cli](https://github.com/react-native-community/cli/blob/main/docs/commands.md)? 

Yes, the same.

In the documentation, it says:
```js
"runArguments": ["--scheme", "customScheme", ...]
// or
"runArguments": ["--scheme=customScheme", ...]
// or
"scheme" : "customScheme"
```
I cannot confirm if it works or not, because I have a complex App with Hermes enabled and it's working only with XCode right now.

**Comment by EzioLi01** [comment]
> > Do you mean the `scheme` property in [react-native-cli](https://github.com/react-native-community/cli/blob/main/docs/commands.md)?
> 
> Yes, the same.
> 
> In the documentation, it says:
> 
> ```js
> "runArguments": ["--scheme", "customScheme", ...]
> // or
> "runArguments": ["--scheme=customScheme", ...]
> // or
> "scheme" : "customScheme"
> ```
> 
> I cannot confirm if it works or not, because I have a complex App with Hermes enabled and it's working only with XCode right now.

`runArguments` is adding property to react-native-cli, it's same as using `react-native run-ios --scheme "myApp-debug"`, the debugger will work well as long as no error occurring in debug process.

**Comment by EzioLi01** [comment]
Hey @MBach, do you have any updates on this? Is `scheme` working for you now?

**Comment by MBach** [comment]
> Hey @MBach, do you have any updates on this? Is `scheme` working for you now?

Well it seems to work with `"runArguments"` (even tough my build is failing as I said), but not with `"scheme"`

**Comment by EzioLi01** [comment]
OK, if you have any other issues in app debugging, please reopen this issue or create a new one, thank you!

**Comment by MBach** [comment]
> OK, if you have any other issues in app debugging, please reopen this issue or create a new one, thank you!

I'm sorry but there might be a misunderstanding right here. See the screenshot below:
![image](https://user-images.githubusercontent.com/1532657/207437792-f801210c-a68e-460c-a805-f44ccfe577b5.png)
