### ISSUE TITLE
snippets dosent work vs code react native

### ISSUE THREAD

**Issue by roei133** [microsoft/vscode-react-native#1913]
snippets dose not work vs code react native .
something wrong with the extension ? 

It started about two days ago when I suddenly noticed that 
there is no longer an option for snippets and it's really annoying.

**Comment by EzioLi01** [comment]
Looks like it should related to vscode issue https://github.com/microsoft/vscode/issues/173244, it should be fixed in next prod release. Also maybe you can try to use vscode-insider, it should work well.
