### ISSUE TITLE
[Bug] Could not read source map for file

### ISSUE THREAD

**Issue by liuxuan30** [microsoft/vscode-react-native#1926]
# 🐛 What is the bug? How can we reproduce it?
Hi there,

I'm relatively new to react-native, and now I have setup my demo app and trying to make debugger work.

I followed some docs and am able to start the debug sesssion, and the break point seems fine to trigger as well, but every time I launch the debugger session, it will print:

>Could not read source map for file:///Users/demo/example/.vscode/.react/debuggerWorker.js: ENOENT: no such file or directory, open '/Users/demo/example/.vscode/.react/debuggerWorker.js.map'

I tried several ways on google to attempt a fix:
following https://reactnative.dev/docs/sourcemaps
>adding 'export SOURCEMAP_FILE="$(pwd)/../main.jsbundle.map";' in the build phase script:
```
export SOURCEMAP_FILE="$(pwd)/../main.jsbundle.map";
echo 'Checking sourcemap file...'
echo $SOURCEMAP_FILE
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

I was able to see the echo message:
```
Checking sourcemap file...
/Users/demo/example/ios/../main.jsbundle.map
```
but still the error is there.

here's my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS",
            "request": "launch",
            "type": "reactnative",
            "cwd": "${workspaceFolder}",
            "platform": "ios"
        },
        {
            "name": "Attach to packager",
            "request": "attach",
            "type": "reactnative",
            "cwd": "${workspaceFolder}",
        }
    ]
}
```

## Expected behavior
launch with out error

## Debug output
DEBUG CONSOLE OUTPUT
```
Attaching to the application
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 25867
Could not read source map for file:///Users/demo/example/.vscode/.react/debuggerWorker.js: ENOENT: no such file or directory, open '/Users/demo/example/.vscode/.react/debuggerWorker.js.map'
Running application DemoExample ({
    initialProps =     {
    };
    rootTag = 11;
})
RCTLog.js:47
Running "DemoExample" with {"rootTag":11,"initialProps":{}}
```

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)
```
["INFO" - 11:02:33 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 11:02:33 AM] Extension Version: 9.10.4.
```

TERMINAL OUTPUT
```
▸ Running script 'Start Packager'
▸ Running script 'Bundle React Native code and images'
▸ Build Succeeded
success Successfully built the app
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:94BAC29D-E39F-47F8-B973-A7C40A718B9D, OS:16.2, name:iPhone 14 }
{ platform:iOS Simulator, id:1C8C9041-4C34-4FDA-B300-D0CAD518D412, OS:16.2, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:F6362EDB-BC0E-4448-A076-AB6946232041, OS:16.2, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:BD50E139-0AFD-46FA-B6E6-0BDB10BD316C, OS:16.2, name:iPhone 14 Pro Max }

2023-03-09 11:08:20.785 xcodebuild[380:10103126] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
info Installing "/Users/Library/Developer/Xcode/DerivedData/DemoExample-blfvafudqxfbmsbadsvymbuqmgwg/Build/Products/Debug-iphonesimulator/DemoExample.app"
info Launching "org.reactjs.native.DemoExample.DemoExample"
success Successfully launched the app on the simulator
✨  Done in 8.81s.

```

## Environment

Please tell us about your system and your project:

I was mainly iOS dev, so I didn't setup android portion:
```text
% npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2023.02.27.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 28.0.3
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   3
Warnings: 1

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2023.02.27.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 28.0.3
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   3
Warnings: 1
```

* `envinfo`:

```text
npx envinfo is hanging like forever, not able to get one.
```

### VSCode version: 
```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```
* React Native Tools extension version: v1.10.2

* Expo SDK version (if applicable): 
```
{
  "name": "DemoExample",
  "displayName": "Demo Example",
  "expo": {
    "slug": "DemoExample",
    "name": "DemoExample",
    "sdkVersion": "38.0.0",
    "entryPoint": ".vscode/exponentIndex.js"
  }
}
```

**Comment by liuxuan30** [comment]
![image](https://user-images.githubusercontent.com/4375169/223910186-b1f10a12-8133-4154-ad87-01b6a530bfda.png)
I was able to see some files under .react

**Comment by EzioLi01** [comment]
Hey @liuxuan30 , thanks for reaching us, is this possible to share any demo for the investigation?

**Comment by liuxuan30** [comment]
[demo.zip](https://github.com/microsoft/vscode-react-native/files/10928556/demo.zip)
here you go. since you are experts, you can modify or remove the wrong lock file or versions.

**Comment by EzioLi01** [comment]
> my demo project is using company's internal source, so I cannot guarantee you can resolve all versions without problem. I could send a demo project, removing all caches.
> 
> But what I did is simply create a demo via
> 
> > npx @react-native-community/bob create @kds/xxx
> 
> and modify the package json and pod file accordingly.

Thanks for the demo, will do investigation, but check the project is using RN V0.62 is the very old version actually(the latest version is v0.71.4), we need to check anything in this version is compatible.

**Comment by EzioLi01** [comment]
Also, saw your config details, I found the Expo platform related config file `{
  "name": "DemoExample",
  "displayName": "Demo Example",
  "expo": {
    "slug": "DemoExample",
    "name": "DemoExample",
    "sdkVersion": "38.0.0",
    "entryPoint": ".vscode/exponentIndex.js"
  }
}`

Could you please confirm that your internal app is created by react-native cli or expo cli, these are different platforms and have different logic for app debugging.

**Comment by liuxuan30** [comment]
> Refere

@EzioLi01 thank you for your effort! I created the demo via 
>npx @react-native-community/bob create @kds/xxx

is this expo or react-native? I'm not quite sure what's the difference.

**Comment by liuxuan30** [comment]
> > my demo project is using company's internal source, so I cannot guarantee you can resolve all versions without problem. I could send a demo project, removing all caches.
> > But what I did is simply create a demo via
> > > npx @react-native-community/bob create @kds/xxx
> > 
> > 
> > and modify the package json and pod file accordingly.
> 
> Thanks for the demo, will do investigation, but check the project is using RN V0.62 is the very old version actually(the latest version is v0.71.4), we need to check anything in this version is compatible.
> 
> Can you please confirm that the app debugging is working well and not impact by this source map error?

our internal policy is to use 0.62 as the app is still using this version, so I cannot do too much about it. Just want to make sure what's wrong and the impact.

**Comment by EzioLi01** [comment]
I believe that if you can stop your code in breakpoint, the debug process should work well. It should not block your working. 
For the source map error, I will try to repro it, but actually I will got `xcrun: error: unable to find utility "instruments", not a developer tool or in PATH` error at this time. It caused by RN limitation in 0.64 and below version. From XCode 13, the `instruments command-line tool` has been removed and replaced by `xctrace `, but it's supported by RN from V0.64. So I will try to find other ways on this.

**Comment by liuxuan30** [comment]
@EzioLi01 what is source map `.react/debuggerWorker.js.map` supposed to do here? If it's just a 'symbol map' for debuggerWoerker.js itself, I think we could move on? Don't want to take too much of your time. Thanks anyway.

**Comment by EzioLi01** [comment]
I'm not sure if it some source map settings on your project or former RN version, but I can confirm that this file is not displayed on RN 0.70+ project and I just related to extension debugging process, should not block your work.

**Comment by liuxuan30** [comment]
sure, I guess this issue could be closed depending on you, if you'd like to investigate a little than please, and if you feel trivial, just close it, thanks!
