### ISSUE TITLE
Macca

### ISSUE THREAD

**Issue by Margie-Rose** [Microsoft/vscode-react-native#193]
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- React Native version: 
- (If relevant) Output of the Debug Console (View -> Toogle Debug Console): 
- (If relevant) Output of the React-Native output channel (View -> Toogle Output -> Select React-Native in ListBox): 
- (If relevant) Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

Steps to Reproduce:
1. 
2. 

What do you expect that should've happened instead:

**Comment by digeff** [comment]
@Margie-Rose What's your issue?

**Comment by digeff** [comment]
@Margie-Rose Closing because we don't have any information. Please re-open if you have any issues to report.
