### ISSUE TITLE
[Bug] Debug with Hermes IOS Experimental get an error due to wrong path

### ISSUE THREAD

**Issue by naquiroz** [microsoft/vscode-react-native#1944]
# 🐛 What is the bug? How can we reproduce it?

When attempting to debug with Hermes IOS Experimental I get an error due to wrong path.

## Expected behavior

For the debug to work but the path is not correct (see debug console)

## Debug output

<details>
<summary>Debug Console</summary>

 the following error:

```console
An error occurred while launching the application. Error while executing command '/Users/myuser/Documents/side-projects/project/node_modules/.bin/react-native run-ios --no-packager --verbose' (error code 101) (error code 303)
```
Notice the missing quote after `react-native`, that leads to the error.
</details>

<details>
<summary>React Native output channel</summary>
</details>

<details>
<summary>Developer Tools console</summary>
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Close invalid issue.

**Comment by EzioLi01** [comment]
@naquiroz Could you please provide some details for your application?

**Comment by naquiroz** [comment]
I would like to apologize, the issue was something else. The path is being parsed correctly.

**Comment by EzioLi01** [comment]
> I would like to apologize, the issue was something else. The path is being parsed correctly.

Great to see your app debugging working well!
