### ISSUE TITLE
[Bug] Error: Opn package location not found

### ISSUE THREAD

**Issue by evelant** [microsoft/vscode-react-native#1945]
# 🐛 What is the bug? How can we reproduce it?

In a pnpm monorepo attaching the hermes debugger fails with

```
Attaching to the application
Connecting to 8081 port
An error occurred while attaching debugger to the application. The package 'opn' was not found. Error: Opn package location not found (error code 501) (error code 502) (error code 1410)
```

using the configuration

```
        {
            "name": "Attach to Hermes application - Experimental",
            "request": "attach",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}/apps/my_app"
        },
```

There is a related closed issue but I think a bug has resurfaced here https://github.com/microsoft/vscode-react-native/issues/1766 since I have specified cwd correctly in launch config

## Expected behavior

The debugger should attach correctly or the error should be more clear if this is a case of missing a required dependency.

## Debug output

<details>
<summary>Debug Console</summary>

```text

Attaching to the application
Connecting to 8081 port
An error occurred while attaching debugger to the application. The package 'opn' was not found. Error: Opn package location not found (error code 501) (error code 502) (error code 1410)
```
</details>

<details>
<summary>React Native output channel</summary>

```text

N/A
```
</details>

<details>
<summary>Developer Tools console</summary>

```text

N/A
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
N/A
```

* `envinfo`:

```text
unable -- "envinfo" hangs with no output on macos 13.3.1

env details:
macos 13.3.1
node 16.19.0
pnpm 8.2.0
expo 48.0.10
vscode 1.77.3
react native tools 1.10.2
```

* React Native Tools extension version: v1.10.2
* Expo SDK version (if applicable): 48.0.10

**Comment by EzioLi01** [comment]
Hey @evelant , thanks for reaching us. Is this possible to share a demo for this issue?

**Comment by EzioLi01** [comment]
Hey @evelant, do you have any update on this?
