### ISSUE TITLE
[Bug] Restart of debugger disables the breakpoint on every alternate restart on vscode 1.78(latest version)

### ISSUE THREAD

**Issue by mousumikundu** [microsoft/vscode-react-native#1969]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Click on Run and Debug with the below configuration
2. {
            "name": "Debug iOS Hermes",
            "request": "launch",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}",
            "platform": "ios"
        },
3. Once the debugger gets connected, try to restart the debugger the breakpoints are disabled(shows as unbound breakpoint)
4. When you try to restart again it gets connected.
5. But the same behaviour is seen for every alternate restart.

## Expected behavior

What were you expecting to happen?

The breakpoints should always be hit and should not get disabled.

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: v1.11.0
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Thanks @mousumikundu reporting this, should have same cause with #1968 .

**Comment by mousumikundu** [comment]
Thanks @EzioLi01

**Comment by EzioLi01** [comment]
Update: this issue will be fixed on next js-debug release. Here is a temporary workaround for the reference - using js-debug nightly version. Please get details in above issue.

**Comment by EzioLi01** [comment]
Close this issue, please comment or discuss the related issue on above issue, thank you!

**Comment by mousumikundu** [comment]
@EzioLi01 Can you please verify this issue. It still persits with vscode 1.82.0. Can we reopen the issue?

**Comment by EzioLi01** [comment]
Actually the breakpoints issue should be related to vscode built-in extension vscode-js-debug, bu I will try on this firstly.

**Comment by mousumikundu** [comment]
Ok thanks, so would you be checking on this issue with this ticket? Or do we need to create a new ticket for this?

**Comment by EzioLi01** [comment]
Hey @mousumikundu , after investigation, the vscode debug adapter is not support restart as default, so it will be executed disconnect request and attach request, when you click restart button twice.
For now we do not have plan to enable restart request when init debug adapter request and handle restart request in extension, so it should be as design for current scenario.
But we will add this to the backlog and will do some investigations in the future.
