### ISSUE TITLE
[Feature] On Debug mode users can be use on normal terminal

### ISSUE THREAD

**Issue by myagizmaktav** [microsoft/vscode-react-native#1972]
# 🚀 Feature request

## What do you want to be added?
I would like to have the ability to use normal terminal keys when in debug mode.

## What scenarios will this solve?
This feature will greatly enhance the developer experience during debugging. Currently, there are certain actions that require specific key presses, such as using the `R` key for reloading, the `A` key for re-opening, or using the `--reset-cache` flag to close and open. However, these actions cannot be easily performed. 

I envision a solution where the JavaScript debug terminal is automatically opened when debugging starts, allowing developers to use normal terminal keys for performing various actions.

## What will this allow you to do? Will this benefit other developers?
By implementing this feature, developers will have a more flexible development experience and will be able to save time during program development. The ability to use normal terminal keys during debugging will streamline the debugging process and improve overall productivity.

Here is a visual representation of the feature request:

![Code_iEO10dZ9fI](https://github.com/microsoft/vscode-react-native/assets/115627863/f4147485-3625-4bfc-a2c3-854d7d4171e3)

**Comment by EzioLi01** [comment]
Thanks @myagizmaktav! We will evaluate on this. For now you may can do as below:

1. Open project in vscode
2. Run `npx react-native run-android` to open native metro terminal and lunch application
3. Add `attach` request on launch.json 
![image](https://github.com/microsoft/vscode-react-native/assets/19662219/c6212527-21ba-4d5b-ad0f-4a1f74f3ef97)
4. Debugger will attach into session and you also can use rn native terminal

OR

We also have [some commands](https://github.com/microsoft/vscode-react-native#react-native-commands-in-the-command-palette) in command palette(Ctrl+Shift+P) to help user execute react-native command 

Please check these firstly, if it can meet your expectations. Thanks!

**Comment by myagizmaktav** [comment]
@EzioLi01 , thank you for your response.

In my VSCode environment, when I start a project first and then click the debug button, the debug mode is attached. However, if I only click the debug button without starting the project first, the attach mode is not activated, and it takes port 8081 by default. As a result, I need to kill the port in order to open the project.

Please let me know if there is anything else you would like me to assist you with.
