### ISSUE TITLE
Debugger known issue on VSCode 1.78+ (vscode-js-debug 1.78+) and temporary workaround

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode-react-native#1977]
**Description**

Issue: https://github.com/microsoft/vscode-js-debug/issues/1715 - _**fixed on V1.82.0**_ :tada:

**Temporary Workaround**

- Using js-debug nightly version

1. Open the extensions view (ctrl+shift+x) and search for @Builtin @id:ms-vscode.js-debug
2. Right click on the JavaScript Debugger extension and Disable it.
3. Search for @id:ms-vscode.js-debug-nightly in the extensions view.
4. Install that extension.
5. Uninstall latest nightly version, select install another version: using v2023.4.1317.

OR

- Using VSCode 1.77.x

OR

- Edit in launch.json

`      "skipFiles": [
        "${workspaceFolder}/<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
       ]`

**Comment by mousumikundu** [comment]
@EzioLi01  I see a new version has been released 1.80.0 but still face the above issues. Can you confirm if they have been fixed or would be done in the next release?

**Comment by EzioLi01** [comment]
This issue should be fixed on vscode-js-debug nightly version(verified on v2023.8.2817), will close this issue once it's fixed on prod release.

**Comment by EzioLi01** [comment]
Update: the fixing is released on js-debug [v1.82.0](https://github.com/microsoft/vscode-js-debug/releases/tag/v1.82.0), once it's added in vscode new prod release as built-in extension, this issue will not occur.

**Comment by EzioLi01** [comment]
VSCode 1.82.0 is released with js-debug V1.82.0 built-in extension, this issue should be fixed. Close as resloved.

**Comment by weinixuehao** [comment]
![image](https://github.com/microsoft/vscode-react-native/assets/17869361/f694bb9d-9f0b-493d-8080-371fb3095e46)
my used is 1.82.0 but not working
