### ISSUE TITLE
Failed to install the app only in vscode

### ISSUE THREAD

**Issue by gwonsuji** [microsoft/vscode-react-native#1978]
# 🐛 What is the bug? How can we reproduce it?

If I try to run the react native app, I keep getting errors like pictures. This is not just in the reaction native cli. It occurs without modifying anything after creating an expo project. If I run through emulator in vscode, the app will not continue to install.
![image](https://github.com/microsoft/vscode-react-native/assets/60372704/052cec9a-5253-4e77-9a61-b7926be7df58)

$ npx react-native run-android --verbose
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1873 file(s) to forward-jetify. Using 6 workers...
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
debug Running command "cd android && gradlew.bat app:installDebug -PreactNativeDevServerPort=8081"
Error: Could not find or load main class     
Caused by: java.lang.ClassNotFoundException: 

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Error: Could not find or load main class 

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Create a project that uses reaction native cli.
2. Run the npx react-native run-android command.

## Expected behavior

I thought the app would run on an Android emulator.

## Debug output(I ran it with debug Android.)

<details>
<summary>Debug Console</summary>

```text
Launching the application
An error occurred while launching the application. 'd:\Android\funglkids_app_\node_modules\.bin\react-native.cmd run-android --no-packager' 명령을 실행하는 동안 오류가 발생했습니다. (error code 101) (error code 303)
```
</details>

<details>
<summary>React Native output channel</summary>(I ran it with debug Android.)

```text

[Info] Need to check main file and entry point of open module, will setup and write new content if they're not existing. Path: d:\Android\funglkids_app_\node_modules\open

[Info] Find open-main.js and entry in open module, skip setup...

[Info] 패키지 작성 도구를 시작하는 중

                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          
                 Welcome to React Native!
                Learn once, write anywhere


[Info] 패키지 작성 도구가 시작되었습니다.

[Info] Prewarming bundle cache. This may take a while ...

[Info] 가져올 예정: http://localhost:8081/index.bundle?platform=android

[Tue Jun 20 2023 16:28:37.632]  BUNDLE  ./index.js 

[Warning] 번들 캐시가 사전 준비되었습니다.

[Info] Building and running application.

[Error] Error: 'd:\Android\funglkids_app_\node_modules\.bin\react-native.cmd run-android --no-packager' 명령을 실행하는 동안 오류가 발생했습니다. (error code 101)

[Error] Error: 'd:\Android\funglkids_app_\node_modules\.bin\react-native.cmd run-android --no-packager' 명령을 실행하는 동안 오류가 발생했습니다. (error code 101)


```
</details>

<details>
<summary>Developer Tools console</summary>

```text

I can't see the debug message because it's not running.

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js
 ✓ yarn
 ✓ Python

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android   
   - Versions found: N/A
   - Version supported: 29.0.2
 ✓ ANDROID_HOME

Errors:   1
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
```
![image](https://github.com/microsoft/vscode-react-native/assets/60372704/61513a67-6187-4ae9-83e4-551c0e221234)

but I have Android SDK 29.0.2.

* `envinfo`:

```text

```
![image](https://github.com/microsoft/vscode-react-native/assets/60372704/84e744f5-e988-46c0-9b47-5950cf841245)
I waited an hour, but it didn't work.

* React Native Tools extension version: 1.11.0
* 
![image](https://github.com/microsoft/vscode-react-native/assets/60372704/7db1f89f-1dc9-4078-9b38-ef1efec592cb)

* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Hey @gwonsuji , thanks for reaching us. I want to confirm some details with you. 
1. I cannot repro this issue in my local, did you try it using sample app as well(create sample app by npx react-native init appName)?
2. I saw that you are using  rn native command `npx react-native run-android` to execute your project.  If the project is failed by rn native command, I believe it should not related to react-native-tools extension. It should have some errors in your rn project. I think you can create new issue in [react-native official repo](https://github.com/facebook/react-native) to get some help. 

Please check these items firstly, thank you!

**Comment by gwonsuji** [comment]
Hi @EzioLi01, I created a new project and tried it, but it didn't work. Below is the order I executed.

1. I created a project with `npx react-native init appName`.
2. I ran the server with `npx react-native start`.
3. I ran it as `npx react-native run-android`.
4. But the same error occurs.

![image](https://github.com/microsoft/vscode-react-native/assets/60372704/8e31e9f5-dd2e-49e0-ac2f-8962a5344cf9)
![image](https://github.com/microsoft/vscode-react-native/assets/60372704/b045578a-d45d-4146-af8a-a8a99c91ad2e)

this is error log
`npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 936 file(s) to forward-jetify. Using 6 workers...
info JS server already running.
info Installing the app...
Unrecognized option: -xmx64m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Unrecognized option: -xmx64m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

    at makeError (D:\sj\reactnative\appName\node_modules\execa\index.js:174:9)
    at D:\sj\reactnative\appName\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\sj\reactnative\appName\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\sj\reactnative\appName\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.`


Uncognized option: I have the -xmx64m option so I changed that option in the gradlew file but it still won't install.

-before
# # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

-After
# # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=''

I ran the project with expo just in case, but the ExpoGo app is not installed on the emulator. Do you want me to attach this, too?

**Comment by EzioLi01** [comment]
Actually, this is the repo about vscode extension. Your problem should relate to react-native basic environment setup. We do not have many experiences on this. So I suggest you create new issue in [react-native official repo](https://github.com/facebook/react-native) to get some help from react-native dev and expert. Thank you!

**Comment by EzioLi01** [comment]
Maybe it related to your java in local, you can try to update your java version.

**Comment by gwonsuji** [comment]
My JDK is version 11. Will there be a problem if I do the 11 version?

**Comment by EzioLi01** [comment]
> My JDK is version 11. Will there be a problem if I do the 11 version?

Theoretically the jdk 11 should be good.

**Comment by EzioLi01** [comment]
Close this issue since it is not extension related.
