### ISSUE TITLE
[Bug] Debugger repeatedly calls a breakpoint that I didn't set when attaching to Hermes application

### ISSUE THREAD

**Issue by JamieColclough** [microsoft/vscode-react-native#1981]
# 🐛 What is the bug? How can we reproduce it?

I have been using React Native tools to debug in viscose for a while but suddenly I am getting this error when trying to use the following "Attach to Hermes Application" command:

```json
// Launch.json

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Hermes application - Experimental",
      "request": "attach",
      "type": "reactnativedirect",
      "cwd": "${workspaceFolder}"
    }
  ]
}
```

When I run this command, the React Native Tools now repeatedly calls a breakpoint that I did not set in `node_modules/metro-runtime/src/polyfills/require.js`, at the `metroRequire` method:

<img width="1047" alt="image" src="https://github.com/microsoft/vscode-react-native/assets/22543944/22c5e524-b4fc-4280-9f8b-b602c380bbec">

When I click 'Continue' it just calls the same breakpoint again immediately even though I have not set the breakpoint myself. It never gets to any code inside the application because it keeps calling this same breakpoint. I cannot use breakpoints on any of my react native code in vscode because of this bug.

## Expected behavior

Breakpoints to work as usual

## Environment

```
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment
```

* React Native Tools extension version: v0.71.7
* React Native Tools extension version: v1.11.0

**Comment by EzioLi01** [comment]
Hey @JamieColclough , this should be a regression issue on vscode-js-debug, please see #1977 for the reference.

**Comment by JamieColclough** [comment]
> Hey @JamieColclough , this should be a regression issue on vscode-js-debug, please see #1977 for the reference. After syncing with js-debug team, this issue should be fixed on July.

Thanks Ezio 

Another temporary solution I found to this issue was from #620 in which I added the `skipFiles` property to exclude these modules that were being called:

```json
// launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Hermes application - Experimental",
      "request": "attach",
      "type": "reactnativedirect",
      "cwd": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceFolder}/<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
       ]
    }
  ]
}
```
