### ISSUE TITLE
ES6 error property declarations

### ISSUE THREAD

**Issue by zhonshu** [Microsoft/vscode-react-native#199]
renderPhotosList = () => {
    if (this.state.showSelectPhotos) {
    }
  }

'property declarations' can only be used in a .ts file.
(property) MainPage. renderPhotosList: () => JSX.Element

in ES6 function  bind this

**Comment by hamiltonia** [comment]
@zhonshu I have copied this issue to VS Code https://github.com/Microsoft/vscode/issues/5055

Please follow the issue there, I will be closing this issue as it's not directly controlled by the react-native extension.
