### ISSUE TITLE
[Bug] Getting error on starting vscode react native tools debug in exponent

### ISSUE THREAD

**Issue by snownoop** [microsoft/vscode-react-native#1996]
Trying to run debug in my vscode with debug in exponent using react native tools. IT is running and i am able to open link with my expo app, however debug breakpoints are not working in vscode at all (only in browser) and i get this next error on every start:

## Debug output
This is message from debug console:
_An error occurred while launching the application. bad rs block @ typeNumber:1/errorCorrectLevel:undefined (error code 303)_

This is message from Extension Host terminal:
_[error] TypeError: Cannot set properties of undefined (setting 'reactNativeVersionWarnings')
    at Object.<anonymous> (/Users/cphr/.vscode/extensions/msjsdiag.vscode-react-native-1.11.1/dist/rn-extension.js:53:123659)
    at Generator.next (<anonymous>)
    at s (/Users/cphr/.vscode/extensions/msjsdiag.vscode-react-native-1.11.1/dist/rn-extension.js:53:122333)_

* React Native Tools extension version: 1.11.1
* Expo SDK version (if applicable): 49.0.3
all latest

**Comment by EzioLi01** [comment]
Hey @snownoop , thanks for reporting this. This issue should be fixed on nightly build, could you please try on [this version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) and let me know if it's working?
It will be fixed on next prod version release.

**Comment by gaurav-kispotta** [comment]
Hi @EzioLi01 I was also facing the same issue but after installing the preview version I did not saw the error message. Thanks.

**Comment by EzioLi01** [comment]
Close this issue, since it's verified for fixing.
