### ISSUE TITLE
Remove parsing args logic from the gulp file.

### ISSUE THREAD

**Issue by dlebu** [Microsoft/vscode-react-native#201]
Adding a tracking issue for the discussion I had with Diego about the gulp file. Using `minimist` as he suggested or `yargs` as suggested here are viable solutions: http://stackoverflow.com/questions/23023650/is-it-possible-to-pass-a-flag-to-gulp-to-have-it-run-tasks-in-different-ways

**Comment by mroswald** [comment]
something like that? https://github.com/Microsoft/vscode-react-native/compare/master...mroswald:feat/remove-manual-args-stripping

**Comment by digeff** [comment]
Yes
