### ISSUE TITLE
Fail to start debugger

### ISSUE THREAD

**Issue by XiSmartElf** [Microsoft/vscode-react-native#202]
I got the following error the first time running the debugger. Is there anything I didn't set up correctly?

node --debug-brk=40955 launchReactNative.js ios 9090 'iPhone 6s' 
Debugger listening on port 40955
[vscode-react-native] Downloaded debuggerWorker.js (Logic to run the React Native app) from the Packager.
[vscode-react-native] Executing command: react-native run-ios --simulator iPhone 6s
[vscode-react-native] [Error : 0706]  Cannot debug application: Error while executing command 'react-native run-ios --simulator iPhone 6s': spawn react-native ENOENT

##Software versions
- React-Native VS Code extension version: latest
- VSCode version: 10.11
- OS platform and version: IOS 6s
- React Native version: 0.2.0

**Comment by MSLaguana** [comment]
What version of react-native is your project using? You can check the package.json of the project to find out (Note that this is different to the version of react-native-cli). Also, is react-native installed globally, or do you have aliases / shell scripts which modify your PATH to set things up?

It looks to me like when we run `react-native run-ios` it is failing to find the `react-native` command, although the react-native packager is running so you must have it installed somewhere.

**Comment by digeff** [comment]
@XiSmartElf Have you been able to resolve the issue?

**Comment by hamiltonia** [comment]
Closing this due to lack of info, @XiSmartElf if you can provide more info please reactivate.

**Comment by shtefanntz** [comment]
![image](https://cloud.githubusercontent.com/assets/3305076/14578804/a3433f44-039b-11e6-876f-669ad6779a30.png)


I started getting this error when trying to open the packager. I'm not really sure where the logs are. 
The error started appearing after the last update

Thanks! :D
