### ISSUE TITLE
Run on device

### ISSUE THREAD

**Issue by Mokto** [Microsoft/vscode-react-native#204]
## Actual Behavior
1. Run on simulator

## Expected Behavior
1. Run on device

## Software versions
React-Native VS Code extension version: 0.1.3
VSCode version: 0.10.11 & March Insider
OS platform and version: Mac OS X El Capitan
React Native version: 0.23.1

[I changed my IP in AppDelegate.m](https://github.com/Microsoft/vscode-react-native#debugging-on-ios-device) and launched the same debug session as simulator but it builds react-native on simulator

## Logs

It is executing `react-native run-ios --simulator iPhone 6`

## Note

If I missed something, I would be happy to improve documentation :)

Thanks !

**Comment by MSLaguana** [comment]
In your `launch.json`, did you specify `"target": "device"`? The target parameter specifies whether to target a simulator (and which simulator to target) or a device. Modifying the IP in `AppDelegate.m` is necessary to have the app function once it runs on the device, but does not impact where the app is run.

**Comment by Mokto** [comment]
Ok I just created a [PR](https://github.com/Microsoft/vscode-react-native/pull/207) because in my opinion it was not clear that we had to change "target" to "device".

There is one more error now :

`Cannot debug application: Error while executing command 'ideviceinstaller -i /Users/theo/Projects/inprogress/showcase/ios/build/Build/Products/Debug-iphoneos/inProgress.app': spawn ideviceinstaller ENOENT`

So I did `brew brew install ideviceinstaller` (I will add this to README) and now I get `[vscode-react-native] [Error : 0706]  Cannot debug application: Cannot read property 'childProcess' of undefined` 



Any idea ?

Thanks :)
