### ISSUE TITLE
[Bug] Variable can't be shown when Debug hermes iOS app

### ISSUE THREAD

**Issue by QDFish** [microsoft/vscode-react-native#2070]
# 🐛 What is the bug? How can we reproduce it?

Debug hermes iOS in VSCode

## Expected behavior

can show variables when the breakpoint is hit

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby - Required for installing iOS dependencies
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✖ .xcode.env - File to customize Xcode environment

Errors:   3
Warnings: 0

* `envinfo`:

  System:
    OS: macOS 14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 229.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
    Watchman: 2023.11.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
    Gradle: 6.9.3 - /Applications/Android Studio.app/Contents/gradle/gradle-6.9.3/bin/gradle
    Homebrew: 4.1.20 - /usr/local/bin/brew
    pip3: 23.3.1 - /usr/local/bin/pip3
    RubyGems: 3.1.6 - /Users/qudian/.rbenv/shims/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 23.0.7344513-beta4
  IDEs:
    Android Studio: EAP AI-211.7628.21.2111.7676841 AI-211.7628.21.2111.7676841
    VSCode: 1.82.3 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.20 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.6 - /usr/local/bin/python3
    Ruby: 2.7.6 - /Users/qudian/.rbenv/shims/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.1

* React Native Tools extension version: v1.12.1

<img width="1323" alt="image" src="https://github.com/microsoft/vscode-react-native/assets/13432354/d18b7f59-ef39-4448-a0fd-3169fc7e9b79">

**Comment by EzioLi01** [comment]
Hey @QDFish , I will look into this, but actually I think it cannot be fixed in extension, it should be related to some scenario of vscode-js-debug.

**Comment by EzioLi01** [comment]
Adding it to backlog and known issue list, will do investigation in the future.

**Comment by EzioLi01** [comment]
I have tried on my local, but no luck to repro this. Will keep investigating soon...

<img width="1328" alt="Screenshot 2023-11-16 at 14 51 34" src="https://github.com/microsoft/vscode-react-native/assets/19662219/dbc3a4db-a7ce-4c2e-89db-1e049b444fc0">

**Comment by QDFish** [comment]
> I have tried on my local, but no luck to repro this. Will keep investigating soon...
> 
> <img alt="Screenshot 2023-11-16 at 14 51 34" width="1328" src="https://user-images.githubusercontent.com/19662219/283347056-dbc3a4db-a7ce-4c2e-89db-1e049b444fc0.png">

which version of your vscode?

**Comment by QDFish** [comment]
> I have tried on my local, but no luck to repro this. Will keep investigating soon...
> 
> <img alt="Screenshot 2023-11-16 at 14 51 34" width="1328" src="https://user-images.githubusercontent.com/19662219/283347056-dbc3a4db-a7ce-4c2e-89db-1e049b444fc0.png">

my vscode can show variables too now, but I don't know why. so weird

**Comment by EzioLi01** [comment]
> > I have tried on my local, but no luck to repro this. Will keep investigating soon...
> > <img alt="Screenshot 2023-11-16 at 14 51 34" width="1328" src="https://user-images.githubusercontent.com/19662219/283347056-dbc3a4db-a7ce-4c2e-89db-1e049b444fc0.png">
> 
> my vscode can show variables too now, but I don't know why. so weird

Interesting behavior, will keep an eye on this in the future...
