### ISSUE TITLE
[Bug] Adding a project to an untitled workspace, gives Failed to activate the React Native Tools extension (error code 702)

### ISSUE THREAD

**Issue by mousumikundu** [microsoft/vscode-react-native#2076]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Open a react native project, add another react native project to the workspace.
2. We cannot see the react native packager button to be there. 
3. We see the below in the react native output window

``` [Debug] Extension version: 1.12.2
[Debug] Projects found: 2
[Error] Failed to activate the React Native Tools extension (error code 702)```


## Expected behavior

What were you expecting to happen?

React native packager button to be seen.
This issue occurs after React native tools upgrade from 1.12.1 to 1.12.2. With 1.12.1 the logs in the react native window would be 

```[Debug] React Native version: errorUnknown
[Debug] react-native package version is not found in /Volumes/workplace/test1. Reason: errorUnknown
[Debug] React Native version: 0.71.8```

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: 1.12.1
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Hey @mousumikundu , thanks for reaching us. Unsaved workspace not have absolute path for workspace settings file, extension needs to get workspace settings in init process, so it throw an error. 
This behavior is expected but we will improve user experience for it, avoid activation failure for this scenario.

**Comment by EzioLi01** [comment]
Hey @mousumikundu , please uninstall your existing extension and give this `.vsix` a try, let me know it you still have this issue. Thank you!

[vscode-react-native-1.12.2.zip](https://github.com/microsoft/vscode-react-native/files/13520136/vscode-react-native-1.12.2.zip)
