### ISSUE TITLE
Unable to select debug environment

### ISSUE THREAD

**Issue by foobar8675** [Microsoft/vscode-react-native#208]
## Actual Behavior
1. when selecting debug environment, nothing happens

## Expected Behavior
1. ext install vscode-react-native

## Software versions
- React-Native VS Code extension version: 0.1.3
- VSCode version: 0.10.11
- OS platform and version: 
- React Native version: 10.11.4 osx  el cap

## Outputs (Include if relevant)
- here is a video of the issue https://www.youtube.com/watch?v=7o-D15uCd4E&feature=youtu.be

**Comment by digeff** [comment]
@foobar8675 Thanks for the video, it made really easy to understand and reproduce your issue!
It seems that VS Code doesn't let you add a new debug configuration after the launch.json file already exists. Can you try renaming that file to something else, to see if that fixes your issue?

**Comment by foobar8675** [comment]
Hi @digeff I just re-ran visual studio code and it prompted me for some updates. I updated the updates and re-ran and it all just seemed to work. thank you!
