### ISSUE TITLE
[Feature] Move telematry disable feature to vscode settings

### ISSUE THREAD

**Issue by MariuzM** [microsoft/vscode-react-native#2096]
Currenty to disable telematry there is seperate file 
![image](https://github.com/microsoft/vscode-react-native/assets/36937039/764ebde1-98e8-4cc2-93c7-d80bebcfb976)

Problem is that this seperate file is not going to be synced with vscode sync function. So everytime i reinstall OS or VsCode this setting wont carry over, i will have to manually change it

**Comment by EzioLi01** [comment]
Hey @MariuzM, thanks for reaching us, we will look into this based on the prioritization of plan. Any updates will comment here. Thank you!
