### ISSUE TITLE
[Bug] Reload and Show dev menu commands not working on Expo project

### ISSUE THREAD

**Issue by balmasri** [microsoft/vscode-react-native#2107]
# 🐛 What is the bug? How can we reproduce it?

Running `React Native: Reload App` command does not lead to anything nor produces any logs

To reproduce

Steps: 
1. Download Expo cli `npm install -g expo-cli`
2. create a new blank project `npx create-expo-app  --template` 
3. choose template: Blank (Bare) and wait for build
5. open vscode in the directory created
6. start react native packager
7. execute  `run ios on simulator` command
8. execute reload command (no output)
9. execute show dev menu command (no output)

## Expected behavior

To reload the application on simulator / show the dev menu

note that pressing r / d in the simulator do actually behave as expected and reload the application and open the dev menu

## Debug output

<details>
<summary>Debug Console</summary>

Nothing gets logged to debug console
</details>

<details>
<summary>React Native output channel</summary>

Nothing gets logged to output channel
</details>

<details>
<summary>Developer Tools console</summary>

Nothing gets logged to developer tools console
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text

balmasri@bcd074a9a2d9 myapp2 % npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

* `envinfo`:

```text
balmasri@bcd074a9a2d9 myapp2 % npx envinfo

  System:
    OS: macOS 13.6.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 631.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    Homebrew: 4.1.25 - /opt/homebrew/bin/brew
    pip3: 23.3.2 - ~/.kepler/kntools/asdf/installs/python/3.10.4/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    CMake: 3.22.6 - /Users/balmasri/.kepler/kntools/cmake/CMake.app/Contents/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.42.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    IntelliJ: 2023.1
    VSCode: 1.85.1 - /Users/balmasri/.kepler/kntools/vscode/VisualStudioCode.app/Contents/Resources/app/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
    Java: 11.0.20 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.10.4 - /Users/balmasri/.kepler/kntools/asdf/installs/python/3.10.4/bin/python
    Python3: 3.10.4 - /Users/balmasri/.kepler/kntools/asdf/installs/python/3.10.4/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
```

* React Native Tools extension version: 1.12.3
* Expo SDK version (if applicable): 6.3.10

Video:

https://github.com/microsoft/vscode-react-native/assets/92213874/fad25232-79f0-447b-ab59-f75ee3086043

**Comment by EzioLi01** [comment]
Hey @balmasri , thanks for reporting this issue. This is the known issue for the new kernel XCode simulator. 
Will investigate and fix it according to priorities of project plan, any updates will comment in #2058. Thank you!
