### ISSUE TITLE
Is it possible to specify arguments to expo start command when debugging?

### ISSUE THREAD

**Issue by kslbdev** [microsoft/vscode-react-native#2110]
My app is built with custom Expo Update (OTA updates) support, to launch the app, i need to specify --private-key-path command with "Expo start". How can i force the debugger to pass that that argument?

**Comment by EzioLi01** [comment]
Hey @kslbdev , could please try to add `runArguments` and pass your argument here?

**Comment by kslbdev** [comment]
Thank you for the prompt response, that works!

**Comment by EzioLi01** [comment]
We will plan to support run argument for `react-native start` or `expo start` in launch.json file in the future.
