### ISSUE TITLE
Port conflict when debugging with Expo-go

### ISSUE THREAD

**Issue by ShimHyesu** [microsoft/vscode-react-native#2118]
Hello, 
When starting debugging with Expo Go, a tab displaying a QR code and URL appears, with the port set to 19000 by default. However, the default port for React Native Tools extension settings is 8081. Therefore, when attempting to run Expo Go with the provided URL or QR code, the following error occurs:

<img width="752" alt="스크린샷 2024-03-08 오후 2 55 02" src="https://github.com/microsoft/vscode-react-native/assets/58768930/eb02948a-f239-447a-991f-dc1192bf690a">

Here is my <code>launch.json</code> file
```
    {
      "name": "Debug Exponent Hermes - Experimental",
      "request": "launch",
      "type": "reactnativedirect",
      "cwd": "${workspaceFolder}",
      "platform": "exponent",
      "expoHostType": "local",
    },
```

Expo SDK 49 and above use port 8081 by default, so it seems necessary to adjust the port.
<br><br>

## Environment
```
  System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 54.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    Homebrew: 4.2.9 - /opt/homebrew/bin/brew
    pip3: 23.3.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    VSCode: 1.87.0 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.20.1 - /opt/homebrew/bin/go
    Java: 17.0.8.1 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.7 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.1.2

```

* React Native Tools extension version: v1.12.3
* Expo SDK version (if applicable): v49.0.11

**Comment by ShimHyesu** [comment]
Furthermore, when using the Hermes engine, it does not support Debug Remote JS. 
Thus, it may be necessary to update the documentation.

Here is the reference link: [Expo Documentation](https://docs.expo.dev/debugging/tools/#debug-remote-js)

**Comment by EzioLi01** [comment]
Hey @ShimHyesu , will look into this. Could you please try to use expo command to launch your app, and using below config to attach debugger?

```
     {
            "name": "Attach to Hermes application",
            "request": "attach",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}"
        }
```

**Comment by ShimHyesu** [comment]
Thank you for the quick response.
It works :)
