### ISSUE TITLE
Debug Android and iOS not working with custom scheme and configuration (iOS) and falvors (android)

### ISSUE THREAD

**Issue by sandeepsuthar** [microsoft/vscode-react-native#2122]
# 🐛 What is the bug? How can we reproduce it?

Debug code working as expected on iOS if we are using any custom scheme with only Debug configuration setting in Xcode. (Go to Edit Scheme -> Select Scheme -> Run -> Build Configuration -> Debug).
If we create custom configuration for each scheme like Debug-QAT, Debug-UAT, Debug-Dev and select anyone from these, It's showing logs in output but breakpoints not working as expected.

Same behaviour with android also. 

## Expected behavior

What were you expecting to happen?

## Pod file

<details>
<summary>Pod file</summary>

```text

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

project 'Boilerplate',
  'Debug-Dev' => :debug,
  'Debug-QAT' => :debug,
  'Debug-UAT' => :debug,
  'Debug-Prod' => :debug,
  'Release-Dev' => :release,
  'Release-QAT' => :release,
  'Release-UAT' => :release,
  'Release-Prod' => :release


# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled(['Debug-Dev', 'Debug-QAT', 'Debug-UAT', 'Debug-Prod'])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Boilerplate' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BoilerplateTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

```
</details>

<details>
<summary>launch.json</summary>

```text

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Android",
      "request": "launch",
      "type": "reactnative",
      "cwd": "${workspaceFolder}",
      "platform": "android",
      "runArguments": [
        "--mode=qatDebug",
        "--appIdSuffix=qat",
        "--active-arch-only"
      ]
    },
    {
      "name": "Debug iOS",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios",
      "sourceMaps": true,
      "scheme": "QAT",
      "runArguments": ["--scheme", "QAT"],
      "target": "4DF508C0-959C-4955-8A86-C750EC2AE511"
    }
  ]
}


```
</details>

<details>
<summary>Debug Console</summary>

```text

Android Output:
An error occurred while launching the application. Error while executing command '/Users/sandeep/Desktop/QBurst/ReactNative_Learning/boilerplate-react-native/node_modules/.bin/react-native run-android --mode=qatDebug --appIdSuffix=qat --active-arch-only --no-packager' (error code 101) (error code 303)

iOS Output:
An error occurred while launching the application. Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712) (error code 303)


```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Packager is already running.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=ios

 BUNDLE  ./index.js 

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

 BUNDLE  ./index.js 

 LOG  Running "Boilerplate" with {"rootTag":1,"initialProps":{}}
 LOG  Device Token:  {"os": "ios", "token": "8013f32150e13f66856d6f346ddc3be783028e16988c8afcdd928a68dc2a45801d4c685765c44d454ea0c77e7a5fe0bc704de3a847377795e2243fc4eff906d732b5c3f2ca93d5c598d9d65713e4f74a"}
[Error] Error: Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712)

[Error] Error: Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

[Extension Host] An error occurred while launching the application. Unknown error: not all success patterns were matched. 
 It means that "react-native run-ios" command failed. 
 Please, check the View -> Toggle Output -> React Native, 
 View -> Toggle Output -> React Native: Run ios output windows. (error code 712) (error code 303)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Common
 ✓ Node.js - Required to execute JavaScript code
 ✖ yarn - Required to install NPM dependencies
   - Version found: N/A
   - Version supported: >= 1.10.x
 ● Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby - Required for installing iOS dependencies
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   2
Warnings: 1
```

* `envinfo`:

```text

  System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 1.93 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.15.2 - /Users/sandeep/.rvm/gems/ruby-2.7.5/bin/pod
    Homebrew: 4.2.12 - /usr/local/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.1.6 - /Users/sandeep/.rvm/rubies/ruby-2.7.5/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK:
      API Levels: 26, 28, 33, 34
      Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
      System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 17.0.10 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.7.5 - /Users/sandeep/.rvm/rubies/ruby-2.7.5/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
```

* React Native Tools extension version: v1.12.3
* Expo SDK version (if applicable): N/A

**Comment by EzioLi01** [comment]
Hey @sandeepsuthar , could you please try to use your specific `react-native start` or  `react-native run` command to launch your app, and use attach request to attach debugger?

**Comment by EzioLi01** [comment]
> > Hey @sandeepsuthar , could you please try to use your specific `react-native start` or `react-native run` command to launch your app, and use attach request to attach debugger? BTW, which version of rn are you using? Is rn 0.74.0-rc?
> 
> React Native - 0.73.6
> 
> When i am trying to run iOS for debug for custom configuration like Debug-QAT, it's causing issue.

Using `react-native run-ios --configuration=Debug-QAT` still have this issue?

**Comment by sandeepsuthar** [comment]
@EzioLi01  It showing below error:
error: unknown option '--configuration=Debug-QAT'

I have added custom configuration in Podfile and commented flipper due to using use_framework. Now below error coming:-

An error occurred while launching the application. Error while executing command '/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist'': Command failed: /usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist'
Print: Entry, ":CFBundleIdentifier", Does Not Exist
(error code 303)

**Comment by EzioLi01** [comment]
> @EzioLi01 It showing below error: error: unknown option '--configuration=Debug-QAT'
> 
> I have added custom configuration in Podfile and commented flipper due to using use_framework. Now below error coming:-
> 
> An error occurred while launching the application. Error while executing command '/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist'': Command failed: /usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist' Print: Entry, ":CFBundleIdentifier", Does Not Exist (error code 303)

If you have issue on using 'npx react-native run-ios --runArguments' directly in terminal, I think it should be react-native issue, not extension related, you should create an issue on correct [repo](https://github.com/facebook/react-native).

**Comment by EzioLi01** [comment]
Close this issue, if you have any updates, please reopen it. Any issue with react-native native command, please create issue in rn repo.

**Comment by sandeepsuthar** [comment]
@EzioLi01 It's working from terminal with below command:-
`react-native run-ios --scheme \"QAT\"`

but while running from launch.json, it's showing below error:-
`An error occurred while launching the application. Error while executing command '/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist'': Command failed: /usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/sandeep/Library/Developer/Xcode/DerivedData/RNDemo-dqioiohnqapxowgklepgivcozpqx/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist' Print: Entry, ":CFBundleIdentifier", Does Not Exist (error code 303)`

Please follow below steps to reproduce issue:
1. Create new RN project
2. Add new scheme (QAT) and custom configuration in Xcode (Debug-QAT)
3. Try to run this scheme and configuration from launch.json file for iOS in debug mode.
