### ISSUE TITLE
[Bug] Cannot find module @react-native-community/cli-platform-ios/build/config/findXcodeProject in react-native 0.74.0 while debugging iOS 

### ISSUE THREAD

**Issue by lexie011** [microsoft/vscode-react-native#2138]

**Comment by EzioLi01** [comment]
This issue should be fixed on master, please using extension nightly version for the latest updates.

**Comment by bbkillen** [comment]
I am seeing this in react-native project default project built with 0.74.2

**Comment by pee0803** [comment]
same with @bbkillen

**Comment by vfilby** [comment]
Also seeing in on the default react-native project with 0.74.3.

**Comment by lexie011** [comment]
We'll release a new version that fix this issue soon, meanwhile please use extension nightly version for workaround.

**Comment by StuStuff777** [comment]
This issue is occurring on 0.72.4 also, I assume the fix will sort all versions affected as I do not have time immediately to upgrade.

**Comment by hjKangIB** [comment]
there's also this issue on react native 0.75.2 version
