### ISSUE TITLE
[React-Native 0.23.x] Debugging on the simulator doesn't always work

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#214]
The product assumes that when calling "react-native run-ios" twice, the Application Unique ID won't change from the first call to the second call. When that happens, the Debugging Mode is not enabled properly in the simulator, so the application doesn't start in debugging mode.

Workaround: Shake the device or press Cmd + D to manually put the app in Debugging Mode (Select Debug in Chrome)

**Comment by jicongw** [comment]
This issue does not repro any more. If we still see this happening, then we will re-open.
