### ISSUE TITLE
[Bug] The packager status indicator shows inconsistent state

### ISSUE THREAD

**Issue by serhergz** [microsoft/vscode-react-native#2142]
# 🐛 What is the bug? How can we reproduce it?

The package indicator changes it state independently of the actual packager state, specifically when the packager is running and one of these 3 actions are performed:

- A new project is created
- An existing project is added to the workspace
- The stop packager command is used, and the user select a project folder not running a packager

In this 3 situations the Packager status indicator reset to the Packager Stopped status, while the packager is still running.

Steps to reproduce:
1. Create a project
2. Start the packager for that project
3. Create a new project without stopping the packager

Other case, to reproduce:
1. Create 2 projects
2. Start the packager for the first project
3. Execute the 'React Native: Stop Packager'
4. On the quickpick select the second project (the one not running)

## Expected behaviour

The expected behaviour is that the Packager indicator actually reflect the packager status, in the given example when creating a project the indicator should not change state since the packager is still running.
Ideally the indicator should track the status of each packager considering that each project could be running one instance of it.

## Debug output

<details>
<summary>React Native output channel</summary>
Image show React Native Packager is still running but packager indicator has reset to the Packager Stopped status
<img width="1426" alt="Screenshot 2024-05-10 at 08 55 14" src="https://github.com/microsoft/vscode-react-native/assets/169430458/1eb79f4a-506e-4777-977b-30a87feb6a16">

</details>

## Environment

* React Native Tools extension version: v1.13.0

**Comment by EzioLi01** [comment]
Hey @serhergz , thanks for reaching us. 
Will fix this issue currently, any update will comment here, thank you!

**Comment by EzioLi01** [comment]
Linked in enhancement https://github.com/microsoft/vscode-react-native/issues/2144.

**Comment by EzioLi01** [comment]
@serhergz Just want to confirm which OS have you used?

**Comment by serhergz** [comment]
> @serhergz Just want to confirm which OS have you used?

Thanks for the quick reply, This have been observed in MacOS Sonoma 14.4.1

**Comment by EzioLi01** [comment]
> > @serhergz Just want to confirm which OS have you used?
> 
> Thanks for the quick reply, This have been observed in MacOS Sonoma 14.4.1

Got it, will look into this.
