### ISSUE TITLE
this.project.getWorkspaceFolder is not a function

### ISSUE THREAD

**Issue by zhaoxuyll** [microsoft/vscode-react-native#2149]
# 🐛 What is the bug? How can we reproduce it?

An error is reported when you call stop package manager in the task configuration.

But there is no problem with invoking directly via command.

Version v1.13.0

1. Create a task.json and setting config
```
    {
      "label": "Stop Packager",
      "command": "${command:reactNative.stopPackager}",
      "problemMatcher": []
    },
```

2. Call this task
The notification area displays an error.
![image](https://github.com/microsoft/vscode-react-native/assets/3224165/e609d0ea-ea50-400a-9f44-7eaecd39db7e)

Log here:
![image](https://github.com/microsoft/vscode-react-native/assets/3224165/b914955f-8f25-4795-a21f-19874c054a9f)

## Expected behavior

What were you expecting to happen?
No error.

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by lexie011** [comment]
Hey @zhaoxuyll , thanks for reaching us.
Will fix this issue currently, any update will comment here, thank you!
