### ISSUE TITLE
[Feature] Node.js binary path customization

### ISSUE THREAD

**Issue by marlondecol** [microsoft/vscode-react-native#2151]
# 🚀 Feature request

It would be very helpful if we could set a custom `node` path for the packager to run.

## What scenarios will this solve?

On systems implementing `nvm`, this configuration would provide a way to choose a Node.js version for the project without needing to set the `default` alias.

---

A question may arise: _hasn't this already been implemented?_

Well, I don't know, but I couldn't find a way to run the packager on another version of Node.js without explicitly running the `nvm default alias` command.

**Comment by EzioLi01** [comment]
Hey @marlondecol , thanks for the suggestion. W'll look into this in the future.

**Comment by EzioLi01** [comment]
Hey @marlondecol , do you have any update on this?

**Comment by marlondecol** [comment]
Hey @EzioLi01, thanks for keeping this open.

My system has two versions of Node.js installed and managed by `nvm`. The `default` is 20, which I use for almost all of my projects. One of them, however, needs it in 16, and so a [`.nvmrc`](https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc) file was created in the root of that project that [tells the Z shell to switch to that version as soon as it is opened](https://github.com/nvm-sh/nvm?tab=readme-ov-file#zsh).

The Code can run all configured tasks that are based on Node.js in the appropriate version (the one set in `.nvmrc`), such as those that run on Yarn, for example, but this extension always runs the packager in the `default` version, regardless of the version required by `.nvmrc`.

The extension's command in question, which I believe is the responsible for running the packager, is [this](https://github.com/microsoft/vscode-react-native/blob/5a9f7e30b96d64dbf8c94d942e6003e8101286eb/src/common/packager.ts#L610), but there may be others with the same problem.

**Comment by EzioLi01** [comment]
> Hey @EzioLi01, thanks for keeping this open.
> 
> My system has two versions of Node.js installed and managed by `nvm`. The `default` is 20, which I use for almost all of my projects. One of them, however, needs it in 16, and so a [`.nvmrc`](https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc) file was created in the root of that project that [tells the Z shell to switch to that version as soon as it is opened](https://github.com/nvm-sh/nvm?tab=readme-ov-file#zsh).
> 
> The Code can run all configured tasks that are based on Node.js in the appropriate version (the one set in `.nvmrc`), such as those that run on Yarn, for example, but this extension always runs the packager in the `default` version, regardless of the version required by `.nvmrc`.
> 
> The extension's command in question, which I believe is the responsible for running the packager, is [this](https://github.com/microsoft/vscode-react-native/blob/5a9f7e30b96d64dbf8c94d942e6003e8101286eb/src/common/packager.ts#L610), but there may be others with the same problem.

Hey @marlondecol , thanks for the details. We'll add this in our plan and look into this soon based on prioritization. Any update will comment here, if you have any thought or suggestion on this, please also let me know. 

Thank you!
