### ISSUE TITLE
adb reverse not working on adb tcpip/adb network(wirelesss) debugging

### ISSUE THREAD

**Issue by ZAB303** [microsoft/vscode-react-native#2169]
### **I connect my phone to PC for debugging using adb network/tcpip for example `adb connect 192.168.xxx.xxx` then I enter code in terminal `adb reverse tcp:8000 tcp:8000` to connect my flutter app to my laravel localhost api but a message always appears like this `adb.exe: error: more than one device/emulator`**

```
//this is the input and output command code in my pc terminal

C:\myPc\myflutterapp>adb tcpip 5555
//then I unplugged my USB cable

C:\myPc\myflutterapp>adb connect 192.168.xxx.xxx
`connected to 192.168.xxx.xxx:5555`

C:\myPc\myflutterapp>adb devices
`192.168.xxx.xxx:5555 device`

C:\myPc\myflutterapp>adb reverse tcp:8000 tcp:8000
`adb.exe: error: more than one device/emulator`

C:\myPc\myflutterapp>adb devices
`192.168.xxx.xxx:5555 device`
```

**### Expected Behavior**
adb **reserve** via tcpip/network(wireless) still works

### **Software versions**
flutter vscode extensions: 3.60.0
VSCode version: 1.69
OS platform and version: Windows 10 pro 22H2
flutter version: 3.13.7

**### Device Debug**
Android Phone(Android 8.0)

**Comment by EzioLi01** [comment]
Hey @ZAB303 , you're using flutter extension, not react-native-tools, please create an issue in correct repo. If your issue related to extension, please create issue in flutter extension repo. If issue related to vscode terminal, you can create issue in vscode repo.
