### ISSUE TITLE
[Bug] specify port

### ISSUE THREAD

**Issue by double12** [microsoft/vscode-react-native#2173]
# 🐛 What is the bug? How can we reproduce it?

8081 port is occupied on my mac. so i need to specify port with vscode when debugging with iPhone. 
i tried some ways below
1. create debug ios launch.json below
"version": "0.2.0",
    "configurations": [
        {
            "name": "Run iOS",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "enableDebug": true
        }
    ]
but it always told me port 8081 already in use. 

## Expected behavior

my question is that how can i specify port of packager and iphone or simulator gracely with vscode extension such as package.json,launch.json.

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment]
Hey @double12 , thanks for reaching us, could you please try to use `npx react-native start --port` to start metro with specific port, and using `attach` configure to debug your app?

**Comment by double12** [comment]
> Hey @double12 , thanks for reaching us, could you please try to use `npx react-native start --port` to start metro with specific port, and using `attach` configure to debug your app?

i try to use scripts in vscode with package.json to start packager with specific port. it's ok...
![image](https://github.com/user-attachments/assets/4742ad09-94e8-4f3c-83e7-0bc73eb48b79)
when i type i in vscode terminal- run on iOS..it wakes another system terminal calling launchPackager.command.
but it launch success

**Comment by double12** [comment]
@EzioLi01 so how can i specify port when attaching

**Comment by EzioLi01** [comment]
You can set port argument in config file.

**Comment by double12** [comment]
> If you only need to change attach port, you can set `port` argument in config file.

i think i have solved the problem. i create settings.json and specify react-native.packager.port value.
i think owner can complete document, it cost me too much time

**Comment by double12** [comment]
omg... i think i have finished set up rn develop enviroment, hot reload and debugging in vscode.
thanks for your answer.  @EzioLi01
