### ISSUE TITLE
[Bug] Unable to hit breakpoints on windows with vscode extension

### ISSUE THREAD

**Issue by TraGicCode** [microsoft/vscode-react-native#2176]
# 🐛 What is the bug? How can we reproduce it?

I'm unable to successfully hit my breakpoint when attempting to attach to the react-native application when using "Attach to Hermes Application"

        {
            "name": "Attach to Hermes application",
            "request": "attach",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}"
        },

Can anyone please help me understand what is going on or an alternative way to help me hit breakpoints in my react-native application?

## Expected behavior

I should hit my breakpoints with no issues

## Environment

- windows
- "react-native": "0.73.4"
- latest version of vscode extension

**Comment by EzioLi01** [comment]
Hey @TraGicCode , thanks for reaching us. Could you please provide below info to us?
1. Repro steps
2. Repro demo is possible

**Comment by EzioLi01** [comment]
Close this issue since it's not updating currently. If you still facing this issue, please reopen it or create a new one. Thank you!
