### ISSUE TITLE
[Bug] Can not use

### ISSUE THREAD

**Issue by Minessential** [microsoft/vscode-react-native#2181]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. npx react-native init test [Initialize]
2. cd test
3. npm i
4. Starting Packager[Vs Code]

## Expected behavior

What were you expecting to happen?
![image](https://github.com/user-attachments/assets/84ad0b9d-111a-4c43-989c-6bdcbc347349)

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

![image](https://github.com/user-attachments/assets/a9eedf39-8f9a-4015-b4e3-db0ebf22aa31)

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

  System:
    OS: Windows 11 10.0.26257
    CPU: (8) arm64 Snapdragon (TM) 8cx Gen 3 @ 3.0 GHz
    Memory: 3.26 GB / 15.43 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Managers:
    Maven: 4.0.0 - ~\Programs\apache-maven\bin\mvn.CMD
    pip3: 24.1.1
  Utilities:
    Git: 2.45.1.
    FFmpeg: 16.0.6 - C:\Users\Mine\Programs\FFmpeg\ffmpeg.EXE
    Curl: 8.8.0 - C:\WINDOWS\system32\curl.EXE
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33, 34, 35
      Build Tools: 30.0.3, 34.0.0, 35.0.0
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.22621.0
  IDEs:
    Android Studio: AI-241.15989.150.2411.11948838
    Visual Studio: 17.10.35013.160 (Visual Studio Community 2022)
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
    Java: 17.0.11
    Python: 3.13.0
    Python3: 3.13.0
  Databases:
    SQLite: 3.42.0 - C:\Users\Mine\Programs\android_sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26257.5000

* React Native Tools extension version: v2024.6.2621
* React Native : 0.74

**Comment by EzioLi01** [comment]
Hey @Minessential , please check info and workaround in #2180.
