### ISSUE TITLE
[Bug] Cannot find module @react-native-community/cli-platform-ios/build/config/findXcodeProject in react-native 0.75.1 while debugging iOS

### ISSUE THREAD

**Issue by loganpar** [microsoft/vscode-react-native#2197]
This seems to be a different problem than [this recently fixed issue](https://github.com/microsoft/vscode-react-native/pull/2140).

**Comment by lexie011** [comment]
Hi @loganpar, thanks for reaching us. Have you tried nightly version of the extension? You can see details in this issue #2138
