### ISSUE TITLE
[Bug] Doesn't support monorepos and relies on package.json too much

### ISSUE THREAD

**Issue by phazei** [microsoft/vscode-react-native#2207]
When I try to launch the debugger, I get this error:
"An error occurred while launching the application. Invalid Version: SemverInvalid"

This is my launch.json:

        {
            "name": "Debug Android Hermes",
            "request": "launch",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}/apps/mobile/",
            "platform": "android"
        },

My package.json is in the ${workspaceFolder}, in the mobile folder it only has `"react-native": "*"` which is generated by NX.  Also, my package name in my package json is "mobile" but when it tried to launch once it gave an error about loading "com.mobile.MainApplication".  But our namespace is "com.ourCompany.ourApp.MainApplication".  Those items should be configurable inside the launch.json.

**Comment by EzioLi01** [comment]
Hey @phazei , thanks for reaching us. Is it possible to share a demo to repro this issue? I have tried on a basic monorepo project and it's working well. 

Also could you please try to launch your application using `npx react-native run-android`, and using attach request to debug you app?

**Comment by EzioLi01** [comment]
Hey @phazei , do you have any update on this?

**Comment by EzioLi01** [comment]
Close this issue since it have no further updates, please renew it or create a new one if you still need help. Thanks!

**Comment by phazei** [comment]
Hey, I'd like to create a demo for this, and I will, but we have a big crunch so I won't have time for a couple weeks.

**Comment by EzioLi01** [comment]
Thanks so much, any time you need help please feel free to let me know!
