### ISSUE TITLE
Cannot run react-native commands from VS Code

### ISSUE THREAD

**Issue by inturbidus** [Microsoft/vscode-react-native#221]
## Actual Behavior
1. Select React Native: Start Packager or Run iOS
2. Get error [Error : 0105]  Failed to run the application in iOS: spawn react-native ENOENT

## Expected Behavior
1. Select React Native: Start Packager or Run iOS
2. Packager or iOS Simulator Runs

## Software versions
- React-Native VS Code extension version: 0.1.4
- VSCode version: 1.0.0
- OS platform and version: OS X El Capitan
- React Native version: 0.23.0

######### Executing command: react-native start --port 8081 ##########
[Error : 0105]  Failed to run the application in iOS: spawn react-native ENOENT

I understand that this is an environment problem, I cannot run any commands from VS Code without there being an issue.  I get similar errors for Debugging on Android and iOS (adb not found, START_PACKAGER errors).  However, I'm not sure what path is supposed to be in my PATH variable for bash.

Also, I have the latest node, nvm, and react-native-cli is installed globally.

**Comment by MSLaguana** [comment]
If you open a command line, does running `react-native` work? If so, have you added things to your .bash_profile or similar to modify your PATH?

**Comment by inturbidus** [comment]
Yes, react-native works on the command line.  Of course I have PATH items in my .bashrc.

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$HOME/.nvm/versions/node/v5.10.1/bin/:$PATH

echo $PATH
/Users/matthudson/.nvm/versions/node/v5.10.1/bin:/Users/matthudson/Library/Android/sdk/platform-tools:/Users/matthudson/Library/Android/sdk/tools:.git/safe/../../bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by MSLaguana** [comment]
Ok, that would explain your issue then. I believe that if you run vscode from the command line, then it should work correctly since it will inherit your modified PATH variable.

Modifying your path via something like http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite/26586170#26586170 should resolve the issue. Alternately, you could add a symlink to your local react-native install somewhere like /usr/local/bin which is already on the default path.

**Comment by inturbidus** [comment]
Ah!  Perfect!  Running code from command line fixed the issue.

**Comment by inturbidus** [comment]
This is probably a dumb question, but where would I find my react-native install?

**Comment by MSLaguana** [comment]
If you run `which react-native` it will tell you where the executable is.

**Comment by inturbidus** [comment]
Thank you, for some reason when I ran that earlier it came up empty.
