### ISSUE TITLE
Question: Is there a way to directly get the lastest nightly version?

### ISSUE THREAD

**Issue by serhergz** [microsoft/vscode-react-native#2213]
Context:
I am trying to automate testing, i would like to test against the nightly version, so that i can detect potential problems early. 

Question: 
Is there a way to get the latest nightly version directly from a github or other? I don't want to depend on the market place.

Thanks.

**Comment by lexie011** [comment]
Hi @serhergz, thanks for reaching us. You can try to package and install your own .vsix file following this [doc](https://github.com/microsoft/vscode-react-native/blob/master/CONTRIBUTING.md#build-the-project) to get the latest version

**Comment by EzioLi01** [comment]
Close this since it's resolved, @serhergz please get info in above link. Thanks!
