### ISSUE TITLE
[Bug] @react-native-community/cli-platform-apple/build/config/findXcodeProject React Native Version 0.76.4

### ISSUE THREAD

**Issue by lizeWrk** [microsoft/vscode-react-native#2258]
"react-native": "0.76.4"

tested with nightly version. 

 "devDependencies": {
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
}

Launch.json

 {
      "name": "Debug iOS",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios",
      "target": "simulator",
      "enableDebug": true
    },

Output
Cannot find module '.../node_modules/@react-native-community/cli-platform-apple/build/config/findXcodeProject'

also tested installed with:
https://github.com/microsoft/vscode-react-native/issues/2230#issue-2620248906

**Comment by EzioLi01** [comment]
Hey @lizeWrk , thanks for reaching us. Unfortunately our pipeline is in a big upgrading that blocking our release process currently, the nightly version is not published in marketplace. 

Please try on this package and let me know if you have any issue. Thanks!

[vscode-react-native-1.13.1.vsix.zip](https://github.com/user-attachments/files/18070673/vscode-react-native-1.13.1.vsix.zip)

**Comment by EzioLi01** [comment]
Please get reference from above comment. Thanks!

**Comment by KrisLau** [comment]
Sorry a bit confused as to what I should do based on the above comments? Should I be downloading the zip?

**Comment by EzioLi01** [comment]
> Sorry a bit confused as to what I should do based on the above comments? I'm having the same error as OP. I tried the nightly build as well and both seem to have issues.
> 
> For the regular version: Cannot find module '.../node_modules/@react-native-community/**cli-platform-ios**/build/config/findXcodeProject'
> 
> For the nightly version: Cannot find module '.../node_modules/@react-native-community/**cli-platform-apple**/build/config/findXcodeProject'
> 
> Should I be downloading the zip?

@KrisLau Yes, since our release is updating, the prod and nightly version is not released to the latest changes (Sorry about that). So I suggest you can download and install above .vsix file or build your own installer according to [this](https://github.com/microsoft/vscode-react-native/blob/master/CONTRIBUTING.md#build-the-project).

**Comment by MoblyDave** [comment]
Seconding @ttruongatl comment. I got stuck on this issue for quite some time until I stumbled upon this thread. I had previously tried the latest nightly as of this comment, but it didn't work. However the 1.13.1.vsix that was posted here does fix it, so also curious why that hasn't been put into the nightly 3 months on.

**Comment by mstoner-aptos** [comment]
Same. From the other threads I thought this would be fixed in the nightly previews, but just tried latest and it's not stopping on breakpoints. Had to use the experimental vsix, similar to what oithers are echoing here
