### ISSUE TITLE
Suggestion: Support Debug Attach

### ISSUE THREAD

**Issue by joewood** [Microsoft/vscode-react-native#233]
This is a great extension. There is one thing I miss from Chrome Dev Tools - with Chrome Dev Tools it is possible to debug a running iOS app from Chrome running on Windows. Issue #142 suggests that should be blocked because the Windows machine cannot initiate running the process. In reality, the binary is rarely changed and can be run from the device at any time.

It should be possible for the iOS app to discover the debugger and attach to it, even on a Windows machine.

**Comment by MSLaguana** [comment]
We will support this in our next release. The code is in now.
