### ISSUE TITLE
Debug IOS not running

### ISSUE THREAD

**Issue by zhonshu** [Microsoft/vscode-react-native#236]
Found Xcode workspace ArtGallery.xcworkspace
Launching iPhone 6s (9.3)...
Building using "xcodebuild -workspace ArtGallery.xcworkspace -scheme ArtGallery -destination id=9A811A4F-BD3C-4A5B-99E4-30C9CFEAA04D -derivedDataPath build"
User defaults from command line:
IDEDerivedDataPathOverride = /Users/zhongshu/Documents/Project/ArtGallery/ios/build
xcodebuild: error: The workspace named "ArtGallery" does not contain a scheme named "ArtGallery". The "-list" option can be used to find the names of the schemes in the workspace.
Installing build/Build/Products/Debug-iphonesimulator/ArtGallery.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/zhongshu/Documents/Project/ArtGallery/node_modules/promise/lib/done.js:10
throw err;
^
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ArtGallery.app/Info.plist

**Comment by MSLaguana** [comment]
How did you create your project, and what happens if you `react-native run ios` in your project? It looks like that is failing because of a missing scheme, which should have been created by `react-native init`.

**Comment by zhonshu** [comment]
react-native run ios same error.
I first create My project use react-native init, vscode debug success two month ago, today I upgrade react native then vscode debug error

**Comment by MSLaguana** [comment]
When you say you upgrade react-native, how did you do that? Did you change the version in your project's package.json? Did you un-install and re-install it locally, or globally?

**Comment by zhonshu** [comment]
yet, I modify package.json react native new version, rm -rf node_modules directory, then npm install

**Comment by MSLaguana** [comment]
Try running `react-native upgrade` and then `react-native run-ios` again. That may fix up any incompatibilities between the files from the previous version of react-native and the new version.

**Comment by zhonshu** [comment]
thank you!
I react-native upgrade, than react-native run-ios have error.

ERROR:
zhongshudeMacBook-Pro:ArtGallery zhongshu$ react-native run-ios
Found Xcode workspace ArtGallery.xcworkspace
Launching iPhone 6 (9.3)...
Building using "xcodebuild -workspace ArtGallery.xcworkspace -scheme ArtGallery -destination id=4CE02304-87F8-4E3C-9769-9BF27868BADF -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/zhongshu/Documents/Project/ArtGallery/ios/build

xcodebuild: error: The workspace named "ArtGallery" does not contain a scheme named "ArtGallery". The "-list" option can be used to find the names of the schemes in the workspace.
Installing build/Build/Products/Debug-iphonesimulator/ArtGallery.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/zhongshu/Documents/Project/ArtGallery/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ArtGallery.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:441:13)
    at Object.execFileSync (child_process.js:461:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/zhongshu/Documents/Project/ArtGallery/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/zhongshu/Documents/Project/ArtGallery/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/zhongshu/Documents/Project/ArtGallery/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/zhongshu/Documents/Project/ArtGallery/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by MSLaguana** [comment]
Do you have `ios/ArtGallery.xcodeproj/.xcshareddata/xcschemes/ArtGallery.xcscheme`? If not, that is the cause for this error. I'm not sure why it would be missing though.

**Comment by MSLaguana** [comment]
Running `react-native upgrade` should fix that though. What is the contents of your `ios` folder in your project?

**Comment by zhonshu** [comment]
I have ios/ArtGallery.xcodeproj/.xcshareddata/xcschemes/ArtGallery.xcscheme this file.
I try new react-native version init project diff old project， see different segment add My old project success.
Thankyou very much for providing us such valuable information, When off duty I can do my private work, do this, today back you.
