### ISSUE TITLE
Cannot import NativeModules

### ISSUE THREAD

**Issue by bigdrum** [Microsoft/vscode-react-native#249]
## Actual Behavior
1. import {NativeModules} from 'react-native';
    var MyNativeObject = NativeModules.MyNativeObject;
2. Error: [ts] Module '"react-native"' has no exported member 'NativeModules'.

## Expected Behavior
1. The first line should be compiled.
2. There is someway to reference a object in NativeModules.

## Software versions
- React-Native VS Code extension version:  Installed on June 14, 2016
- VSCode version: 1.2 
- React Native version: 0.21.0 

Extra question: Is it possible to use custom d.ts file?

**Comment by MSLaguana** [comment]
If you look in `.vscode/typings/react-native` you'll find the `react-native.d.ts` file that we use. It's a bit of an old version at the moment, and we're trying to work out a better way to provide typings here, but if you modify or replace that file then it will update the intellisense and compilation behavior.

Specifically in terms of NativeModules, I don't see that defined in the DefinitelyTyped repo where we took the typings from, so you may need to provide your own typings for how that behaves.

**Comment by bigdrum** [comment]
It seems the file in .vscode/typings/react-native would get replaced automatically when the editor restarts.
I agreed the missing definition of NativeModules is an upstream issue though. I have found a workaround by importing it in a js file, then re-export it.
