### ISSUE TITLE
Debugger doesn't stop at breakpoints in event handlers when debugging Android emulator

### ISSUE THREAD

**Issue by xharmagne** [Microsoft/vscode-react-native#251]
I'm trying to debug a modified version of the Welcome to React Native app that is set up by react-native init. Modification = add a TextInput with an onSubmitEditing event handler which logs the text to console, add if(true) before return on the render function.

A breakpoint on console.log within the handler is never hit, but the text does get logged to Output - LogCat - emulator. (Doesn't get logged to debug console though.)

However, a breakpoint not within the handler is hit. e.g. on the registerComponent line, on the import line/s, or inside a function outside the class. A breakpoint within the render function on if(true) is also hit.

I've got only one VS Code instance open, no other packager running. Packager status is "running". 

TextInput setup as follows:
<TextInput
 returnKeyType="search"
 enablesReturnKeyAutomatically={true} onSubmitEditing={ (event) => this.testEvent(event) } />
...
 testEvent(event) {
    console.log(event.nativeEvent.text);
  }

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.2.1
- OS platform and version: Windows 10.0.10586 Build 10586
- React Native version: 0.27.2

**Comment by MSLaguana** [comment]
It looks like your code uses JSX, is that correct? I've noticed that when compiling JSX react-native produces sourcemaps which don't properly account for the transformation from JSX to plain javascript. I suspect that any breakpoints you have before the JSX will be hit as-expected, and any breakpoints set after it will be shifted by some number of lines, giving unpredictable behaviour.

If you want to use typescript, then @frogcjn has a guide at https://gist.github.com/frogcjn/3bb47ce01a5168d8cd570a46cc71bb02 which explains how to set up source maps there, and that uses the typescript compiler to handle TSX which does maintain sourcemaps correctly. You may be able to follow similar steps to use the typescript compiler to transpile your JSX to JS while maintaining sourcemaps.

I'd expected this JSX sourcemap issue to be addressed by react-native, but it looks like it's still there so we may need to do something further about it.

**Comment by MSLaguana** [comment]
@xharmagne Are you still having this issue, and can you confirm whether it only seems to happen when using JSX?
