### ISSUE TITLE
Always flash error message when open another folder in VSCode

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode-react-native#255]
`vscode.window.showErrorMessage("Current workspace is not a React Native project.");`
Should remove this line in `/src/extension/commandPaletteHandler.ts`

See PR: https://github.com/Microsoft/vscode-react-native/pull/245/commits/aebaf0e3fd7c15120c408af3f473de4395cfca25

**Comment by MSLaguana** [comment]
@frogcjn Does this still happen for you after you built the code with your change? I think that some recent changes to how we detect react-native projects should mean we don't complain as often, but if it still happens then I'll look further into it.

**Comment by frogcjn** [comment]
@MSLaguana 
There is no frequent alert right now. Thanks!
