### ISSUE TITLE
this extension causes initial state of Output pane to be open

### ISSUE THREAD

**Issue by jokeyrhyme** [Microsoft/vscode-react-native#258]
## Actual Behavior
1. install extension
2. restart VSCode
3. observe that Output pane is always open initially

## Expected Behavior
1. install extension
2. restart VSCode
3. initial state of the Output pane should not _always be open, maybe consider whether it was open last time, or only open it based on user actions later?

## Software versions
- React-Native VS Code extension version: latest as of today (can't see a way to find the actual number)
- VSCode version: 1.3.0-insider
- OS platform and version: macOS 10.11.6 beta
- React Native version: not installed

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

**Comment by mquandalle** [comment]
I also think this pane shouldn't be open on editor start—especially for *non-RN* projects. Is it done on propose or is it a bug with this extension? with VSCode?

**Comment by MSLaguana** [comment]
I've looked into this, and I think I understand why it happens.

We create an OutputChannel (that's a thing that writes to a tab in the output window) when our extension is loaded, and it seems that by default when an OutputChannel is created, it brings it into focus.

I've played around a little and I can explicitly hide the output channel we created, but that will hide the output window if it was already open as well.

I can certainly limit the creation of the output channel to when we detect a react-native project, but it looks like I'm limited in how much we can respect the initial state of the window.

**Comment by jokeyrhyme** [comment]
Think it's worth creating and upstream VSCode issue to discuss the behaviour of OutputChannel initialisation?

**Comment by MSLaguana** [comment]
I thought about this some more, and we primarily use the output window for the packager output, which is triggered by some user interaction. I've got a PR out which delays creating the output channel until we actually want to write to it, so now the window won't open up until you've done some action which prints to it.
