### ISSUE TITLE
No mention of setting user defined ports through user and workspace settings

### ISSUE THREAD

**Issue by kulmajaba** [Microsoft/vscode-react-native#260]
In case the user cannot use the default port for the packager (8081) React Native Tools has the option to set the port by placing the following snippet under either user or workspace settings:

    "react-native": {
        "packager": {
            "port": 8088 // User defined port
        }
    }

However, there is no mention of this in the docs. This would save some time when troubleshooting problems with the packager.

**Comment by PatoBeltran** [comment]
@kulmajaba thanks for noticing! We have a PR (https://github.com/Microsoft/vscode-react-native/pull/261) out to fix this

**Comment by zhouhao27** [comment]
It doesn't work for me. Still using 8081
