### ISSUE TITLE
React Stateless function don't get syntax coloring

### ISSUE THREAD

**Issue by prashid** [Microsoft/vscode-react-native#263]
Hi,
Using latest version of VSCode with [React Native extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native). 

I don't get syntax coloring for React Stateless functions. You can see in the image. There is no yellow coloring on `<Text></Text>` or `<View></View>`
![problem](https://cloud.githubusercontent.com/assets/620377/16782006/254de526-4897-11e6-96c0-733a48f82488.png)

**Comment by MSLaguana** [comment]
Thanks for reporting this, but the syntax highlighting is actually provided by vscode itself and not our extension. Please report this at https://github.com/Microsoft/vscode/issues

**Comment by prashid** [comment]
Reported on VSCode

https://github.com/Microsoft/vscode/issues/9160

**Comment by panarasi** [comment]
@MSLaguana Given that there is no action for this specific bug, should we close this bug for the extension ?
