### ISSUE TITLE
Debugger for iOS does not compile xcworkspace projects correctly

### ISSUE THREAD

**Issue by MikeBlair** [Microsoft/vscode-react-native#264]
## Actual Behavior
1. When launching debugger, it ignores the workspace file, and finds the related project file and only uses the project file when calling xcodebuild. 

## Expected Behavior
1.  If the project is contained in an Xcode workspace (like many projects that use cocoapods), Visual Code React Native should use the workspace file instead when calling xcodebuild.

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.3.1
- OS platform and version: Mac OS X 10.11.5 
- React Native version: 0.25.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
`* BUILD FAILED **
The following commands produced analyzer issues:
	Analyze Modules/RCTUIManager.m
(1 command with analyzer issues)
The following build commands failed:
	CompileC build/Build/Intermediates/NucleusMobile.build/Debug-iphoneos/NucleusMobile.build/Objects-normal/armv7/ARDWebSocketChannel.o ARDWebSocketChannel.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[vscode-react-native] [Error : 0101]  Cannot debug application: Error while executing command 'xcodebuild -project /Users/mblair/dev/nucleusmobile/ios/NucleusMobile.xcodeproj -scheme NucleusMobile -destination generic/platform=iOS -derivedDataPath /Users/mblair/dev/nucleusmobile/ios/build': Error while executing command 'xcodebuild -project /Users/mblair/dev/nucleusmobile/ios/NucleusMobile.xcodeproj -scheme NucleusMobile -destination generic/platform=iOS -derivedDataPath /Users/mblair/dev/nucleusmobile/ios/build'`
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

Please note, the xcodebuild command used above works fine if -workspace and the workspace filepath are substituted for the -project. The react-native command line tool (react-native run-ios) successfully builds projects contained in workspaces.

**Comment by MSLaguana** [comment]
Thanks for pointing this out, I see that we missed a part of the `react-native run-ios` workflow.

**Comment by MikeBlair** [comment]
@MSLaguana, thanks for the quick response.  

It would be really nice if we could specifically specify workspace and scheme settings in the launch.json file.  If they are specified there, you can skip the part of your code that tries to determine what they are.  That would help for more complex workspace files.

**Comment by MSLaguana** [comment]
Which settings in particular would you like to set? Or would you like to be able to specify the xcode command line argument completely?

**Comment by strefethen** [comment]
@MSLaguana any update on this? Seems pretty essential for working with Cocoapods as well where the pod is part of the workspace.

**Comment by MSLaguana** [comment]
Are you happy with react-native's current behavior, where it picks the first `.xcodeproj` or `.xcworkspace` file that it finds? Or do you want to specify what should be used? How hands-on do you want to be? I was hoping to get more insight into what would be helpful before making the change.

**Comment by strefethen** [comment]
I'm happy with react-native's current behavior. My needs at this point aren't more specific than that.

**Comment by MikeBlair** [comment]
@MSLaguana, sorry for the late response on this.  

Just getting parity with how React Native currently works (chooses the project or workspace file automatically) would be a good first start.

Ideally, we would eventually have an option to completely control the xcode command line argument for users who want more control.
