### ISSUE TITLE
Feature request - reactNative.restartPackager command

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode-react-native#265]
There are many situations when we need to restart the packager, like adding some images to folder causing [`TransformError...Unexpected character`](https://github.com/facebook/react-native/issues/6691), as far as I know, the only way to fix it is to restart packager, right now I had to stop packager first then start it again. It would be helpful if there are a `restartPackager` command.

**Comment by MSLaguana** [comment]
@chenxsan @DominicTobias @tapir We are looking into doing this now. When you want this, is it because the packager is in an invalid state and you would also like the cache to be reset?

**Comment by BretJohnson** [comment]
I implemented this in the restart_packager branch, PR #299

**Comment by vladimir-kotikov** [comment]
@MSLaguana, @mbraude, can we close this? This seems to be implemented and works perfectly for me.
