### ISSUE TITLE
Unable to specify variant for debug

### ISSUE THREAD

**Issue by danmattsson** [Microsoft/vscode-react-native#270]
## Actual Behavior
When starting to debug an Android app, I'm not allowed to select av valid variant which leads to all sub projects getting built and pushed to the device. A command such as `react-native run-android --variant=devDebug` is not available.

## Expected Behavior
Some way to specify which variant should be build/debugged.

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.3.1
- OS platform and version: Windows 10 x64
- React Native version: 0.29.0

**Comment by MSLaguana** [comment]
@danmattsson FYI we've just published the version containing support for this now.
