### ISSUE TITLE
Run npm install if node_modules is empty

### ISSUE THREAD

**Issue by forki** [Microsoft/vscode-react-native#271]
If I clone a react native project and open in VS code then the plugin can't start the ract native app.
This is because of the missing node-modules. Can you just run npm install in that case?

**Comment by MSLaguana** [comment]
Vscode extensions typically do not try to be a full IDE, but to provide enhancements to a typical workflow. Currently we don't have any project-management functionality, such as creating a project, updating a project to a newer version, adding ios or android platforms if they were removed, etc.

Part of the reason for this is we expect people to use vscode for the text editing and debugging, but still use the command line regularly and thus we felt there was little benefit in adding once-off features like `npm install` which don't happen regularly in the lifetime of a project.

Do you disagree?

**Comment by forki** [comment]
Thx for laying project philosophy. I think that's fine.
