### ISSUE TITLE
Cannot debug inside vscode when using a custom port

### ISSUE THREAD

**Issue by Riglerr** [Microsoft/vscode-react-native#272]
## Actual Behavior
1.  Change packager port via user settings
     `"react-native": {
        "packager" : {
            "port": 8088
        }
    }`

2.  Change AppDelegate.m to use new port 
`jsCodeLocation = [NSURL URLWithString:@"http://localhost:8088/index.ios.bundle?platform=ios&dev=true"];`

3. Debug Ios, then launches an external terminal with the packager and opens the chrome debugger tools instead of using the vscode editor.

## Expected Behavior
1. Starts packager using vscode terminal on the correct port.
2. Should be able to debug using the vscode editor and debug tools

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.3.1
- OS platform and version: OS X El Capitan: 10.11.6
- React Native version: 0.26.2

**Comment by MSLaguana** [comment]
When you modify the port in `settings.json` that is primarily modifying the port used for commands done in the command palette, when you use `cmd-shift-p`. When debugging, the launch.json entry is the source of truth for configuration options. Did you also modify the port there? If not, then there will actually be 2 packagers running, and your app connected to the one which is not being debugged at the time.

**Comment by Riglerr** [comment]
Ok, i'll give this a try in a few hours and report back.
Cheers for the quick response

**Comment by MSLaguana** [comment]
Hello @Riglerr, did changing the launch.json fix the issue for you?

**Comment by zhouhao27** [comment]
@MSLaguana How to change the port in launch.json? I did the following:

```
{
      "name": "Debug iOS",
      "program": "${workspaceRoot}/.vscode/launchReactNative.js",
      "type": "reactnative",
      "request": "launch",
      "platform": "ios",            
      "react-native": { "packager" : { "port": 9999 } },
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/.vscode/.react"
    },
```

But doesn't work.

**Comment by SounD120** [comment]
Hi @zhouhao27 . You need to add packager port settings in your `settings.json` as described in [documentation](https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#setting-up-the-react-native-packager).

**Comment by zhouhao27** [comment]
It works when I add port in settings.json.

**Comment by SPopenko** [comment]
@SounD120  the link you posted is broken, could you please update it?

**Comment by SounD120** [comment]
@SPopenko Done!
