### ISSUE TITLE
Add support for debugging react-native universal windows platform (UWP)

### ISSUE THREAD

**Issue by jmcginty** [Microsoft/vscode-react-native#278]
This is a feature request to add debug support for the windows port of react-native.

The Windows Universal Platform port of react-native is here: https://github.com/ReactWindows/react-native-windows

VSCode react-native extension seems the logical way to debug on windows, but currently we only support ios and android.

**Comment by panarasi** [comment]
@jmcginty We are currently looking into this. There does not seem to be much work we would need to do, and this is a planned work item.

**Comment by jmcginty** [comment]
@panarasi Is there a public view of the planned work items?

**Comment by panarasi** [comment]
@jmcginty This is the query we are using - https://github.com/Microsoft/vscode-react-native/labels/copiedtobacklog

**Comment by sasivarnan** [comment]
We love to have this feature. Now we can develop UWP apps using Windows Standalone SDK without Visual Studio Code.

I already raised an [issue](https://github.com/ReactWindows/react-native-windows/issues/409) regarding this in [react-native-windows](https://github.com/ReactWindows/react-native-windows/) repo.

Hope we will get this feature soon. Excited to build UWP apps in react-native using VS Code.

![image](https://cloud.githubusercontent.com/assets/5305600/20456117/d1899f9e-ae93-11e6-8f1a-f286891e282b.png)
(Screenshot taken from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)

**Comment by sasivarnan** [comment]
@panarasi Any update on this ?

**Comment by leesolway** [comment]
This would be extremely helpful to have.

**Comment by panarasi** [comment]
VSCode now supports "attaching" to the Windows platform. For this workflow, you would now have to select "Attach to packager" in the debug options, and then put the windows react native app into debug mode. VSCode will automatically become the debugger.

**Comment by ncomo11** [comment]
@panarasi Can you please share Launch.json for this as for me I am getting below error:
`windows is not a valid platform`

FYI I am tracking this under separate issue if you have any input please update it:
https://github.com/Microsoft/vscode-react-native/issues/719#issuecomment-395773872
