### ISSUE TITLE
Better error handling / reporting for configuration issues

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode-react-native#279]
## Actual Behavior
1.  If react-native is not installed, the extension does not activate
2.  Running other commands will result in unexpected errors such as complaining of missing `.vscode/*` files because we have not configured the project on activation
## Expected Behavior
1. Attempting to run commands without activating the extension should either ensure that the extension is initialized, or report a message explaining why the extension was not activated.
## Software versions
- React-Native VS Code extension version: 1.5.0

**Comment by vladimir-kotikov** [comment]
Running any "React Native:*" commands or starting debug session now shows an error message w/ explanation why the command has failed, so this probably can be closed.
