### ISSUE TITLE
React Native does not show up in debug environments

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode-react-native#281]
## Actual Behavior
1. Open a react native project folder
2. Try to create a new debug environment
3. React Native does not show up in the list

## Expected Behavior
1. There should be a React Native option

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.4.0
- OS platform and version: Windows 7 64bit
- React Native version: 1.0.0

**Comment by levito** [comment]
Same here. 

After downgrading VSCode to 1.3.1 and deleting ${workspaceRoot}/.vscode, the debug environment will be created and works.

When upgrading VSCode to 1.4.0 afterwards, debugging fails with the error: The configured debug type "reactnative" is not supported.

**Comment by MSLaguana** [comment]
This sounds like the same issue as https://github.com/Microsoft/vscode-react-native/issues/276
Can you try updating your version of vscode to the insider build, as mentioned there?

**Comment by levito** [comment]
Yes, with the insider build it works again. Thanks for the hint, looking forward to the next official VSCode release!

**Comment by panarasi** [comment]
@levito We were not able to repro this. Are you still seeing this issue ?

**Comment by tapir** [comment]
I'm still having this issue. You can repro by having a clean install of 1.4.

**Comment by MSLaguana** [comment]
@tapir: We've tried that and it still seems to only affect some people for some reason.

Can you please try something for us, to try and narrow down possible causes: Go to `C:\Users\<username>\.vscode\extensions\vsmobile.vscode-react-native-0.1.5\` and open the package.json, search for `enableBrekapointsFor` and replace with `enableBreakpointsFor`, then restart vscode and see if that has any impact. Either way, please report back to https://github.com/Microsoft/vscode/issues/10148 and we'll see if we can find out anything more.

**Comment by levito** [comment]
I'm also having this issue.

These are the steps I tried to see if it is/can be resolved:
1. update VSCode Insiders build
2. Fix the typo in the vscode-react-native extension (in `~/.vscode-insiders`)
3. Remove auto-generated directory `.vscode` and `.tsconfig.json` from my project
4. Restarte VSCode Insiders build and open React Native project

Result: there is still no `.vscode/launch.json` being created.

Doing the same with VSCode 1.3.0 will create the `.vscode/launch.json` and debugging works with both iOS Simulator and Android (even with the typo in the vscode-react-native extension).

*My setup:*
* Mac OS X 10.11.5
* VSCode Insiders build 2f2d6502638fa108f8ddbcc5831b38a35d5a1c11 with these extensions:
    - npm Intellisense 0.1.3
    - Path Intellisense 1.0.2
    - Flow language support 0.0.3
    - Color Highlight 1.2.1
    - React Native Tools 0.1.5
    - ReactJS Code Snippets 1.1.1
* Node 5.11.0 with NPM 3.8.6
* flow 0.27.0
* Project: React Native 0.30.0

**Comment by tapir** [comment]
@levito it's fixed on VScode side. For now you can uninstall flow plugin. that's the culprit.

**Comment by levito** [comment]
Yep, that's it. Uninstalling Flow language support makes debugging work again. But unfortunately this also disables flow type checking (VSCode itself only understands vanilla JS and TypeScript when I set `"javascript.validate.enable": true`, and the other available flow extension (vscode-flow 276.1.0) also breaks debugging). So I'll stick with VSCode 1.3.0 for now.

**Comment by girvo** [comment]
Has this bug been fixed? This is a pretty big mark against using Code for React Native, as Flow is pretty integral to it.

**Comment by MSLaguana** [comment]
This should be fixed in the current VSCode build. If it is not, please file an issue on https://github.com/microsoft/vscode
