### ISSUE TITLE
Cannot find runtime 'node' on path error

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode-react-native#284]
## Actual Behavior
1. Run debugger
2. You get `Cannot find runtime 'node' on path` error eventhough node.exe is on path and it works when I try to run it from command line. 

## Expected Behavior
1. Run debugger
2. Debugger starts

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.4.0 and Insider
- OS platform and version: Windows 7 64Bit
- React Native version: 1.0.0

**Comment by MSLaguana** [comment]
At what point does it print that message? If anything is printed to the debugging console, can you please include that here.

Can you also please try creating a simple nodejs project (a hello world will suffice) and verify that you can run that via vscode?

**Comment by tapir** [comment]
A simple node.js application gives the same error as well. I've triple checked that node.exe is on PATH and it works on the command line by simple invoking "node".

**Comment by MSLaguana** [comment]
Sounds like your vscode installation may be broken in some manner. I would suggest that you try reporting the issue at https://github.com/microsoft/vscode

**Comment by tapir** [comment]
I was recommended to put an absolute path to the node.exe within launch.json and indeed it works for a node app. In node apps it's the "runtimeExecutable" property but how can I set it in react-native apps' launch.json?

**Comment by MSLaguana** [comment]
We actually build on top of the node debugger, and so you should be able to specify the same arguments. It will show up with green squiggles since we don't explicitly say that we allow the same arguments, but I believe it should work.

However I also see that in the vscode issue you have found the cause. If that has resolved your issue, then I'll close the issue here as well.

**Comment by tapir** [comment]
It's indeed fixed. Thank you.
