### ISSUE TITLE
Setting custom port for packager results in faulty adb reverse command

### ISSUE THREAD

**Issue by kulmajaba** [Microsoft/vscode-react-native#296]
Setting a custom packager port in settings.json (in this case 8088) results in faulty adb reverse command when using react native run android from command palette.

From react native console:
`######### Executing command: adb -s "*device-code*" reverse tcp:8081 tcp:8088 ##########`

When the command should be:
`######### Executing command: adb -s "*device-code*" reverse tcp:8088 tcp:8088 ##########`

As a result my Android device says it could not connect to development server until I run `adb reverse tcp:8081 tcp:8081` from the command line.

This only occurred after updating to React-Native tools version 0.1.6

### Software versions
- React-Native VS Code extension version: 0.1.6
- VSCode version: 1.4.0
- OS platform and version: Windows 8.1, device: Android 6.0.1
- React Native version: 0.31

**Comment by MSLaguana** [comment]
Can you please explain the problem you have with this a bit more? Are you modifying both the port that the packager runs on and the port that the device expects to communicate with? My thoughts were that if you change the packager to run on another port, such as `8088`, you can leave the device as trying to connect to `localhost:8081` and the port forwarding will connect the device's `localhost:8081` to the dev machine's `localhost:8088`.

**Comment by kulmajaba** [comment]
Thanks for the answer. Yes, previously I've modified both the packager port and set a custom port on the device. This has been the way I've done it until the latest update.

Now that you said it, I left the device to the default port of 8081 and everything worked fine. I still get `Could not connect to BatchedBridge` on initial run of a freshly installed app,  but I think that's not from VSCode React Native. In any case reloading the app fixes that issue.

I guess the original issue was actually just a misunderstanding on my part. Still, I think the behavior of setting a custom port for the packager should be explained in the docs as it might not be clear to everyone (like me).
