### ISSUE TITLE
Unable to set up communication with VSCode react-native extension.

### ISSUE THREAD

**Issue by Cal-L** [Microsoft/vscode-react-native#298]
## Actual Behavior
1. launchReactNative.js does not get generated when opening a React Native project from the root and running Debug iOS/Debug Android shows the error:
![image](https://cloud.githubusercontent.com/assets/10508597/18144315/d51e7b28-6f7a-11e6-910a-fd7d8c590fa8.png)

## Expected Behavior
1. launchReactNative.js should get auto generated and choosing the Debug iOS option should run iOS with the debugger attached.

## Software versions
- React-Native VS Code extension version: 0.1.6
- VSCode version: 1.4.0
- OS platform and version: OSX 10.11.5
- React Native version: 0.32

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
![image](https://cloud.githubusercontent.com/assets/10508597/18144381/39e45424-6f7b-11e6-889e-a839c17658c4.png)

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 
![image](https://cloud.githubusercontent.com/assets/10508597/18144398/5482162c-6f7b-11e6-9384-1ea1632de97a.png)

I've had an earlier project that had the launchReactNative.js file, but the debug console still shows the same "Could not debug" error whenever I try to run Debug iOS.

Related to #99 #152

**Comment by MSLaguana** [comment]
Do you have react-native installed in your project? We try to detect whether you have a react native project by running `react-native -v` as you see in the console there, and it looks like it is failing which we interpret as meaning the project is not a react-native project and so we don't initialize ourselves.

**Comment by Cal-L** [comment]
Yep, I have react-native 0.32 installed and it is listed as a dependency in package.json. In my terminal, lowercase **-v** is not recognized but **react-native -V** does work and displays 0.32.

**Comment by MSLaguana** [comment]
That's strange. When I run the command I get this output:

```
>react-native -v
react-native-cli: 0.1.10
react-native: 0.32.0
```

If I use `react-native -V` then I just get the 0.32.0 like you say. I wonder if this is a mac/windows difference...

**Comment by MSLaguana** [comment]
What version of react-native-cli do you have installed globally?

**Comment by MSLaguana** [comment]
I think that may be the cause actually: Do you have a global installation of `react-native`, or `react-native-cli`? They both create a `react-native` executable, but they behave differently and only `react-native-cli` is intended to be a global install.

**Comment by Cal-L** [comment]
Good catch! It looks like that was the case, I had react-native installed globally. Thank you.
