### ISSUE TITLE
[vscode-react-native] [Error : 0706]  Cannot debug application: Another debugger is already connected to packager. Please close it before trying to debug with VSCode.

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode-react-native#307]
It just sucks

**Comment by MSLaguana** [comment]
Do you have Chrome open displaying the react-native debugging page? Or do you have multiple instances of VSCode running trying to debug things?

Did you start the react-native packager yourself? You could try killing all instances of the react-native packager, close all instances of chrome and VSCode, then try to debug using VSCode.

**Comment by mbraude** [comment]
Hey @neilyoung, I'm sorry this experience isn't better. Unfortunately, Chrome does not allow multiple debuggers to attach to the same browser window.
