### ISSUE TITLE
Debugging typescript react-native apps

### ISSUE THREAD

**Issue by faisalil** [Microsoft/vscode-react-native#310]
Hey, 

Can you guys provide clear instructions on how to debug typescript code in vs-code? As everyone else, I can debug the output js files fine. But when it came to debugging typescript, all what I was able to find is this section: 
https://github.com/Microsoft/vscode-react-native#create-a-babelrc-file-for-reactnative-packager-transformer

I tried to create this .babelsrc file but it doesn't really work. Am I missing some other instructions? 

Faisal

**Comment by faisalil** [comment]
any update on this?

**Comment by ryanjsalva** [comment]
@faisalil see http://reactnative.tools

**Comment by panarasi** [comment]
@faisalil I wanted to close this bug since the instructions on using VSCode with ReactNative is published at http://www.reactnative.tools/tutorials/2016/09/20/reactnative-ts/. 

Please re-open if there are questions.

**Comment by cubabit** [comment]
The link is now dead - is there another place I can see this?

**Comment by ruslan-bikkinin** [comment]
Hi @cubabit If you are using [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer) then debugging should work out-of-the-box. If you are using some custom TS configuration for your project, please, use these [instructions](https://github.com/Microsoft/vscode-react-native/blob/master/doc/debugging.md#debugging-with-typescript-and-haul) to make it work with the extension.
