### ISSUE TITLE
Attach Packager fails the first time

### ISSUE THREAD

**Issue by panarasi** [Microsoft/vscode-react-native#314]
## Actual Behavior
1. Remove any `.vscode` folder from the workspace
2. Start debugging and select the project to use React Native Debugger
3. Select `Attach to packager` as a way to start debugging
4. Debugger fails in `outDir` in `launch.json` does not have a `.vscode\.react` folder
5. Even if I manually change the outDir, the `launchReactNative` script is not yet downloaded. 

## Expected Behavior
1. Debugging should start as is, even if attachDebugger is used the first time.  

When we attachDebugger, that should also download the launchReactNative.js script, just like the other debug options.

**Comment by mbraude** [comment]
@vladimir-kotikov  was not able to repro this issue.
