### ISSUE TITLE
Support debugging app running on iOS device on Windows platform

### ISSUE THREAD

**Issue by compulim** [Microsoft/vscode-react-native#319]
## Background

Currently, it is possible to **develop + debug** React Native app running on iOS device, with Chrome running on Windows and connect over Wi-Fi. However, it is not possible to build RN app and deploy to iOS device, so a Mac is needed to bootstrap the app by building + deploying the solution to iOS device first (which happen very infrequently).

I assume if it works for Android thru Chrome debugger protocol, it should also works for iOS because both share the same debugging protocol.
## Actual Behavior
1. It say `Could not debug. Platform 'ios' is not supported on host platform: win32: Platform 'ios' is not supported on host platform: win32`
## Expected Behavior
1. Able to start the project and debug
## Software versions
- React-Native VS Code extension version: 0.2.0
- VSCode version: 1.6.1
- OS platform and version: Windows 10 (10.0.14393)
- React Native version: 0.31.0
## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
  `[Error] "Could not debug. Platform 'ios' is not supported on host platform: win32: Platform 'ios' is not supported on host platform: win32"`
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

**Comment by MSLaguana** [comment]
Apologies for the delay in responding. This scenario is currently somewhat supported if you make some slight changes to your project:

If you follow the instructions at https://facebook.github.io/react-native/docs/running-on-device.html (or whatever is appropriate for your version of react-native, it seems to be changing recently) to ensure that the device is looking for a packager running on your windows machine, then from vscode you can start the packager from the command palette (`ctrl-p` then `>React Native: Start Packager`) and then run the `Attach to packager` debug configuration to register as a debugger. Then if you shake the device and start debugging it should connect to the packager that vscode started and begin debugging in vscode, with any JS changes you make effecting your app. Any native changes will require recompiling on a mac though, and the final bundling of everything in a release-mode app will also require a mac.

**Comment by MSLaguana** [comment]
I'm going to close this since I believe we already support this scenario. If you have any problems, feel free to reopen.

**Comment by liupeng5843** [comment]
i got the same issue,how to fix it

**Comment by sergey-akhalkov** [comment]
Hi @liupeng5843, thanks for reaching us, could you please create new issue and provide us as much info as possible so we would be able to help you faster?
