### ISSUE TITLE
react-native launch fail after changing app name

### ISSUE THREAD

**Issue by atlanteh** [Microsoft/vscode-react-native#320]
## Actual Behavior 

1. Create new react-native app
2. Build it with vscode
3. Change the app name via Xcode
4. Try building with vscode
5. build succeed.
6. launch fail I get error:

Touch Build/Products/Debug-iphonesimulator/NewMyApp.app
cd /Users/myUser/git/myApp/ios
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/usr/bin/touch -c /Users/myUser/git/myApp/ios/Build/Products/Debug-iphonesimulator/NewMyApp.app
** BUILD SUCCEEDED **

// vscode is trying to install my old app name -->
**Installing build/Build/Products/Debug-iphonesimulator/OldMyApp.app**
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/OldMyApp.app/Info.plist
## Software versions
- React-Native VS Code extension version: 0.2.0
- VSCode version: 1.6.1
- OS platform and version: mac 10.11.6
- React Native version: 0.34.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): Like above.
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): Empty.

**Comment by MSLaguana** [comment]
This will be because we pick the first workspace/project that we find. The simplest fix is to clean up the `ios` folder and remove the older project files.

Potentially we can also allow you to specify the project name and resolve any ambiguity that way.

**Comment by atlanteh** [comment]
I did clean the ios/build folder and it doesn't seem to solve the issue..

**Comment by MSLaguana** [comment]
Oh I think I misread your initial circumstance. Just to be clear: You have a `ios/OldMyApp.xcodeproj` file, which you modified (via xcode) to build a `NewMyApp.app` application, is that correct?

That will break us unless you rename `ios/OldMyApp.xcodeproj` to `ios/NewMyApp.xcodeproj` since we assume the final output is named the same as the xcodeproj. If you rename the xcodeproj, does it work for you?

**Comment by atlanteh** [comment]
I changed what u said and also changed the Scheme name and this solved the issue.
Thx!
