### ISSUE TITLE
Cannot connect adb devices 

### ISSUE THREAD

**Issue by ForteenC** [Microsoft/vscode-react-native#321]
## Actual Behavior
1. failed to connecting  Android phone in VSCode
2. success when run `react-native run-android` in cmd

## Software versions
- React-Native VS Code extension version: 0.2.0
- VSCode version: 1.6.1
- OS platform and version: Windows 10
- React Native version: 0.35.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 

`[Error] "Could not debug. Error while executing command 'adb devices': Command failed: adb devices\n'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n"`
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

`[Error : 0101]  Failed to run the application in Android: Error while executing command 'adb devices': Command failed: adb devices
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���`

**Comment by MSLaguana** [comment]
If you open up a command line and type `adb`, does it find `adb` or does it complain that it is an unknown command?

I'm not sure what those non-printable characters there are, but it seems like we are failing to find `adb` which we use to interact with android. If you ensure that `adb` is added to your `PATH` and that vscode gets that `PATH` then I believe it should work for you.

**Comment by ForteenC** [comment]
@MSLaguana Thanks ,I solved this problem by restart my  computer,it was because the port 8081 been occupied ,and now it's doing well.
