### ISSUE TITLE
IntelliSense for react/react-native not working

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-react-native#322]
_From @Mirodil on October 18, 2016 21:44_
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 14.5.0
- Extensions: EditorConfig.EditorConfig-0.3.3, dbaeumer.vscode-eslint-1.0.8, donjayamanne.python-0.4.2, johnpapa.Angular2-1.0.2, ms-vscode.csharp-1.4.1, msjsdiag.debugger-for-chrome-1.2.2, vsmobile.vscode-react-native-0.2.0, xabikos.JavaScriptSnippets-1.2.0

Steps to Reproduce:
Intelligent for react even with typings not working
1. create project with this tool https://github.com/infinitered/ignite
2. and open vscode install typings

_Copied from original issue: Microsoft/vscode#13966_

**Comment by roblourens** [comment]
Where are you missing intellisense? Can you give a code example?

**Comment by roblourens** [comment]
Are you using the react native extension? Is it a bug on their end? I think they try to get typings automatically somehow.

**Comment by roblourens** [comment]
_From @Mirodil on October 19, 2016 13:7_

I checked again in freshly created sources as described above. if you open any file inside app folder, for instance `app/components/AlertMessage.js` and try to get IntelliSense for react.

**Comment by roblourens** [comment]
I don't think intellisense is supposed to work out of the box in vscode for JS so I'm moving this to react-native.

**Comment by vladimir-kotikov** [comment]
@Mirodil, are you installing typings using tsd/typings/npm or trying to use the typings that are shipped with the extension? If latter, could you please try put [this file](https://github.com/vladimir-kotikov/vscode-react-native/blob/fcac97e97dabfc0908cc7baa33ebc5d3e199561c/ReactTypings/react-native.d.ts) to the root of the project and see if it works for you?

**Comment by Mirodil** [comment]
this file did not help, the project has 2 `typings` folders, in the root and in the `.vscode`. for install typings this commands `typings install dt~react --global --save` and `typings install dt~react-native --global --save` have been used.

**Comment by vladimir-kotikov** [comment]
If intellisense doesn't work even after installing typings using `typings` command then it's probably has nothing to do with the extension - typescript engine should pick these typings automatically so you would get intellisense even without this extension installed.

**Comment by vladimir-kotikov** [comment]
@Mirodil, were you able to get intellisense working? Does it work in your project if you uninstall/disable this extension?

**Comment by Mirodil** [comment]
after update vscode to latest version and installations `typings` it works with or without `react-native`

**Comment by vladimir-kotikov** [comment]
Well, since 0.2.2 it should work even without manual typings installation - we did some changes to install proper typings automatically. I would appreciate if you could confirm that. Thanks in advance.

**Comment by Mirodil** [comment]
yes, it works. the problem is when you import react from lib like this `import React from 'react'` in this case IntelliSense does not show correct suggestions, if you remove this line, it works like a charm.

**Comment by vladimir-kotikov** [comment]
Just for better understanding could you please attach a screenshot or code snippet where you can't see intellisense suggestions?

**Comment by Sameer-Ijaz** [comment]
It's pretty easy to get it up & working again, using this https://www.youtube.com/watch?v=59vqVqIGEe8&feature=youtu.be
