### ISSUE TITLE
Debugger on Android Simulator doesn't stop on breakpoints

### ISSUE THREAD

**Issue by Marco62** [Microsoft/vscode-react-native#331]
## Actual Behavior
1. I have a react native project that I download to an Android Simulator
2. The project has only javascripts file (not .ts)
3. All compile and works fine, but the debugger doesn't stop on setted breakpoints
![breaks](https://cloud.githubusercontent.com/assets/23256721/20001468/8ecfd42a-a27c-11e6-8553-1ae8f169595b.jpg)

2. I have followed the recommended installation procedure, here is my **.babelrc**
![babelrc](https://cloud.githubusercontent.com/assets/23256721/20001133/12ec80de-a27b-11e6-8fa4-17f91461da32.jpg)

and my launch.json:

![launch_json](https://cloud.githubusercontent.com/assets/23256721/20001688/9b5d95d2-a27d-11e6-85a2-577268d9c828.jpg)

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 0.2.1
- VSCode version: 1.6.1 / 1.7.1
- OS platform and version: Windows 7 Professional
- React Native version: 0.36.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
[vscode-react-native] Attaching to running packager at port: 8081
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Executing command: react-native.cmd run-android
(node:1372) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:1372) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
JS server already running.
Running C:\Users\artys\AppData\Local\Android\sdk\/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDebug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-contacts:compileLint
:react-native-contacts:copyReleaseLint UP-TO-DATE
:react-native-contacts:preBuild UP-TO-DATE
:react-native-contacts:preReleaseBuild UP-TO-DATE
:react-native-contacts:checkReleaseManifest
:react-native-contacts:preDebugAndroidTestBuild UP-TO-DATE
:react-native-contacts:preDebugBuild UP-TO-DATE
:react-native-contacts:preDebugUnitTestBuild UP-TO-DATE
:react-native-contacts:preReleaseUnitTestBuild UP-TO-DATE
:react-native-contacts:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-contacts:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-contacts:prepareComFacebookFrescoDrawee061Library UP-TO-DATE
:react-native-contacts:prepareComFacebookFrescoFbcore061Library UP-TO-DATE
:react-native-contacts:prepareComFacebookFrescoFresco061Library UP-TO-DATE
:react-native-contacts:prepareComFacebookFrescoImagepipeline061Library UP-TO-DATE
:react-native-contacts:prepareComFacebookFrescoImagepipelineOkhttp061Library UP-TO-DATE
:react-native-contacts:prepareComFacebookReactReactNative0120Library UP-TO-DATE
:react-native-contacts:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-contacts:prepareReleaseDependencies
:react-native-contacts:compileReleaseAidl UP-TO-DATE
:react-native-contacts:compileReleaseRenderscript UP-TO-DATE
:react-native-contacts:generateReleaseBuildConfig UP-TO-DATE
:react-native-contacts:generateReleaseAssets UP-TO-DATE
:react-native-contacts:mergeReleaseAssets UP-TO-DATE
:react-native-contacts:generateReleaseResValues UP-TO-DATE
:react-native-contacts:generateReleaseResources UP-TO-DATE
:react-native-contacts:mergeReleaseResources UP-TO-DATE
:react-native-contacts:processReleaseManifest UP-TO-DATE
:react-native-contacts:processReleaseResources UP-TO-DATE
:react-native-contacts:generateReleaseSources UP-TO-DATE
:react-native-contacts:processReleaseJavaRes UP-TO-DATE
:react-native-contacts:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-contacts:extractReleaseAnnotations UP-TO-DATE
:react-native-contacts:mergeReleaseProguardFiles UP-TO-DATE
:react-native-contacts:packageReleaseJar UP-TO-DATE
:react-native-contacts:compileReleaseNdk UP-TO-DATE
:react-native-contacts:packageReleaseJniLibs UP-TO-DATE
:react-native-contacts:packageReleaseLocalJar UP-TO-DATE
:react-native-contacts:packageReleaseRenderscript UP-TO-DATE
:react-native-contacts:packageReleaseResources UP-TO-DATE
:react-native-contacts:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0360Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareJoinMeAppReactNativeContactsUnspecifiedLibrary UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'emulator-5554 - 5.1.1'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 25.279 secs
Starting the app on emulator-5554 (C:\Users\artys\AppData\Local\Android\sdk\/platform-tools/adb -s emulator-5554 shell am start -n com.joinmeapp/.MainActivity)...
Starting: Intent { cmp=com.joinmeapp/.MainActivity }

[vscode-react-native] Finished executing: react-native.cmd run-android
[vscode-react-native] Executing command: adb -s emulator-5554 shell am broadcast -a "com.joinmeapp.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Broadcasting: Intent { act=com.joinmeapp.RELOAD_APP_ACTION (has extras) }

Broadcast completed: result=0

[vscode-react-native] Finished executing: adb -s emulator-5554 shell am broadcast -a "com.joinmeapp.RELOAD_APP_ACTION" --ez jsproxy true
node --debug-brk=46516 --nolazy launchReactNative.js 9090 
Debugger listening on 127.0.0.1:46516
[vscode-react-native] Downloaded debuggerWorker.js (Logic to run the React Native app) from the Packager.
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugging session started successfully.
Running application "JoinMeApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, , performance optimizations are OFF
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
Getting exponent dependecy.
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Executing command: react-native.cmd start --port 8081 ##########
(node:8052) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:8052) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Scanning 714 folders for symlinks in c:\Progetti\ReactNative\JoinMeApp\node_modules (50ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   c:\Progetti\ReactNative\JoinMeApp 

[Hot Module Replacement] Server listening on /hot

React packager ready.

######### Packager started. ##########
[2016-11-04 10:08:05] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android"}
[2016-11-04 10:08:39] <START> Initializing Packager
[2016-11-04 10:08:39] <START> Building in-memory fs for JavaScript
[2016-11-04 10:08:40] <END>   Building in-memory fs for JavaScript (124ms)
[2016-11-04 10:08:40] <START> Building Haste Map
[2016-11-04 10:08:40] <END>   Building Haste Map (142ms)
[2016-11-04 10:08:40] <END>   Initializing Packager (350ms)
[2016-11-04 10:08:40] <START> Transforming modules
[2016-11-04 10:08:41] <END>   Transforming modules (883ms)
[2016-11-04 10:08:41] <END>   Requesting bundle: {"url":"/index.android.bundle?platform=android"} (35684ms)
######### The Bundle Cache was prewarmed. ##########
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Progetti\ReactNative\JoinMeApp"
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Progetti\ReactNative\JoinMeApp"
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Progetti\ReactNative\JoinMeApp"
[2016-11-04 10:09:25] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&hot=false&minify=false"}
[2016-11-04 10:09:25] <START> Transforming modules
[2016-11-04 10:09:26] <END>   Transforming modules (574ms)
[2016-11-04 10:09:26] <END>   Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&hot=false&minify=false"} (807ms)
[2016-11-04 10:09:26] <START> Requesting bundle: {"url":"/index.android.map?platform=android&dev=true&hot=false&minify=false"}
[2016-11-04 10:09:26] <END>   Requesting bundle: {"url":"/index.android.map?platform=android&dev=true&hot=false&minify=false"} (14ms)
[2016-11-04 10:09:27] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&hot=false&minify=false"}
[2016-11-04 10:09:27] <END>   Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&hot=false&minify=false"} (53ms)
[2016-11-04 10:09:27] <START> Requesting bundle: {"url":"/index.android.map?platform=android&dev=true&hot=false&minify=false"}
[2016-11-04 10:09:27] <END>   Requesting bundle: {"url":"/index.android.map?platform=android&dev=true&hot=false&minify=false"} (22ms)
[2016-11-04 10:10:22] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android"}
[2016-11-04 10:10:22] <END>   Requesting bundle: {"url":"/index.android.bundle?platform=android"} (26ms)
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

**Comment by mbraude** [comment]
Hi @Marco62 , thanks for reporting this. What version of Node.js are you using?

**Comment by Marco62** [comment]
The problem was in the emulator settings, first I switch it in developer mode (Settings->About phone then hitting 10 times on Build Number):

![emulator_fix_02](https://cloud.githubusercontent.com/assets/23256721/20013219/a7fcd728-a2b2-11e6-8b5f-9758a15210d7.jpg)

Then hit **Ctrl-M** when the app is in foreground for showing development Menu, then chose **Dev Settings** and enable JS minify option:

![emulator_fix](https://cloud.githubusercontent.com/assets/23256721/20014233/6e12a2a0-a2b6-11e6-8846-4d7be746715d.jpg)

After this when I run Debug Android from VS Code the debugger was able to stops on enabled breakpoints

**Comment by mbraude** [comment]
Thanks for the update @Marco62 !
