### ISSUE TITLE
The status keeps in 'installing'.

### ISSUE THREAD

**Issue by Coder-ZJQ** [Microsoft/vscode-react-native#333]
- VSCode Version:1.7.1
- OS Version:10.12.1
- React Native Tools Version:0.2.2

Steps to Reproduce:

1. I have tried to install the 'React Native Tools' extension of version 0.2.2, but the status always keeps in 'installing'.
2. But I tried with other extensions, they could install successfully.
3. Or where can I download the `vsmobile.vscode-react-native-0.2.2.zip` file to copy it to the path of `./.vscode/extensions/`

**Comment by vladimir-kotikov** [comment]
It could be an infrastructure or network issue. I doubt this could be caused by extension itself. @MSLaguana, what do you think?
