### ISSUE TITLE
Maximum stack size exceeded with react-native 0.37

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode-react-native#340]
## Actual Behavior
1.  Try to debug a freshly `react-native init` application using the vscode extension
2. Get an exception complaining that the maximum stack size is exceeded

## Software versions
- React-Native VS Code extension version: 0.2.2
- VSCode version: 1.7.1
- OS platform and version: 
- NodeJS version: 6.6.0
- React Native version: 0.37.0

This happens due to https://github.com/facebook/react-native/blob/master/Libraries/Core/InitializeCore.js#L156 being called repeatedly. It looks like this might actually be a bug in react-native, but for some reason this code path isn't triggered when running outside of vscode.

It looks like it may be to do with our use of `vm.runInContext`, which seems to be trying to clone properties from the global object we pass in, which triggers a lookup on `regeneratorRuntime` and leads to the infinite recursion.

**Comment by mbraude** [comment]
Yes - @vladimir-kotikov / @daserge, can one of you please take a look?

**Comment by vladimir-kotikov** [comment]
I've sent a PR to react-native, @MSLaguana, please take a look

**Comment by isaldin** [comment]
Hi there. Any solution for this issue? (same behavior in webstorm)

**Comment by MSLaguana** [comment]
We are still trying to work out the best way to solve it. The root cause of the issue is a bug in nodejs: Because we (and webstorm) run the react-native application inside a nodejs vm, it's triggering a bug where properties do not get deleted properly which is what leads to the infinite recursion in a getter method.

**Comment by isaldin** [comment]
@MSLaguana thanks for quick response.
i've upgrade nodejs to version 7.1 and downgrade react-native to version 0.36.
and it's work now for me.

**Comment by MSLaguana** [comment]
I believe that only a change to react-native 0.36 should be required, but I haven't yet had a chance to test whether node 7.X has the bug that causes this issue.

**Comment by gharwood** [comment]
Reverting to react-native 0.36 solved this for me for now.

**Comment by thiyaga123** [comment]
@gharwood  How to revert to  react-native 0.36 in Visual studio code (react-native-cli)

**Comment by gharwood** [comment]
@thiyaga123 don't revert visual studio code, install react-native@0.36.0 instead of react-native@0.37.0.

**Comment by thiyaga123** [comment]
ok Thank you @gharwood

**Comment by MSLaguana** [comment]
We've just published an update (0.2.3) which has a workaround for this issue. If you update then you should be able to use react-native 0.37

**Comment by thiyaga123** [comment]
@MSLaguana  I just tried 0.2.3 with react-native 0.37, The problem still persist. Kindly let me know what should be done to fix this bug

**Comment by MSLaguana** [comment]
@thiyaga123 After you updated our extension to 0.2.3 did you make sure to restart vscode? I've double checked that downloading the published version works for me.

What version of node are you running?

**Comment by thiyaga123** [comment]
I have upgraded to Node 6.9.1. And its ok now.

**Comment by vladimir-kotikov** [comment]
Just verified, that debugging app with RN@0.37 in 0.2.3 works perfectly

**Comment by vladimir-kotikov** [comment]
@MSLaguana, can we close this?
