### ISSUE TITLE
Don't download the typings in .vscode/typings folder

### ISSUE THREAD

**Issue by nschurmann** [Microsoft/vscode-react-native#348]
Please don't download automatically this typings. It mess up with my typings configuration. I prefer to have a typings folder filled up manually instead of automatically, i have a lot of errors just at startup like undefined Ref variable, react duplicate identifier, etc.

**Comment by vladimir-kotikov** [comment]
@MSLaguana, perhaps we can make installation of typings an opt-in feature? We can show a prompt asking user whether he wants to install typings or not and introduce an option to disable this feature for current project.

**Comment by MSLaguana** [comment]
@panarasi what are your thoughts?

I feel that it would be better as opt-out, so it provides intellisense automatically via typings by default, but users could add a setting in settings.json to disable the feature if they want fine grained control over typings.

**Comment by ryanjsalva** [comment]
Opt-out seems like the right way to go.

**Comment by panarasi** [comment]
@MSLaguana @vladimir-kotikov does VSCode not automatically download typings ? @nschurmann has a point that if typings are just for intellisense, is there any other way that VSCode can enable that, without adding to the `typings` folder ?

**Comment by vladimir-kotikov** [comment]
> does VSCode not automatically download typings?

I think they have a plans to enable this in future versions, but in VSCode 1.7.1 this feature is disabled

`typings` folder is not a strict requirement for intellisense - we can add this file to any folder inside of the project, but this still would lead to conflicts between typings we add and used-installed ones, at least in typescript-based projects. I can see a few options, how we can avoid these conflicts:

1. add a workspace setting so user can opt-in/opt-out
2. be more interactive when setting up a workspace and ask user whether he/she wants us to install typings or prefer to configure them manually
3. detect presense of `tsconfig/jsconfig.json` and if it present - assume that the workspace/typings already configured

**Comment by MSLaguana** [comment]
This should be fixed in newer versions of vscode by #357
