### ISSUE TITLE
Please add changelog to every release

### ISSUE THREAD

**Issue by forki** [Microsoft/vscode-react-native#350]
The changelog in the VSCode view is empty:

![image](https://cloud.githubusercontent.com/assets/57396/20423601/921d81d6-ad71-11e6-8eb4-f44ed89ad3a6.png)

that's not helpful.

**Comment by MSLaguana** [comment]
I hadn't noticed that vscode had support for `CHANGELOG.md`, we should definitely add that. Thanks for pointing this out!

**Comment by MSLaguana** [comment]
I've added a changelog that should show up in our next release. For now, the current and next release's changes can be viewed at https://github.com/Microsoft/vscode-react-native/blob/master/CHANGELOG.md
