### ISSUE TITLE
VS Code not hitting breakpoints

### ISSUE THREAD

**Issue by bijeebuss** [Microsoft/vscode-react-native#354]
## Actual Behavior
1.  breakpoint is hit in index.ios.js but skipped in imported files

## Expected Behavior
1. Execution should stop when a breakpoint set in render() from the imported index.ios.js is hit

## Software versions
- React-Native VS Code extension version: 0.2.3
- VSCode version: 1.7.1
- OS platform and version: OS X El Capitan 10.11.4
- NodeJS version: 7.1.0
- React Native version: 0.38
- Typescript 2.0.3

This is what my index.ios.js looks like
```
import helloworld from "./build/react/index.ios"
import { AppRegistry } from "react-native"

AppRegistry.registerComponent("helloworld", () => hello world)
```
The build directory is the output of tsc
I used to be able to set breakpoints in tsx or the compiled js files but now neither works.
I'm not sure what dependency change caused it to stop working since I haven't tried setting a breakpoint in a while. Iv been working on server side components.

**Comment by vladimir-kotikov** [comment]
@bijeebuss, does this reproduce for you consistently? Could you please provide an exact repro steps or share a minimal app where this problem reproduces? Do you see any errors/warnings in debug console or packager/device output?

I've just tried to reproduce the issue without any luck. I took [ReactNativeTS](https://github.com/panarasi/ReactNativeTS), updated rect-native and react dependencies to latest versions and compiled it. The debugging in generated project works just fine - debugger stops on breakpoints in both `index.ios.js` and imported component:

![image](https://cloud.githubusercontent.com/assets/3857604/20625678/f03e7ae0-b325-11e6-8a51-b9411d6f8da8.png)
![image](https://cloud.githubusercontent.com/assets/3857604/20625677/f03d794c-b325-11e6-844e-54c61e8b581c.png)

**Comment by bijeebuss** [comment]
@vladimir-kotikov you can close this if you want. I think it has something to do with my setup specifically but I'm not going to have time to look into it any time soon.

**Comment by MSLaguana** [comment]
If you do get a chance to look into it further, please feel free to re-open this issue with more information.
