### ISSUE TITLE
Is it possible to run the android debugger without enabling remote debugging?

### ISSUE THREAD

**Issue by THPubs** [Microsoft/vscode-react-native#358]
Hi, sometimes I turn off remote debugging because it makes the emulator a lot laggy. Is it possible to run the android debugger without enabling remote debugging in the emulator? Currently, whenever we run the debugger, it automatically enables remote debugging.

**Comment by MSLaguana** [comment]
Can you please clarify what you mean?

Do you want to just run your app in the android emulator and not debug it? If so, then currently we don't provide a way to launch-without-debugging, but it's something that we could add. What you can do, however, is disable JS debugging after the app is launched using the developer menu. You need to either trigger a shake, or something like `adb shell input keyevent 82` to bring it up.

**Comment by MSLaguana** [comment]
I'm closing this issue because it isn't clear what you mean. Feel free to reopen with a clarification.
