### ISSUE TITLE
service.AddMvc()

### ISSUE THREAD

**Issue by Ayoubexax** [Microsoft/vscode-react-native#361]
Hi every one , i used Ubuntu and i install all i should do to beginning a project of .NET , but i have this error , and i don't know how to fix it 

![cont](https://cloud.githubusercontent.com/assets/12201966/20945750/53c34d38-bc00-11e6-832b-7a878298fec1.png)

**Comment by MSLaguana** [comment]
What kind of project is this? It doesn't look like a react-native project to me. What are you trying to do?

**Comment by Ayoubexax** [comment]
i'm trying to create a contact Manager by .NET

**Comment by code4aman** [comment]
Hey, @Ayoubexax, looks like u r developing asp.net web app. It is not related to vscode-react-native.
