### ISSUE TITLE
Debugging crashes under some conditions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-react-native#367]
_From @vladimir-kotikov on November 17, 2016 14:12_

We're using this extension in `vscode-react-native` to debug react-native code running inside separate Node process.

We've found that debuggee process sometimes just crashes after hitting some specific breakpoints with error message, that looks like it's coming somewhere from Node core.

```
#
# Fatal error in runtime\runtime-debug.cc, line 1423
# Check failed: args[0]->IsJSObject().
#

==== C stack trace ===============================

    v8::Testing::DeoptimizeAll [0x00007FF78E61D346+1835286]
    v8::Testing::DeoptimizeAll [0x00007FF78E7C9EFD+3591373]
    (No symbol) [0x000001C9699063AB]
```

After some investigation it appeared that the debuggee is actually stops on the breakpoint and reports this event to debugger but right after that, when the extesion tries to request stack, variables, one of these requests causes the crash.

The problem is 100% reproducible using the example at https://github.com/vladimir-kotikov/react_debug_mock/tree/node_v7_crash using the repro steps in README

_Copied from original issue: Microsoft/vscode-node-debug#112_

**Comment by weinand** [comment]
@vladimir-kotikov this is related to Proxy objects: see https://github.com/Microsoft/vscode/issues/12749 
Workaround: use the experimental node debugger `node2`.

**Comment by weinand** [comment]
_From @gmramaswamy on December 16, 2016 11:30_

@weinand Can you please help me understand where to specify this debugger "node2". i am using with vscode-react-native extension and in launch.json type is reactnative. please help.

**Comment by weinand** [comment]
@vladimir-kotikov aha, if your debug type is "reactnative" then you cannot switch to "node2" (and I will move this issue to the vscode-react-native extension).

**Comment by vladimir-kotikov** [comment]
This issue has been fixed by switching to `node2` debugging engine in #390. @MSLaguana, can we close this?
