### ISSUE TITLE
auto complete support for folder aliased by package.json file

### ISSUE THREAD

**Issue by talarari** [Microsoft/vscode-react-native#372]
React native's packager has a nice feature that allows us to add a package.json file including a name field in any folder and that would be that alias for that folder.
so if i have this project structure:
```
/index.js
/src
    /app
      package.json
    /infra
       FetchData.js
       package.json
```

then i can import like this:
```
import fetchData from 'infra/FetchData'
```

the problem is, vscode autocomplete for require paths doesnt support this.
would be awesome if this would be supported since we use these aliases quite a lot to prevent relative path imports like this '../../../'

**Comment by talarari** [comment]
any advice on how to resolve this?

**Comment by MSLaguana** [comment]
We use the typescript language service to provide intellisense / autocomplete by default (and you can also install the flow extension and use flow for intellisense) and I don't think they support this for 'free', but you could explicitly provide typescript typings for the `infra/FetchData` module and then if you reference that elsewhere in your project it should use those typings for autocomplete.

**Comment by vladimir-kotikov** [comment]
As mentioned this is a feature we don't provide - there are a few extensions that provide intellisense for ES5 imports ([Path intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) - also have a ["Mappings"](https://github.com/ChristianKohler/PathIntellisense#mappings) that sounds very similar to what you suggested, [NPM intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense)) , so this request is better to be addressed to them. Closing this

**Comment by talarari** [comment]
path intellisense is close to what i'm suggesting, but not quite.
1. you need to add mappings manually, while the way to do this in react-native is to add a package.json file in the folder with a name property.
2. path intellisense doesn't support go to definition on absolute paths, just autocomplete.

as you said, this is not specifically a react native problem (using webpack with aliases will present the same problem), but it is very common to alias folders with package.json file in react-native, so this can be very helpful for RN developers.

**Comment by talarari** [comment]
this comment provides a great solution:
https://github.com/ChristianKohler/PathIntellisense/issues/58#issuecomment-290050049

**Comment by vladimir-kotikov** [comment]
Great! I'm glad that you found the solution.
