### ISSUE TITLE
.vscode/.react/ not compatible with git because it is not .gitignore-able without runtime error

### ISSUE THREAD

**Issue by RobIsHere** [Microsoft/vscode-react-native#375]
## Actual Behavior
1. VS Code deletes .vscode/.react/** on disconnect debugger
2. VS Code errors: outDir not set in launch configuration (it is set!) on start debugging, if .vscode/.react folder does not exist
3. (1) => Not possible to have a .gitkeep in .vscode/.react because it gets deleted
4. (2) => Not possible to just exclude whole .vscode/.react 
Conclusion => intermediate files of packager are committed to git repo => This Extension is not compatible with git. 

## Expected Behavior
1. It works without bugs :)

## Software versions
- React-Native VS Code extension version: fresh install
- VSCode version: fresh install
- OS platform and version: osx el capitan
- NodeJS version: 6.9.x
- React Native version: fresh install

**Comment by MSLaguana** [comment]
The `.vscode/.react` folder should be created by our extension if we believe the project is a react-native project, and if we don't believe the project is a react-native project then debugging will fail for several other reasons.

One thing that causes us to not believe a project is a react-native project would be if there is no `node_modules/react-native/package.json` at the root of the workspace, and that will be the case if you have just checked out a new repo. Does this still happen for you if you `npm install` before opening the workspace in vscode?

**Comment by MSLaguana** [comment]
It is our intention that you can gitignore the whole `.vscode` folder with no detriment to the project.

**Comment by RobIsHere** [comment]
That's a fast reply :) Thanks!

No, the node_modules/react-native/package.json does exist

The debug works again after i create this subfolder ".react" again. There is nothing else needed.

**Comment by MSLaguana** [comment]
We should be creating the .react folder when our extension activates shortly after you open the workspace, using the code at https://github.com/Microsoft/vscode-react-native/blob/master/src/extension/rn-extension.ts#L73

That code is triggered if we believe it is a react-native project, just after we set up the debugging stub entry point. If you delete `.vscode/launchReactNative.js` and re-open your project, does that get re-created? And if so, is the `.vscode/.react` folder still missing?

**Comment by RobIsHere** [comment]
Ok. You wrote the solution: "when our extension activates shortly after you open the workspace".

You have to close vscode. Kill it on the mac (make sure it is not just backgrounded). Reopen it. Then it works. 

From UX I would expect the folder to be created before use. E.g. when you start the debugger. Maybe documentation can help, too, if that's hard to change?

.vscode/launchReactNative.js deleted or not does not make a difference.

**Comment by MSLaguana** [comment]
Unfortunately I'm not sure we can create the folder as we start the debugger, since I believe the "it doesn't exist" error is happening before it runs our code in the debugger, but that's something worth looking into. Ideally if nothing external is changing the `.vscode` folder then our extension should manage the lifetime of the `.react` folder appropriately and not cause issues, so if you can find a scenario that reliably runs into the issue I'd definitely like to hear it so we can try and improve.

**Comment by panarasi** [comment]
@vladimir-kotikov  - Do we know if there is a way to solve this issue ? I am also removing the enhancement tag since this is not a feature request yet.

**Comment by RobIsHere** [comment]
In my recent project - started 7/2017 - I didn't have an issue anymore. There aren't any intermediate files of packager anymore, that get committed if i don't change.gitignore.

I don't know if this has been solved or solved by changed external circumstances.

For me that's not an issue anymore. So I'm happy if you close. With or without further investigation.

Thanks a lot! The team here is great 👍 and it's the main reason why I'm looking into MS technology with confidence that it helps me again.

**Comment by vladimir-kotikov** [comment]
@panarasi I think we just need to document that the extension uses `.react` directory inside `.vscode` to store intermediate files during debugging and users need to add `.vscode/.react` pattern to their `.gitignore`

 ![image](https://user-images.githubusercontent.com/3857604/28863684-a2d9b9ec-7772-11e7-9527-45a019bc99e5.png)

Notice that we also create `jsconfig.json` automatically which needs to be added to source control

**Comment by vladimir-kotikov** [comment]
@panarasi please take a look at #505

**Comment by vladimir-kotikov** [comment]
@RobIsHere thanks for the king words :)

I think it still _might_ make sense to add `.vscode/.react` to gitignore just to be sure, but generally it should never appear as changed unless you not going to `git commit` something during debug session :)
