### ISSUE TITLE
Move debugger to use CDP as V8 debugging protocol in Node will get deprecated

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-react-native#377]
Node 8.0.0 will [deprecate](https://twitter.com/jasnell/status/816690727988015108) the existing V8 debugging protocol, as it has been replaced with the Chrome Debugging Protocol (CDP). This debugger relies on the V8-based Node debugger for VS Code, which will be deprecated.

This debugger should either switch to https://github.com/Microsoft/vscode-node-debug2 or use the https://github.com/Microsoft/vscode-chrome-debug-core library to implement a React Native specific debugger.

**Comment by vladimir-kotikov** [comment]
Linking other issues, relevant to `node` debugger engine (will be fixed after migrating to `node2`/`chrome` debugger): #334, #356, #367, #368

**Comment by vladimir-kotikov** [comment]
@MSLaguana, can we close this due to #390 has been merged?
