### ISSUE TITLE
View tag JS breaks vscode code formatting

### ISSUE THREAD

**Issue by ggomersall** [Microsoft/vscode-react-native#381]
## Actual Behavior
1. File save on JS files breaks the formatting  :

```
import React, { Component } from "react";
import { View, Text, StyleSheet } from "react-native";

class Footer extends Component {
    render() {
        return ( <
            View / >

        );
    }
}

export default Footer;
```

## Expected Behavior
1. Should be saved as: 
```
import React, { Component } from "react";
import { View, Text, StyleSheet } from "react-native";

class Footer extends Component {
    render() {
        return (
            <View />
        );
    }
}

export default Footer;
```

## Software versions
- React-Native VS Code extension version: 0.2.5
- VSCode version: Version 1.8.1
- OS platform and version: Mac OSX 10.12.2
- NodeJS version: 6.2.0
- React Native version: 0.40.0

**Comment by MSLaguana** [comment]
Can you please clarify: Do you mean that you wrote the code in the second snippet, but when you saved it was converted to the first? Or you wrote the first and expected save to fix the formatting?

**Comment by ggomersall** [comment]
Hello,

I wrote it as the expected behaviour like this:
```
import React, { Component } from "react";
import { View, Text, StyleSheet } from "react-native";

class Footer extends Component {
    render() {
        return (
            <View />
        );
    }
}

export default Footer;
```

But when i saved the file the formatting was like this:
```
import React, { Component } from "react";
import { View, Text, StyleSheet } from "react-native";

class Footer extends Component {
    render() {
        return ( <
            View / >

        );
    }
}

export default Footer;
```

**Comment by y2kbug** [comment]
I suspect that you may have installed  `JS-CSS-HTML Formatter` plug-in effects, try to remove it

**Comment by vladimir-kotikov** [comment]
@ggomersall, `react-native` extension doesn't performa any automatic code formatting - try to look for `JS-CSS-HTML Formatter` (or perhaps any other code formatting extension) in the list of installed extensions, as @y2kbug mentioned, and disable it to see if that solve the problem

**Comment by ggomersall** [comment]
That's exactly what the issue was. I was using `JS-CSS-HTML Formatter` extension, deleted it and now it works fine.
Thanks for the help guys

**Comment by amitdubey8888** [comment]
Thank for help

**Comment by diwakarsingh** [comment]
Thanks for the help.
I was also facing the same issue.

**Comment by a3pelawi** [comment]
It's work.
Thanks for the help. Disabled JS-CSS-HTML Formatter.

**Comment by bschwartz757** [comment]
Interesting... I uninstalled `JS-CSS-HTML Formatter` as suggested above, but was still getting the same behavior (which I've noticed in all the React projects I've opened in the past.) I went through and disabled all the plugins I thought could possibly matter, and it looks like the one that's still causing the issue for me is Beautify (The HookyQR one with over 1.5M downloads....) That's a bit of a pain because disabling it will probably mean none of my other Javascript will be beautified.

**Comment by IonCaza** [comment]
@bschwartz757 have you found an alternative? I'm running into the same issue

**Comment by bschwartz757** [comment]
@IonCaza No, not yet. I haven't experimented much since posting (I don't usually work in React, just doing a tutorial) but after disabling Beautify for that workspace I still seem to get formatting ok. I would guess that's courtesy of editor configs not specific to Beautify. The plugin doesn't seem to remember that I turned it off for that workspace though so if I were to re-open a large file and hit save without remembering to disable it first I'd have to go through and manually fix everything - not exactly an ideal "developer experience" (much as I cringe at using that term.)

**Comment by neetin** [comment]
@bschwartz757 I am having the same issue. Did you find any solution? or any alternative React code formatter that does well.

**Comment by IonCaza** [comment]
No sir, I apologize for the late reply... I ended up giving up on the tech
stack.

**Comment by supersanyam** [comment]
To solve this , search for "JS-CSS-HTML Formatter" and "Beautify" in your visual studio code extensions , if any of them is enabled , disable and uninstall them

**Comment by PolymathWhiz** [comment]
Try searching for prettier or beautify and disable them or any other js code formatter you have installed.

**Comment by SumitShukla007** [comment]
I was using beautify and after uninstalling it solved the problem.

**Comment by kalpeshasuthar** [comment]
> @ggomersall, `react-native` extension doesn't performa any automatic code formatting - try to look for `JS-CSS-HTML Formatter` (or perhaps any other code formatting extension) in the list of installed extensions, as @y2kbug mentioned, and disable it to see if that solve the problem

I was having same issue and solve it using this trick thanks :)

**Comment by Nahi3an** [comment]
> I suspect that you may have installed `JS-CSS-HTML Formatter` plug-in effects, try to remove it or disable it

Thank you  It worked <3

**Comment by mametur** [comment]
thx I had same issue

**Comment by nayakakashjit** [comment]
I did all the steps but could not solve

**Comment by wntdhananjay** [comment]
thanks for helps

**Comment by ahmedsgit** [comment]
uninstall **JS-CSS-HTML Formatter** , **beautify** or any other formatting extension. Use only **Prettier**

**Comment by Nrusingha** [comment]
I follow all the steps but it did not work.
