### ISSUE TITLE
Android variant support

### ISSUE THREAD

**Issue by pcguru** [Microsoft/vscode-react-native#382]
My build.gradle file has multiple variants which have different applicationId overrides. I want to debug a specific variant. I have specified "variant": "foo" in launch.json to try to start that variant as the plugin indicates that could be possible.

## Actual Behavior
1.  The variant is not propagated to runAndroid in node_modules/react-native/local-cli/runAndroid/runAndroid.js
2. The incorrect applicationId is used when trying to start the app/activity.
3. The debugger shuts down when it can't start the activity.

## Expected Behavior
1. applicationId override from variant config should be used.
2. variant should propagate to react-native-local-cli so that it can start the correct applicationId.

## Software versions
- React-Native VS Code extension version: 0.2.5
- VSCode version: 1.8.1
- OS platform and version:  Windows 10 Pro
- NodeJS version: 6.9.2
- React Native version: 0.38.1
- React Native CLI version: 2.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Starting React Native Packager.
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Executing command: react-native.cmd run-android
// console.log in runAndroid.js:28, method runAndroid
// console.log('runAndroid', argv, config, args);
runAndroid [] { getProjectRoots: [Function: getProjectRoots],
  getProjectConfig: [Function: getProjectConfig],
  getDependencyConfig: [Function: getDependencyConfig],
  getAssetRoots: [Function: getAssetRoots],
  getAssetExts: [Function: getAssetExts],
  getBlacklistRE: [Function: getBlacklistRE],
  getTransformModulePath: [Function: getTransformModulePath],
  cwd: 'c:\\projects\\foo\\node_modules\\react-native\\local-cli' } { installDebug: undefined,
  root: '',
  flavor: undefined,
  variant: undefined,
  config: undefined }
```

**Comment by vladimir-kotikov** [comment]
Looks like it was possible in the past to specify `"variant"` in launch configuration, but it's undocumented and, in fact, is not working at all. I'll send a PR to fix this

Also, @MSLaguana, we might consider having a `"reactNativeArgs"` section in launch configuration to allow users to specify any arbitrary args that need to be passed to local-cli/packager. This would also help with other scenarios, like specifying source maps transformer to enable typescript debugging, etc. What do you think?

**Comment by vladimir-kotikov** [comment]
@pcguru, I'm just curious about how are you specifying different app IDs for different build variants. Are you using `applicationIdSuffix` for that? I'm asking because react-native doesn't seem to resolve application id properly and tries to launch app using wrong id

```
Starting the app on 192.168.56.101:5555 (/Users/kotikov.vladimir/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 shell am start -n com.androidmultiplevariants/.MainActivity)...
```

whereas it should be `com.androidmultiplevariants.staging/.MainActivity`

**Comment by pcguru** [comment]
Oh indeed the wrong applicationId is used by
react-native run-android --variant=foo
as well.

Seems like that is being worked on:
https://productpains.com/post/react-native/android-support-varying-application-ids-for-different-build

But there is a difference in that the react-native command at least builds
and installs the correct variant, whereas the vscode plugin always builds
the default config?

Ability to specify more args would be a neat bonus!

Den 19 jan. 2017 15:57 skrev "Vladimir Kotikov" <notifications@github.com>:

**Comment by vladimir-kotikov** [comment]
@pcguru, I made a PR for that (#385). However we're still relying on react-native for running app on device, so in case if build variant adds a suffix to application Id, we won't be able to run app as well. A workaround here is to run app manually and then use "Attach to packager" launch configuration.

**Comment by MSLaguana** [comment]
We've published the version of our extension which has support for variants now, so I'm going to close this issue. If you have further problems, feel free to reopen or create a new issue with relevant details.
