### ISSUE TITLE
Add color name intellisense

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-react-native#387]
From https://github.com/Microsoft/vscode-react-native/issues/379#issuecomment-274783876
> Color name intellisense would be appreciated for any color style (eg borderColor, backgroundColor, etc).
See https://facebook.github.io/react-native/docs/colors.html

**Comment by pierredewilde** [comment]
Well, color names are just an example.

In fact, we expect a complete support of React-Native StyleSheet intellisense. 

For example, for `justifyContent`, we expect a list of all available options:

```
flex-start
center
flex-end
space-around
space-between
```

**Comment by vladimir-kotikov** [comment]
Closing this one as we're not maintaining own RN typings anymore and requests like this are more approriate to be filled against DT repo: [DefinitelyTyped/DefinitelyTyped/issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues)
