### ISSUE TITLE
Cannot get the prompt for enable IntelliSense

### ISSUE THREAD

**Issue by BrooklynaT** [Microsoft/vscode-react-native#389]
I cannot get the prompt `React Native intellisense was successfully configured for this project. Restart to enable it.`
There is .vscode folder in the root of my project.
I have close ( cmd + q ) and restart vscode many times, but the problem is not resolved.
Any idea on what I might be missing to enable it?
Thanks.

## Software versions
- React-Native VS Code extension version: 0.2.5
- VSCode version: 1.8.1
- OS platform and version: macOS Sierra 10.12.2
- NodeJS version: 6.9.2
- React Native version: 0.40.0

**Comment by matrosov-nikita** [comment]
@BrooklynaT, recent VSCode versions are setting up react-native IntelliSense without need to reload VSCode, so you might not see this prompt message. If there are any other problems with getting IntelliSense to work, please let us know.

**Comment by BrooklynaT** [comment]
<img width="359" alt="2017-01-31 09 56 34" src="https://cloud.githubusercontent.com/assets/17695989/22449507/ab8022be-e79b-11e6-8cca-170ceeccf3ce.png">
There isn't 'React' or 'Salsa' words in the Status Bar.
I don't sure if it is normal.
Thank you for your reply.

**Comment by matrosov-nikita** [comment]
@BrooklynaT, do you have `Sublime-Babel-VSCode` extension installed? If so, Javascript (Babel) is just an [alias for javascript](https://github.com/joshpeng/Sublime-Babel-VSCode/blob/15e8ff744b2c3b54ce5d7a1b7fe04b7d2a9776c4/package.json#L23-L36)  - it affects only code appearenace, not IntelliSense.

**Comment by BrooklynaT** [comment]
@matrosov-nikita , I don't have `Sublime-Babel-VSCode` extension installed, but there are `Babel ES6/ES7` and `ESLint` extension.

**Comment by vladimir-kotikov** [comment]
Babel ES6/ES7 (aka vscode-babel) also defines `Javascript (Babel)` as an alias for `javascript` and shouldn't affect intelisense in any way.

**Comment by vladimir-kotikov** [comment]
@BrooklynaT, are you still having any issues with intellisense in your project?

**Comment by vladimir-kotikov** [comment]
Closing this. @BrooklynaT, feel free to reopen if you're still having any issues w/ this
