### ISSUE TITLE
Property "trace" is not allowed in launch.json

### ISSUE THREAD

**Issue by bluntcoder** [Microsoft/vscode-react-native#391]
## Actual Behavior
1. Trying to figure out why my source maps are not working. (Typescript / Node.js command line project)
2. Added "trace": "sm" to my launch.json, configuration named "Launch"
3. Green squiggly line underneath trace saying "Property "trace" is not allowed"

{
    "version": "0.2.0",
    "configurations": [        
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/bin/Main.js",            
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "tsc",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "trace" : "sm"
        }
]}

## Expected Behavior
1. Accepts the parameter.
2. Upon building, I'd love to understand how tracing source maps actually works, cause I've never seen it. :)

## Software versions
- React-Native VS Code extension version: N/A
- VSCode version: 1.9.0
- OS platform and version: Windows 7
- NodeJS version: Node 6.5
- React Native version:  N/A

**Comment by bluntcoder** [comment]
My mistake everyone this bug should be in [vscode](https://github.com/Microsoft/vscode), apologies. Can it be moved?

**Comment by vladimir-kotikov** [comment]
@bluntcoder, we can't "move" issues. You could just close this one and create the same issue in the repo you want.

**Comment by vladimir-kotikov** [comment]
@MSLaguana, could you please close this?
