### ISSUE TITLE
Unhandled error in debugadapter

### ISSUE THREAD

**Issue by hjpsievert** [Microsoft/vscode-react-native#399]
## Actual Behavior
1. When a break point is set prior to start of debugging or when restarting debugger, a warning is issued, but break point(s) work fine; it looks like one warning is issued per breakpoint with identical wording, same as shown in the debug console output below
2. When break points are removed and debugger is restarted, no warning is issued

## Expected Behavior
1. No warning, break points work fine
2. No warning

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version:  1.9.1
- OS platform and version: Microsoft Windows 10 Pro 10.0.14393 Build 14393
- NodeJS version: 6.8.0
- React Native version: 0.41.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

[vscode-react-native] Debugger worker loaded runtime on port 12918
(node:9556) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Set breakpoints request timed out
    at Timeout.setTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:55:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Running application "PDPAppTest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
######### The Bundle Cache was prewarmed. ##########
Starting custom debugger by executing: echo A debugger is not needed:  "d:\PDP Intermediate\Git\PDPAppTest"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\PDP Intermediate\Git\PDPAppTest"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\PDP Intermediate\Git\PDPAppTest"
Bundling `index.android.js`
  Transforming modules  100.0% (651/651), done.
Bundling `index.android.js`
  No module changed.
Bundling `index.android.js`
  No module changed.
Bundling `index.android.js`
  No module changed.
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

no output

**Comment by MSLaguana** [comment]
@vladimir-kotikov do you have any ideas what might be causing this? Looks like the new debug adapter is having trouble setting breakpoints in the child process?

**Comment by MSLaguana** [comment]
I suspect that this is because we restart the child process early on, so the adapter tries to set breakpoints in the process, the process is terminated (and a new one started), and the initial breakpoint function times out.

**Comment by vladimir-kotikov** [comment]
@MSLaguana, that's very possible but I can't confirm this because neither me nor Nikita wasn't able to reproduce this.

Yet we could try to override `setBreakpoints` method in our debug adapter to catch these errors and prevent them from logging to debug console (as in #403). What do you think?
