### ISSUE TITLE
How do I debug the typescript code?

### ISSUE THREAD

**Issue by yahue** [Microsoft/vscode-react-native#405]
I can debug the built js code, in the ts or tsx code set breakpoints, suggesting: Breakpoint ignored because generated code not found (source map problem?)

[my github  repository](https://github.com/yahue/TimeTop)

**Comment by vladimir-kotikov** [comment]
@yahue, there are a couple of threads, where you can find more info about configuring typescript & react-native to be able to debug it in vscode, see #328 and #402. As for your particular case, you just need to add these lines to `tsconfig.json`:
```
"sourceRoot": "src",
"inlineSourceMap": true,
```

to generate _inline_ tsx -> js maps, so react packager would consider them when generating map for bundle (you can find more about this behavior [here](https://github.com/Microsoft/vscode-react-native/issues/328#issuecomment-275660678))

**Comment by vladimir-kotikov** [comment]
Closing this. @yahue, feel free to reopen in case if you're still experiencing any issues w/ debugging typescript
