### ISSUE TITLE
.vscode/.react is not generated

### ISSUE THREAD

**Issue by pvinis** [Microsoft/vscode-react-native#411]
## Actual Behavior
1. open a react native project 
2. no .vscode/.react is generated

## Expected Behavior
1. open a react native project 
2. a .vscode/.react is generated

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.1
- OS platform and version: macos 10.12.3
- Node version: v7.7.1
- Yarn version: v0.21.3
- React Native Cli version:  2.0.1
- React Native version: 0.42.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):

selection not available in the list

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] Unhandled Rejection at: Promise  Object {exception: Object}  reason:  Error: spawn react-native ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
extensionHost.ts:282 [Extension Host] rejected promise not handled within 1 second
shell.ts:426 spawn react-native ENOENT: Error: spawn react-native ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:426(anonymous function) @ shell.ts:383e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by vladimir-kotikov** [comment]
@pvinis, it looks like the issue in your case is that we couldn't spawn `react-native` command - the error in DevTools console is self-explanatory: `reason:  Error: spawn react-native ENOENT`.
Is react-native-cli package is installed globally in your system? What happens when you run `react-native --version` inside of your project folder?

**Comment by pvinis** [comment]
yea i thought of that. i have `react-native-cli` installed globally, and `react-native` in the `package.json` in the folder. if i do `react-native -v` in the terminal of vscode, i get teh versions nicely.

**Comment by vladimir-kotikov** [comment]
Hmm.. I suspect this might have something to do with `PATH` configuration. Could you please execute and post here
1. output of `which react-native` in terminal
2. output of `process.env.PATH` in VSCode dev tools

**Comment by pvinis** [comment]
```
> which react-native
/usr/local/Cellar/node/7.7.1/bin/react-native
```
and thats what `yarn global bin` returns, so thats the correct path i guess.

```
> process.env.PATH
"/Users/pvinis/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/node/7.6.0/bin"
```
hm thats different. how can i refresh it or make sure its always up to date?

**Comment by vladimir-kotikov** [comment]
Is that possible that you have removed node 7.6.0 and installed 7.7.1 while VSCode window was opened? This would explaing why your path has changed and doesn't match one which VSCode has beel launched with. To fix this I guess you could just restart VSCode so it'd pick up new environment.

**Comment by pvinis** [comment]
hm, yes. and i had the old terminal still open, so the path on that one has still the old. and i opened code by `code .` so that caused it. i `source`d my `.zshrc` and launched code again, and it was generated. thank you :)

**Comment by rendomnet** [comment]
Wow my problem with react-native-tools not working for months was fixed by this.
What is difference when you launch vscode with "icon click" and with "code ." command?

**Comment by vladimir-kotikov** [comment]
@rendomnet I believe that the difference is that when you run it from console it inherits all environment variables from that console session and you probaby have your `$PATH` extended somewhere in `.bashrc` or `.bash_profile` to include global node's executable directory (in my case it's `~/.nvm/versions/node/v8.2.1/bin`)

**Comment by rendomnet** [comment]
@vladimir-kotikov so how can I make it read my zsh nvm stuff correctly without launching it from terminal?

**Comment by vladimir-kotikov** [comment]
@rendomnet I can't imagine any easy way. Though you might want to try to modify global path (https://serverfault.com/questions/16355/how-to-set-global-path-on-os-x) but that's IMO is just an overkill
