### ISSUE TITLE
Debug Android on an actual device has unverified breakpoints 

### ISSUE THREAD

**Issue by JonnyLinja** [Microsoft/vscode-react-native#412]
## Actual Behavior
1. When I Debug Android, it successfully runs on my physical Android device and shows the correct Output from various console.logs
2. However, breakpoints are unverified and it does not stop on the breakpoints.

## Expected Behavior
1. When debugging on an Android device, it stops on breakpoints.

## Note
1. Breakpoints work perfectly in the iOS simulator. I have not tested on an Android emulator.
2. I have not tested an iOS device as it was mentioned as experimental.
3. Not sure if it matters, but I do not have launchReactNative.js in my .vscode folder. I do have react-native as a dependency in my package.json located in the root, and react-native exists in my node_modules with its own package.json.
4. I tried the restart mentioned in https://github.com/Microsoft/vscode-react-native/issues/386 to no avail

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.1
- OS platform and version: Mac OS Sierra 10.12.1
- NodeJS version: 6.9.1
- React Native version: 0.35.0 (because some of my dependencies haven't been updated for latest React Native)

**Comment by vladimir-kotikov** [comment]
@JonnyLinja, thanks for reporting. Unfortunately I wasn't able to repro this using simple RN app, so this might depend on your project configuration. To check if this is configuration related issue, could you please try creating an empty react-native project and try debugging it? Also, for further investigation could you please add the following two lines to your "Debug Android" configuration in `launch.json`:
```json
"diagnosticLogging": true,
"verboseDiagnosticLogging": true
```
, run debug session and paste debug console content here (or upload somewhere, as it most probably will be pretty long)

As for missing `launchReactNative.js` - that's ok. Due to some VSCode debug protocol limitations, launch configuration must contain `"program"` property, but react-native debugger doesn't use it anyway.

**Comment by JonnyLinja** [comment]
I created a brand new RN project and added those two lines to my Debug Android configuration. Again, it launches on the device but the bar is blue and not orange, so the breakpoints aren't operating.

Specs:
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.2
- OS platform and version: Mac OS Sierra 10.12.1
- NodeJS version: 6.9.1
- React Native version: 0.39.2 (I can't move to 0.40+ yet)

```
[vscode-react-native] Starting React Native Packager.
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Executing command: react-native run-android
JS server already running.
Running adb -s 006d595750d741ef reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug)...
:app:preBuild
 
UP-TO-DATE
:app:preDebugBuild
 
UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild
 UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
 
UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library
 
UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library
 
UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library
 
UP-TO-DATE
:app:prepareComFacebookReactReactNative0392Library
 
UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library
 
UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library
 
UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl
 
UP-TO-DATE
:app:compileDebugRenderscript
 
UP-TO-DATE
:app:generateDebugBuildConfig
 
UP-TO-DATE
:app:generateDebugAssets
 
UP-TO-DATE
:app:mergeDebugAssets
 
UP-TO-DATE
:app:generateDebugResValues
 
UP-TO-DATE
:app:generateDebugResources
 
UP-TO-DATE
:app:mergeDebugResources
 
UP-TO-DATE
:app:bundleDebugJsAndAssets
 
SKIPPED
:app:processDebugManifest
 
UP-TO-DATE
:app:processDebugResources
 
UP-TO-DATE
:app:generateDebugSources
 UP-TO-DATE
:app:processDebugJavaRes
 
UP-TO-DATE
:app:compileDebugJavaWithJavac
 
UP-TO-DATE
:app:compileDebugNdk
 
UP-TO-DATE
:app:compileDebugSources
 
UP-TO-DATE
:app:preDexDebug
 UP-TO-DATE
:app:dexDebug
 
UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
 
UP-TO-DATE
:app:zipalignDebug
 
UP-TO-DATE
:app:assembleDebug
 
UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Nexus 4 - 5.1.1'
Installed on 1 device.
BUILD SUCCESSFUL
Total time: 31.974 secs
This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Starting the app on 006d595750d741ef (adb -s 006d595750d741ef shell am start -n com.mynewapp/.MainActivity)...
Starting: Intent { cmp=com.mynewapp/.MainActivity }

[vscode-react-native] Finished executing: react-native run-android
[vscode-react-native] Executing command: adb -s "006d595750d741ef" reverse tcp:8081 tcp:8081
[vscode-react-native] 
[vscode-react-native] Finished executing: adb -s "006d595750d741ef" reverse tcp:8081 tcp:8081
[vscode-react-native] Executing command: adb -s 006d595750d741ef shell am broadcast -a "com.mynewapp.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Broadcasting: Intent { act=com.mynewapp.RELOAD_APP_ACTION (has extras) }
Broadcast completed: result=0
[vscode-react-native] Finished executing: adb -s 006d595750d741ef shell am broadcast -a "com.mynewapp.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
```

**Comment by vladimir-kotikov** [comment]
@JonnyLinja, thanks for details. Unfortunately in your case the debugger doesn't even try to connect to your app. Does the app start successfully and has JS debugging enabled in developer menu? Also, could you please check `.vscode/.react` directory after starting debug session to see if there is a `debuggerWorker.js` file is present?

**Comment by vladimir-kotikov** [comment]
@JonnyLinja, is this is still actual? Are you still experiencing the problem?

**Comment by JonnyLinja** [comment]
@vladimir-kotikov Apologies, I missed your previous message.

The app does start successfully when launched from VSCode.
I do not see debuggerWorker.js

I realized that I didn't enable developer mode on the phone, so I did that and tried again to no avail. USB debugging is enabled as well. Is there something else I need to do to enable JS debugging?

**Comment by panarasi** [comment]
@vladimir-kotikov Do we have all the info we need to triage this bug ?

**Comment by vladimir-kotikov** [comment]
@panarasi yes. Unfortunately it was a long time ago and it wasn't clear if this is a bug in extension on some misconfiguration so @JonnyLinja, could you please confirm if you're still seeing this?

**Comment by vladimir-kotikov** [comment]
Okay, closing this as outdated. @JonnyLinja feel free to reopen if it still reproes.
