### ISSUE TITLE
Resolve TravisCI issues

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-react-native#416]
### Actual:
Travis CI currently is failing on valid PRs (see https://github.com/Microsoft/vscode-react-native/pulls). 

### Expected
Travis tests should pass on valid PRs (when tests ran with `gulp test && npm test` are passing locally)

**Comment by vladimir-kotikov** [comment]
@matrosov-nikita, could you take a look please?

**Comment by matrosov-nikita** [comment]
@vladimir-kotikov, I've sent [PR](https://github.com/Microsoft/vscode-react-native/pull/419), could you please review?
