### ISSUE TITLE
I would like to be able to customize the command that starts the app when running the debugger.

### ISSUE THREAD

**Issue by ciceroneves** [Microsoft/vscode-react-native#418]
## Actual Behavior
1. When starting the debugger for a React-Native Android app, the command 'react-native run-android' is ran. However my app has custom flavors (let's say one of them is 'dev').  So the task that I have is 'installDevDebug' and thus it fails to run the app.

## Expected Behavior
1. As a developer I would like to be able to specify parameters to the 'react-native run-android' command. For instance, I would like to be able to run the command 'react-native run-android --variant=devDebug '  when starting the debugger from Visual Studio Code.
2. 

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.2 (1.10.2)
- OS platform and version: macOS Sierra Version: 10.12.3 
- NodeJS version: v7.6.0
- React Native version: 
 --react-native-cli: 2.0.1
 --react-native: 0.41.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Starting React Native Packager.
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Executing command: react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...
FAILURE: Build failed with an exception.
* What went wrong:
Task 'installDebug' not found in root project 'Sesame'. Some candidates are: 'installDevDebug'.
* Try:
Run 
gradlew tasks
 to get a list of available tasks. Run with 
--stacktrace
 option to get the stack trace. Run with --info or 
--debug option to get more log output.
BUILD FAILED
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### Attaching to running React Native packager ##########
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Packager is already running. ##########
(node:43633) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): NotFoundError: Cannot find entry file index.android.js in any of the roots: 
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
None
```

**Comment by vladimir-kotikov** [comment]
Hey @ciceroneves, sorry for late response. It looks like that all you need is to specify `variant` option in your `launch.json` - it would have exactly the same effect as supplying `--variant` parameter to `react-native` command. It's not yet mentioned in README unfortunately, but VSCode autocompletion for 'launch.json' will suggest you that the option exists. See also https://github.com/Microsoft/vscode-react-native/blob/master/package.json#L231-L234 for description.

Please let me know if it doesn't work for you.

**Comment by vladimir-kotikov** [comment]
Closing this. @ciceroneves, feel free to reopen if solution w/ `variant` option in `launch.json` doesn't work for you.

**Comment by ciceroneves** [comment]
Thanks @vladimir-kotikov!
Sorry for the delay as well. That worked fine!
