### ISSUE TITLE
Unable to run command: 'React Native: Run Android' without debugging after configuring debugging

### ISSUE THREAD

**Issue by Firgeis** [Microsoft/vscode-react-native#420]
## Actual Behavior
1. Configure Debugging
2. From command palette run: 'React Native: Run Android'
3. Once the application launches it tries to connect to the remote debugger

## Expected Behavior
1. From command palette run: 'React Native: Run Android'
2. Application runs without connection to external debugger

## Software versions
- React-Native VS Code extension version:  0.3.1
- VSCode version:  1.10.2
- OS platform and version:  Windows 8.1 
- NodeJS version: 7.7.1
- React Native version: 0.42

For performance reasons, I would like to not always run the debugging session when running my react native application. After configuring debugging, when the application launches in the emulator, it always tries to connect to the external (vscode) debugger. 
```

**Comment by matrosov-nikita** [comment]
Hi @Firgeis, thanks for reporting!
Could you please try the following steps:
1) Run your app in debug mode (`Debug Android`) and in dev menu choose `Stop remote JS Debugging`
2) Run `React Native: Run android` from command palette

**Comment by Firgeis** [comment]
Hi @matrosov-nikita , thanks for the response!

This solved my problem.
