### ISSUE TITLE
Create React Native App

### ISSUE THREAD

**Issue by quincycs** [Microsoft/vscode-react-native#421]
https://forums.expo.io/t/about-the-create-react-native-app-crna-category/34

Perhaps using this as an integration point for expo would be a good long term solution?   Not sure just a suggestion. :)

**Comment by axemclion** [comment]
@quincycs I am working on a demo - looks like you can already use VSCode with Exponent !! Will send an update soon.

**Comment by vladimir-kotikov** [comment]
@quincycs, thanks for suggestion! Just to clarify - do you propose to add an ability to bootstrap new RN project from VS Code using CRNA or just to support debugging and other features for CRNA-created projects?

**Comment by axemclion** [comment]
@quincycs I wrote a [blog post and video](http://blog.nparashuram.com/2017/03/debugging-create-react-native-app-with.html) on how you can debug CRNA with VSCode. I spoke to @dikaiosune and he told me that they are introducing a way to add environment variables that control which port the packager runs on. With this, we would be able to attach the VSCode debugging to 8081.

**Comment by axemclion** [comment]
https://github.com/react-community/create-react-native-app/issues/108

**Comment by axemclion** [comment]
I also believe that we do not want a way to bootstrap new CRNA projects using VSCode. I would suggest using CRNA from the command line. Debugging CRNA apps however should be supported.

**Comment by quincycs** [comment]
Thanks guys.  @axemclion looks great.  I'm happy with any path that makes the integration work long term without being brittle.  Obviously exponent / CRNA changes very often.

**Comment by wenzhiwang** [comment]
@axemclion Excellent blog and video. I can successfully remotely debug the code within VS, however, it causes the same issue when I use socket.io. 
https://github.com/react-community/create-react-native-app/issues/133#issuecomment-292050965
Client side code
```javascript

window.navigator.userAgent = "react-native";
const io = require('socket.io-client/dist/socket.io');

// Must specifiy 'jsonp: false' since react native doesn't provide the dom and
// thus wouldn't support creating an iframe/script tag
const socket = io('https://015780b2.ngrok.io', {
  jsonp: false,
  transports: ['websocket'] // you need to explicitly tell it to use websockets
});
`

**Comment by vladimir-kotikov** [comment]
Closing this as debugging CRNA and Expo apps is supported using both RN and Expo packagers. There is also a new version that fixes multiple small issues w/ Expo/CRNA debugging.
