### ISSUE TITLE
[QUESTION] Is it any way to start as sub folder ?

### ISSUE THREAD

**Issue by ButuzGOL** [Microsoft/vscode-react-native#424]
Currently i have 
root folder -> app folder (react native app)
when i run debug it gives me 
```
[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"
```
when i run React Native: Run ios
```
Current workspace is not a React Native project.
```
so is there any setting to setup app root ?

**Comment by daserge** [comment]
See https://github.com/Microsoft/vscode-react-native#customization

```
To specify a subfolder in which the react-native project is located, set react-native-tools.projectRoot. You can use either absolute or relative path here:

{
  "react-native-tools": {
    "projectRoot": "./your/react-native/project"
  }
}
```

**Comment by ButuzGOL** [comment]
thx

**Comment by Jarrio** [comment]
This does not seem to work for me? I've added ```json
    "react-native-tools": {
        "projectRoot": "./bin"
    }
``` to my `settings.json` file and it still says "Current workspace is not a React native project."

**Comment by iTOYS** [comment]
Hi @Jarrio 
Could you please restart your vscode after added setting and then check again?
Thanks!

**Comment by Jarrio** [comment]
I did multiple times

**Comment by iTOYS** [comment]
Ok! @svekl could you please try it?

**Comment by svekl** [comment]
Hi @Jarrio, can you, please, tell, where your `settings.json` is located? You need to put it in `.vscode` folder in your root folder, not subfolder with RN project. I just tried to reproduce, but it seems working fine to me.

**Comment by Jarrio** [comment]
@svekl That is exactly where I have it, is there perhaps a thing I need to setup in my react native project specifically?

![image](https://user-images.githubusercontent.com/748557/31897699-1d0223a8-b80f-11e7-8c26-fc5830ceab6d.png)

simply doing `cd bin` `react-native start` works as expected for me so not sure why this isn't picking up the `react-native--tools` directory

**Comment by Jarrio** [comment]
Not sure why, but I tried to start the packager again just now and it seems to have picked it up fine. Apologies!
