### ISSUE TITLE
Showing timeout error when trying to debug

### ISSUE THREAD

**Issue by cooolan00p** [Microsoft/vscode-react-native#425]
## Actual Behavior
1. 
![screenshot 128](https://cloud.githubusercontent.com/assets/18212873/24075991/fd977dec-0c4c-11e7-917e-403bec36b3d9.png)

2. 

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.10.2
- OS platform and version: Windows 8.1
- NodeJS version: 4.4.3
- React Native version: 0.42.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by matrosov-nikita** [comment]
Hi @cooolan00p, thanks for reporting.
I was able to reproduce this with your node.js version (4.4.3). The thing is, `--inspect` flag is supported since v6.3.0. Could you please try to upgrade node.js version and let us know whether it works for you?

**Comment by cooolan00p** [comment]
yup... that did the trick... thanx
