### ISSUE TITLE
Specify custom entry file for debugger

### ISSUE THREAD

**Issue by jpshelley** [Microsoft/vscode-react-native#432]
## Actual Behavior
1. After running the Android Debugger with a React Native project that has one root index file, it complains that it cannot find the index.android.js file.
2. The debugger doesn't "fail" and it keeps trying to load the wrong file to the device.

## Expected Behavior
1. It finds that I've set the root file to be `index.js` instead of `index.android.js` or `index.ios.js`
2. It should connect to the application and the debugger should work as intended

package.json: `"main": "index.js"`
build.gradle:
```
project.ext.react = [
    entryFile: "index.js",
]
````
MyApplication.java:
```
@Override
protected String getJSMainModuleName() {
   return "index";
}
```

## Software versions
- React-Native VS Code extension version: `0.3.1`
- VSCode version: `1.10.2`
- OS platform and version: macOS `10.12.3`
- NodeJS version: node --version = `v4.1.1`
- React Native version: react-native -version
```
react-native-cli: 2.0.1
react-native: 0.43.0-rc.4
```

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
Not relevant as it reads `BUILD SUCCESSFUL`  

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Starting Packager ##########
######### Executing command: react-native start --port 8081 ##########
Scanning 963 folders for symlinks in /Users/johnshelley/Developer/Hudl/rn-hudl-messaging/node_modules (10ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/johnshelley/Developer/Hudl/rn-hudl-messaging 


React packager ready.

######### Packager started. ##########
Loading dependency graph, done.
error: bundling: NotFoundError: Cannot find entry file index.android.js in any of the roots: ["/Users/johnshelley/Developer/Hudl/rn-hudl-messaging"]
    at DependencyGraph._getAbsolutePath (/Users/johnshelley/Developer/Hudl/rn-hudl-messaging/node_modules/react-native/packager/src/node-haste/index.js:285:11)
    at /Users/johnshelley/Developer/Hudl/rn-hudl-messaging/node_modules/react-native/packager/src/node-haste/index.js:228:28
    at process._tickCallback (node.js:356:9)
Bundling `index.android.js`  0.0% (0/1), failed.
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/johnshelley/Developer/Hudl/rn-hudl-messaging"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/johnshelley/Developer/Hudl/rn-hudl-messaging"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/johnshelley/Developer/Hudl/rn-hudl-messaging"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/johnshelley/Developer/Hudl/rn-hudl-messaging"
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
Don't think this is relevant but can include if needed.

VSCode Error Toast:
`Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:15152).`

**Comment by vladimir-kotikov** [comment]
Sorry for the late response, @jpshelley. I can observe the behaviour you described - the following error
```
######### Packager started. ##########
Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: "Cannot find entry file index.ios.js in any of the roots: [\"/Users/kotikov.vladimir/sandbox/foo\"]"
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/kotikov.vladimir/sandbox/foo"
```
is logged by packager to output channel (the message is a bit different but that's because I have another react-native version installed), however after starting the app is able to fetch proper bundle file and breakpoints in renamed entry files are also working.

What's happening there is that when you start debugging we try to "prewarm" packager by triggering bundle generation ahead of time, just to make next bundle requests perform faster - for this process we just use `index.${platform}.js`as bundle name assuming that entry points for both android and iOS have standard names.

However when debugger attaches to app, the app sends to us proper bundle path/name which we then use for debugging.

That said I don't think that this problem is critical and if you have some serious troubles with debugging then I'd say this is a different issue.

**Comment by vladimir-kotikov** [comment]
In theory we might have an option to specify entry file path for each platform but since this only affects packager "prewarming" and not causing problems with debugging experience I'd say this is a low-priority feature

**Comment by vladimir-kotikov** [comment]
@panarasi thoughts?

**Comment by jpshelley** [comment]
@vladimir-kotikov thanks for the input! I've recently moved away from react-native work for the time being. Feel free to keep this open or close it depending on what Microsoft thinks is best. Good to know it would still work in case others were having the same issue.
