### ISSUE TITLE
iOS debug configuration specifying scheme

### ISSUE THREAD

**Issue by peterp** [Microsoft/vscode-react-native#434]
I've added custom schemes to my Xcode project, I would like to specify the scheme, this is the error I receive when trying to run debug:

```The project named "MyApp" does not contain a scheme named "MyApp". The "-list" option can be used to find the names of the schemes in the project.```

**Comment by galkahana** [comment]
+1

**Comment by gchiacchio** [comment]
+1

**Comment by peterp** [comment]
Howdy folks, I appreciate the `+1` comments here in support, but let's try not to flood the maintainers, use the handy 👍  thumbs-up emoji on the top-right hand corner to show your support!

**Comment by TomSwift** [comment]
I added support for "scheme" in this PR:  https://github.com/Microsoft/vscode-react-native/pull/444
