### ISSUE TITLE
Android Debugging not working

### ISSUE THREAD

**Issue by jt100xu** [Microsoft/vscode-react-native#435]
## Actual Behavior
1. Start Debug Android
2. Could not debug

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.11.1
- OS platform and version: Mac OS 10.12.3
- NodeJS version: v7.8.0
- React Native version: 0.43.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Installing APK 'app-debug.apk' on 'GT-I9100 - 6.0.1' for app:debug
Installed on 1 device.
BUILD SUCCESSFUL
Total time: 29.175 secs
Running /Program-files/android-sdk/platform-tools/adb -s 00094d8e1b442f reverse tcp:8081 tcp:8081
Starting the app on 00094d8e1b442f (/Program-files/android-sdk/platform-tools/adb -s 00094d8e1b442f shell am start -n com.finviet/.MainActivity)...
Starting: Intent { cmp=com.finviet/.MainActivity }
[vscode-react-native] Finished executing: react-native run-android
[Error] "Could not debug. Unexpected string in JSON at position 170"
```

**Comment by terbooter** [comment]
@jt100xu ,
could you try run this project from console using [react-native-cli](https://www.npmjs.com/package/react-native-cli)
```
react-native run-android
```

**Comment by jwtea** [comment]
@jt100xu 
I was having a similar problem after debugging on a physical device. What i did to fix was:
Close vscode
run in terminal `adb forward --remove-all `
reopen vscode and run debug android with the emulator running. Hope this helps

**Comment by vladimir-kotikov** [comment]
Closing as this doesn't sound like a problem with extension
