### ISSUE TITLE
Android Debugger doesn't hit the breakpoints  (Please help !!!! F1 :) )

### ISSUE THREAD

**Issue by sergul** [Microsoft/vscode-react-native#436]
## Actual Behavior
1. breakpoints are not getting hit on app launch (sometimes it hits one or 2 breakpoints but only during app run-time).
2. 

## Expected Behavior
1. hit the breakpoints on app launch (when app starts in android emulator)
2. 

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.11.1
- OS platform and version: Windows 10
- NodeJS version: v6.10.2
- React Native version: react-native-cli: 2.0.1
                                     react-native: 0.43.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugger worker loaded runtime on port 35523
sdfsd
Please debug my code ! 
6
[vscode-react-native] Debugger worker loaded runtime on port 24808
sdfsd
Please debug my code ! 
6
Running application "ReactNativeTest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Error: Set breakpoints request timed out
    at Timeout.setTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:54:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Error: Set breakpoints request timed out
    at Timeout.setTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:54:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### Attaching to running React Native packager ##########
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Packager is already running. ##########
######### The Bundle Cache was prewarmed. ##########
Starting custom debugger by executing: echo A debugger is not needed:  "d:\workspace\ReactNativeVSCode\ReactNativeTest"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\workspace\ReactNativeVSCode\ReactNativeTest"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\workspace\ReactNativeVSCode\ReactNativeTest"
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
empty here
```
As an addition here is my launch.json file content:

{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\start"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858
        }
    ]
}

**Comment by vladimir-kotikov** [comment]
@sergul, I apologise for late response. Could you please let me know if the issue still actual?

**Comment by vladimir-kotikov** [comment]
Closing this. @sergul feel free to reopen if you run into this again
