### ISSUE TITLE
Setup instructions seems broken

### ISSUE THREAD

**Issue by jrmgx** [Microsoft/vscode-react-native#443]
## Actual Behavior
1. I follow the Readme from the extension 
2. Everything seems in place until I reach https://github.com/Microsoft/vscode-react-native#setup-debug-environment
3. *Click the debugging icon Choose React Native debugger in the View bar, and then click the configure gear icon Configure-gear to choose the React Native debug environment.* Clicking on this gear icon does not open a dialog where I can choose "React Native debug environment". It does generate/open a `launch.json` file
4. From here I am lost.

## Expected Behavior
1. I follow the Readme from the extension
2. I arrive to that point https://github.com/Microsoft/vscode-react-native#setup-debug-environment
3. The gear icon opens up a dialog with multiple choices (including React Native)
4. Happy me

## Software versions
- React-Native VS Code extension version: 0.3.2 (last I can get from VCS)
- VSCode version: Version 1.11.2 (1.11.2) (last from the official website)
- OS platform and version: macOS 10.12.4 (last)
- NodeJS version: 6.8.0
- React Native version: 2.0.1

**Comment by Slapbox** [comment]
I don't even see a gear icon... I go to the `Debug` menu from the top menu and choose `Start Debugging` and then choose `React Native` as an attempted workaround and nothing happens.

There is no gear after pressing the debug icon.

Windows 7 - Node 7.9.0, other versions same as above post.

![image](https://cloud.githubusercontent.com/assets/6835891/25568304/ba93a64a-2dcd-11e7-8fb2-5c523110f98d.png)

**Comment by irtemed88** [comment]
@jrmgx You may have already figured out the solution to your problem, but if not, here's what I did to get this working:

Initially I didn't have the Debug options either, but if you open the debug dropdown there should be an "add configuration" option.

![screen shot 2017-05-21 at 9 41 35 pm](https://cloud.githubusercontent.com/assets/630204/26290658/bf2597a2-3e6e-11e7-832c-678e3d3466ef.png)

Clicking that should open `launch.json` with a popover that gives you the option to add the iOS debug config to your `launch.json` file. 

![screen shot 2017-05-21 at 9 41 57 pm](https://cloud.githubusercontent.com/assets/630204/26290665/c9cbd784-3e6e-11e7-9966-8945b2ec6f9a.png)

Selecting the Debug iOS option should add an entry to `launch.json` and then you can select the Debug option from the initial dropdown (like I have pictured above).

**Comment by vladimir-kotikov** [comment]
@irtemed88, thanks for detailed instructions, @jrmgx I hope that helped and closing this. Feel free to reopen if you still have any issues w/ setting up debugging.

**Comment by jrmgx** [comment]
Thank you all for your help
