### ISSUE TITLE
Support VSCODE , React Native 0.44.0 and Typescript  debugging 

### ISSUE THREAD

**Issue by saeedtabrizi** [Microsoft/vscode-react-native#445]
## Actual Behavior
1. VScode must be launch or attach to react native project as a debugger .
2. Officially support for changes 
3. debugger does not working with typescript Sourcemaps .

## Expected Behavior
1. Vscode does not working exactly after upgrade chrome debugger and RN to 0.44.0 .
2. There is no update or fixture and seems to  project is not alive . 
3. Debugging tsx and ts file through the vscode . 

## Software versions
- React-Native VS Code extension version:  0.3.2
- VSCode version: 1.11.2
- OS platform and version:  Ubuntu 16.04
- NodeJS version: 7.9
- React Native version:  0.44.0

## Outputs (Include if relevant)
- [Error] "Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"

**Comment by tslearn** [comment]
Me too,  breakpoints not hit.  OS platform: MacOS 10.12.4

**Comment by roblourens** [comment]
Ping @MSLaguana, @vladimir-kotikov?

**Comment by vladimir-kotikov** [comment]
Just trying to clean up existing issues and looks like this is basically the same as #441 even though react-native version is a bit different. Closing this for now.

**Comment by saeedtabrizi** [comment]
@vladimir-kotikov
 Forever trusting who we are
And nothing else matters .
