### ISSUE TITLE
How to debug with chakra to get time traveling?

### ISSUE THREAD

**Issue by D1no** [Microsoft/vscode-react-native#448]
I tried to have visual study code run vscode-react-native from chakra to get time traveling. However, it seems that the launch configuration for runtimeExecutables are ignored.
```json
            "runtimeExecutable": "/Users/.../node-nightly.../bin/node",
            "runtimeArgs": ["-TTDebug:log", "-TTBreakFirst"]
```

When running the debugWorker manually it leads to an
```bash
/Users/worker/.nvs/chakracore/8.0.0-pre2/x64/bin/node --record .vscode/.react/debuggerWorker.js
Recording is enabled (but not yet started)...
TypeError: Object doesn't support property or method 'send'
   at postMessage (/Users/worker/development/shoplink-app/.vscode/.react/debuggerWorker.js:17:5)
   at Anonymous function (/Users/worker/development/shoplink-app/.vscode/.react/debuggerWorker.js:107:1)
   at Module.prototype._compile (module.js:585:3)
   at Module._extensions[.js] (module.js:595:3)
   at Module.prototype.load (module.js:503:3)
   at tryModuleLoad (module.js:466:5)
   at Module._load (module.js:458:3)
   at Module.runMain (module.js:620:3)
   at run (bootstrap_node.js:447:7)
   at startup (bootstrap_node.js:153:9)
```

Maybe you guys could look into this. Time traveling is one of the most appealing features to switch to visual study code and chakra fro react-native development.

Btw: The idea comes from you guys were Parashuram introduced it on react Conf 2017 (watch the video):
https://youtu.be/iMLpUVZseEg?t=21m39s
![image](https://cloud.githubusercontent.com/assets/2397125/26025734/53bc3574-37ee-11e7-9a24-14978b1c769e.png)

**Comment by D1no** [comment]
Any info/progress on this? I mean, it was proposed on react conf (?)

**Comment by iTOYS** [comment]
http://blog.nparashuram.com/2016/08/time-travel-debugging-with-reactnative.html
https://gist.github.com/axemclion/ee760a748bd6390d0f3540ea0c292caf

**Comment by D1no** [comment]
@iTOYS thanks Artem. I'll take a look when I have some time. In the mean time we decided to simply write less bugs

**Comment by iTOYS** [comment]
Great decision! 😃
