### ISSUE TITLE
Add an option to specify iPad as simulator when execute `Run iOS`?

### ISSUE THREAD

**Issue by hnq90** [Microsoft/vscode-react-native#462]
## Actual Behavior
1. Choose `React Native: Run IOS`
2. iPhone 6 Simulator is opened.

## Expected Behavior
1. Has a setting for specify other simulators device (Same as `--simulator 'iPad Pro 9.7'`
2. Choose `React Native: Run IOS`
3. iPad Pro 9.7 simulator is opened.

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.13.1
- OS platform and version: Mac OS 10.12.5
- NodeJS version: v7.9.0
- React Native version: 0.42.x

**Comment by hnq90** [comment]
Btw, I've just create a patch here for just testing: https://github.com/hnq90/vscode-react-native/tree/feature/add_simulator_name_setting

**Comment by Uby501** [comment]
Did you try with `"target": "iPad Pro 9.7"` in the Run iOS configuration?

**Comment by hnq90** [comment]
@Uby501 Does it work? After read the source code of this extension, I found that it always starts iPhone 6 simulator.

**Comment by Uby501** [comment]
Yes, it works for me. Actually the correct string is "iPad Pro (9.7 inch)" for my simulator, but still, it works.
I'm on version 0.3.2

**Comment by hnq90** [comment]
@Uby501 There's no `Run iOS` configuration. I only see `Debug iOS`.

**Comment by Uby501** [comment]
That's just a label, the iOS configuration is working fine for me, it switch simulator based on the parameter I set.

**Comment by vladimir-kotikov** [comment]
@Uby501 @hnq90 I think there is a little bit of confusion there - it's possible to point debugger to use specific target device, however it's currently not possible if you invoke 'React-native: Run ios" command from command palette. Those 2 things use completely different code paths and @hnq90's PR is about the second option, while @Uby501 is talking about the first one, I guess

**Comment by Uby501** [comment]
My bad, I just noticed that @hnq90 was referring to `React Native: Run iOS`

**Comment by hnq90** [comment]
@vladimir-kotikov Yes, thank you for explanation.

**Comment by vladimir-kotikov** [comment]
Implemented in #512, closing
