### ISSUE TITLE
File Locking Issues

### ISSUE THREAD

**Issue by danderson00** [Microsoft/vscode-react-native#466]
## Actual Behavior
1. Run app in VS Code
2. Stop app
3. Attempt to install new npm module
4. Installation fails due to inability to delete staging file

A similar file locking issue is sometimes also present when attempting to clean the Android native project by running `gradlew clean`, though this is usually resolved by rerunning the operation.

## Expected Behavior
No file locking errors!

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.13.1
- OS platform and version: Windows 10 Pro Version 1607 (OS Build 14393.1358)
- NodeJS version: 6.9.2
- React Native version: 0.45.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
N/A
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
N/A
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
C:\Projects\picturemyhistory\mobile [mobile ≡ +1 ~10 -0 !]> npm install react-native-svg --save
npm WARN enoent ENOENT: no such file or directory, open 'C:\Projects\picturemyhistory\mobile\node_modules\stream\package.json'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-svg" "--save"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! path C:\Projects\picturemyhistory\mobile\node_modules\.staging\color-string-3ea664bd
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\picturemyhistory\mobile\node_modules\.staging\color-string-3ea664bd' -> 'C:\Projects\picturemyhistory\mobile\node_modul
es\color-string'
npm ERR!     at destStatted (C:\Users\Dale\AppData\Roaming\nvm\v6.9.2\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Users\Dale\AppData\Roaming\nvm\v6.9.2\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\picturemyhistory\mobile\node_modules\.staging\color-string-3ea664bd' -> 'C:\Projects\picturemyhistory\mobile\node_modul
es\color-string'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Projects\picturemyhistory\mobile\node_modules\.staging\color-string-3ea664bd' -> 'C:\Projects\picturemyhistory\mobile\node_mo
dules\color-string'
npm ERR!     at destStatted (C:\Users\Dale\AppData\Roaming\nvm\v6.9.2\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Users\Dale\AppData\Roaming\nvm\v6.9.2\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\picturemyhistory\mobile\node_modules\.staging\color-string-3ea664bd' -> 'C:\Projects\picturemyhistory\mobile\node_modul
es\color-string'
npm ERR!     at Error (native) parent: 'picturemyhistory' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\picturemyhistory\mobile\npm-debug.log
```

**Comment by vladimir-kotikov** [comment]
@danderson00, thanks for reporting. However ths this doesn't sound like an issue with extension itself - looks like this is known issue with VSCode itself, see https://github.com/Microsoft/vscode/issues/29204 and https://github.com/Microsoft/vscode/issues/28593. Looks like the problem was fixed in 1.14 so upgrading VSCode should help

**Comment by vladimir-kotikov** [comment]
@danderson00 closing this. If you're still having this problem and feel that this is a problem with extension - please reopen

**Comment by einarpersson** [comment]
This appears to still be a problem for me in **VSCode 1.14.2**.

1. Tried installing ava "npm install ava --save dev" in Integrated Terminal (Powershell), but failed

`2229 verbose unlock done using C:\Users\Einar\AppData\Roaming\npm-cache\_locks\staging-74d71e8b8f4dd1a0.lock for D:\Projects\cranford\node_modules\.staging
2230 verbose stack Error: EPERM: operation not permitted, scandir 'D:\Projects\cranford\node_modules\fsevents\node_modules\getpass\node_modules'
2231 verbose cwd D:\Projects\cranford
2232 verbose Windows_NT 6.1.7601
2233 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "ava"
2234 verbose node v8.2.0
2235 verbose npm  v5.3.0
2236 error path D:\Projects\cranford\node_modules\fsevents\node_modules\getpass\node_modules
2237 error code EPERM
2238 error errno -4048
2239 error syscall scandir
2240 error Error: EPERM: operation not permitted, scandir 'D:\Projects\cranford\node_modules\fsevents\node_modules\getpass\node_modules'
2240 error  { Error: EPERM: operation not permitted, scandir 'D:\Projects\cranford\node_modules\fsevents\node_modules\getpass\node_modules'
2240 error   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\Projects\\cranford\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
2240 error   errno: -4048,
2240 error   code: 'EPERM',
2240 error   syscall: 'scandir',
2240 error   path: 'D:\\Projects\\cranford\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
2241 error Please try running this command again as root/Administrator.
2242 verbose exit [ -4048, true ]
`


2.  Opened up Powershell as administrator in a second terminal (outside VSCode) but got the same error.

3. Finally, closed VSCode and tried again in the separate Powershell window - and this time it worked!
