### ISSUE TITLE
Debugging with Typescript and Haul

### ISSUE THREAD

**Issue by EamonnLaffey** [Microsoft/vscode-react-native#469]
In order to try and get debugging with React Native Tools and Typescript I have set up Haul. When using the launch configuration to "attach to packager" and setting to "debug JS remotely", the phone screen becomes white and breakpoints within vscode are marked as unverified due to potential source map issue.

However, I can use the the chrome dev tools to view and debug tsx source (under webpack://./src).

I have created an example to show this here: [https://github.com/EamonnLaffey/tshaulreactnative](https://github.com/EamonnLaffey/tshaulreactnative)

**Comment by vladimir-kotikov** [comment]
@EamonnLaffey this has been addressed in #482. The fix would likely be available in next extension release but you can try build and link it to your extensions folder manually to verify if it works.

**Comment by foobar8675** [comment]
@vladimir-kotikov do you know if the next extension release has happened yet - or can you point me to the docs for how to track extension releases?

**Comment by vladimir-kotikov** [comment]
@foobar8675 the answer is depends on which version of extension you have :) The actual version is 0.4.2 which has been published about 3 weeks ago. To track releases you can use [this repo releases page](https://github.com/Microsoft/vscode-react-native/releases) or refer to [changelog](https://github.com/Microsoft/vscode-react-native/blob/master/CHANGELOG.md)

**Comment by foobar8675** [comment]
thank you @vladimir-kotikov
