### ISSUE TITLE
After updating code to the July update (1.14.0) packager keeps restarting 

### ISSUE THREAD

**Issue by zeflash** [Microsoft/vscode-react-native#470]
## Actual Behavior
1. When reloading in the simulator, or saving a file in the project, it seems the packager is killed and restarted. That triggers a rebuild of the binary, a restart of the IOS app. Clearly not good!
2. 

## Expected Behavior
1. For the packager to keep running I guess? 
2. 

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.14.0
- OS platform and version: OSX Sierra 10.12.5
- NodeJS version: 8.1.3
- React Native version: 0.44.0

**Comment by iainroyle** [comment]
Confirmed. Same platform except on Windows 10.

**Comment by vladimir-kotikov** [comment]
Closing this one in favor of #471
