### ISSUE TITLE
[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-react-native#475]
_From @myGitHubLxd on July 15, 2017 3:15_

[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"

- VSCode Version:版本 1.14.1 (1.14.1)
- OS Version:macOS 10.12.5 (16F73)
我已经安装了npm,并且用命令可以跑起来，Xcode也可以跑起来，就是VScode起不来。
Steps to Reproduce:

1.Open my project.
2.click run.

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#30745_

**Comment by vladimir-kotikov** [comment]
@myGitHubLxd what `react-native -v` says in your project's directory?

Also from our experience this issue very often caused by some environment issues - see #365

**Comment by vladimir-kotikov** [comment]
@myGitHubLxd, any news? Are you still experiencing any issues with that?

**Comment by vladimir-kotikov** [comment]
Closing this due to lack of response. @myGitHubLxd, if you're still experiencing this, feel free to reopen.

Thanks
