### ISSUE TITLE
It's not a bug report, it's a question: Where is the new release?

### ISSUE THREAD

**Issue by adyanced** [Microsoft/vscode-react-native#479]
Guys reported a bug, vscode-rn can't work with vscode v1.14.1. I know you have closed the issue 6 days ago, but WHERE IS THE NEW RELEASE ? Or how can I patch the code before you issue a new release?
Thx

**Comment by vladimir-kotikov** [comment]
@adyanced please be patient :) We plan to release it soon. In the meantime if you want to test unreleased version you can take a look at this https://github.com/Microsoft/vscode-react-native/pull/472#issuecomment-315054799
