### ISSUE TITLE
Incorrect source-map work when VS Code and sources located on different disk(Windows)

### ISSUE THREAD

**Issue by iTOYS** [Microsoft/vscode-react-native#492]
## Actual Behavior
Breakpoints in TS code don't work if VS Code and sources located on different disk

## Expected Behavior
Breakpoints work correct

**Comment by iTOYS** [comment]
Problem with our dependencies https://github.com/lydell/source-map-resolve/issues/9

**Comment by lydell** [comment]
Is the source-map-resolve package helpful to you? I'm not sure that source-map-resolve is a good abstraction anymore. If it is to you we can try to fix things. Otherwise it might be worth having source-map-resolve as a reference while implementing something on your own.

**Comment by vladimir-kotikov** [comment]
Fixed in #493

Thanks for suggestion, Simon (@lydell) - we'll definitely look at rewriting sourcemaps resolution logic to not depend on external components, but in the meantime this patch should unblock Windows users experiencing the issue.
