### ISSUE TITLE
Updated directions to connect to Expo debugger?

### ISSUE THREAD

**Issue by GollyJer** [Microsoft/vscode-react-native#496]
Hi.  I'm unable to get debugging working with Expo.  It's been a while since the original direction in the Read Me were written.  Is there a different process now?

Thanks!

**Comment by vladimir-kotikov** [comment]
@GollyJer thanks for reporting. In the latest version we improved Expo support and with that version  no any specific actions to debug Expo or CRNA apps required. Could you please upgrade and describe in details what kind of issues you're experiencing?

**Comment by GollyJer** [comment]
Hi @vladimir-kotikov.  I have my React Native app running via teh Expo XDE.  The code is open in vscode.  In vscode I go to the DEBUG window and select "Debug in Exponent" and get the following error in the debug console.

`[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"`

**Comment by zimmed** [comment]
I'm having the same issue.

**Comment by vladimir-kotikov** [comment]
@GollyJer, this message usually means that the extension wasn't able to activate. Most of the times this happens due to react-native not installed globally (even though this is an Expo project we still require react-native-cli to be installed on machine).

Could you please check if `react-native-cli` is installed and post here output of `react-native -v` inside of your ptoject

**Comment by vladimir-kotikov** [comment]
@GollyJer, @zimmed guys could you please confirm that `react-native-cli` is installed globally and let me know about result of `react-native -v` inside your app?

**Comment by vladimir-kotikov** [comment]
@GollyJer, @zimmed, guys, if you're still seeing the issue - please confirm that `react-native-cli` is installed globally and `react-native -v` inside of your app prints correct version.

**Comment by vladimir-kotikov** [comment]
@GollyJer Thanks 👍

**Comment by GollyJer** [comment]
Hi @vladimir-kotikov.  Just wanted to follow up and let you know I got this working great with Expo.
Installing react-native packager globally did the trick.

**react-native -v**
```
react-native-cli: 2.0.1
react-native: 0.46.1
```

**Comment by GollyJer** [comment]
"working great" may have been an overstatement. 😛 
It starts, and I'm able to debug, but working with it today I often get a debug adapter error and have to restart vscode and my app in Expo.
![image](https://user-images.githubusercontent.com/689204/29257949-db60921c-8083-11e7-81ce-1692b098f42b.png)

**Comment by vladimir-kotikov** [comment]
@GollyJer thanks for confirmation. This seems to be another issue and original problem with unability to debug Expo app is resolved, so I'm going to close this and create a separate ticket. Could you please take a look at #511 and help me to file missing details?
