### ISSUE TITLE
extension crashes when minify=false on large source map

### ISSUE THREAD

**Issue by boguscoder** [Microsoft/vscode-react-native#498]
## Actual Behavior
1. attach to react-packager 
2. start debugging project of substantial size (index.android.map is 39 MB)
3. Wait for several minutes until Code Helper instances bloat to ~ 2 GB (with largest being 1.5 GB) and crash 

Note that there was plenty of free RAM left but probably VSCode failed to allocate big chunk due to fragmentation or 32bitness...

## Expected Behavior
1. No crash
2. Correct ts debugging experience (with minify=true breakpoints are working but variables are all messed up obviously)

## Software versions
- React-Native VS Code extension version: 0.4.0 (and latest local master build too)
- VSCode version: 1.14.2
- OS platform and version: OS X 10.12.6
- NodeJS version: 7.5.0.
- React Native version: 0.42.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Debugger ready. Enable remote debugging in app.
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugger worker loaded runtime on port 27471
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### [Internal] [Info] Extension messaging server started at /tmp/vscode-reactnative-564e0706e4ae67c5e97f9f6afbf8eec873e9f8f8e6e293e3ab07e507da8ac870.sock. ##########
######### [Internal] [Info] Handling message: GET_PACKAGER_PORT ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:125
```

If you can provide any pointers Im ready to debug it personally

**Comment by vladimir-kotikov** [comment]
@boguscoder thanks for reporting. Unfortunately we've never tested this scenario and perhaps it would take some time to craft a repro case unless you don't have an example (maybe some OSS project written in react-native) which we could use.

Another point is that not only this extension is involved in dealing with source maps - there are vscode-node2-debug and vscode-chrome-debug-core behind the scenes that might also be causing such aggressive memory consumption

Anyway this need an additional investigation and I'll let you know once we have any results here.

**Comment by vladimir-kotikov** [comment]
@boguscoder I tried to repro this with relatively large app (https://github.com/infinitered/ChainReactApp, map size for unminified source ~12 Mb) without any luck.

Bundle load/reload time was quite long but I didn't notice any uncommon resources consumption (one of vscode processes has caused CPU load about ~100% though it then decreased to normal values).

Memory consumption stayed stable during both bundle load and regular debugging. Here is a pic of how memory load was looking in my case

![image](https://user-images.githubusercontent.com/3857604/29273248-4741c626-810c-11e7-967a-98fa2a780624.png)

Any other ideas about reproducing this would be really appreciated

**Comment by sergey-akhalkov** [comment]
Hi @boguscoder, I'm closing this for now, please feel free to reopen or create new one if you have any updates.
