### ISSUE TITLE
[Error : 0105]  Failed to run the application in iOS

### ISSUE THREAD

**Issue by syq7970** [Microsoft/vscode-react-native#500]
## Actual Behavior
1. vscode output `[Error : 0105]  Failed to run the application in iOS: Cannot read property 'Symbol(Symbol.iterator)' of undefined` when I excute the command `React Native: Run iOS`

## Expected Behavior
1. The `React Native: Run iOS` command should be excute correctly

## Software versions
- React-Native VS Code extension version: 0.4.0
- VSCode version: 1.14.2 
- OS platform and version: OS X 10.12.6
- NodeJS version: v8.2.1
- React Native version: 0.44.3

Otherwise, `React Native: Run Android` command works well, and I tried excute `react-native run-ios` in terminal, it works well too. so what should I do to fix this?

**Comment by ddthuan87** [comment]
today, i'm got a same problem =((

**Comment by vladimir-kotikov** [comment]
@syq7970 thanks for reporting. I confirm that I'm seeing the same. We'll investigate and let you know if any workaroung is available
