### ISSUE TITLE
"Debug Android" hang up during start up the mobile application

### ISSUE THREAD

**Issue by bgiavotto** [Microsoft/vscode-react-native#501]
## Actual Behavior
1. Create a simple react native application (no expo)
2. After creation is done, start Visual Studio Code, select the Application Folder Name, then choose "Debug Android" from the launch configurations
3. the build process starts up
4. after the deploy is done, the main android activity is showed on mobile emulator then it hang up, while connecting to the debugger.

## Expected Behavior
1. application should start and connect to the debugger.

## Software versions
- React-Native VS Code extension version: 0.4.0
- VSCode version: 1.14.2, Commit cb82febafda0c8c199b9201ad274e25d9a76874e, Date 2017-07-19T23:34:09.706Z , Shell 1.6.6 , Renderer 56.0.2924.87

- OS platform and version: Win7 Ent
- NodeJS version: Node 7.4.0
- React Native version: 0.46

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

PASTE OUTPUT HERE

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):

[vscode-react-native] Broadcasting: Intent { act=com.myapp.RELOAD_APP_ACTION (has extras) }
Broadcast completed: result=0
[vscode-react-native] Finished executing: adb -s emulator-5554 shell am broadcast -a "com.myapp.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
**[vscode-react-native] Debugger worker loaded runtime on port 41462
[vscode-react-native] Debugger worker loaded runtime on port 9096**

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

PASTE OUTPUT HERE

Please note that when started, there are TWO lines saying "debugger worker loaded run time". Is does appear that this process is happening twice. I think only one line should be in the log.

Effectively, if i brutally kill the hanged up app, then i restart using the android launcher i see only one line in the log instead of two, and the debugger works fine.

**Comment by bgiavotto** [comment]
I think it is related to a react native bug. similar behaviour also happen without using VSCode. 
When the chrome debugger is attached, doing a reload of the app causes the hangup.
I think should be reported to the react-native team, because as it is now, debugging is ineffective

**Comment by bgiavotto** [comment]
I think it is related to a react native bug. similar behaviour also happen without using VSCode. 
When the chrome debugger is attached, doing a reload of the app causes the hangup.
I think should be reported to the react-native team, because as it is now, debugging is ineffective

**Comment by vladimir-kotikov** [comment]
@bgiavotto thanks for update. Actually we also observe the same issue on WIndows and came to the same conclusion. Interesting fact is that I can observe this on Windows but on Mac debugging works smoothly.

Unfortunately I can't propose any workaroung for now. In the meantime I'm going to look into RN Android native code to try to find where the problem might come from.

**Comment by bgiavotto** [comment]
Hi, did you opened an issue for the problem in react-native support?

**Comment by vladimir-kotikov** [comment]
Hi @bgiavotto, not yet unfortunately. I plan to investigate this first to find out the real reason as looking at similar react-native issues (including one that you have created) no body have an idea what's happening and why debugging stuck.

**Comment by vladimir-kotikov** [comment]
Upd. There is also a PR that mentions the same problem - https://github.com/facebook/react-native/pull/13116 - however i'm hot sure if it would fix the issue
