### ISSUE TITLE
Debug adapter error while debugging Expo app

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-react-native#511]
## Actual Behavior
From #496 
> I often get a debug adapter error and have to restart vscode and my app in Expo.
> ![image](https://user-images.githubusercontent.com/689204/29257949-db60921c-8083-11e7-81ce-1692b098f42b.png)

## Expected Behavior
1. No crashes :)

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 0.46.1 (CLI 2.0.1)

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by iTOYS** [comment]
Fixed in https://github.com/Microsoft/vscode-react-native/commit/5c8365a68f95fcc6792e2d26a4303d8c5fc7dc23#diff-ccd5d2e3d6201ee161bc408336a8bfb7R117

**Comment by vladimir-kotikov** [comment]
Okay, closing this as it has been already fixed #507 and will be available in next release

**Comment by GollyJer** [comment]
@vladimir-kotikov Are you guys close to the next release?  I'm anxious for the fix. 😃

**Comment by vladimir-kotikov** [comment]
@GollyJer, sorry for late response - yes, we plan to release new version this week. Stay tuned :)

**Comment by vladimir-kotikov** [comment]
@GollyJer, just published a new version - please try it out ;-)
