### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5052).

### ISSUE THREAD

**Issue by JohannBlake** [Microsoft/vscode-react-native#518]
I use to be able to debug my Electron app's main process. Now after an update of VS Code, I get the error:

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5052).`

My configuration has these settings:

```
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "/usr/local/bin/electron",
            "program": "${workspaceRoot}/main.js",
            "webRoot": "${workspaceRoot}"
```
I am able to run my Electron app by starting it with:

`npm start`

when I execute this command from a terminal in the project's root directory. I am using the latest version of VS Code (1.15.1)

**Comment by vladimir-kotikov** [comment]
@JohannBlake could you please elaborate how is this connected to this extension? Looking at your debug configuration this seems to be more related to node debugger from VSCode.

**Comment by JohannBlake** [comment]
Oops. Posted to wrong forum. Can't seem to delete it. No delete button.

**Comment by vladimir-kotikov** [comment]
Nevermind, I'll close it
