### ISSUE TITLE
Attach to packager: remoteRoot

### ISSUE THREAD

**Issue by alexisbg** [Microsoft/vscode-react-native#525]
Hi,

In "Attach to packager" debugging configuration, is it possible to define a remoteRoot property like Node.js attach configuration ?

My workstation runs on Windows and therefore also VSCode and Android Emulator.  But I prefer to work and run my command lines (Bash power...) from my headless Linux VM.

**Comment by vladimir-kotikov** [comment]
Hello @alexisbg. Just to clarify - are you describing the scenario when packager runs on your Linux VM whether VSCode and Android app (in emulator) on local Windows machine?

**Comment by alexisbg** [comment]
Yes exactly

**Comment by vladimir-kotikov** [comment]
Unfortunately I don't hink we currently support this scenario, however in theory this might work if we add a way to configure packager host to connect debugger to. Remote root property in that case would be required to properly map remote sources to local, e.g. for setting breakpoints and other debugger features.

@jwargo, what do you think?

**Comment by vladimir-kotikov** [comment]
Adding this to our backlog
