### ISSUE TITLE
Plugin doesn't use custom port number setting

### ISSUE THREAD

**Issue by kulmajaba** [Microsoft/vscode-react-native#534]
## Actual Behavior
When starting the packager via the command palette `Run Android` or `Start Packager` React Native Tools tries to use port 8081 for the packager even when you have defined a custom port in either user or workspace settings:
```json
"react-native": {
    "packager" : {
        "port": 8088
    }
}
```

## Expected Behavior
React Native Tools should honor the custom port.

## Software versions
- React-Native VS Code extension version: 0.4.1
- VSCode version: 1.16.0
- OS platform and version: Windows 8.1
- NodeJS version: 6.9.1
- React Native version: 0.48.3

**Comment by vladimir-kotikov** [comment]
@kulmajaba Thanks for reporting, we already looking into this

**Comment by callagga** [comment]
I've an issue trying to get custom port porting.  so is the way forward:
a) await React Native Tool v0.4.3 to be release
b) then put the above-mentioned config into FILE - PREFERENCES - SETTINGS (i.e. user settings)?   i.e. no need to touch launch.json? 

Any idea when React Native Tool v0.4.3 will be released?

**Comment by iTOYS** [comment]
Hi @callagga 
a) Yes.
b) Go to FILE - PREFERENCES - SETTINGS, then select "Workspace Settings" in dropdown menu(or create settings.json file in ".vscode/" folder) and then add above-mentioned config

I plan to release a new version later this week! Thanks!

**Comment by callagga** [comment]
any update iTOYS re the v0.4.3 release at all?

**Comment by iTOYS** [comment]
Hi @callagga,
Current version is 0.5.2

**Comment by callagga** [comment]
oh sorry - I see my mistake re checking for update versions.... I'll check out custom port approach now

**Comment by mimranshahid** [comment]
I spend a couple of hours to fix the issue and the fix that works for me is:

- I load the project in VSCode and replace all the occurrence of 8081
- After first step, I was successful in running the project in Xcode however I was facing issue in VSCode
- Managed to fix the issue in VSCode by changing the value in Setting.json file under .vsCode\Setting.json

   "react-native.packager.port": 7070

**Comment by zhouhao27** [comment]
@mimranshahid I made it work finally. But the debug stop working after I set to a custom port. The iPhone shows "No bundle url presented". I guess the iOS app is still using the old port.
