### ISSUE TITLE
Feature request: Add different prefixes to packager and run-<platform> commands

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#54]
It's sometimes difficult to know which process outputed an error. It might be useful to put some prefixes to the outputs like:
[Packager] Error: Null pointer exception
[Run android] Error: Null pointer exception

Or some other way to distinguish which processes made that output.
Alternatively, we could move the processes to the extension process, and use different channel outputs.

**Comment by panarasi** [comment]
+1. I think we should do this work.
