### ISSUE TITLE
Auto-close (generate closing tag) for RN JSX

### ISSUE THREAD

**Issue by ssomnoremac** [Microsoft/vscode-react-native#540]
## Actual Behavior
1.  Typing or autocompleting `<View>` or other tags does not generate closing tag

## Expected Behavior
1. Auto generated `</View>` to mirror 1.16+ behavior in HTML

## Software versions
- React-Native VS Code extension version: 0.4.2
- VSCode version: 1.16.1
- OS platform and version: OSX 10.12.6
- NodeJS version: 6.11.1
- React Native version: RN 47.2

**Comment by iTOYS** [comment]
Hello @ssomnoremac 
Intellisense is not controlled by this extension.
Intellisense for JSX provided by VSCode should work out-of-the box even if you don't have this extension installed.

Please see the [same issue](https://github.com/Microsoft/vscode/issues/18427#issuecomment-321821525) from vscode repo
