### ISSUE TITLE
android runArguments not working

### ISSUE THREAD

**Issue by kralcifer-ms** [Microsoft/vscode-react-native#541]
## Actual Behavior
1. added this to my settings.json:
    "react-native.android.runArguments.device": [ "--appIdSuffix=internal" ]
2. selected 'Debug Android' in vscode
3. vscode debug console windows shows:
[vscode-react-native] Executing command: react-native run-android

and app start fails because it cannot find the starting activity.

## Expected Behavior
1.  expected 'Debug Android' to pick up the runArguments.
2. expected it to say: Executing command: react-native run-android --appIdSuffix=internal
3. then the app will find the correct starting activity and launch successfully

From a terminal window, when I type 'react-native run-android --appIdSuffix=internal', the app starts the correct activity and launches successfully.

## Software versions
- React-Native VS Code extension version: 4.2
- VSCode version: 1.16.1
- OS platform and version: macOS Sierra 10.12.6
- NodeJS version: 
- React Native version: 0.45.1

**Comment by iTOYS** [comment]
Hello @kralcifer-ms 
You should modify your `Debug Android` configuration in `launch.json`
By default `target` property set to `simulator`, just change(or set) it to `device`

Please, let me know if it's work!

**Comment by kralcifer-ms** [comment]
That worked.  Thanks!
