### ISSUE TITLE
Start Packager doesn't show progress

### ISSUE THREAD

**Issue by bochen2014** [Microsoft/vscode-react-native#543]
is it possible to make react-native packager show progress?
so that I know bundling is in porgress

**Comment by iTOYS** [comment]
Hi @bochen2014 
Are you about this kind of `progress`?
```
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  100.0% (304/304), done.
```
We just spawn new process with `react-native start` command and pipe all outputs in `React-Native` vscode output channel.
Unfortunately, we don't get any `progress` updates, only completed string that looks like string above.

**Comment by bochen2014** [comment]
hi @iTOYS , yes that's what I was talking about. 
I have seen different output by running `react-native start` via windows `cmd` (on windows 7) and `vscode-react-tools`. but you are right, we just spawn a process to run the same command and redirect the output to vscode command output -- nothing we can do about it.

interestingly, when I do the same on my windows 10 box, I got different behavior again


![image](https://user-images.githubusercontent.com/8207081/31154596-f2c31ebe-a8f3-11e7-93c7-0e93f4fe1986.png)
