### ISSUE TITLE
command 'reactNative.runAndroidDevice' not found

### ISSUE THREAD

**Issue by somedude111** [Microsoft/vscode-react-native#546]
![screenshot_1](https://user-images.githubusercontent.com/3116731/31213337-612dbcda-a9a6-11e7-9198-7441ee6b5b52.png)

This started to happen yesterday, opening my react native project and I can't use the commands from the command palette. Do you have any idea what could that be? I've already tried re-installing the extension, didn't help.

Running `react-native run-android` works when used from command line, my operating system is windows 10.

**Comment by somedude111** [comment]
Weird, after like few minutes since creating this issue it started to work. (?????????????)

**Comment by nonameolsson** [comment]
I have experienced this issue also. It occurs when I try to run the command immediately after VS Code is started.
