### ISSUE TITLE
React native fails while debugging an app on device

### ISSUE THREAD

**Issue by Hemsza** [Microsoft/vscode-react-native#552]
The app is failing while enabling Debug JS Remotely dev option.
Beside of accessing **index.android.js** from running react package server ip address, it accessing  from device ip address.

## Software versions
- OS platform and version:  Ubuntu 16.04
- NodeJS version: 8.6.0
- React Native version:  0.49
- Realm: 1.13.0

## Outputs 
- Output on Browser Debug Console 
![screenshot_2](https://user-images.githubusercontent.com/32870742/31666716-d9435428-b36a-11e7-9bcd-3267728cf954.png)

- Output on Device 
![screenshot1](https://user-images.githubusercontent.com/32870742/31666727-dfeac388-b36a-11e7-8987-63e43573ea82.png)

All the hidden ip address before port is the Device Ip address on network.

**Comment by iTOYS** [comment]
Hi @Hemsza,
Do you use `vscode-react-native` tools?
Looks like this is problem with react-native, not with vscode tools.
If it's true, please move your issue to https://github.com/facebook/react-native repo.

Feel free reopen this issue if all works fine if you run react-native from terminal and it isn't work with vscode-react-native tools.

Thanks!
