### ISSUE TITLE
Intelligence for StyleSheet.create

### ISSUE THREAD

**Issue by condorman** [Microsoft/vscode-react-native#555]
When i try to create my StyleSheet, intelligence not found

![intelligence](https://user-images.githubusercontent.com/1047377/31770773-a6837d54-b4d9-11e7-90b7-b78d34123fb8.JPG)

## Software versions
- React-Native VS Code extension version: 0.4.2
- VSCode version: 1.17.2 x64
- OS platform and version:  windows pro x64
- NodeJS version: 8.7.0
- React Native version: 0.49.3

**Comment by iTOYS** [comment]
Hi @condorman 
Please see #542
