### ISSUE TITLE
Application Hang while reloading if debug is enabled.

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode-react-native#559]
## Actual Behavior
1.  Build a simple  application with react-native-cli
2. switch to application directory then type code .
3. with react-native-tools choose debug android
4. place a breakpoint then verify that is working
5. with the developer menu choose 'reload'
6. application does not reload instead hang.

on the other hand if you have hot reload enabled, changing source code does effectively reload, but from now , breakpoints became inefective.

## Expected Behavior
1. should reload, without hang, breakpoint should be retained.

## Software versions
- React-Native VS Code extension version: 
- VSCode version: [Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code:

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:46.104Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS platform and version: WINDOWS 7 ULTIMATE
- NodeJS version: 8.7.0
- React Native version: 0.49.3
- React Native CLI version: 2.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by iTOYS** [comment]
Hi @Gremlin80
Could you please provide some logs(if you have any of that):

* Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
* Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
* Output of the React-Native: Run Android output channel (View -> Toggle Output -> Select React-Native: Run Android in ListBox):
```
PASTE OUTPUT HERE
```
* Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

Thanks!

**Comment by Gremlin80** [comment]
Umfortunately i ve got no usefull info on logs. 
However it is easy to reproduce the issue, after you generate the sample app with react native init, switch to app directory then run vs code. 
Select debug configuration then run android, place a breakpoint and hit it. Then do continue.
On device activate the dev menu and choose reload
App does not restart

**Comment by iTOYS** [comment]
I do everything the same way, but all works good(

**Comment by Gremlin80** [comment]
Is there a way to send you a small video?

**Comment by Gremlin80** [comment]
OK: First Start. Application work ok. Logs:
Output of the Debug Console (View -> Toggle Debug Console):
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 32395
Running application "TEST" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF



Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] Starting React Native Packager.

[Info] Attaching to running React Native packager

Scanning folders for symlinks in c:\PROGETTI\ReactNative\TEST\node_modules (27ms)
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0493Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Api_25(AVD) - 7.1.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 14.47 secs
Running C:\AndroidSdk\sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\AndroidSdk\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.test/com.test.MainActivity)...
Starting: Intent { cmp=com.test/.MainActivity }


     
Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 32395
Running application "TEST" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF



then in my app.js i have this code:

 constructor()
  {
    super();
    var dummy = 1;
    dummy++;
  }

then i place a breakpoint in line "var dummy = 1".

i switch to the emulator and i hit ctrl-m (on windows). the developer menu popup, the first top options ar e (please make sure you have the same):
"Reload"
"Stop Remote Js Debugging"
"Disable Live Reload"
"Disable Hot Reloading"

then i choose "Reload"

the app does reload, the breakpoint is reached and execution is paused . 
then i choose ">" on the debug menu (continue) then application hang with the main android activity fully blanked and non responsive.

Here the logs after the "Reload Command"

Output of the Debug Console (View -> Toggle Debug Console):
Debugger worker loaded runtime on port 39732
Running application "TEST" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF


Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
Starting custom debugger by executing: echo A debugger is not needed:  "c:\PROGETTI\ReactNative\TEST"

Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

Debugger worker loaded runtime on port 39732
Running application "TEST" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

**Comment by Gremlin80** [comment]
OK: First Start. Application work ok. Logs:
Output of the Debug Console (View -> Toggle Debug Console):
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 32395
Running application "TEST" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF



Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] Starting React Native Packager.

[Info] Attaching to running React Native packager

Scanning folders for symlinks in c:\PROGETTI\ReactNative\TEST\node_modules (27ms)
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0493Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Api_25(AVD) - 7.1.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 14.47 secs
Running C:\AndroidSdk\sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\AndroidSdk\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.test/com.test.MainActivity)...
Starting: Intent { cmp=com.test/.MainActivity }


     
Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 32395
Running application "TEST" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF



then in my app.js i have this code:

 constructor()
  {
    super();
    var dummy = 1;
    dummy++;
  }

then i place a breakpoint in line "var dummy = 1".

i switch to the emulator and i hit ctrl-m (on windows). the developer menu popup, the first top options ar e (please make sure you have the same):
"Reload"
"Stop Remote Js Debugging"
"Disable Live Reload"
"Disable Hot Reloading"

then i choose "Reload"

the app does reload, the breakpoint is reached and execution is paused . 
then i choose ">" on the debug menu (continue) then application hang with the main android activity fully blanked and non responsive.

Here the logs after the "Reload Command"

Output of the Debug Console (View -> Toggle Debug Console):
Debugger worker loaded runtime on port 39732
Running application "TEST" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF


Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
Starting custom debugger by executing: echo A debugger is not needed:  "c:\PROGETTI\ReactNative\TEST"

Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

Debugger worker loaded runtime on port 39732
Running application "TEST" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

**Comment by iTOYS** [comment]
Thank you!
Could you please trying the same scenario with [Chrome Dev Tools](https://facebook.github.io/react-native/docs/debugging.html)
Is it also hang?

**Comment by Gremlin80** [comment]
Unfortunately it does hang too even with chrome. I've found a lot of reports with similar issues in react native project, but they seems to ignore the issue. I've found it's a old bug.

**Comment by iTOYS** [comment]
Sad news(
Looks like it depends on Android SDK version.
You can change it to 26 version(make new virtual device), if it's possible, and try again.
Unfortunately we can't fix that on our side.

**Comment by Gremlin80** [comment]
Are you able to reproduce the issue?it's not deterministic. something i've been able to do "reload" two or three times before getting the hang up

**Comment by iTOYS** [comment]
Actually not. I'm going to try one more time a bit later on other Android SDKs

**Comment by Gremlin80** [comment]
the trick to reproduce this is relatively simple: take the breakpoint active on a code part that is executed during app reload.
Every time the breakpoint stops, hit 'continue' then force a reload. 
the breakpoint will break again, hit 'continue' then force a reload.
.......
repeat 5 or more times, should hang

**Comment by iTOYS** [comment]
All works fine on Android SDK API 26

```
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 13308
Running application "AwesomeProject49" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 19876
Running application "AwesomeProject49" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 30161
Running application "AwesomeProject49" with appParams: {"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 36070
Running application "AwesomeProject49" with appParams: {"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 39775
Running application "AwesomeProject49" with appParams: {"rootTag":41}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 11520
Running application "AwesomeProject49" with appParams: {"rootTag":51}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 24199
Running application "AwesomeProject49" with appParams: {"rootTag":61}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 24484
Running application "AwesomeProject49" with appParams: {"rootTag":71}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 6411
Running application "AwesomeProject49" with appParams: {"rootTag":81}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 28725
Running application "AwesomeProject49" with appParams: {"rootTag":91}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 39647
Running application "AwesomeProject49" with appParams: {"rootTag":101}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 29061
Running application "AwesomeProject49" with appParams: {"rootTag":111}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 42335
Running application "AwesomeProject49" with appParams: {"rootTag":121}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Debugger worker loaded runtime on port 8620
Running application "AwesomeProject49" with appParams: {"rootTag":131}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

But sometimes crashes on Android SDK API 23
