### ISSUE TITLE
"runArguments" options in "launch.json" doesn't work

### ISSUE THREAD

**Issue by iTOYS** [Microsoft/vscode-react-native#567]

**Comment by SrikanthKabadi** [comment]
@iTOYS Since it is fixed now, how can I use this? Should I wait till the update is released?

**Comment by iTOYS** [comment]
@SrikanthKabadi see [there](https://github.com/Microsoft/vscode-react-native/blob/master/CONTRIBUTING.md#development-setup).
Or you can just add fix from PR in your extension that installed in `~/.vscode/extensions/vsmobile.vscode-react-native`

**Comment by SrikanthKabadi** [comment]
@iTOYS Thank you so much, that worked beautifully :)

**Comment by iTOYS** [comment]
You are welcome =)

**Comment by SrikanthKabadi** [comment]
@iTOYS Now it says `Error: ENOENT: no such file or directory, scandir '/Users/<username>/<path-to-repo>/ios'`

**Comment by iTOYS** [comment]
Do you have "ios" folder inside your "--project-path"? If yes, just modify your launch.json to:
```
"runArguments": [
    "--project-path", "../App/ios"
]
```

**Comment by SrikanthKabadi** [comment]
@iTOYS I don't have `iOS` folder itself in my project. I added react native support to existing project. 

App folder structure looks like this. 

<AppName>
        <App>
                App.xcodeproj
                App.xcworkspace

        <Libraries>

        <SDK>

        <React-Native>
                node_modules
                package.json
                tsconfig.json
                index.ios.js
                src

**Comment by iTOYS** [comment]
You should set "--project-path" directly to folder with ios native code:
It's "ios" folder for `react-native init` project,
Could you please try to run it from command line, is it work?

**Comment by SrikanthKabadi** [comment]
I have set "—project-path" to iOS native code.
If I run it from command line like this react-native run-ios --project-path "../App/“, it works.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.79&pv=10.13.0&source=email_footer_2]
On Mon, Oct 30, 2017 at 6:51 PM, Artem Egorov <notifications@github.com> wrote:
You should set "--project-path" directly to folder with ios native code:
It's "ios" folder for react-native init project,
Could you please try to run it from command line, is it work?

**Comment by iTOYS** [comment]
Could you please put you ios native into "../App/ios" folder, just for test?
I have idea.

**Comment by SrikanthKabadi** [comment]
If I just do a soft link ln -s ../App/ ios it works. But I don’t know why ios folder is that important. It used to work flawlessly with iosRelativeProjectPath argument in launch.json earlier.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.79&pv=10.13.0&source=email_footer_2]
On Mon, Oct 30, 2017 at 7:02 PM, Artem Egorov <notifications@github.com> wrote:
Could you please put you ios native into "../App/ios" folder, just for test?
I have idea.

**Comment by iTOYS** [comment]
Unfortunately it's very important for us(

**Comment by SrikanthKabadi** [comment]
Oh!! okay. Thank you so much :) Will do softlinking only then.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.79&pv=10.13.0&source=email_footer_2]
On Mon, Oct 30, 2017 at 7:15 PM, Artem Egorov <notifications@github.com> wrote:
Unfortunately it's very important for us(
