### ISSUE TITLE
Feature request: More steps/messages to track where we are in the workflow

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#57]
It's sometimes difficult to know without debugging the code, where is the code failing. This is particularly difficult when we get an error on a handler for a promise, because it's not easy to know what code was executed that failed.

To make debugging easier, we should add more steps or messages during the code (internal messages if they are too many), so we can track more easily where things are failing.

We could add more telemetry steps to the code, so we'll get a clear picture of where the code failed if we get telemetry for it, and also either modify telemetry.step to print an internal log message, or instead of using telemetry generator, use a wrapper that will call telemetry.step, and also log an internal message with the telemetry we are logging.

**Comment by iTOYS** [comment]
No longer relevant
