### ISSUE TITLE
React-Native Tools: Settings were changed, Please restart VSCode to apply their

### ISSUE THREAD

**Issue by matheusrocha89** [Microsoft/vscode-react-native#572]
I am using Typescript with React Native and every time I start to write some code this popup appears and I don't exactly which configuration is it talking about. I just use this plugin because of the Intellisense, is it possible to disable just the debug part of the plugin to stop showing this message?

```
React-Native Tools: Settings were changed, Please restart VSCode to apply their
```
![image](https://user-images.githubusercontent.com/3718366/32287843-d189e740-bf10-11e7-8788-653814060b14.png)

**Comment by jing2si** [comment]
The below 'Vim' plugin's setting will dynamically change settings cause this issue.
```js
  "vim.statusBarColorControl": true,
  "vim.statusBarColors": {
    "normal": "#005f5f",
    "insert": "#5f0000",
    "visual": "#5f00af",
    "visualline": "#005f87",
    "visualblock": "#86592d",
    "replace": "#000000"
  }
```

**Comment by matheusrocha89** [comment]
@jing2si Thanks, I will to remove it and see if it works.

**Comment by matheusrocha89** [comment]
@jing2si It worked fine. Thanks for the tip.
