### ISSUE TITLE
debug js remotely doesn't work, app is slow

### ISSUE THREAD

**Issue by uriva** [Microsoft/vscode-react-native#578]
My app is very slow on dev unless I choose "debug js remotely" on the dev menu and debug via chrome.

With this extension if I choose this option it seems to interfere with the debugger (the app loses connection).

Is there a workaround?

**Comment by iTOYS** [comment]
Hi @uriva,
Could you please fill issue description by [template](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by iTOYS** [comment]
Also, please check with new version of the extension(0.5.2)

**Comment by iTOYS** [comment]
@uriva 
Just a friendly ping. Any updates?

**Comment by uriva** [comment]
I've managed to get it to work in a hybrid manner, I first run react-native start outside, then give commands using vs-code. It's not perfect but it works.

**Comment by iTOYS** [comment]
close: couldn't repro
