### ISSUE TITLE
??? markup in debuggerWorker.js

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode-react-native#580]
It does appear that debuggerWorker.js have some markup inside, like this:
< !  doctype html >< div>< a href="/debug/bundles">Cached Bundles< /a>< /div>
// Notify debugger that we're done with loading
// and started listening for IPC messages
this causes VSCode to fail when launching debugger.....

**Comment by iTOYS** [comment]
Fixed in 0.5.2

**Comment by redlock** [comment]
I'm still having this issue in version 0.5.7

**Comment by iTOYS** [comment]
Hi @redlock,
Could you please open new issue and fill it by template
