### ISSUE TITLE
Intellisense not working after a semicolon

### ISSUE THREAD

**Issue by newfylox** [Microsoft/vscode-react-native#590]
When adding a semicolon after declaring static propTypes inside a *Class*, intellisense stops working. I don't know if it's a fault of this plugin but I thought I could share my experience here.

![working](https://user-images.githubusercontent.com/3361669/32871900-bf639916-ca51-11e7-81a9-8a6e113d0548.png)

![not-working](https://user-images.githubusercontent.com/3361669/32871908-c76f1e96-ca51-11e7-9257-136d6cd235ad.png)

## Software versions
- React-Native VS Code extension version: 0.5.2
- VSCode version: 1.18.0
- OS platform and version: Ubuntu 16.04
- NodeJS version: 6.11.2
- React Native version: 0.49.3

**Comment by iTOYS** [comment]
Hi @newfylox,

Intellisense is not controlled by this extension, yet.
Please see [that thread](https://github.com/Microsoft/vscode-react-native/issues/379#issuecomment-327747121) for more info.
