### ISSUE TITLE
Error when debugging with ios simulator

### ISSUE THREAD

**Issue by yuwenhuisama** [Microsoft/vscode-react-native#599]
## Actual Behavior
1. click `Debug ios`
2. the output window gives messages as follow

>[Info] Packager started.
>
>[Info] Prewarming bundle cache. This may take a while ...
>
>[Info] Entry point at /Users/huisama/Projects/Money-Andriod/index.ios.js doesn'tLog. exist. Skipping prewarming...
>
>[Info] Building and running application.
>
>**[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT**

3. and cannot continue debugging.

## Expected Behavior
1. Debugging normally.

## Software versions
- React-Native VS Code extension version: 0.5.4
- VSCode version: 1.18.1
- OS platform and version: mac OS 10.12.6
- NodeJS version: 8.9.1
- React Native version: 0.50.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4
Could not debug. Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point at /Users/huisama/Projects/Money-Andriod/index.ios.js doesn'tLog. exist. Skipping prewarming...

[Info] Building and running application.

**[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT**
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 使用扩展程序 /Users/huisama/.vscode/extensions/ms-vscode.node-debug2-1.19.0 覆盖扩展程序 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2。
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9
workbench.main.js:sourcemap:9 [Extension Host] (node:13054) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.main.js:sourcemap:9
t._logExtensionHostMessage @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:9
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Comment by gvillenave** [comment]
I'm still seeing this error on version 0.5.7 of the extension, with RN 0.49.5. Can you explain what the fix was and if there's anything required to make it work properly?

**Comment by iTOYS** [comment]
Hi @gvillenave what error have you seen? Could you please paste output here?

Is `react-native run-ios --simulator --no-packager` work for you if you run this in your terminal?

**Comment by novellizator** [comment]
the issue persists

**Comment by hufans** [comment]
First use Xcode to build successfully before using vscode debugging
