### ISSUE TITLE
Connect to a running RN

### ISSUE THREAD

**Issue by fcaride** [Microsoft/vscode-react-native#609]
Is it possible to connect the debugger to an existing react native application runing? 
I have a react native application running in another port and i would like to connect the debugger to it instead of running inside the VCode

**Comment by svekl** [comment]
Hi @fcaride,
sure, you need to use `Attach to packager` for that. For example let's say you run your app on another port like that
`react-native run-android --port 11111`
so, you will need to add port `Attach to packager` configuration in `launch.json`, it will look like that
```
{
            "name": "Attach to packager",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react",
            "port": "11111"
        }
```

then after attaching you can set a breakpoint in your app, `Enable Remote JS Debugging` and `Reload` your RN app from it's dev menu and debug session will start.

**Comment by fcaride** [comment]
Hi @svekl ! Thanks for your quick response!

I tried that using this config:
        {
            "name": "Attach to packager",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react",
            "port": "19000"
        }

And it returns this in the console:
Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json.

**Comment by fcaride** [comment]
Also, I didn't say it but I am using the packager of Expo, i know there is a way to attach an expo project but this is a detached expo project so it's not so easy.

**Comment by svekl** [comment]
@fcaride, may I ask you to create some small project that reproduces this issue to test? And to provide a command that you are using to run packager. I'm asking because there are a lot of possible set ups of RN apps and I tried to eject expo on my project and had no luck in reproducing.

By the way, did you try to run packager from our extension directly? We have `Debug in Exponent` launch configuration, that runs packager, attaches to it and provides you a QR code for Expo.

**Comment by fcaride** [comment]
No problem i just could do it! Thanks my bad

**Comment by svekl** [comment]
Awesome, glad to hear it works, you are welcome!

**Comment by svekl** [comment]
@fcaride, Now I see what your issue was and what I was doing wrong trying to reproduce it, you can see details and workaround here
https://github.com/Microsoft/vscode-react-native/issues/553#issuecomment-348531053
