### ISSUE TITLE
Salsa Doesn't Provide Intellisense When Using Import Statements

### ISSUE THREAD

**Issue by joshuaskelton** [Microsoft/vscode-react-native#61]
Salsa IntelliSense does not work when using ES6 style import statments. I've tried tweaking some tsconfig.json settings, but without much luck.

This does not work:
`import React, {
  AppRegistry
} from 'react-native';`

But this does:
`var React = require('react-native');
var {
  AppRegistry
} = React;`

This is a known TypeScript issue:
https://github.com/Microsoft/TypeScript/issues/7000

**Comment by billti** [comment]
Fix is out for review. See https://github.com/Microsoft/TypeScript/pull/7249#issuecomment-190297728

**Comment by joshuaskelton** [comment]
Thanks for keeping us looped in! :+1:

**Comment by joshuaskelton** [comment]
Looks like the change was merged. I'll verify once we get the typescript bits.

**Comment by zchrykng** [comment]
Any update on when this fix will be pushed out? Negates one of the most awesome features of VSCode, at least for my current project.

**Comment by egamma** [comment]
@zchrykng The fix is available in the latest VS Code insiders build. Pls see https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build

**Comment by zchrykng** [comment]
@egamma Awesome. Thanks! Installing now.
