### ISSUE TITLE
request: support react-native-windows

### ISSUE THREAD

**Issue by arolson101** [Microsoft/vscode-react-native#614]
I created a project with react-native-windows and this debug extension works if I attach to packager but it doesn't support launching the windows platform.  The cli would be "react-native run-windows"

**Comment by jwargo** [comment]
@arolson101 we do not support the Windows platform today, but the team's listed this as an enhancement request and will investigate adding support in the future.

**Comment by iTOYS** [comment]
Added debugger for `react-native-windows` in #618 

For debugging `react-native-windows` add new `launch.json` configuration:
```
{
	"name": "Debug Windows",
	"program": "${workspaceRoot}/.vscode/launchReactNative.js",
	"type": "reactnative",
	"request": "launch",
	"platform": "windows",
	"sourceMaps": true,
	"outDir": "${workspaceRoot}/.vscode/.react"
},
```

> Command palette commands(show dev menu, restart js) don't work for `react-native-windows`, but I'm working on it!
