### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by egorshulga** [Microsoft/vscode-react-native#616]
- Extension Name: vscode-react-native
- Extension Version: 0.5.7
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 162,
		"activateCallTime": 59,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Error while executing command 'react-native.cmd -v'"
		}
	]
}
```

**Comment by egorshulga** [comment]
Error message is `Error while executing command 'react-native.cmd -v'`. 
But for react-native this switch is not defined. 
I found a place in the code with a `-v` option coded [here](https://github.com/Microsoft/vscode-react-native/blob/0a68f8db56aae8352c5b9ca8062abd78cfdaa44a/src/common/commandExecutor.ts#L38). Shouldn't it be changed to `-V`?

**Comment by iTOYS** [comment]
Hi Egor! @egorshulga 
`react-native.cmd -v` is correct command for react-native-cli on Windows.
Could you please try to run `react-native -v` from cmd in your project folder, is it work?

**Comment by egorshulga** [comment]
@iTOYS, nope: `error: unknown option '-v'`

`react-native -V` shows 0.52.0 version.

**Comment by iTOYS** [comment]
Which version of `react-native-cli` do you use?
BTW my output:
```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.52.0
```

**Comment by egorshulga** [comment]
```
S:\...\MobileUI>react-native -V
Scanning folders for symlinks in C:\Users\...\AppData\Local\Yarn\config\global\node_modules (60ms)
0.52.0
```

**Comment by egorshulga** [comment]
It is hard to find any other piece of information to find out, what's going on.

This is console output from vscode dev tools.
![image](https://user-images.githubusercontent.com/6253488/34991929-693705f8-fadc-11e7-8062-a81d4a5ecfad.png)

**Comment by svekl** [comment]
@egorshulga Can you, please, show output from `yarn global list`

**Comment by iTOYS** [comment]
Seems like problem with your CLI, because the latest CLI doesn't output similar error:
```
$react-native -DUMMY
You did not pass any commands, run `react-native --help` to see a list of all available commands.
```
Could you please try to reinstall `react-native-cli`:
```
$ npm uninstall react-native-cli
$ npm cache clean
$ npm install -g react-native-cli
```

**Comment by egorshulga** [comment]
react-native-cli should be installed globally?

**Comment by egorshulga** [comment]
@svekl,
```
yarn global v1.3.2
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
warning " > react-native@0.52.0" has unmet peer dependency "react@16.2.0".
info "gulp@3.9.1" has binaries:
   - gulp
info "jshint@2.9.5" has binaries:
   - jshint
info "react-native@0.52.0" has binaries:
   - react-native
info "source-map-explorer@1.5.0" has binaries:
   - source-map-explorer
info "typescript@2.6.2" has binaries:
   - tsc
   - tsserver
info "vsce@1.31.1" has binaries:
   - vsce
info "webpack-cyclic-dependency-checker@0.0.1" has binaries:
   - iscyclic
Done in 15.99s.

```

**Comment by iTOYS** [comment]
Yes!)

**Comment by iTOYS** [comment]
Remove `react-native` from global and install `react-native-cli`

**Comment by egorshulga** [comment]
Let me clarify: `react-native-cli` should be installed globally for this extension to work properly.
It should be definitely added to the readme.

**Comment by iTOYS** [comment]
@egorshulga 
It does! Please see [getting started](https://github.com/Microsoft/vscode-react-native/#getting-started) guide

**Comment by egorshulga** [comment]
Thanks to maintainers for help and support!

**Comment by iTOYS** [comment]
You are welcome)
