### ISSUE TITLE
Couldn't work with specified scheme when debugging iOS in vscode

### ISSUE THREAD

**Issue by matthew-an** [Microsoft/vscode-react-native#617]
For React Native project, when debugging iOS in vscode, By default, it will use `react-native run-ios` to start the debug session, however sometimes i would like to pass in a different scheme.

I specify the sheme in launch.json like as:

`"arguments": [ "--scheme", "HelloWorld_dev" ],`

## Actual Behavior
1. The specified scheme doesn't take effect 

## Expected Behavior
1. It should 

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.19.2 
- OS platform and version: Mac OS X 10.13.2 (17C205)
- NodeJS version: v6.11.0
- React Native version: 0.49.5

**Comment by iTOYS** [comment]
Hi @matthew-an 
Correct name of launch option is `runArguments`, please try:
> "runArguments": [ "--scheme", "HelloWorld_dev" ]

Or you can use `scheme` launch option for your purposes:

> "scheme": "HelloWorld_dev"

**Comment by matthew-an** [comment]
Thanks a lot! @iTOYS It works. 

But it will be great if you can update the "Debug on iOS device" part in the documentation below to avoid confusion for other users. 
https://github.com/Microsoft/vscode-react-native/blob/master/doc/debugging.md

Cheers!

**Comment by sergey-akhalkov** [comment]
@matthew-an, docs have been updated, thanks for the feedback!
