### ISSUE TITLE
React Native Tools seems to be broken on insiders 1.20.0

### ISSUE THREAD

**Issue by rodrigoelp** [Microsoft/vscode-react-native#619]
If you create a brand new project with `react-native-cli: 2.0.1` and `react-native: 0.52.1` on `vscode-insiders-1.20.0` and try to generate a new debugging session (by typing on the launcher > react native debug) nothing happens and trying to add the configuration only shows you node.js and another one that isn't for this.

Had to create manually a `launch.json` file in the `.vscode` folder and then click on add configuration to get it back.

## Actual Behavior
1. Create new react-native project
2. Click on the debug button
3. On the drop-down menu, click on `add configuration`
4. Notice how react-native is not offered as part of the options

## Expected Behavior
1. Create new react-native project
2. Click on the debug button
3. On the drop-down menu, click on `add configuration`
4. Select react native and wait for vscode to configure your `launch.json` file
5. Debug your app

## Software versions
- React-Native VS Code extension version: `react-native-cli: 2.0.1` and `react-native: 0.52.1`
- VSCode version: Version 1.20.0-insider (1.20.0-insider)
- OS platform and version: macos high sierra 10.13.2 (17C205)
- NodeJS version: v9.3.0
- React Native version: `react-native: 0.52.1`

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
No debug console output
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
None
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] 2018-01-23T22:13:16.811Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.0.0/out/utilities/logger.js:45:25))
workbench.main.js:sourcemap:253 [Extension Host] 2018-01-23T22:13:16.888Z - debug: [CodeOutline] activeWindowChanged, reparsing (at ConsoleLogTransport.log (/Users/rod/.vscode-insiders/extensions/rbbit.typescript-hero-2.0.0/out/utilities/logger.js:45:25))
```

**Comment by iTOYS** [comment]
Hi @rodrigoelp 

I can't repro this.
Could you please double check that you open exactly react-native project's folder
Also please check that this extension installed and no one another extensions haven't needed reload

Thanks!

**Comment by sergey-akhalkov** [comment]
Hi @rodrigoelp, just a friendly ping.

**Comment by sergey-akhalkov** [comment]
Closing this, please free to reopen if you have any updates.

**Comment by MacKentoch** [comment]
I encounter same issue, with:
- VSCode 1.21
- React Native Tools up to date
- node 8.9.3
- react-native-cli: 2.0.1
- react-native: 0.51.0
- macOS 10.13.3

No react-native configuration is showed to selection, see talkative print screen:

<img width="633" alt="capture d ecran 2018-03-08 a 14 52 47" src="https://user-images.githubusercontent.com/11223428/37154476-707fa460-22e0-11e8-97d1-8129c51bdd1b.png">

I never use react-native-tools but I wanted to give a try...
Seems like no luck for me 😅

**Comment by rodrigoelp** [comment]
Hi @sergey-akhalkov, I am really sorry I did not reply before as I was away from civilisation for a month. I still have this issue and I was considering removing vscode entirely and install it again to see if there is a corrupted configuration or something. I got the same behaviour as described by @MacKentoch
