### ISSUE TITLE
How to exclude node modules and node internals from VS --debugger-- ??

### ISSUE THREAD

**Issue by dancomanlive** [Microsoft/vscode-react-native#620]
## Actual Behavior
1. debugger goes into node internals and node modules 

## Expected Behavior
1. debugger skips node internals and node modules

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: Code - Insiders Version 1.20.0-insider (1.20.0-insider)
- OS platform and version: MacOs 10.13.2
- NodeJS version: 9.3
- React Native version: ^0.48.4 

## Note

```
"skipFiles": [
    "${workspaceFolder}/node_modules/**/*.js",
    "<node_internals>/**/*.js"
  ]
```

from https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome does not work. 

 "skipFiles" shows "Unknown configuration setting "inside Workspace Settings
"skipFiles" shows "Property skipFiles is not allowed."  inside launch.json

**Comment by iTOYS** [comment]
Hi @dancomanlive 
Actually `skipFiles`  option works, you can use it as mentioned [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome).
Do not pay attention to the error - `Property skipFiles is not allowed.`
I'll add definition for this option to avoid errors in the future.

Thanks!

**Comment by cawoodm** [comment]
I have used every skipFiles setting on the internet and still VSCode occasionally jumps into node_modules and node_internals. My feeling is the feature is flaky. I wish we could just whitelist instead of blacklist.

**Comment by JiglioNero** [comment]
Hi @cawoodm and thanks for contacting us. Could you please open a new issue and add repro steps, so we could reproduce the issue? If it’s a project specific issue, could you please also create and send us a minimal demo project with this problem? This would be very helpful for us to investigate the issue faster.
You can try to use these patterns to exclude `node_modules` and `node_intenrals` from the list of files for debugging in VSCode:
```json
{
    "skipFiles": [
                 "${workspaceFolder}/<node_internals>/ **",
                 "${workspaceFolder}/node_modules/ **"
    ]
}
```

**Comment by egarkavy** [comment]
Well guys, may be off topic but keep in mind that if you do not await you function you will also be navigated to some internal library code. it was just my case, I hit f10 to bubble up from internal async function but eventually got stopped in RxJs code. Awaiting the function did the thing
