### ISSUE TITLE
Error when debugging with ios simulator (again)

### ISSUE THREAD

**Issue by novellizator** [Microsoft/vscode-react-native#627]
## Actual Behavior (issue #599 persists)
1. I click "Debug in iOS"
2. I get an error

## Expected Behavior
1. The debugging should start normally

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.19.3
- OS platform and version: macOS 10.13.3
- NodeJS version: 8.9.0
- React Native version: react-native-cli: 2.0.1
react-native: 0.51.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.5
Could not debug. Error while executing command 'react-native run-ios --simulator --no-packager': Error while executing command 'react-native run-ios --simulator --no-packager'
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Metro Bundler ready.

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point at /Users/tomasnovella/workspace/salsita/ecourt/ecourt/index.ios.js doesn'tLog. exist. Skipping prewarming...

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': Error while executing command 'react-native run-ios --simulator --no-packager'

**Comment by novellizator** [comment]
As a matter of fact I just selected an action "stop packager" in VS Code and it works again! probably solved, even though it doesn't make sense, since when I started debugging, the process launched the packager.

**Comment by AnitaVPN** [comment]
I am having the same issue , i am new to react-native and i want to do debugging , i am using vscode and expo to run app, but when i do debugging i have same issue which you had mention. 

Could you please specify the steps for resolving ?

**Comment by ruslan-bikkinin** [comment]
Hi @AnitaVPN, please submit separated issue using our [issue template](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md) so we could help you faster.

**Comment by liberalisman** [comment]
> I am having the same issue , i am new to react-native and i want to do debugging , i am using vscode and expo to run app, but when i do debugging i have same issue which you had mention.
> 
> Could you please specify the steps for resolving ?

-----------------------

Open your Xcode, Prefercnces -> Locations ->  Choose your Command Line Tools 

Solved!!!

**Comment by liberalisman** [comment]
Open your Xcode, Prefercnces -> Locations ->  Choose your Command Line Tools 

Solved!!!
