### ISSUE TITLE
Add checks for exceptional cases

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode-react-native#652]
Currently, there are several cases that could be processed programmatically (for example show informational message to the user) instead of being processed by global error handler: 
* user opens up non-RN project and tries to run extension commands
* user opens up RN project with no react-native package installed and tries to run extension commands
* user opens up RN project with no react-native package installed, then install react-native package and and tries to run extension commands

For example, here is result of executing `React Native: Start Packager` command on non-RN project:

![image](https://user-images.githubusercontent.com/30265843/36785719-d9c08a7c-1c94-11e8-95bd-53e20dd9f5a7.png)

**Comment by iTOYS** [comment]
Fixed #737
