### ISSUE TITLE
Source maps with react native 0.54.0

### ISSUE THREAD

**Issue by pennyandsean** [Microsoft/vscode-react-native#660]
## Actual Behavior
1. Source maps not generated even with launch option set to true
2. Same project with react native 0.53.0 works fine

## Expected Behavior
1. Source maps generated
2. 

## Software versions
- React-Native VS Code extension version: 0.6.4
- VSCode version: Insiders 1.21.0
- OS platform and version: OSX 10.13.3
- NodeJS version: 9.2.1
- React Native version: 0.54.0

**Comment by Yria** [comment]
+1

**Comment by max-mironov** [comment]
Hey guys, seems that latest version of metro bundler doesn't generate 

`//# sourceMappingURL=http://localhost:8081/index.map?platform=ios&dev=true&minify=false` 

for bundle. 
I have posted a question here with some details: https://github.com/facebook/metro/issues/147

In the meantime will look at how we can overcome this.

**Comment by max-mironov** [comment]
UPDATE: 
This should be fixed in new version of Metro Bundler (0.29.0) and hopefully be released soon.
So please keep calm and be patient!

**Comment by pennyandsean** [comment]
Looks like 0.29.0 was released. And 0.30.0.

**Comment by max-mironov** [comment]
@pennyandsean thanks for heads up, I've looked at and RN0.54.2 is going with `metro 0.28.0`. Hope next version of `metro` will be included in new RN release.

**Comment by max-mironov** [comment]
Hey guys, closing this issue for now as we have added tmp fix for this case in https://github.com/Microsoft/vscode-react-native/releases/tag/0.6.5. 
Please reach us if you have any questions or see any problems.

**Comment by pennyandsean** [comment]
Ripper, thanks Max, it works!
