### ISSUE TITLE
"Could not find iPhone 6 simulator" 

### ISSUE THREAD

**Issue by WesleydeSouza** [Microsoft/vscode-react-native#662]
## Actual Behavior
1. Press play button on debugger
2. Error `Could not debug. Error while executing command 'react-native run-ios --simulator --no-packager': Error while executing command 'react-native run-ios --simulator --no-packager'` appear on Debug Console

## Expected Behavior
1. Press play button on debugger
2. Project runs on iOS simulator

## Software versions
- React-Native VS Code extension version: 0.6.4
- VSCode version: 1.21.0 (1.21.0)
- OS platform and version: macOS High Sierra 10.13.3 (17D102)
- NodeJS version: v9.8.0
- React Native version: 0.53.0

## Outputs (Include if relevant)
- Output of the Debug Console:
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
Could not debug. Error while executing command 'react-native run-ios --simulator --no-packager': Error while executing command 'react-native run-ios --simulator --no-packager'

```
- Output of the React-Native: Run ios output channel:
```
[Info] Starting React Native Packager.

[Info] Attaching to running React Native packager

Scanning folders for symlinks in /Users/wesley/Work/[project]/node_modules (25ms)
Found Xcode project [project].xcodeproj

Could not find iPhone 6 simulator
```

## More details

The same configuration is working on another machine. I tried following the documentation to force another simulator by setting `react-native.ios.runArguments.device` but it was ignored by the extension.

I've also ran the project on XCode targeting an iPhone 6 simulator, and it still shows it's not found on VSCode.

**Comment by annakocheshkova** [comment]
@WesleydeSouza thank you for your request!
Try executing `react-native run-ios --simulator --no-packager` in terminal, does it work for you?

**Comment by ruslan-bikkinin** [comment]
@WesleydeSouza just a friendly ping on this.

**Comment by WesleydeSouza** [comment]
@annakocheshkova neither work once the Simulator is open.

If I quit the simulator, most times it works.

**Comment by ruslan-bikkinin** [comment]
@WesleydeSouza Well, seems to be that your issue doesn't relate with extension itself. I recommend you to search for similar issues in [react-native](https://github.com/facebook/react-native) repo, besides there was already [bug](https://github.com/facebook/react-native/issues/5850) that caused inability for targeting iPhone 6 in extension as well.
