### ISSUE TITLE
VS code react native break points still working or not ?

### ISSUE THREAD

**Issue by isurugajasinghe** [Microsoft/vscode-react-native#665]

**Comment by Gremlin80** [comment]
who can say? actually with 0.6.5 we cannot reach the QR code screen. 
It is incredible how can any release can be worst and unusable compared to the previous.
this plugin is really crappyware

**Comment by Gremlin80** [comment]
now we get

Successfully ran `adb reverse`. Localhost urls should work on the connected Android device.Successfully ran `adb reverse`. Localhost urls should work on the connected Android device.Loading dependency graph, done.
[Error] Error starting tunnel: Error: Starting tunnels timed out

[Error] Error starting tunnel: Error: Starting tunnels timed out

[Error] Error: Starting tunnels timed out

**Comment by ruslan-bikkinin** [comment]
Hi guys. We already have https://github.com/Microsoft/vscode-react-native/issues/625 issue so please let's discuss it one place. I am going to close this as duplicate.

@isurugajasinghe If you are sure that your issue doesn't relate with #625, please submit a new one using our issue template so we could help you faster.
