### ISSUE TITLE
Debug mode is not off when release-react

### ISSUE THREAD

**Issue by booker-laputa** [Microsoft/vscode-react-native#669]
## Actual Behavior
1. Use GUI to do release-react
2. App update and the debug warning box(Yellow box at the bottom) is shown in the app

## Expected Behavior
1. Use GUI to do release-react
2. Debug mode should be off, app should not see the yellow warning box

Using `appcenter codepush release-react` has no problem

## Software versions
- React-Native VS Code extension version:  0.6.6
- VSCode version: 1.21.1
- OS platform and version: Mac OS 10.12.4
- NodeJS version: v7.10.0
- React Native version: 0.43.1

**Comment by sergey-akhalkov** [comment]
Hi @booker-laputa, thank you for reaching us and for the issue details, we are going to investigate it and let you know if we have any questions/updates.

**Comment by ruslan-bikkinin** [comment]
HI @booker-laputa, I tried to reproduce your issue using the following steps but it works like a charm for me:

1. Initialize empty RN-project.
2. Install react-native-code-push into it.3.
3. Update App.js with simple CodePush update logic and add code that throws exception by clicking on a button.
3. Compile app in `Release` mode in XCode and run it.
4. Release new code-push update via extension.
5. Install and apply update for application and then click button to throw exception - application crashes as shown here:

![rn669](https://user-images.githubusercontent.com/30265843/37703850-1167464a-2d08-11e8-95d0-ac02de73368e.gif)

Did I miss something when I was trying to reproduce your issue? Could you please double check that you are running your app in `Release` mode?

**Comment by firofame** [comment]
I am having the same issue. is there any fix?

**Comment by ruslan-bikkinin** [comment]
@booker-laputa @firofame AppCenter functionality (and CodePush stuff as well) has been moved since 0.6.9 from `vscode-react-native` extension to the brand new extension [vscode-appcenter](https://github.com/Microsoft/vscode-appcenter) so please try it instead. If you will be experiencing current issue there as well, please, submit new issue in that repo.
