### ISSUE TITLE
Debugger not working for react-native app & react-native command incorrect

### ISSUE THREAD

**Issue by sramzan** [Microsoft/vscode-react-native#673]
## Actual Behavior
Error message: "Debug adapter process has terminated unexpectedly" is thrown. I checked the '.vscode' directory and I don't see the launch scripts being created (i.e.'launchReactNative.js'). I have opened code via cli and typical gui methods from mac (launchpad, spotlight). I have also uninstalled the extension multiple times in combination with restarting vscode.

I did notice an issue when I opened the dev tools. It seems that the extension is checking the version of react-native to see if it's installed, but the command is using '-v' instead of '-V'.

## Expected Behavior
Expect debugger to work for react-native app

## Software versions
- React-Native VS Code extension version: latest
- VSCode version: 1.21.1
- OS platform and version: Mac, High Sierra (v10.13.2)
- NodeJS version: 8.8.1
- React Native version: 0.52.2

## Outputs 
<img width="1333" alt="screen shot 2018-03-25 at 9 05 10 pm" src="https://user-images.githubusercontent.com/8163657/37882490-b657b7f4-3071-11e8-8eb8-73bb6b729c31.png">
<img width="133" alt="screen shot 2018-03-25 at 9 06 07 pm" src="https://user-images.githubusercontent.com/8163657/37882491-b65fb940-3071-11e8-9c5b-abff2bd61278.png">
<img width="204" alt="screen shot 2018-03-25 at 9 07 06 pm" src="https://user-images.githubusercontent.com/8163657/37882492-b66997f8-3071-11e8-92bd-0e02b16988e7.png">=

Please see the screenshots for the issue described with 'react-native'. I may be doing something wrong. More than happy to raise a PR if it's a valid issue.

Not sure why my debugger refuses to work. Would appreciate some support there. I feel tapped on resources.

**Comment by Gatix** [comment]
I'm running into the same issue and finally found the culprit. Running `which react-native` outputs `node_modules/.bin/react-native` where it should be calling the global `react-native-cli` package.

A workaround is removing `node_modules/.bin` or making sure you're loading the `react-native-cli` bin.

**Comment by ruslan-bikkinin** [comment]
Hi @sramzan @Gatix and sorry for such delayed response. 
@sramzan did @Gatix 's advice help you? Are we good to close this?

**Comment by ruslan-bikkinin** [comment]
I am closing this, feel free to re-open if needed.
