### ISSUE TITLE
Emmet is not working with react-native

### ISSUE THREAD

**Issue by mhamri** [Microsoft/vscode-react-native#675]
I wonder it would be awesome to have emmet works in react-native. unfortunately if I enable emmet by file expression in user settings, then the react-native intellisense stop working and I get html suggestion.
specially if press (Ctrl+K+M) and choose the language `javascript react` then things doesn't work as it should.

**Comment by ruslan-bikkinin** [comment]
Hi @mhamri 
`vscode-react-native` doesn't control intelisense for react-native anymore. This functionality is the part of VS Code builtin extension now.
I believe you should file this issue to https://github.com/Microsoft/vscode instead as it's better place for solving it now.
