### ISSUE TITLE
Debug in Exponent throws "Error while executing command 'npm.cmd install xdl @expo/ngrok --verbose -no-save'

### ISSUE THREAD

**Issue by joshsiegl1** [Microsoft/vscode-react-native#676]
## Actual Behavior
1.  Error is thrown when Debug in Exponent is first run

## Expected Behavior
1. Dependencies install successfully and QR code is generated

## Software versions
- React-Native VS Code extension version: 0.6.6
- VSCode version: Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS platform and version: Windows 10 
- NodeJS version: 6.11.3
- React Native version: 0.54.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Could not debug. Error while executing command 'npm.cmd install xdl @expo/ngrok --verbose --no-save'
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Checking if this is Expo app......
[Error] Error: Error while executing command 'npm.cmd install xdl @expo/ngrok --verbose --no-save'
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
mainThreadExtensionService.ts:44 Error: Error while executing command 'npm.cmd install xdl @expo/ngrok --verbose --no-save'
	at Function.getInternalError (C:\Users\Josh\.vscode\extensions\vsmobile.vscode-react-native-0.6.6\src\common\error\errorHelper.js:11:16)
	at ChildProcess.spawnedProcess.once (C:\Users\Josh\.vscode\extensions\vsmobile.vscode-react-native-0.6.6\src\common\node\childProcess.js:44:58)
	at Object.onceWrapper (events.js:293:19)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
Would really appreciate some help with this, this is on a fresh run of expo debug (while installing dependencies)

**Comment by ruslan-bikkinin** [comment]
Hi @joshsiegl1 and thanks for your request. It looks very odd, did you log into expo before running debugger?

**Comment by joshsiegl1** [comment]
Hey @ruslan-bikkinin , this isn't an issue for me anymore, thanks for replying. I believe my solution was to upgrade to the latest version of Node.

**Comment by max-mironov** [comment]
Thanks for getting back, closing the current one.
