### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by YaAlfred** [Microsoft/vscode-react-native#685]
## Actual Behavior
1. React native debugger didn't start. Error appears: Debug adapter process has terminated unexpectedly
- (tried #616, and #612 advices, reinstalling module)

## Software versions
- React-Native VS Code extension version: 1.22.2 
- VSCode version: 0.6.7
- OS platform and version: mac-os 10.13.3
- NodeJS version: v8.9.4
- React Native version: 0.42.0
- React Native Cli: 2.0.1

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
notificationsAlerts.ts:39 Debug adapter process has terminated unexpectedly
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
b.onServerExit @ rawDebugSession.ts:541
(anonymous) @ rawDebugSession.ts:455
emitTwo @ events.js:111
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by jsslai** [comment]
https://github.com/Microsoft/vscode-react-native/pull/686 :)

**Comment by YaAlfred** [comment]
Great, 0.6.8 works well, thanks a lot

**Comment by max-mironov** [comment]
Hi there guys, thanks for pointing out, fixed in latest version, my sincerest apologies for any inconvenience this may have caused.
