### ISSUE TITLE
Get the path to adb from local.properties for an existing project

### ISSUE THREAD

**Issue by shivawu** [Microsoft/vscode-react-native#688]
## Actual Behavior
1. Fails to find adb if it's not in PATH

## Expected Behavior
1. Should be able to find adb using the ANDROID_HOME specified in local.properties in a react-native project, which is the case for all the other tooling for react-native 

## Software versions
- React-Native VS Code extension version: 0.6.6
- VSCode version: 1.22.2
- OS platform and version: Mac OS X 10.13.4
- NodeJS version: 9.11.1
- React Native version: 0.55.2

**Comment by ruslan-bikkinin** [comment]
Hi @shivawu and thanks for your request. We will add this to our backlog and pick it up in order of priority.

**Comment by ruslan-bikkinin** [comment]
Hi @shivawu I have implemented your request in this PR: #754. Could you please take a look on it and let me know whether it satisfy your needs?

**Comment by ruslan-bikkinin** [comment]
Okay, I am closing this for now as original feature request has been implemented. @shivawu if you think that this feature should be complemented please feel free to submit new issue.
