### ISSUE TITLE
Log points cause break

### ISSUE THREAD

**Issue by Elijen** [Microsoft/vscode-react-native#691]
## Actual Behavior
1. Add a log point
2. Run the code
3. VSCode breaks when log point is reached
4. Nothing is logged in the Debug Console

## Expected Behavior
1. Add a log point
2. Run the code
3. VSCode logs the message but continues code execution

## Software versions
- React-Native VS Code extension version: 0.6.9
- VSCode version: 1.22.2
- OS platform and version: macOS
- NodeJS version: v7.9.0 x64
- React Native version: Expo SDK v26.0.0

**Comment by lardissone** [comment]
Same thing is happening to me. Also there's no way to see the log point message on the break.

**Comment by ruslan-bikkinin** [comment]
Hi @Elijen @lardissone, I tried to reproduce your issue after updating VS Code to 1.24 but with no success - log points are working without any problem. Please try to update VS Code to 1.24 and let us know whether it solves your issue or not. 
Please feel free to re-open this if needed.
