### ISSUE TITLE
Breakpoints are disabled when reloading react native code in iOS Simulator

### ISSUE THREAD

**Issue by maxmamis** [Microsoft/vscode-react-native#693]
## Actual Behavior
1. Set a breakpoint by clicking in editor gutter
2. Start the debugger, running app in iOS Simulator
3. Observe that the breakpoint is triggered as expected 
4. Reload the app in simulator using cmd-R hotkey
5. Observe that all breakpoints are disabled 

## Expected Behavior
1. Set a breakpoint by clicking in editor gutter
2. Start the debugger, running app in iOS Simulator
3. Observe that the breakpoint is triggered as expected 
4. Reload the app in simulator using cmd-R hotkey
5. Breakpoints are not disabled and continue to be triggered as appropriate 

## Software versions
- React-Native VS Code extension version: 0.6.9 
- VSCode version: 1.22.2
- OS platform and version: Mac OS 10.13.3
- NodeJS version: 8.6.0
- React Native version: 0.50.3

**Comment by ruslan-bikkinin** [comment]
Hi @maxmamis and thanks for your report. It is known issue: https://github.com/Microsoft/vscode-react-native/issues/625 and, currently, we are working for a solution for it.

**Comment by maxmamis** [comment]
@ruslan-bikkinin thanks, didn't realize that was the same issue
