### ISSUE TITLE
Click debug ios  vscode will build and install app everytime. 

### ISSUE THREAD

**Issue by ldhios** [Microsoft/vscode-react-native#696]
## Actual Behavior
1. vscode will build native code xcode project and install app in  ios simulator, after click debug ios.  
it will happen every time I click the button.
2. console tip "
Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081?" when click attach to packager.

## Expected Behavior
1.  support a option  parameter? like webstorm  
![image](https://user-images.githubusercontent.com/9722423/39864982-0b16f374-547e-11e8-8ada-3530a1b0a1bb.png)
2. can auto run "npm start"?   in my click  "attach to packager".  webstorm it can.
![image](https://user-images.githubusercontent.com/9722423/39865223-bd8f57f8-547e-11e8-8ec2-946f64a8e7df.png)
Sorry for my bad English!
## Software versions
- React-Native VS Code extension version: 0.6.9
- VSCode version: 1.23.0 
- OS platform and version: mac os  10.13.4  ios 11
- NodeJS version: 6.11.2
- React Native version: 0.44.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by ldhios** [comment]
Hi @ruslan-bikkinin 

2,  Maybe you not understand. My package is not started. Auto run package start, when i click attach to packager.  That is my mean.  
Sorry for my bad english, I will improve it.

**Comment by ruslan-bikkinin** [comment]
@ldhios 
1. After further investigation I realized that extension already have the feature you are looking for.
To mimic WebStorm behavior in case of "Build and Launch application" option unchecked you need to do the following:
* Run application manually (actually, webstorm warns that it should be done at first). 

![image](https://user-images.githubusercontent.com/30265843/39991386-123ff7fc-5778-11e8-8e42-c49dbdda0798.png)

By the way, you can run application using extension by opening command pallete, typing "react native run" and then selecting any command from the list:
![image](https://user-images.githubusercontent.com/30265843/39990786-3041f55e-5776-11e8-89f1-0061660028ca.png)
* Then attach to the debugger (Click on "Gear" icon -> Select "Attach to packager" option in drop-down list)

2. Oh, I got it now. You are looking for **"Start/Stop/Restart packager"** commands.
![image](https://user-images.githubusercontent.com/30265843/39991138-34870f68-5777-11e8-9eda-0ea68c06ea9c.png)
You can control packager instance that has been started via extension by using those commands. Also, you can track packager status in status bar that is usually placed on the bottom of VS Code window:

![image](https://user-images.githubusercontent.com/30265843/39991293-be21f710-5777-11e8-84cb-b7612bed53bb.png)

![image](https://user-images.githubusercontent.com/30265843/39991304-c876a5a8-5777-11e8-88d4-f3c55b11d928.png)

Please let us know if this information helps you.

**Comment by ldhios** [comment]
@ruslan-bikkinin 
Hi, thanks for your reply. vscode debug is good than webstorm debug,through my use few days. The stability vscode also better webstorm.  That's perfect, if your fix the #625.  I will absolute deprecated chrome debug.

Thans!

**Comment by ruslan-bikkinin** [comment]
Glad to hear that your problem is solved @ldhios. I am closing this.
