### ISSUE TITLE
Reloading debugger disable all breakpoints

### ISSUE THREAD

**Issue by nicecatch** [Microsoft/vscode-react-native#698]
## Actual Behavior
1. Reloading debugger disable all breakpoints

## Expected Behavior
1. Breakpoints should not be disabled on app reload

## Software versions
- React-Native VS Code extension version:  0.6.9
- VSCode version: 1.23.0
- OS platform and version: Windows 10 Pro x64
- NodeJS version: 7.9.0
- React Native version: 0.55.4

Whenever I reload the app (after a red screen tapping or reload, throught the developer menu or stopping and restarting the development completely) all breakpoints get deactivated.

The simplest way to reactivate them is to tap on one, but this way only the bp within the same page get re activated

**Comment by ruslan-bikkinin** [comment]
Hi @nicecatch and thanks for your question. This is a known issue https://github.com/Microsoft/vscode-react-native/issues/625.
