### ISSUE TITLE
Running on iPhone 6 simulator may fail

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode-react-native#71]
Due to a react-native issue (https://github.com/facebook/react-native/issues/5850) if a simulator target is ambiguous then the simulator will not launch and running the app will most likely fail. This can happen if you have both "iPhone 6 (9.0)" and "iPhone 6 (9.0) + Apple Watch - 38mm (2.0)" as valid targets for example.

Until `react-native run-ios` is updated with a fix, you can work around the issue by manually launching the appropriate simulator prior to running the app.

**Comment by icodethings** [comment]
This will be fixed with https://github.com/facebook/react-native/pull/6043

**Comment by MSLaguana** [comment]
That's great to hear!

**Comment by mbraude** [comment]
Thanks @icodethings !
