### ISSUE TITLE
Enhancement for status bar

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode-react-native#713]
- The status bar takes message takes allot of space. Allow disable or/and custom message. Icon alone is good enough.
- If status bar is enabled; clicking on it should allow toggling start/stop package or just one click lead to quick restart.

Thx

**Comment by ruslan-bikkinin** [comment]
Hi @jas99 and thanks for your feedback. We will discuss your suggestions and come back soon.

**Comment by phatmann** [comment]
I don't use RN status bar because it is too wide. Would love icon-only mode.

**Comment by SounD120** [comment]
Hi @phatmann . Please send a feature request if you would like to see some enhancements that will be helpful for you during the extension usage.

**Comment by phatmann** [comment]
@SounD120 I thought this *was* a feature request! How do I file one?

**Comment by molant** [comment]
@phatmann you can go https://github.com/microsoft/vscode-react-native/issues/new/choose and select "Feature request" 😊

**Comment by phatmann** [comment]
Done!
