### ISSUE TITLE
[Feature Request] Select iOS Simulator for "Run iOS on Simulator" target

### ISSUE THREAD

**Issue by peterjuras** [Microsoft/vscode-react-native#714]
## Actual Behavior
1. Launching the "Run iOS on Simulator" target always starts the iPhone 6 simulator

## Expected Behavior
Launching the "Run iOS on Simulator" target should launch the app on the open simulator

or

There should be a configuration in the launch.json config specifying the name of the emulator that should be launched.

## Software versions
- React-Native VS Code extension version: 0.6.10
- VSCode version: 1.23.1
- OS platform and version: macOS 10.34.4
- NodeJS version: 9.11.1
- React Native version: 0.55.2
- XCode version: 9.4 (9F1027a)

**Comment by ruslan-bikkinin** [comment]
Hi @peterjuras and thanks for your question.

> Launching the "Run iOS on Simulator" target always starts the iPhone 6 simulator

To start running app extension is using `react-native run-ios` command. According to [official React Native docs](https://facebook.github.io/react-native/docs/running-on-simulator-ios.html), in this case it is standard behavior:

> You can specify the device the simulator should run with the --simulator flag, followed by the device name as a string. **The default is "iPhone 6"**. 

To run your app on different simulator you should create `.vscode/settings.json` file at the root of your project and fill it with the following content:
```json
{
    "react-native.ios.runArguments.simulator": [
        "--simulator", "iPhone 7"
    ]
}
```
where `iPhone 7` is the simulator name. To read more about specifying custom arguments for `react-native run-*` command, please, follow this [documentation section](https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#specifying-custom-arguments-for-react-native-run--command).

Please let us know whether it helps you or not.

**Comment by peterjuras** [comment]
Thanks this solved my issue! 👍
