### ISSUE TITLE
visual studio code1.24  could not debug react native project

### ISSUE THREAD

**Issue by LingYun** [Microsoft/vscode-react-native#718]
## error info
debug console Could not debug. Unable to find plist file to configure debugging

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.24
- OS platform and version: 10.12.6
- NodeJS version: 
- React Native version: 0.55.4

**Comment by ruslan-bikkinin** [comment]
Hi @LingYun and thanks for reaching us. Could you please open your project in XCode, click `Product->Clean` and try to debug again? Please, let us know whether it helps you. 
Also, please make sure that you can run your project via `react-native run-ios`.

**Comment by LingYun** [comment]
Hi @ruslan-bikkinin I try you say methods run project in XCode set debug again and via react-native run-ios.But vscode do not debug. I screenshot A few picture send you.
![f926aee4-167b-4ac6-b180-783f0c25db5f](https://user-images.githubusercontent.com/1118261/41133972-a20f2b9a-6afc-11e8-9668-2d3e1d6d11ba.png)
![cb37ca8c-1ab9-4402-8834-a3e12bddc981](https://user-images.githubusercontent.com/1118261/41133975-a760a9ca-6afc-11e8-8106-f8f5d08937f8.png)
![9f02d805-2781-49ad-b698-bb8826db784e](https://user-images.githubusercontent.com/1118261/41133993-cb8f332a-6afc-11e8-9908-11407565e90a.png)



![35d9522b-8194-45e6-9dec-199769359aea](https://user-images.githubusercontent.com/1118261/41133953-7c94a228-6afc-11e8-8364-a55546c72ae5.png)

**Comment by ruslan-bikkinin** [comment]
@LingYun could you please share with us the whole following logs from VS Code:

- Output of the Debug Console (View -> Toggle Debug Console):
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

**Comment by LingYun** [comment]
@ruslan-bikkinin I'm sorry.The reply is late you.  This question is because of the mac system.
Everything is normal after I reinstall the system.
Thanks for your help.

**Comment by ruslan-bikkinin** [comment]
Thanks for coming back. Glad to here that your problem has resolved. Please, don't hesitate to ask for a help if you have any other questions/issues regarding usage of the extension. I am closing this.

**Comment by DreamwareDevelopment** [comment]
This isn't solved. I'm not going to reinstall my OS just to get this working.

**Comment by ruslan-bikkinin** [comment]
@DreamwareDevelopment please submit separate issue describing your specific case and using our issue template.
