### ISSUE TITLE
Error thrown while debugging windows/WPF based project in VSCode

### ISSUE THREAD

**Issue by ncomo11** [Microsoft/vscode-react-native#719]
### Environment

react-native -v:
react-native-cli: 2.0.1
react-native: 0.55.4

npm ls rnpm-plugin-windows:
rnpm-plugin-windows@0.2.8

npm ls react-native-windows:
react-native-windows@0.55.0-rc.0

node -v:
v6.11.1

npm -v:
3.10.10

yarn --version:

Then, specify:

Target Platform: WPF
Target Platform Version(s): .NET 4.6.0 WPF
Target Device(s): Desktop
Development Operating System: Windows 10 Pro version: 1709
Visual Studio Version: 2017

###  Steps to Reproduce

(Write your steps here:)

    react-native init test
    cd test
    npm install --save-dev rnpm-plugin-windows
    npm install react-native
    react-native wpf
    In VSCode edit launch.json
    "type": "reactnative",
    "request": "launch",
    "platform": "windows"
    react-native run-wpf 
    Error thrown: "windows is not a valid platform"

###  Expected Behavior
Should be able to debug windows/wpf code in VSCode using breakpoints

###  Actual Behavior
On debugging code in VScode with platform as 'windows' in launch.json below error thrown:
"windows is not a valid platform"

**Comment by ruslan-bikkinin** [comment]
Hi @ncomo11 and thanks for submitting the issue. I will investigate it and come back soon to let you know about the results.

**Comment by ruslan-bikkinin** [comment]
Hi @ncomo11 Extension supports debugging only for windows (UWP) platform. I believe we can add support for WPF as well in the nearest future as we have already did for UWP platform here: https://github.com/Microsoft/vscode-react-native/pull/618/files.
