### ISSUE TITLE
Can't connect to debug with adb over wifi

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode-react-native#721]
Can't connect to debug with adb over wifi
Getting 
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. error: more than one device/emulator
```
Since `adb reverse tcp:8081 tcp:8081` don't work over wifi, I manually set 192.168.x.x:8081 in my dev server.

Any way i can work this thing out?

**Comment by ruslan-bikkinin** [comment]
Hi @jas99 could you please update your post with all the information from issue template?

**Comment by jas99** [comment]
Well I can but this is feature request and not bug report; `adb reverse tcp:8081 tcp:8081` is not designed to reverse tunnel over wifi, but vscode rn-extension is designed to connect debugger via hardcoded localhost port which is tunneled with adb reverse. I you can introduce option to use add android ip to directly connect with android port somehow, over the air adb rn-debugging might work.

Still let me know if you wanna post all the info.

Thx

**Comment by ruslan-bikkinin** [comment]
Hi @jas99. I could debug android application remotely over wi-fi using the following steps:
1. Install application on device and run it.
2. Set debug server host and port in `Dev Settings -> Debug server host & port for device` on device pointing to IP-address of my dev machine on which packager has been started.
3. Start packager on dev machine.
4. Open application folder in VS Code and run `Attach to debugger` configuration.
6. Enable remote JS debugging in application on device.

Could you please let us know, if it is that what are you looking for?

**Comment by jas99** [comment]
@ruslan-bikkinin Thx for getting back to me, lil hectic schedule for me over week or two but will try out at point of time; excuse me for time gap :).
But as I remember I did tried exactly all these steps and didn't worked out for me at that time. But I will gladly retry it and post my feedback. 

Thx

**Comment by ruslan-bikkinin** [comment]
Hi @jas99 also please take a look at these similar issues: https://github.com/Microsoft/vscode-react-native/issues/324, https://github.com/facebook/react-native/issues/17379. It seems that you are facing the same problem here. In this case I believe that we could close this for now, but feel free to re-open it if none of solutions suggested there would help you.
