### ISSUE TITLE
Unable to connect to packager for debugging

### ISSUE THREAD

**Issue by rakeshgits** [Microsoft/vscode-react-native#722]
## Actual Behavior
1. Not connecting to the debugger, showing the below error

OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Could not debug. <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /debuggerWorker.js</pre>
</body>
</html>

## Expected Behavior
 Should connect to packager and attach the debugger

## Software versions
- React-Native VS Code extension version: 0.6.11
- VSCode version: 1.24
- OS platform and version: MACOS HighSerria
- NodeJS version: 
- React Native version: 0.55.4
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Could not debug. <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /debuggerWorker.js</pre>
</body>
</html>

```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by jas99** [comment]
There might be also regression, in latest release, debugger started complaining of root project, 
`"react-native-tools.projectRoot": "./packages/client"`

**Comment by rakeshgits** [comment]
After adding that, it get stuck on 
```OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3```

it worked just after installing latest version, but stopped after rebooting the system

**Comment by rakeshgits** [comment]
Is there any way to go to previous versions?

**Comment by ruslan-bikkinin** [comment]
Hi @rakeshgits well, that's strange. Could you provide to us more details about your case:
* Are you trying to debug android or ios app? What command are you using: `Debug iOS`/`Debug Android` or `Attach to debugger`?
* Could you please share with us directories structure of workspace you opens? For example you can share with us screenshot of Explorer tab just like this one:
![image](https://user-images.githubusercontent.com/30265843/41342935-086f1050-6f06-11e8-8ce1-1abf35c52e85.png)
It is important to understand what directories you are opening to reproduce issue on our side.
* Are you using `.vscode/settings.json` for you project?

**Comment by jas99** [comment]
@rakeshgits yes 
1. download vsix
https://vsmobile.gallery.vsassets.io/_apis/public/gallery/publisher/vsmobile/extension/vscode-react-native/0.6.10/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
2. uninstall extension from vscode
3. update user settings to disable auto extension install `"extensions.autoUpdate": false`
4. use command pallet in vscode to install vsixpackage, remember to rename extension from .VSIXPackage to .vsix

Its pain in the ass,
so upvote my suggestion at
https://github.com/Microsoft/vscode/issues/51675

Thx

**Comment by ruslan-bikkinin** [comment]
@jas99 thanks for posting this, I just wanted to do the same as you did. :+1:

**Comment by rakeshgits** [comment]
Thanks for the response, I am debugging ios, by attaching to packager. i tried adding older version of the extention, but of no use, it still is showing the same problem.
I tried completely removing vscode, by deleting all settings and extentions, reinstalling npm and yarn.
probably it is because of the updated yarn/npm. because that is the only thing i remember doing before it stopped working suddenly, second to the updated extention before 20 hours.

 I am adding the screenshots for more info.


<img width="1680" alt="screen shot 2018-06-14 at 11 05 34 am" src="https://user-images.githubusercontent.com/11597177/41393416-58f947da-6fc3-11e8-8906-f3de2f6c9df3.png">
<img width="1680" alt="screen shot 2018-06-14 at 11 05 48 am" src="https://user-images.githubusercontent.com/11597177/41393417-59206cc0-6fc3-11e8-962c-6f7cb244fe00.png">
<img width="1680" alt="screen shot 2018-06-14 at 11 06 03 am" src="https://user-images.githubusercontent.com/11597177/41393418-59468cde-6fc3-11e8-9716-d3cca5b802a9.png">
<img width="1680" alt="screen shot 2018-06-14 at 11 06 05 am" src="https://user-images.githubusercontent.com/11597177/41393419-596e500c-6fc3-11e8-8749-6580448a405a.png">
<img width="1680" alt="screen shot 2018-06-14 at 11 06 21 am" src="https://user-images.githubusercontent.com/11597177/41393420-599668c6-6fc3-11e8-89ba-3ff03960334c.png">
<img width="1680" alt="screen shot 2018-06-14 at 11 06 27 am" src="https://user-images.githubusercontent.com/11597177/41393421-59f34848-6fc3-11e8-827b-bf5cb841d008.png">

**Comment by rakeshgits** [comment]
@ruslan-bikkinin  i tried it in a brand new mac OS, with LTS version of node, and got the same error. am i missing something in the settings? it used to work for me earlier without any modifications.

**Comment by ruslan-bikkinin** [comment]
Hi @rakeshgits 

* I noticed that you specified 0.55.6 version of React Native, but there is no such version of React Native in NPM:
![image](https://user-images.githubusercontent.com/30265843/41422557-d1de6fc0-7001-11e8-90d6-f0523327dbca.png)
May be you meant v0.55.4?

* Could you please, also, add `"trace": "verbose"` to `Attach to packager` task, try to attach to packager and share with us `About to download: ...` part of the logs in `Debug console` window. It points what URL debugger uses to download `debuggerWorker.js`.

* Does your project use Haul? If it does, please follow [this documentation section](https://github.com/Microsoft/vscode-react-native/blob/master/doc/debugging.md#debugging-with-typescript-and-haul) to set up your debug configuration for it. if it doesn't, please, make sure that you don't have `haul` package installed in `node_modules`.

**Comment by rakeshgits** [comment]
Also i am not using haul library.

i am unable to comprehend that it was working just before i restarted my system. i haven't made any modifications to anything, and suddenly after restarting i realise it stopped working

**Comment by rakeshgits** [comment]
@ruslan-bikkinin  it is haul library, thanks, it started working after removing that.

Thanks a lot for all the help.

**Comment by ruslan-bikkinin** [comment]
I'm glad to help you.

**Comment by LorienOlive** [comment]
> @ruslan-bikkinin it is haul library, thanks, it started working after removing that.
> 
> Thanks a lot for all the help.

I'm having the same issue, would you guys be able to clarify how it was solved?  I don't see anything called "haul" among the libraries I have installed.

**Comment by ruslan-bikkinin** [comment]
Hi @LorienOlive, please submit new issue.
