### ISSUE TITLE
/bin/sh: 1: adb: not found on Linux

### ISSUE THREAD

**Issue by christianmtr** [Microsoft/vscode-react-native#723]
## Actual Behavior
1. Select "React native: Run Android on device/emulator" or "Debug Android".
2. Get error "adb not found".

## Expected Behavior
1.  Select "React native: Run Android on device/emulator"
2. Run app on android device/emulator

## Software versions
- React-Native VS Code extension version: 0.6.11
- VSCode version: 1.24.0
- OS platform and version: linux x64
- NodeJS version: 10.4.0
- React Native version: 0.55.4

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: linux x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: 1: adb: not found
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Stack: Error: Failed to run the application in Android: Error while executing command 'adb devices': Command failed: adb devices
/bin/sh: 1: adb: not found

	at Function.getWrappedError (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/src/common/error/internalError.js:35:16)
	at Function.wrapError (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/src/common/error/errorHelper.js:18:44)
	at resultOfCode.done.reason (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/src/common/entryPointHandler.js:40:72)
	at _rejected (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:844:24)
	at /path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:870:30
	at Promise.when (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:1122:31)
	at Promise.promise.promiseDispatch (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:788:41)
	at /path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:604:44
	at runSingle (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:137:13)
	at flush (/path/.vscode/extensions/vsmobile.vscode-react-native-0.6.11/node_modules/q/q.js:125:13)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)

```

I know that there are a few issues like this, but I have all environment paths, in terminal works fine all commands like `adb devices`.

**Comment by ruslan-bikkinin** [comment]
Hi @christianmtr and thanks for reporting.
> in terminal works fine

Could you please clarify which terminal you mentioned: system terminal or VS Code terminal? Please make sure that `adb` works in both terminals. 

> but I have all environment paths

But anyway, could you please run `echo $PATH` and show us the output? Also, please show where and how did you export environment variables for android sdk?

**Comment by christianmtr** [comment]
Hello!
Yes. `adb` command works in both terminals.

> Could you please clarify which terminal you mentioned: system terminal or VS Code terminal? Please make sure that adb works in both terminals.

This is the output of `echo $PATH`:
```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/my/path/Android/Sdk/tools:/my/path/Android/Sdk/platform-tools
```
Thanks!

**Comment by ruslan-bikkinin** [comment]
@christianmtr could you reproduce this issue when running VS Code from terminal?

**Comment by christianmtr** [comment]
I did run VS Code from the terminal and all works fine. By this way I can run "React native: Run Android on device/emulator" or "Debug Android" and it works.

**Comment by ruslan-bikkinin** [comment]
@christianmtr Where did you set SDK exports: either in .bash_profile or .bashrc?

**Comment by christianmtr** [comment]
In `.bashrc`

**Comment by ruslan-bikkinin** [comment]
Please try to add them to ~/.bash_profile.

**Comment by christianmtr** [comment]
It's working now!
I rename the `.bashrc` to `.bash_profile` and alias commands that I had does not working.
I added the alias commands to `.bashrc` and works fine. Now I have the both files ( `.bashrc` and `.bash_profile`).
Thanks :+1:

**Comment by ruslan-bikkinin** [comment]
No problem, don't hesitate to turn to us for any help with the extension.

**Comment by detroit007** [comment]
/bin/sh: 1: adb: not found
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
Could'nt solve this issue by this method is there any other way to solve this my path is :

"  /home/hami/.npm-global/bin:/home/hami/.nvm/versions/node/v12.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.8.0_201/bin:/usr/lib/jvm/jdk1.8.0_201/db/bin:/usr/lib/jvm/jdk1.8.0_201/jre/bin:/snap/bin:/home/hami/bin:/usr/lib/jvm/java-8-openjdk-amd64/bin
  "
