### ISSUE TITLE
Duplicate module load error

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-react-native#727]
_From @echeypaz on June 11, 2018 19:19_

Bundling `index.android.js`  [development, non-minified]  0.0% (0/2), failed.
error: bundling failed: ambiguous resolution: module `f:\shoutem\aaa\extensions.js` tries to require `shoutem.about`, but there are several files providing this module. You can delete or fix them: 

  * `F:\shoutem\aaa\extensions\shoutem.about\app\package.json`
  * `f:\shoutem\aaa\extensions\shoutem.about\app\package.json`

_Copied from original issue: Microsoft/vscode#51636_

**Comment by RMacfarlane** [comment]
@echeypaz Please provide more details about how to reproduce this problem. What did you run to see this error? What version of VSCode are you using and what is your OS?

**Comment by RMacfarlane** [comment]
_From @echeypaz on June 12, 2018 7:1_

Hi @RMacfarlane, Thanks,
VSCode Version 1.24.0
Nodo 7.9.0
Arquitectura x64.
Windows 10.
I was debugg a react-native app (with react-native tools)

**Comment by RMacfarlane** [comment]
Thank you for the details! I'm still not sure how to reproduce this. Can you please describe exactly what you did to see this, or share your code? Is this an issue with VSCode itself, or is this specific to the `react-native` extension? This does not sound like a feature of VSCode itself and might be better moved to https://github.com/Microsoft/vscode-react-native

**Comment by RMacfarlane** [comment]
_From @echeypaz on June 13, 2018 6:45_

I completely agree. The problem arises when debugging with react-native-tools, because when I use the chrome debugger, after launching react-native run-android, this problem does not play. Could you move the post to the right place?

**Comment by iTOYS** [comment]
Hi @echeypaz,
Could you please provide a little sample project, if possible?

Thanks!

**Comment by iTOYS** [comment]
@echeypaz 
Just a friendly ping.

**Comment by echeypaz** [comment]
Hi, sorry, but I've been busy.
I am begining with shoutem project cloned from the builder.

Best Regards,

2018-06-19 16:55 GMT+01:00 Artem Egorov <notifications@github.com>:

**Comment by iTOYS** [comment]
@echeypaz 
How I can clone app from shoutem builder?
BTW, is it work from command line?
```
react-native run-android
```

**Comment by echeypaz** [comment]
Yes, there are shoutem CLI, you can create shoutem builder account and then
"shoutem login", "shoutem clone" ...


2018-06-19 19:41 GMT+01:00 Artem Egorov <notifications@github.com>:

**Comment by iTOYS** [comment]
I've tried to run cloned `shoutem` app in terminal and no success. 
Please try `react-native run-android` on your side.
Closing this issue for now. Feel free to reopen if all works fine for you from terminal.

Thanks!
