### ISSUE TITLE
Breakpoints is set not yet bound (Resetting does not fix issue)

### ISSUE THREAD

**Issue by VanessaChu** [Microsoft/vscode-react-native#728]
## Actual Behavior
Breakpoints is set not yet bound every time app launches. From the previous thread, I tried resetting the breakpoint, still does not work. Downgrading to VSCode 1.19 does not work. VSCode 1.24 also does not work.  

## Expected Behavior
Breakpoints be set or at least the workaround of resetting a breakpoint to work.

## Software versions
- React-Native VS Code extension version: 0.6.11
- VSCode version: 1.24.1
- OS platform and version: MacOS Sierra V10.13.4
- NodeJS version: v8.11.2
- React Native version: 0.54.4

**Comment by iTOYS** [comment]
Hi @VanessaChu,
I tested with the latest extension and vscode versions, all works fine for me. 
Could you please provide a bit more info:
* Which configuration did you run?
* Is it reproduce on `react-native init` project
* Simulator or real device(versions)
* and all what you think may be helpfull

![screen shot 2018-06-15 at 10 52 01 am](https://user-images.githubusercontent.com/4017593/41457024-020f9712-708b-11e8-92a6-d84d829b7c44.png)


Thanks!

**Comment by SantyPatrignani** [comment]
Hi mates.
I have same problem, I'm using VSCode:

![image](https://user-images.githubusercontent.com/40295423/41465535-d5bcf498-709e-11e8-9031-16a750e56a32.png)

Any help is welcome, thanks

**Comment by VanessaChu** [comment]
This is my launch configuration:
```
  {
    "name": "Debug iOS",
    "program": "${workspaceRoot}/.vscode/launchReactNative.js",
    "type": "reactnative",
    "request": "launch",
    "platform": "ios",
    "sourceMaps": true,
    "target": "iPhone 6 Plus",
    "outDir": "${workspaceRoot}/.vscode/.react"
  }
```

**Comment by VanessaChu** [comment]
Same issue on both simulator and real device.

Launch configuration for real device:
```
{
    "name": "Debug iOS Device",
    "program": "${workspaceRoot}/.vscode/launchReactNative.js",
    "type": "reactnative",
    "request": "launch",
    "platform": "ios",
    "target": "device",
    "sourceMaps": true,
    "outDir": "${workspaceRoot}/.vscode/.react"
}
```

**Comment by gagaJay** [comment]
I see why now. "Debug iOS" simply does not work when you create project with create-react-native-app cause it will run app on the expo client which will listen to different port other than 8081. you have to eject your project to make it run solely on the simulator so that it will listen to the same port as VSCode. 
Does anyone knows a way to change the listening port on "Debug iOS"?

**Comment by iTOYS** [comment]
@gagaJay
You can attach to running CRNA app with this configuration:
```
{
    "name": "Attach to packager",
    "program": "${workspaceRoot}/.vscode/launchReactNative.js",
    "type": "reactnative",
    "request": "attach",
    "sourceMaps": true,
    "port": "19001",
    "outDir": "${workspaceRoot}/.vscode/.react"
}
```

**Comment by iTOYS** [comment]
@VanessaChu 
Could you please paste following outputs here:
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the React-Native ios output channel (View -> Toggle Output -> Select React-Native ios in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by iTOYS** [comment]
@VanessaChu just a friendly ping

**Comment by delciopolanco** [comment]
Hi guys, the same happening to me using vscode 1.24.1. 

- angular 6.0.4
- angular cli 6.0.8
- node 8.11.2



![breakpoints](https://user-images.githubusercontent.com/20881846/41814646-c02d8c80-7721-11e8-9dce-d5f2422dce19.gif)

**Comment by delciopolanco** [comment]
My Bad!!!

**Comment by iTOYS** [comment]
I cant' reproduce this. 
Closing for now. Feel free to reopen if you still faced this issue.

Thanks!
