### ISSUE TITLE
vscode-react-native fails to start the debugger, where as 'react-native run-ios' does

### ISSUE THREAD

**Issue by asaravi** [Microsoft/vscode-react-native#729]
Hey guys,

I've tried reinstalling the plugin, however the issue still persists.
When I click on the Green arrow in the debugger panel to start debugging, it starts metro, goes through the build procedure, and succeeds, then I get a message in the output window that says unknown error, not all success patterns were matched.

I've pasted the outputs below. 

Running 'react-native run-ios' works as expected, and opens the chrome debugger successfully.

please let me know if you require additional information.

Thanks,

## Actual Behavior
1. Press 'Start Debugger'
2. starts metro
3. successfully builds the app
4. throws an error in metro

## Expected Behavior
1. Press 'Start Debugger'
2. starts metro
3. successfully builds the app
4. starts debugger, waiting for app to connect to it

## Software versions
- React-Native VS Code extension version: 0.6.11
- VSCode version: 1.24.1
- OS platform and version: Mac, darwin x64
- NodeJS version: v8.9.4
- React Native version: 0.54.0
- Expo SDK version (include if relevant): expo not being used

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
14:50:31, 2018-6-14
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"reactnative","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLogPoints":true}}
Could not debug. Unknown error: not all success patterns were matched.
It means that "react-native run-ios" command failed. Please, check the View -> Toggle Output -> React-native, View -> Toggle Output -> React-native: Run ios output windows.
To client: {"seq":0,"type":"event","event":"terminated"}
From client: disconnect({"restart":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning folders for symlinks in /Users/allan/Documents/PlexiaEMR3/DEV/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileApp/plexia-mobile-app/node_modules (24ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/allan/Documents/PlexiaEMR3/DEV/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileApp/plexia-mobile-app 


Metro Bundler ready.

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Entry point at /Users/allan/Documents/PlexiaEMR3/DEV/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileApp/plexia-mobile-app/index.ios.js doesn't exist. Skipping prewarming...

[Info] Building and running application.

Loading dependency graph, done.
[Error] Error: Unknown error: not all success patterns were matched.
It means that "react-native run-ios" command failed. Please, check the View -> Toggle Output -> React-native, View -> Toggle Output -> React-native: Run ios output windows.

Starting custom debugger by executing: echo A debugger is not needed:  "/Users/allan/Documents/PlexiaEMR3/DEV/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileWebApp/PlexiaMobileApp/plexia-mobile-app"
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (778/778), done.

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
```

- Output of the React-Native: Run iOS (trace: verbose):
```


** BUILD SUCCEEDED **



The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/plexia-mobile.app
Launching ca.plexia.Plexia-Mobile
ca.plexia.Plexia-Mobile: 5389
```

**Comment by iTOYS** [comment]
Hi @asaravi,
Could you please run commands below in your project root and paste output here:

```bash
ls -la ./ios
```

```bash
/usr/libexec/PlistBuddy -c "Print:CFBundleIdentifier" ./ios/build/Build/Products/Debug-iphonesimulator/plexia-mobile.app/Info.plist
```

Thanks!

**Comment by iTOYS** [comment]
Could you also please run:
```
/usr/libexec/PlistBuddy -c "Print:CFBundleIdentifier" "./ios/build/Build/Products/Debug-iphonesimulator/plexiaMA.app/Info.plist"
```
I suppose that result will be like:
```
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

This goes because we expect that  `Debug-iphonesimulator/<app_name>.app/Info.plist` should be the same as `<app_name>.xcodeproj`.

https://github.com/Microsoft/vscode-react-native/blob/14ebf4e6fdee5f69a41d9a7deea4dc164dd28b7e/src/extension/ios/plistBuddy.ts#L25-L33

**Comment by asaravi** [comment]
Hi @iTOYS 

I've researched your comment a bit, and decided to remove the space in the project name, and run 'react-native-rename' to rename the project more correctly. 

However after running that, vscode-react-native was still creating a "Plexia Mobile.app" bundle inside the build folder. I manually modified these files to "PlexiaMobile.app" wherever it was written with a space:
```
./ios/<app name>.xcodeproj/project.pbxproj
./ios/<app name>/xcshareddata/xcschemes/<app name>.xcscheme
```
I'm not sure which section in Xcode allows you to modify the above xml files as I'm not too familiar with Xcode.

I then went in Xcode and changed "CFBundleDisplayName" to "Plexia Mobile"
This seems to be working.

Thank you for your help!

**Comment by iTOYS** [comment]
Unfortunately we can't detect app name if it different with project name. If you'd like to use different name you can run app with `react-native run-ios` and attach with vscode for debug(`Attach to packager`)

**Comment by rluncasu** [comment]
same issue here

**Comment by SounD120** [comment]
Hi @rluncasu . Please create a new issue for your specific case.
