### ISSUE TITLE
Run iOS commands not respecting projectRoot setting

### ISSUE THREAD

**Issue by peterjuras** [Microsoft/vscode-react-native#732]
## Actual Behavior
Similar to the `Run Android` extension command, `Run iOS (simulator|device)` should be run from the projectRoot folder

## Expected Behavior
The `Run iOS (simulator|device)` commands are being run from the workspace root, often leading to an `unknown command 'run-ios'.` error in monorepos.

Most likely, this is due to the differences how the project root is retrieved, when you compare the [Android](https://github.com/Microsoft/vscode-react-native/blob/master/src/extension/commandPaletteHandler.ts#L146) and [iOS](https://github.com/Microsoft/vscode-react-native/blob/master/src/extension/commandPaletteHandler.ts#L182) code.

## Software versions
- React-Native VS Code extension version: 0.6.11
- VSCode version: 1.24.1
- OS platform and version: macOS 10.13.5
- NodeJS version: 9.11.2
- React Native version: 0.55.2

**Comment by iTOYS** [comment]
Hi @peterjuras 
Thanks for pointing us!
Fixed in #733
