### ISSUE TITLE
Editing code in debugging mode while breakpoints are set, might change the position of the breakpoints to incorrect places, or remove them at all

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-react-native#74]
If breakpoints are set on a source file, and then we start editing that file, sometimes breakpoints will be moved to incorrect places, and sometimes they might even be removed completely.

**Comment by MSLaguana** [comment]
Note that this should only happen if you are currently in debug mode while making edits. If the debugger is not active, breakpoints should remain in the correct location.

**Comment by Mokto** [comment]
Also having this issue.

Please note that sometimes, when passing through breakpoints, they also disappear from the editor. They are still internally here because if I reload simulator, they are being handled.

**Comment by Gentlee** [comment]
also they often appear on the last line and can't be removed

**Comment by mbraude** [comment]
Let's close this issue since the real issue is tracked in the vscode repo.
