### ISSUE TITLE
Login to exponent

### ISSUE THREAD

**Issue by MartinMasek** [Microsoft/vscode-react-native#744]
I want to debug iOS mobile app on my Mac and I use VSCode and react-native plugin. I was able to install everything successfully but when I click on the green arrow to debug my app, I get a small notification window at the bottom saying:

"You need to login to exponent. Please provide username and password to login. If you don't have an account we will create one for you."

I know my login and password but I don't know where to enter it. The notification window doesn't have any call to action.

I tried running npm start and open my iOS emulator. I am logged-in in Expo app but when I click the green debug arrow, the problem still continues.

## Actual Behavior
1. I selected "Debug in Exponent"
2. I clicked the green debug arrow.
2. Notification window saying that I have to log-in to Expo appeared.

## Expected Behavior
1. After clicking the green button, iOS emulator is started or I am pointed to a place where I have to enter my credentials.

## Software versions
- React-Native VS Code extension version: 0.6.12
- VSCode version: 1.25
- OS platform and version: macOS High Sierra 10.13.5
- NodeJS version: 8.11.3
- React Native version: 0.55.4

**Comment by MartinMasek** [comment]
I resolved it like this:
installed exp through npm:
npm install -g exp
run command:
exp login

**Comment by Dagurmart** [comment]
This should be addressed though
