### ISSUE TITLE
Module HMRClient is not a registered callable module (calling enable) __callFunction index.bundle?

### ISSUE THREAD

**Issue by rmrudro** [Microsoft/vscode-react-native#756]
## Actual Behavior
1. Hello I'm new in React-native I have a problem with building react-native first I have faced react-native Version After I downgrade and recreate project I can build into my android emulator . Please Note that I'm using Windows OS. then I make a separate directory for component then and i change it in index.js for that directory. whenever i did I find this error .
Module HMRClient is not a registered callable module (calling enable) __callFunction index.bundle?
_callfuntion
2. 

## Expected Behavior
1. Expected Behavior is to App.js file output  
2. 

## Software versions
- React-Native VS Code extension version: 0.55.4
- VSCode version: 1.25.0
- OS platform and version: Windows 10
- NodeJS version: 10.7.0
- React Native version: 0.55.4
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by rmrudro** [comment]
First I reload by pressing R,R then I react-native run-android after cleaning gradle in last build

**Comment by ruslan-bikkinin** [comment]
Seems to be that something wrong directly with your react-native project and it's not related with React Native Tools extension. I believe that a better place for discussing such kind of problems is [react-native](https://github.com/facebook/react-native/issues) repo. 
I am closing this issue, please, feel free to re-open if needed.
