### ISSUE TITLE
Can't debug if build configuration is different than Debug

### ISSUE THREAD

**Issue by sregg** [Microsoft/vscode-react-native#764]
I followed this article https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5 to have different build variants pointing to different environments (e.g. dev, staging, prod).

I have these 4 build configurations:
- Debug
- Release
- Dev.Debug
- Dev.Release

and these 2 schemes:
- appname (using Debug and Release)
- appname-dev (using Dev.Debug and Dev.Release)

Dev.Debug and Dev.Release have a different bundle id (com.appname.dev) than Debug and Release (com.appname).

I manage to make everything install and run fine using this VS code extension using `runArguments` in `launch.json` like so:

```
{
  "name": "Debug iOS - iPhone X - Dev",
  "program": "${workspaceRoot}/.vscode/launchReactNative.js",
  "type": "reactnative",
  "request": "launch",
  "platform": "ios",
  "sourceMaps": true,
  "outDir": "${workspaceRoot}/.vscode/.react",
  "runArguments": [
    "--simulator=iPhone X",
    "--scheme=appname-dev",
    "--configuration=Dev.Debug"
  ]
},
{
  "name": "Debug iOS - iPhone X - Prod",
  "program": "${workspaceRoot}/.vscode/launchReactNative.js",
  "type": "reactnative",
  "request": "launch",
  "platform": "ios",
  "sourceMaps": true,
  "outDir": "${workspaceRoot}/.vscode/.react",
  "runArguments": [
    "--simulator=iPhone X",
    "--scheme=appname",
    "--configuration=Debug"
  ]
}
```

The only issue is that the debugger doesn't seem to work properly and I see this error in the DEBUG CONSOLE tab:

```
Could not debug. Error while executing command '/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/simonreggiani/dev/appname/ios/build/Build/Products/Debug-iphonesimulator/appname.app/Info.plist'': Command failed: /usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' '/Users/simonreggiani/dev/appname/ios/build/Build/Products/Debug-iphonesimulator/appname.app/Info.plist'
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

The issue is that `/Users/simonreggiani/dev/appname/ios/build/Build/Products/Debug-iphonesimulator/appname.app/Info.plist` doesn't exist.
But `/Users/simonreggiani/dev/appname/ios/build/Build/Products/Dev.Debug-iphonesimulator/appname.app/Info.plist` does exist.

The difference is the build configuration `Dev.Debug` instead of `Debug`.

Would it be possible to have a param of the `reactnative` launch type that would specify the build configuration?

If that makes sense, I'd be happy to send a PR with that change.

## Actual Behavior
1. Have a project with different build configurations in Xcode
2. Launch debug
3. Debug doesn't work

## Expected Behavior
1. Have a project with different build configurations in Xcode
2. Launch debug
3. Debug works

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.25.1
- OS platform and version: 0.6.13
- NodeJS version: v8.11.3
- React Native version: 0.56.0

**Comment by ruslan-bikkinin** [comment]
Hi @sregg and thanks for submitting the issue. Yes, you are right, extension doesn't support yet such scenarios.

> Would it be possible to have a param of the reactnative launch type that would specify the build configuration?
> If that makes sense, I'd be happy to send a PR with that change.

Yes, sure, we'd love to get such a contribution. Please, don't hesitate to ask us if you need any help.

**Comment by iTOYS** [comment]
Hi @sregg,
I've added support for this in https://github.com/Microsoft/vscode-react-native/pull/766
If you'd like you can try it.([Development setup](https://github.com/Microsoft/vscode-react-native/blob/master/CONTRIBUTING.md#development-setup))

Thanks!
