### ISSUE TITLE
Debug adapter process has terminated unexpectedly when attempting to run any debug configuration

### ISSUE THREAD

**Issue by rsouthgate** [Microsoft/vscode-react-native#767]
This appears related to this SO question/solution: https://stackoverflow.com/questions/47650633/react-native-debug-adapter-process-has-terminated-unexpectedly/47932583#47932583

In my project I definitely do not get a .react folder created in the .vscode folder. There is also nothing else in that folder. I have been through all the suggestions on how to fix this as it appears to be some thing to do with permissions. But nothing works so I wonder if it's been outdated with later versions of vs code.

## Software versions
- React-Native VS Code extension version: 0.6.13
- VSCode version: 1.25.1
- OS platform and version: Mac OS 10.13.6
- NodeJS version: 8.1.3
- React Native version: 0.56.0

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
(I think the install has not completed correctly since this output is not listed in the listbox...)

**Comment by iTOYS** [comment]
Hi @rsouthgate 
Thanks for reaching us.
Could you please reinstall extension, setup [extended logging](https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#logging) and try again?

Please note that you should reload VSCode window to apply settings changes:
```
Shift+Cmd+P > Reload Window
```
Please paste outputs here as mentioned in [ISSUE_TEMPLATE.md](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md)

Thanks!

**Comment by rsouthgate** [comment]
Hi,
I tried to do that... In my workspace settings the react-native-tools is highlighted as an unknown configuration setting - so not sure the set up and installation is even getting far enough to register settings... After installing and setting the log level the only thing I can see in the logs is in the Log (Window) output when I attempt to start a debug session and I see this:

> [2018-08-11 09:24:56.294] [renderer1] [error] spawn react-native ENOENT: Error: spawn react-native ENOENT
> 	at exports._errnoException (util.js:1050:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 	at onErrorNT (internal/child_process.js:367:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 	at process._tickCallback (internal/process/next_tick.js:104:9)

I'm not sure whether this is related to the react-native-tools module or not since the stack doesn't go very far!

Anything else I can try?

**Comment by iTOYS** [comment]
@rsouthgate 
Seems like you haven't have globally installed `react-native-cli`
```
npm install -g react-native-cli
```
Please install it and try to debug again.

Thanks

**Comment by rsouthgate** [comment]
Sorry, you're right. It worked straight away after that!
