### ISSUE TITLE
[feature] Element Inspector for react native inside vscode

### ISSUE THREAD

**Issue by tavrez** [Microsoft/vscode-react-native#791]
It would be nice if we have a element inspector, just like what nuclide(and react-dev-tools) already has, inside vscode. Sorry if it's duplicate, I didn't found anything related here

**Comment by ruslan-bikkinin** [comment]
Hi @tavrez as first step we have added pallete command to start React Dev Tools in the extension and it will be included in upcoming 0.6.19 version.
