### ISSUE TITLE
error: unknown option `--root'

### ISSUE THREAD

**Issue by Bobozee** [Microsoft/vscode-react-native#797]
## Actual Behavior
1. The packager does not start

## Expected Behavior
1. The packager starts

## Software versions
- React-Native VS Code extension version: 0.6.16
- VSCode version: 1.27.2
- OS platform and version: OSX macOS Hight Sierra 10.13.6
- NodeJS version: 8.11.3
- React Native version: 0.57.0
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. Could not start the packager.
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager


  error: unknown option `--root'

[Error] Error: Could not start the packager.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
 INFO no standard startup: panel is active
extensionService.ts:917 [PeterJausovec.vscode-docker]: Command `vscode-docker.delete-ACR-Image` appears multiple times in the `commands` section.
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] (node:38429) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:136
```

**Comment by ruslan-bikkinin** [comment]
Hi @Bobozee and thanks for reaching us. We already have a fix for this (please see https://github.com/Microsoft/vscode-react-native/issues/790) that will be included in upcoming 0.6.17. Closing this as a duplicate.
