### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by semenyakNik** [Microsoft/vscode-react-native#812]
gulp-util has been deprecated. Continuing to use this dependency may prevent the use of web-build-tools with version 4 of Gulp.

The README.md lists alternatives for all the components so a simple replacement should be enough.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- gulpjs/gulp-util#143

**Comment by ruslan-bikkinin** [comment]
Hi @semenyakNik and thanks for your contribution. We've merged your changes with some slightly updates from our side so they will be included in upcoming release. I am closing this.
