### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-react-native#827]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by ruslan-bikkinin** [comment]
Hi @mjbvz and thanks for warning us. Could you please clarify the following items:
* Since which version of `vscode` package webview API was introduced?
* Since which version of VS Code it supports webview API?

**Comment by ruslan-bikkinin** [comment]
@mjbvz thanks for reply. How can we get any logs from webview like console.log() outputs or maybe errors  outputs? Does it support it?

**Comment by SounD120** [comment]
Hi @mjbvz . 
We use `previewHtml` to render web page `exp://192.168.10.76:19000/` is generated by Expo Framework, which have unstandard scheme `exp://`. This is the code we use:
```
vscode.commands.executeCommand("vscode.previewHtml", vscode.Uri.parse(exponentUrl), 1, "Expo QR code");
```
and it renders such a page:![2018-11-13_18-44-01](https://user-images.githubusercontent.com/32372875/48425635-484d9000-e776-11e8-8aa5-14c70e65bd10.png) Looks like previewHtml magically resolves `exp://`, but we didn't find any documantation how to do the same with WebView API. Could you please clarify what exactly we need to do to get WebView API work this way?

**Comment by SounD120** [comment]
Hi @mjbvz . We migrated from `vscode.previewHtml` to new VS Code WebView API for this extension. Thanks.
