### ISSUE TITLE
Simplify generated launch.json 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-react-native#830]
Hey,

VSCode dev here. This milestone I am looking into simplifing generated `launch.json` for various extensions Microsoft/vscode#62851

The `launch.json` that react native generates is attached at the end. This is too complex for the avarage user and we can improve. I suggest to simplify it the following way:

- [x] Start using [`DebugConfigurationProvider`](https://github.com/Microsoft/vscode/blob/b4c6906b62e3199eee87c17649979939a4e43323/src/vs/vscode.d.ts#L8191) and remove `initialConfigurations` from the package.json. This will give us a dynamic way of contributing configurations
- [x] `DebugConfigurationProvider` should use the `quickPick` to ask the user if he would like to launch android, launch ios, launch launch exponent or to attach. After that it should just generate one file
- [x] Remove default fields which are not necessery like `sourceMaps`, and `outDir`. They should have the respective default values `true` and `"${workspaceRoot}/.vscode/.react"`
- [x] You are already contributing `configuraitonSnippets` which is great. However these snippets also need to be simplified. I suggest to remove all default attributes like  sourceMaps and outDir

If you agree with the suggestions I am making here I am also here to help with any potential questions you might have. The changes should not require a lot of work but will simplify the flow a lot imho. It should be much less complex and not too much like a wizard experience

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Attach to packager",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Debug in Exponent",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        }
    ]
}
```

**Comment by isidorn** [comment]
Are there any plans to address this?
Do you agree with my suggesstions here?
If you do not have cycles to address this but would like to see it done, I can try to get some users to provide a PR which tackles this.

**Comment by ruslan-bikkinin** [comment]
Hi @isidorn and thanks for your proposal. We have added it to our backlog and will pick it up in order of priorities. It is near the top so I think we will be able to work on it soon. Nevertheless, we need to investigate and discuss your suggestions with the team to make sure that everything would be fine in terms of user expirience. We wil keep you posted.

**Comment by isidorn** [comment]
@ruslan-bikkinin awesome, thanks a lot for your reply. Let me know if we can help somehow or if you have questions.

**Comment by ruslan-bikkinin** [comment]
Hey @isidorn, does something form your list is getting deprecated in nearest version of VS Code and we should take care of it ASAP?

**Comment by isidorn** [comment]
@ruslan-bikkinin no, nothin is getting deprecated.
I am just providing suggestions on how we should improve this process, I would love if we could tackle this but there is no rush.

**Comment by SounD120** [comment]
Hi @isidorn . We have finished simplifying `launch.json` generation workflow. Thanks for your proposal.
