### ISSUE TITLE
Flutter - VS Code - Gradle task assembleDebug failed

### ISSUE THREAD

**Issue by ravirsrsrs** [Microsoft/vscode-react-native#835]
I have created a flutter project on vs code a week ago. 
i opened it now. but, it is showing error. I have used firebase in my project.
but, this error is not showing for new projects.

Running "flutter packages get" in flutter_tictactoe...           3.0s
Launching lib\main.dart on Google Pixel XL, 8 0, API 26, 1440x2560 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.1,16.0.1]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by ruslan-bikkinin** [comment]
Hi @ravirsrsrs and thanks for reaching us. Seems to be that your problem is related to Gradle or Flutter, but not to the extension. I suggest you to turn to [Fultter support](https://github.com/flutter/flutter/issues) or [Gradle support ](https://gradle.org/help/) pages as more relevant places for your question.

**Comment by arshadmo** [comment]
iam having the issue can anyone help me out
