### ISSUE TITLE
VSCODE_TSJS environment variable is not set

### ISSUE THREAD

**Issue by taypo** [Microsoft/vscode-react-native#84]
React Native extension installation does not set VSCODE_TSJS to 1.

Extension page implies that is set during installation.
https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native#enabling-intellisense

Manually setting the variable enables salsa as desired.

**Comment by MSLaguana** [comment]
When you open a react-native project with our extension, if the environment variable is not set then you should be prompted with an info message at the top of the window. Did that not happen for you?

**Comment by taypo** [comment]
Yes there was a message saying intelli sense has been enabled and I should restart vscode. But it kept popping up after every restart. And it went away when I set the var myself.

If it matters, I installed the extension while the project was already open in vscode.

**Comment by MSLaguana** [comment]
Were you running on a mac, and if so how were you restarting vs code? On a mac the vscode process does not fully close unless you close using the menu bar or `cmd-q`, so it would not pick up environment variable changes.

**Comment by taypo** [comment]
I was on windows 7 enterprise. And it was reproducable. Each six member of my team had the same issue.

**Comment by MSLaguana** [comment]
Sounds like we're doing something wrong there. I suspect that it's to do with how we check the OS to determine how to configure environment variables.

**Comment by joshuaskelton** [comment]
This was resolve with #115
