### ISSUE TITLE
[Spelling] found should be find

### ISSUE THREAD

**Issue by rensutheart** [Microsoft/vscode-react-native#842]
A spelling mistake in the warning. It should read "Could not **find** workspace while activating"

https://github.com/Microsoft/vscode-react-native/blob/0d28fb4d04eedfb16f15414d4ca88bce75586cd3/src/extension/rn-extension.ts#L67

**Comment by ruslan-bikkinin** [comment]
Hi @rensutheart and thanks for letting us know. Nice catch!
