### ISSUE TITLE
using expo: .vscode/exponentIndex.js not found

### ISSUE THREAD

**Issue by Morriz** [Microsoft/vscode-react-native#846]
## Actual Behavior
1. debugger started
2. first request kills debugger

## Expected Behavior
1. debugger to continue

## Software versions
- React-Native VS Code extension version: 0.7.0
- VSCode version: 1.29.1
- OS platform and version: OSX 10.14.1
- NodeJS version: 11.2.0
- React Native version:
react-native-cli: 2.0.1
react-native: 0.57.7
- Expo SDK version (include if relevant):
31.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```

```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
BUNDLE  [ios, dev] .vscode/exponentIndex.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4362 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///Users/Morriz/.vscode/extensions/mgmcdermott.vscode-language-babel-0.0.21/grammars/Babel-Language.json
e.register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4362
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1446  INFO standard startup
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] Git extension API method 'getGitPath' is deprecated.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] (node:18318) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by ruslan-bikkinin** [comment]
Thanks for moving it here @Morriz. Have `.vscode/exponentIndex.js` file been created after the debugging session had stopped? Seems to be that packager could find it. Please, also, show us what debug configuration do you use and what app are you trying to debug: Expo one or pure React native one?

**Comment by Morriz** [comment]
> Thanks for moving it here @Morriz. Have `.vscode/exponentIndex.js` file been created after the debugging session had stopped? Seems to be that packager could find it. Please, also, show us what debug configuration do you use and what app are you trying to debug: Expo one or pure React native one?

I am using the expo one (as mentioned in the bug report title). But no,  no such file is created. Only the `.react/debuggerWorker.js` file. Here's my config
```
        {
            "name": "Debug in Exponent",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "trace": "verbose",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        }
```

**Comment by Morriz** [comment]
A more complete output of the ReactNative console:
```
::ffff:192.168.178.12 - - [29/Nov/2018:15:06:37 +0000] "GET /.vscode/exponentIndex.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=$PROJECT_DIR%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles HTTP/1.1" 200 - "-" "Expo/2.9.0.103161 CFNetwork/976 Darwin/18.2.0"
error: bundling failed: Error: The resource `$PROJECT_DIR/.vscode/exponentIndex.js` was not found.
    at $PROJECT_DIR/node_modules/metro/src/IncrementalBundler.js:122:24
    at gotStat (fs.js:1619:21)
    at $PROJECT_DIR/node_modules/graceful-fs/polyfills.js:282:31
    at FSReqCallback.oncomplete (fs.js:161:21)
 BUNDLE  [ios, dev] .vscode/exponentIndex.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```
(I replaced the project dir refs with `$PROJECT_DIR`)

@hatton did you not have the same problem as me before?

**Comment by Morriz** [comment]
nevermind, I now got it working by resetting the expo client...breakpoints are working now too!

**Comment by hatton** [comment]
So, this was closed, and I can debug, but I'm still not clear why .vscode/exponentIndex.js  is not created. I'm finding [the documentation section](exponentIndex.js) that mentions it unclear... is this perhaps only created if you are *not* using expo? If so, we could improve the title of this section to "Configuring Expo when not using the Expo SDK".
