### ISSUE TITLE
IntelliSense/React-Native tools NOT enabled on Mac after opening React Native project root directory in VS Code

### ISSUE THREAD

**Issue by mgleason** [Microsoft/vscode-react-native#86]
a) Installed VS Code 0.10.9 on my Mac running OS X El Capitan.
b) Created a new project by running this in the terminal > react-native init AwesomeProject 
c) Tried opening the AwesomeProject 3 ways:
   1) Start VS Code, from File menu choose "Open", browse to AwesomeProject and open it
   2) > code ./AwesomeProject
   3) > cd AwesomeProject; code .
...but VS Code never recognized it was a React project
  - Never saw the: "React Native was successfully configured for this project. Restart to enable it" message
  - Open index.ios.js and it shows 35 errors and 24 warnings

**Comment by MSLaguana** [comment]
In your steps above you do not list installing the react-native extension for vscode. If you did not, you will need to hit `cmd-p`, type `> ext install` and select install extension, then type react-native  and select the react native tools preview:

![image](https://cloud.githubusercontent.com/assets/14098340/13365255/d3ef1fda-dc88-11e5-8026-5f93e313ec08.png)

**Comment by mgleason** [comment]
@MSLaguana - Apologies, after reading the 0.10.8 release notes I somehow assumed it was "built-in" as of 0.10.8.  Thanks for pointing out what was probably obvious.

To be fair, the first step in the Getting started could be changed to two steps:

> * Be sure you're running VS Code 0.10.8+
> * Install the react-native extension: cmd-shift-p, type "> ext install", then type "react-native" and  select the react native tools preview
...

Currently it reads:

> Getting started
> * Install the extension in VS Code (0.10.8+)
> * Run npm install -g react-native-cli to install React Native CLI (0.1.10+)
> * Set up React Native (0.19+) using the steps detailed on the React Native getting started documentation

...

**Comment by digeff** [comment]
We fixed this. Now the read-me looks like:
![image](https://cloud.githubusercontent.com/assets/14098140/14027153/78ee2d70-f1b3-11e5-8cf8-9f42eecdc6b5.png)
