### ISSUE TITLE
Can't debug Expo app

### ISSUE THREAD

**Issue by mustafahafidi** [Microsoft/vscode-react-native#863]
## Actual Behavior
1. The extension throws "Error: React Native is not installed. Please run `npm install` in your project directory."
2. if I comment out the resolution of "react-native/local-cli/cli.js" from the extension's source code (Doctor.js), the extension keeps on running and shows a QR code, but the expo app cannot load it. Visiting the expo url through http I receive: "{"error":"Error: Cannot find module 'expo/tools/hashAssetFiles'"}", even though that module actually exists.

## Expected Behavior
1. Run and debug the Expo app

## What works
1. Running the app without the extension works perfectly fine

## Software versions
- React-Native VS Code extension version: 0.7.0
- VSCode version: 1.30.0
- OS platform and version: Win 10
- NodeJS version: 8.11.1 
```
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
```

**Comment by ruslan-bikkinin** [comment]
hi @mustafahafidi and thanks for reaching us. Did you try solution from this https://github.com/Microsoft/vscode-react-native/issues/857#issuecomment-446605727?

**Comment by mustafahafidi** [comment]
It works thanks! sorry I missed that comment.

> hi @mustafahafidi and thanks for reaching us. Did you try solution from this [#857 (comment)](https://github.com/Microsoft/vscode-react-native/issues/857#issuecomment-446605727)?
