### ISSUE TITLE
Error: Cannot start packager (Expo project)

### ISSUE THREAD

**Issue by devlinb** [Microsoft/vscode-react-native#869]
## Actual Behavior
1. Running Debug in Exponent result in following errors in the "react native" output
    ENOENT: no such file or directory, stat ''
    [Error] Error: Could not start the packager.

## Expected Behavior
1. Debugger starts

A new launch file was created by the extension, I didn't have an existing one.
FWIW launchReactNative.js doesn't exist.

## Software versions
- React-Native VS Code extension version: 0.7.0
- VSCode version: 1.30.1
- OS platform and version: Windows 10 17134
- NodeJS version: 8.9.0
- React Native version: 
- Expo SDK version (include if relevant): 30

- Output of the Debug Console (View -> Toggle Debug Console):
(I enabled verbose)
```    
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateRequest":false}}
Handle launch request: {
  "name": "Debug in Exponent",
  "program": "C:\\Users\\com2k\\thawd-app/.vscode/launchReactNative.js",
  "type": "reactnative",
  "request": "launch",
  "platform": "exponent",
  "sourceMaps": true,
  "outDir": "C:\\Users\\com2k\\thawd-app/.vscode/.react",
  "trace": "verbose",
  "__sessionId": "691caa7d-5ac4-47ef-86cc-61ed9a46d171"
}
Could not debug. Could not start the packager.
To client: {"seq":0,"type":"event","event":"terminated"}
From client: disconnect({"restart":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"FullSessionStatistics/SourceMaps/Overrides","data":{"aspNetClientAppFallbackCount":0}}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}

```

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

```
Debugger listening on ws://127.0.0.1:44172/ea4b1574-015e-492b-a7d1-144e611a4a09
For help see https://nodejs.org/en/docs/inspector

console.ts:134 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
t.log @ console.ts:134
console.ts:134 [Extension Host] GET https://api.github.com/user/repos 
console.ts:134 [Extension Host] 401 Bad credentials 
console.ts:134 [Extension Host] Failed to connect to provider "Connection with GitHub Client failed. Please make sure your git executableis setup correct, and your token has enought access rights."
console.ts:134 [Extension Host] GET https://api.github.com/user/repos 
console.ts:134 [Extension Host] 401 Bad credentials 
console.ts:134 [Extension Host] 2018-12-19T19:06:06.516Z - debug: [TypescriptHero] Setting up extension and activatables.
console.ts:134 [Extension Host] 2018-12-19T19:06:06.517Z - debug: [ImportOrganizer] Setting up ImportOrganizer.
console.ts:134 [Extension Host] 2018-12-19T19:06:06.517Z - debug: [TypescriptHero] Starting up extension and activatables.
console.ts:134 [Extension Host] 2018-12-19T19:06:06.517Z - info: [ImportOrganizer] Starting up ImportOrganizer.
console.ts:134 [Extension Host] (node:44904) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:134
console.ts:134 [Extension Host] 2018-12-19T19:20:42.789Z - debug: [ImportOrganizer] OrganizeOnSave is deactivated through config
```

**Comment by devlinb** [comment]
Setting "react-native.packager.port": 19001 lets me use "Attach to Packager", which works really well! Loving the experience!

**Comment by ruslan-bikkinin** [comment]
Hi @devlinb and thanks for contacting us. Seems to be that you need to clean your metro bundler cache. Please try these commands and let us know if it helps:
```shell
del %TEMP%\react-native-* & ^
del %TEMP%\metro-cache* & ^
del %APPDATA%\Temp\react-native-* & ^
del %APPDATA%\Temp\metro-cache* & ^
del node_modules & ^
npm cache clean --force & ^
npm install
```

**Comment by ruslan-bikkinin** [comment]
Hi @devlinb do you have a chance to look at this?

**Comment by devlinb** [comment]
Hi @ruslan-bikkinin, I was out for the holidays, I'll see if this fixes it on Monday and report in.

**Comment by devlinb** [comment]
Hi @ruslan-bikkinin same issue after running the commands, and rebooting even!

Also of note, only the following files are in the .vscode directory

    1,913 launch.json
    147 settings.json

I have also noticed that if expo is already running and I press "debug in exponent" in VSCode, that the error

    [Error] Error: Error while executing command 'taskkill /pid 6676 /T /F': Command failed: taskkill /pid 6676 /T /F
    ERROR: The process "6676" not found.

shows up in the Output.

I checked what PIDs Expo is using, and indeed none of the 9 (!!!) processes that ```expo start```  kick off have the PID of 6676

**Comment by devlinb** [comment]
Upgrading to expo 32, deleting node_modules, and the package.lock file (which was apparently causing lots of issues), fixed this.

I'm getting gallons of warnings and errors, e.g. 

    No issue with doctor-watchman-versionNo issue with doctor-watchman-versionNo issue with doctor-watchman-version

is repeated 20+ times and breakpoints aren't working, but I can connect now!

Console.log output is working however, huh.

Anyway, these all sound like separate issues, so I'm closing this one out! Thank you for your help!
