### ISSUE TITLE
Cannot find module 'expo/tools/hashAssetFiles'

### ISSUE THREAD

**Issue by SounD120** [Microsoft/vscode-react-native#878]
## Actual Behavior
1. Ran "Debug on Exponent" debug scenario on **pure React Native application**
2. Get some Expo error like something went wrong, or receive Metro bundler error.
3. Get `{"error":"Error: Cannot find module 'expo/tools/hashAssetFiles'"}` error instead of getting Expo app information that is needed for debugging on `localhost:19000` host.

## Expected Behavior
Expo app starts debugging

## Software versions
- React-Native VS Code extension version: 0.7.0
- VSCode version: 1.30.1
- OS platform and version: Windows 10, macOS Mojave 10.14.2, (Linux is not tested yet, but may be affected)
- NodeJS version: 8.12
- React Native version: 0.57.8
- Expo SDK version (include if relevant): 31.0.0

This behaviour is connected to a [bug described in this issue](https://github.com/expo/expo-cli/issues/255) that reproduces on latest `xdl@52.0.13` package. 
Until this situation is resolved you can use such solution:
1. Open `vsmobile.vscode-react-native-0.x.x` extension folder in your VS Code extensions folder.
   * **Windows:** `%USERPROFILE%\.vscode\extensions`
   * **macOS:** `~/.vscode/extensions`
   * **Linux:** `~/.vscode/extensions`
2. Open `node_modules`, find and delete `xdl` folder.
3. Open `vsmobile.vscode-react-native-0.x.x` extension folder in terminal and run this command
```
npm i xdl@52.0.9 --no-save
```
4. Close and reopen VS Code.

**Comment by SounD120** [comment]
Due to [official Expo team commentary](https://github.com/expo/expo-cli/issues/255#issuecomment-453214632) all RN projects that is going to be ran using expo must have installed expo package. To solve the issue run `npm i expo --save-dev`

**Comment by hadpro24** [comment]
> Due to [official Expo team commentary](https://github.com/expo/expo-cli/issues/255#issuecomment-453214632) all RN projects that is going to be ran using `expo` must have installed `expo` package. To solve the issue run `npm i expo --save-dev`

This solution not work for me

**Comment by SounD120** [comment]
Hi @hadpro24, @HopeKD  . Please describe your problems in separate issues.
