### ISSUE TITLE
Debug what happens when 'Start Debugging' pressed

### ISSUE THREAD

**Issue by supagu** [Microsoft/vscode-react-native#884]
## Actual Behavior
I recently refactored my project and now when I press 'start Debugging' the blue progress bar goes for a bit, then stops with no indication of an error.

I can still run my app fine using the command line, so something is going wrong with visual studio, and there is no output to show me what is wrong.

## Expected Behavior
Debugging to run successfully...

## Software versions
- React-Native VS Code extension version: 0.8.0
- VSCode version: 1.29.1
- OS platform and version: Arch/Manajaro Linux
- NodeJS version: 8.9.3
- React Native version: 2.0.1

**Comment by ruslan-bikkinin** [comment]
hi @supagu and thanks for questioning. In VS Code 1.29 were some problems with debug console outputs including not showing it if debugging session has not been started. Please, try to update to the VS Code 1.30 or higher where this problem is resolved.

**Comment by supagu** [comment]
Thanks, problem turned out to be I was missing package.json
