### ISSUE TITLE
[Error] Error: Unknown error: not all success patterns were matched.   It means that "react-native run-android" command failed.   Please, check the View -> Toggle Output -> React Native,   View -> Toggle Output -> React Native: Run android output windows. (error code 712)

### ISSUE THREAD

**Issue by harryharihar** [Microsoft/vscode-react-native#898]
## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by ruslan-bikkinin** [comment]
Hi @harryharihar and thanks for reaching us. You didn't provide any details about your environment, so I am closing this issue due to lack of technical information. Please create a new one and next time fill all gaps in issue template.

**Comment by RichardsonVJohnson** [comment]
i am getting the same issue

**Comment by SounD120** [comment]
Hi @RichardsonVJohnson and thanks for reaching us. Please create new issue for your specific case and describe your problem using our [issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md).
