### ISSUE TITLE
I dont't wish to install debug apk every time when I debug android/ios,what should I do?

### ISSUE THREAD

**Issue by fantasy525** [Microsoft/vscode-react-native#899]
## Actual Behavior
1. my phone has installed a debug apk,and I run debug android,it install again

## Expected Behavior
1. I don't want to install debug apk every times,Are there configuration options to Prohibit installing apk again?I just want to  start packager server and debug program.
2. 

## Software versions
- React-Native VS Code extension version: 0.8.0
- VSCode version: 1.30.2
- OS platform and version: window10
- NodeJS version: 8.9.3
- React Native version: 0.57.8
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by ruslan-bikkinin** [comment]
Hi @fantasy525 and thanks for questioning. You can start packager once via palette command `> React-Native: Start packager` and then use `Attach to packager` debug configuration to connect to it.
Please let us know if it helps.

**Comment by ruslan-bikkinin** [comment]
@fantasy525 could you please give us code snippet or demo project so we could take a look? Also, was something logged in React-Native output channel?

**Comment by fantasy525** [comment]
@ruslan-bikkinin  I find it works sometimes,but not sometimes,
![image](https://user-images.githubusercontent.com/22516157/52332086-b384c680-2a34-11e9-8dc9-5ee6a6010943.png)
Do you want to see anything else ？

**Comment by ruslan-bikkinin** [comment]
@fantasy525 debugger won't stop at 48 line because there is no statements at this line, but if you set breakpoint on 46,47 or 50 it should stop at them (assuming that this code would be ever reached). Did you try it? I see, that breakpoint at 47 line is gray and it's strange, do you use Haul packager?

**Comment by fantasy525** [comment]
@ruslan-bikkinin I didn't use Hual,and I tried to change the position of the breakpoint,but it  still doesn't work at timers. now I test it ,it works,so I will close this issue  for the moment.
