### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of errorStrings.NotAllSuccessPatternsMatched"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#903]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Unknown error: not all success patterns were matched. \n It means that "react-native run-{0}" command failed. \n Please, check the View -> Toggle Output -> React Native, \n View -> Toggle Output -> React Native: Run {1} output windows.

File Name:
Src\vscode-extensions\vscode-react-native.xlf

Resource ID:
errorStrings.NotAllSuccessPatternsMatched"

Query:
Is this entry translatable or non-MS?

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek, it's partially translatable. These parts **should not be translated**:
* `"react-native run-{0}"`
* `View -> Toggle Output -> React Native, \n View -> Toggle Output -> React Native: Run {1}`

**Comment by ruslan-bikkinin** [comment]
@PDostalek I updated my previous comment.

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek do you need any more help from my side?

**Comment by PDostalek** [comment]
Thanks for confirmation
