### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of packager.AboutToGetURL"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#904]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
About to get: {0}

File Name:
Src\vscode-extensions\vscode-react-native.xlf

Resource ID:
packager.AboutToGetURL"

Query:
Meaning is not clear. We understand (Resource ID) it will show a URL where you get something. Please, explain

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek, we log this message when extension is going to download JS bundle from packager by URL. In other words, the alternative phrase would be `Are going to download: {0}`.

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek do you need any more help from my side?

**Comment by PDostalek** [comment]
Thanks!
