### ISSUE TITLE
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root. 

### ISSUE THREAD

**Issue by mlostekk** [Microsoft/vscode-react-native#905]
## Actual Behavior
1. Try to attach the packager
2. See error below

```
OS: darwin x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.23.11
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: spawn react-native ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root. 
 If so, please, follow these instructions: https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#project-structure. (error code 604)
```

## Expected Behavior
1. Try to attach the packager
2. Debugger should attach to the packager
 
## Software versions
- React-Native VS Code extension version: 0.8.0
- VSCode version: Version 1.30.2 (1.30.2)
- OS platform and version: 10.14.2
- NodeJS version: v8.15.0
- React Native version: 0.55.3
- Expo SDK version (include if relevant): nope

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.23.11
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: spawn react-native ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root. 
 If so, please, follow these instructions: https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#project-structure. (error code 604)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] debugger listening on port 44769
extensionService.ts:505 Overwriting extension /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2 with /Users/mlostek/.vscode/extensions/ms-vscode.node-debug2-1.31.3.
t._logMessageInConsole @ extensionService.ts:505
extensionHost.ts:235 Extension Host
extensionHost.ts:236 Debugger listening on ws://127.0.0.1:44769/9d1bd9e4-7cb9-41e0-9bdc-8e727790284b
For help see https://nodejs.org/en/docs/inspector

log.ts:157  INFO no standard startup: panel is active
console.ts:134 [Extension Host] [vscode-icons] v8.1.0 activated!
console.ts:134 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:134
log.ts:169   ERR spawn react-native ENOENT: Error: spawn react-native ENOENT
	at _errnoException (util.js:1024:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```
I am having a react native project in the root of VSCode.

**Comment by ruslan-bikkinin** [comment]
Hi @mlostekk and thanks for contacting us. Do you use nvm??

**Comment by mlostekk** [comment]
Yes

**Comment by mlostekk** [comment]
Also when trying to use your recommended setting,  i see thi 
![bildschirmfoto 2019-02-06 um 15 01 50](https://user-images.githubusercontent.com/10534316/52346590-32233900-2a20-11e9-80cc-e5cf1dd38c94.jpg)

**Comment by mlostekk** [comment]
Ah, good hint... NVM using `8.15.0` does not work. But `8.11.1` works

**Comment by ruslan-bikkinin** [comment]
> Also when trying to use your recommended setting, i see thi
> ![bildschirmfoto 2019-02-06 um 15 01 50](https://user-images.githubusercontent.com/10534316/52346590-32233900-2a20-11e9-80cc-e5cf1dd38c94.jpg)

To override RNT settings please use `react-native-tools.SETTING`, where SETTING is parameter you want to override? in your case it'd be `projectRoot`:

![image](https://user-images.githubusercontent.com/30265843/52346820-85ea4e00-2a31-11e9-9987-0f8d7a15cf16.png)

> Yes, it was always working fine.. till 2 weeks ago

Please, try to run `node -v` command in system terminal outside VS Code and using VS Code terminal. If versions are different then run `nvm alias default NODE_VER`, where NODE_VER is needed version  of node, restart VS Code and check again.

Please let us know if it helps.

**Comment by mlostekk** [comment]
Regardless of the setting `"react-native-tools.projectRoot": ".",` its not working with `8.15.0` set via `nvm alias`. Its only working with `8.11.1`

**Comment by ruslan-bikkinin** [comment]
@mlostekk did you install react-native-cli globally for v8.15.0?

**Comment by mlostekk** [comment]
oh yes. sorry, that was my fault. did not do that! thank you for your quick help

**Comment by pilot4u** [comment]
I have the same issue after installing react-native-cli globally.

OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.8.2
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: spawn react-native.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Could not debug. Seems to be that you are trying to debug from within directory that is not a React Native project root. 
 If so, please, follow these instructions: https://github.com/Microsoft/vscode-react-native/blob/master/doc/customization.md#project-structure. (error code 604)

**Comment by ARJUN-JAKKA** [comment]
PS D:\project\app> react-native run-windows
 √ Found NuGet Binary
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.4.29806.167)    
- Restoring NuGetsC:\Users\jsvis\AppData\Local\Temp\nuget.4.9.2.exe
 √ Restoring NuGets
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.4.29806.167)    
 √ Found Solution: D:/project/app/windows/edelweissV1.sln
 i Build configuration: Debug
 i Build platform: x86
Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=16.0 /bl
 - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... / Building Solution: Adding file 'Microsoft.ReactNative.pdb'... - Building Solution: Adding file 'Microsoft.ReactNative.pdb'... \ Building Solution: Adding file 'Microsoft.ReactNative.pdb'... | Building Solution: Adding file 'Microsoft.ReactNative.pdb'... √ Building Solution
 √ Starting the React-Native Server
 √ Removing old version of the app
 √ Enabling Developer Mode
 √ Installing new version of the app
 × Failed to deploy: Fail to check the installed app, maybe developer mode is off on Windows
PS D:\project\app>


I have turned on my Developer mode also
still getting this error

**Comment by SounD120** [comment]
Hi @ARJUN-JAKKA . The first issue looks similar to #1152, and it is not connected to the extension since it is reproduced even without the extension. With respect to errors with building in Visual Studio, I'm afraid that this is not the correct place for resolving such questions. I suppose that it is better to ask your questions in [React Native for Windows repository](https://github.com/microsoft/react-native-windows). Feel free to open new issues if they are about debugging React Native apps with React Native Tools extension in VS Code.
