### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "./src/extension/android/adb.CouldNotReadFrom"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#909]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Couldn't read from {0}.

File Name:
Src\vscode-extensions\vscode-react-native.xlf

Resource ID:
0; "./src/extension/android/adb.CouldNotReadFrom"

Query:
Please, could you provide the meaning of the placeholder?

**Comment by SounD120** [comment]
Hi, @PDostalek . This placeholder will be replaced by the path to the `local.properties` file for Android project. In case of this error the next string will be `Using Android SDK location from PATH.`
You can find more context [here](https://github.com/Microsoft/vscode-react-native/blob/41041b3d1859d828b927310e09d7033d805090e2/src/extension/android/adb.ts#L212)

**Comment by PDostalek** [comment]
Thanks!
