### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "./src/common/error/errorStrings.DebuggingFailedInNodeWrapper"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#910]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Cannot debug application due to an error in the internal Node Debugger
Failed to configure the node debugger location for the debugger

File Name:
Src\vscode-extensions\vscode-react-native.xlf.lcg

Resource ID:
0; "./src/common/error/errorStrings.DebuggingFailedInNodeWrapper"
0; "./src/common/error/errorStrings.NodeDebuggerConfigurationFailed"

Query:
Does Node refer to the open source platform and, therefore, it is not translatable?
Or is it a generic term and we can translate?

**Comment by SounD120** [comment]
Hi @PDostalek , `Node` is a platform reference in both cases and it should not be translated. Internal Node Debugger is a reference for internal Visual Studio Code debugger for Node.js  [vscode-node-debug2](https://github.com/Microsoft/vscode-node-debug2)

**Comment by PDostalek** [comment]
Thank you.
