### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability  of "Expo/Exponent"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#914]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
No link provided by Expo. Is your project correctly setup?

File Name:
0; "./src/common/error/errorStrings.ExpectedExponentTunnelPath"

Resource ID:
0; "./src/common/error/errorStrings.ExpectedExponentTunnelPath"

Query:
Please clarify the meaning of "Expo/Exponent". Is "Expo" a short form of "Exponent"? Shall we use the full form in the target, or translate as per the source?

0; "./src/common/error/errorStrings.ExpectedExponentTunnelPath"
0; "./src/common/error/errorStrings.FailedToRunExponent"
0; "./src/common/error/errorStrings.RNVersionNotSupportedByExponent"
0; "package.reactNative.command.publishToExpHost.title"
0; "package.reactNative.command.runExponent.title"

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek please translate as per the source.

**Comment by ruslan-bikkinin** [comment]
@PDostalek I am closing this, feel free to re-open if needed.
