### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of <Shake or press menu button>,” “<Dev Settings>” and “<Debug Server host & port for Device>”? 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#918]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Device {0} supports only API Level {1}. \r\n Level {2} is needed to support port forwarding via adb reverse. \r\n For debugging to work you'll need <Shake or press menu button> for the dev menu, \r\n go into <Dev Settings> and configure <Debug Server host & port for Device> to be \r\n an IP address of your computer that the Device can reach. More info at: \r\n https://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps

File Name:
Src\vscode-extensions\vscode-react-native.xlf

Resource ID:
0; "./src/extension/android/androidPlatform.DeviceSupportsOnlyAPILevel"

Query:
Would you please check the localizability of “<Shake or press menu button>,” “<Dev Settings>” and “<Debug Server host & port for Device>”? For now, I translated “<Shake or press menu button>” and “<Dev Settings>” because they seem to be Android UIs; however, I left “<Debug Server host & port for Device>” in English because it is marked in grey on the following live page: https://github.com/facebook/react-native/issues/17644.

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek looks like you are missing some text in “,” “”.

**Comment by PDostalek** [comment]
Corrected:  the localizability of “<Shake or press menu button>,” “<Dev Settings>” and “<Debug Server host & port for Device>”?

**Comment by PDostalek** [comment]
SRC:
Shake or press menu button 
Dev Settings
Debug Server host & port for Device

**Comment by ruslan-bikkinin** [comment]
@PDostalek I marked in **bold** those parts that are localizable:
**Shake or press menu button**
Dev Settings
Debug Server host & port for Device

**Comment by PDostalek** [comment]
Thank for confirmation
