### ISSUE TITLE
RN 0.59 = Could not debug. Could not found executable in .../ios/build/Build/Products/Debug-iphonesimulator (error code 403)

### ISSUE THREAD

**Issue by lfiorini** [Microsoft/vscode-react-native#934]
## Actual Behavior
1. react-native init newproject
2. cd newproject
3. code .
4. Add configuration ( choose React Native )
5. Debug IOS
6. App runs but debug is not active

## Expected Behavior
1. Debug active

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.32.1 
- OS platform and version: MacOS 10.14.3
- NodeJS version: 11.11.0
- React Native version: 0.59
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
OS: darwin x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 3.23.11
Could not debug. Could not found executable in /Users/.../ios/build/Build/Products/Debug-iphonesimulator (error code 403)

**Comment by ruslan-bikkinin** [comment]
Hi @lfiorini and thanks for reporting, I confirm that this is a bug due to changes in RN 0.59. I am working on a fix now and will let you know about any updates from our side.

**Comment by ruslan-bikkinin** [comment]
@lfiorini  v0.9.0 has been released in which this issue should be resolved. I am closing this for now, please, feel free to reopen if needed.
