### ISSUE TITLE
Activity class does not exists

### ISSUE THREAD

**Issue by TeamAntani** [microsoft/vscode-react-native#935]
## Actual Behavior
1. Execute "React Native: Run Android on Simulator" from palette
2. App is built and installed successfully
3. App is not launched because we're adding an applicationIdSuffix ".development" in buildType debug from gradle and our launch activity is called HomeActivity rather than MainActivity

## Expected Behavior
1. We'd like to specify packageName and activity to launch in settings

## Software versions
- React-Native VS Code extension version: 0.8.0
- VSCode version: 1.32.
- OS platform and version:  macOS Mojave 10.14.3
- NodeJS version: 10.15.3
- React Native version: 0.58.4
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
BUILD SUCCESSFUL in 12s
30 actionable tasks: 6 executed, 24 up-to-date
Running /home/xpuser/Android/Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (/home/xpuser/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -n it.trovaprezzi.android/it.trovaprezzi.android.MainActivity)...
Starting: Intent { cmp=it.trovaprezzi.android/.MainActivity }
Error type 3
Error: Activity class {it.trovaprezzi.android/it.trovaprezzi.android.MainActivity} does not exist.
```

**Comment by ruslan-bikkinin** [comment]
Hi @TeamAntani and thanks for reaching us. Could you please try to manually run `react-native run-android` manually and let us know if problem is still persist?

**Comment by ruslan-bikkinin** [comment]
@TeamAntani oh, now I see. Thanks for your feedback, we'll consider that and manage in order of priorities. As workaround, you can try to use `Attach to packager` debug configuration.
