### ISSUE TITLE
vscode cannot open chrome tab when pressing F5

### ISSUE THREAD

**Issue by aflext** [Microsoft/vscode-react-native#945]
## Actual Behavior
1. vscode react-native debugger cannot open chrome tab
2. 

## Expected Behavior
1. After installing the `React Native Tools` and have configured the file `launch.json`, vscode will open chrome tab to help debug react-native when press `F5`

## Software versions
- React-Native VS Code extension version: 0.9.0
- VSCode version: 1.32.3
- OS platform and version: windows 7
- NodeJS version: v10.12.0
- React Native version: 2.0.1
- Expo SDK version (include if relevant):

I can open an simulator from `avd manager` and then press `F5` in the vscode and vscode could install and open the app in the simulator.
But if i did not open the simulator from the `avd manager`  and just press `F5`  and the vscode just stuck showing like below 
```
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\john\dev\files\workspace\projects\rn\AwesomeProject 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (575/575), done.

::ffff:127.0.0.1 - - [21/Mar/2019:12:30:14 +0000] "GET /index.bundle?platform=android HTTP/1.1" 200 3325471 "-" "-"
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)
```
I just want to debug the react-native in the vscode within an chrome tab so i can see the network or see the dom elements like debuging an web project in chrome browser.

![image](https://user-images.githubusercontent.com/3211461/54752889-938f1800-4c1a-11e9-912e-48ac0a1b622b.png)
![image](https://user-images.githubusercontent.com/3211461/54752894-95f17200-4c1a-11e9-9425-e9411effb72c.png)

**Comment by ruslan-bikkinin** [comment]
Hi @aflext and thanks for questioning. You need to manually run emulator in order to make debugging work because `react-native run-android` requires it. If you want to inspect UI elements of your native application you can install [React Developer Tools](https://github.com/facebook/react-devtools) and then use command "React Native: Run Element Inspector" in VS Code to run it (instead of running it manually in terminal every time).
Please let me know if it helps or you have any other questions.

**Comment by aflext** [comment]
Thanks a lot for replying. So i will use the simulator only.
