### ISSUE TITLE
How can I disable translations?

### ISSUE THREAD

**Issue by jack1913** [Microsoft/vscode-react-native#946]
I am sorry in advance if this is not the place to ask about such simple matters, but could you please point me where can I disable translations? I do not want my editor to be partially in Polish and English. I want it to be completely in English.

I know this is a 'new feature', but it REALLY is annoying and it reduces my productivity. :/ For ex. in past 2 years I got used to pressing cmd+shift+p then typing 'run ios/andr sim' and having a running simulator of a platform I wanted. Now I get nothing... I need to type the command in PL.

Even if I could set for my whole editor to be in Polish I would not do this because I prefer it to be in EN.

Please consider adding an option to turn off translations.

**Comment by SounD120** [comment]
Hi @jack1913 , and thanks for reaching us. You can find this settings in the Command Pallete as indicated in the picture below. Just change language to "en" and reload VS Code. Please let us know if it helps or if you have some other questions.
![2019-03-21_21-25-58](https://user-images.githubusercontent.com/32372875/54775998-40b85f00-4c20-11e9-91f9-b7ac1d17ccfd.png)

**Comment by jack1913** [comment]
I already had this set to EN. I just restarted my VS Code and everything went back to normal.

I think the issue here was more of VS Code itself than extension, after updating the extension the locale default was not properly passed down to it.

Sorry to bother and thanks!
