### ISSUE TITLE
React Native not in debug environment list

### ISSUE THREAD

**Issue by canpoyrazoglu** [Microsoft/vscode-react-native#950]
I've been following the exact steps from Facebook for creating a new React Native project, and following the VS Code extension guide. I'm stuck where it says:

> In case if you haven't created the .vscode/launch.json file yet, you can add a whole default debug configuration set. To do that click the debug icon Choose React Native debugger in the View bar, and then click the configuration (gear) icon Configure-gear, then choose the React Native debug environment.

I don't have a .vscode/launch.json file, I go to debug page, click the configuration icon but there's only Chrome and node.js, and a "More..." link which takes me to extensions page with the search query "tag:debuggers @sort:installs", where I can also see React Native Tools 0.9.0 installed and enabled.

(Yes, I've seen https://github.com/Microsoft/vscode-react-native/issues/281 but I don't have Flow installed anyway)

## Actual Behavior
1. Follow instructions at https://github.com/Microsoft/vscode-react-native to create React Native debug environment
2. React Native is not in list:

![Screen Shot 2019-03-24 at 11 48 18](https://user-images.githubusercontent.com/4348413/54877054-bf80e800-4e2a-11e9-8264-b560dd4c7cde.jpg)

## Expected Behavior
1. Follow instructions at https://github.com/Microsoft/vscode-react-native to create React Native debug environment
2. React Native should be in the list for creating a debug environment.

## Software versions
- React-Native VS Code extension version: 0.9.0
- VSCode version: 1.32.3
- OS platform and version: macOS 10.14.2 
- NodeJS version: 11.12
- React Native version: 0.59.1

**Comment by ruslan-bikkinin** [comment]
Hi @canpoyrazoglu and thanks for questioning. Please, try the following steps as said in [documentation section](https://github.com/Microsoft/vscode-react-native#debugging-react-native-applications):
> To start debugging create a new debug configuration for your ReactNative app in your `.vscode/launch.json`. Adding a new configuration can be done by opening your `launch.json` file and clicking on `Add Configuration...` button and choosing a relevant debug configuration. All available debug configurations for ReactNative can be accessed by typing in *ReactNative* and picking one from the list populated by Intellisense as shown in the image below.

> ![Add React Native debug configuration](https://github.com/Microsoft/vscode-react-native/blob/master/images/add-debug-configuration.gif?raw=true)

**Comment by canpoyrazoglu** [comment]
@ruslan-bikkinin Hello,

It was exactly what I've already tried 😄 
When I create the .vscode/launch.json manually, I see the Add Configuration button but it's grayed out. I am unable to click on it.

**Comment by ruslan-bikkinin** [comment]
Well, that's interesting. Could you please open `launch.json` in VS Code and share a screenshot of VS Code window?

**Comment by canpoyrazoglu** [comment]
@ruslan-bikkinin that file didn't exist, I've created it manually and it's empty.

**Comment by ruslan-bikkinin** [comment]
@canpoyrazoglu Oh, now I see. Then you need to add these lines to it and after that "Add Configuration" button should be enabled:
```js
{
    "version": "0.2.0",
    "configurations": [
    ]
}
```

**Comment by canpoyrazoglu** [comment]
@ruslan-bikkinin That worked. Thank you!

**Comment by ruslan-bikkinin** [comment]
Similar issue: #985
