### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mmswi** [Microsoft/vscode-react-native#957]
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `0.9.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.3`
[vsmobile.vscode-react-native-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-react-native/files/3014752/vsmobile.vscode-react-native-unresponsive.cpuprofile.txt)

**Comment by SounD120** [comment]
Hi @mmswi . Thanks for reaching us. Could you please describe the VS Code behaviour that leads to that situation? Is something hangs while debugging? More information about how this affects your debugging experience will be very helpful.

**Comment by mmswi** [comment]
Hello @SounD120 ,

Thanks for the reply. I've installed the flutter plugin (https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) and when I first compiled and ran the app, it gave me the error. 

In the end, it worked, but I don't know if this issue will still appear.

**Comment by SounD120** [comment]
@mmswi Can you remember the exact error that you have faced? Did you ran a Flutter app or a React Native one?

**Comment by mmswi** [comment]
Oh, I thought this report contained everything. It was automatically generated by vscode and I just hit submit. I think the error was: Extension causes high cpu load

**Comment by mmswi** [comment]
The Flutter app

**Comment by SounD120** [comment]
@mmswi Have you opened a workspace with multiple folders or just one folder?

**Comment by mmswi** [comment]
It had multiple folders. I don't remember if this error occured when trying to run the project, or trying to create it from the vs code. Anyways. you can close this issue, just wanted to inform you guys on it.

**Comment by SounD120** [comment]
@mmswi I am closing this then. We'll discuss this with [VS Code](https://github.com/Microsoft/vscode) team and as soon as we'll find out anything more about this problem we'll let you know.
