### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "./src/extension/android/androidPlatform.DeviceSupportsOnlyAPILevel" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-react-native#960]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Device {0} supports only API Level {1}. \r\n Level {2} is needed to support port forwarding via adb reverse. \r\n For debugging to work you'll need <Shake or press menu button> for the dev menu, \r\n go into <Dev Settings> and configure <Debug Server host & port for Device> to be \r\n an IP address of your computer that the Device can reach. More info at: \r\n https://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps

File Name:
Src\vscode-extensions\vscode-cordova.xlf

Resource ID:
0; "./src/extension/android/androidPlatform.DeviceSupportsOnlyAPILevel"

Query:
<Debug Server host & port for Device> are segments in brackets localizable ?

**Comment by SounD120** [comment]
Hi @PDostalek . No need to localize this entry.

**Comment by PDostalek** [comment]
OK, thanks for your confirmation
