### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by HalimeErkul** [Microsoft/vscode-react-native#981]
## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 
- OS platform and version: 
- NodeJS version: 
- React Native version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hi @HalimeErkul , thanks for reaching. You didn't provide any details about your environment, so I am closing this issue due to lack of technical information. Please create a new one and next time fill all gaps in issue template.
