### ISSUE TITLE
the debug stops suddenly and the app stop responding

### ISSUE THREAD

**Issue by mouadFahsi** [Microsoft/vscode-react-native#983]
## Actual Behavior
 after i start the debugger everything is normal until suddenly it stops and the app freeze on me i need to restart the app again to resume working,
chrome debugger works normal, the issue only when i use the extension

i use redux-logger to check my redux state and i think it has something to do with that

##Expected Behavior
1. debugging the app for a lounge period of time 

## Software versions
- React-Native VS Code extension version: 0.9.2
- VSCode version: 1.33.1
- NodeJS version: 10.2.0
- React Native version: 0.57.8
- OS platform and version: Windows 10 version 1809
- Expo SDK version : i didn't use EXPO

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Object {type: "LOAD_VIEW_OBJECT", playload: Object}
redux-logger.js:1
 next state
redux-logger.js:1
Object {UserReducer: Object, ShareParObjectReducer: Object, PaymentsReducer: Object, BookingCalendarReduser: Object, ApplicationStateReducer: Object, …}
redux-logger.js:1
‹End group›
redux-logger.js:1
‹Start group›:  action BOOK_NOW_BTN_LOADER @ 14:18:42.418
redux-logger.js:1
 action BOOK_NOW_BTN_LOADER @ 14:18:42.418
console.js:237
 prev state
redux-logger.js:1
Object {UserReducer: Object, ShareParObjectReducer: Object, PaymentsReducer: Object, BookingCalendarReduser: Object, ApplicationStateReducer: Object, …}
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\Projects\shareparmob 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1164/1164), done.

::ffff:127.0.0.1 - - [25/Apr/2019:13:16:35 +0000] "GET /index.bundle?platform=android HTTP/1.1" 200 6038884 "-" "-"
[Info] Enable JS Debugging

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1164/1164), done.

::ffff:127.0.0.1 - - [25/Apr/2019:13:18:02 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "okhttp/3.11.0"
Starting custom debugger by executing: echo A debugger is not needed:  "d:\Projects\shareparmob"
::ffff:127.0.0.1 - - [25/Apr/2019:13:18:21 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "okhttp/3.11.0"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

::ffff:127.0.0.1 - - [25/Apr/2019:13:18:23 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 200 6038906 "-" "-"
 MAP  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

::ffff:127.0.0.1 - - [25/Apr/2019:13:18:24 +0000] "GET /index.map?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "-"
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
workbench.main.js:sourcemap:3264 [Extension Host] debugger listening on port 24344
workbench.main.js:sourcemap:3343 [jundat95.react-native-snippet]: Unknown language in `contributes.react-native-snippet.language`. Provided value: jsx
_logMessageInConsole @ workbench.main.js:sourcemap:3343
workbench.main.js:sourcemap:235 [Extension Host] (node:8000) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.main.js:sourcemap:235
```

**Comment by SounD120** [comment]
Hi @mouadFahsi . Could you please fill all the gaps in our [issue template](https://github.com/Microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md), it would be helpful for understanding the situation from our side. You can add all missing information by the template described below. Also, could you please give us more detailed steps to reproduce the behaviour that you have faced. Any screenshots, demo projects and code samples also would be very helpful.

## Expected Behavior
1. 
2. 

## Software versions
- OS platform and version: 
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hi @mouadFahsi . Do you have a chance to look at this?

**Comment by mouadFahsi** [comment]
@SounD120 sorry for the late response i had some personnel matters and i couldn't open my Computer for a couple of days. I just updated my issue

**Comment by SounD120** [comment]
@mouadFahsi It's not obvious by this logs what may be the reason of such behaviour. Could you please provide a small demo application with repro steps which reproduces that behaviour? Also, it will be very helpful if you can share the application in which this behaviour is reproduces.

**Comment by mouadFahsi** [comment]
@SounD120 i just created a demo code in : https://github.com/mouadFahsi/VSCodeDebugTest
to reproduce the issue all you have is to click on the items and return do that a couple of times. sometimes it take about 15 click and sometimes just two

**Comment by SounD120** [comment]
@mouadFahsi I was able to reproduce this behaviour. Thanks a lot for your help, we'll investigate the reason.

**Comment by SounD120** [comment]
Hi @mouadFahsi . I found out what could be the reason of such behaviour, it looks like `redux-logger` cause this. When I removed this package from middlewares, application stopped to freeze. Could you please try to delete `redux-logger` from the middlewares and let us know how application works?

**Comment by SounD120** [comment]
Hi @mouadFahsi . After further investigations I found out that:
1) `redux-logger` have officially known [performance issues with React Native](https://github.com/LogRocket/redux-logger#known-issues)
1) Redux >= `4` is not yet officially supported. [More info](https://github.com/LogRocket/redux-logger/issues/292)
1) The amount of logs which goes through logger is huge, it stores all the data that is rendering on the screen and prints it to debug logs, so I'd recommend to decrease amount of logs, or disable `redux-logger` for that application.

**Comment by serkanz** [comment]
Hi,

I think this behavior is not related with redux-logger only. In my project I don't use redux-logger, I use redux, redux-thunk and react-navigation. After request a resource and dispatch an action with redux-thunk a number of times, app stops responding. When using expo start command, everything is working as expected.

Regards
